### ISSUE TITLE
Duplicated entry for show with no episodes

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#1005]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 20171204

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac OSX High Sierra

**Describe the problem you are having and steps to reproduce if available**
Some shows have multiple results/entry but only one has the correct information for episodes

**Attach any DuckieTV statistics or Developer Console logs if available**

This is something I've experienced before but never reported, this is the case scenario:

- Added a show before any episodes where released (in this case Marvel's The Gifted)
- Totally forgot about show, since that is the point of having duckie ;)
- Read somewhere that season for the show was on episode 9, WTF Duckie?
- Checked duckie calendar, no episodes showed up, searched in favorites, found show but had no episodes or release date listed.
- Went to Add new show, searched and found another entry for the same show that had all the correct data. 
- Removed first added entry and added the new one > everything works

Is there a way this entries that are made way before a series has been released get cleaned up/merged with the correct one?
Workaround could be for Duckie to actually integrate the TracktTV Watchlist somehow so I can add unreleased shows via trackt instead and they get added to duckie upon release.

**Comment by garfield69** [comment]
>Is there a way this entries that are made way before a series has been released get cleaned up/merged with the correct one?      

DuckieTV gets all its data from Trakt.TV, under the direction of your series selection when you add that show to your favourites. Therefore, from DuckieTV's point of view, all the series it is managing for you are valid ones.    
The fact that later it turns out that the series you picked is not being populated by episodes is not something that DuckieTV can do anything about.     

>Workaround could be for Duckie to actually integrate the TracktTV Watchlist somehow       

As for the watchlist idea, that might be possible. But not by me. I'm cutting back my contributions as I have other interests that I prefer to spend time on, so I will only be fixing bugs and working on finishing any existing tickets I started, as my free time allows.

**Comment by lonelyfairie** [comment]
Sorry to hear that, is the watchlist support added to any pending features request? Should I submit it as one?

**Comment by garfield69** [comment]
ticket #956
