### ISSUE TITLE
Mark an episode as watched directly on the Calendar doesn't push a history update to trakt.tv

### ISSUE THREAD

**Issue by marcelpaulo** [SchizoDuckie/DuckieTV#1013]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Xubuntu 17.10

**Describe the problem you are having and steps to reproduce if available**
When I mark an episode as watched directly on the Calendar, without opening the episode on the sidebar, DuckieTV doesn't push a history update to trakt.tv. However, if I open the episode, and mark it as watched on the sidebar, the history update is indeed pushed, immediately.

_Steps to reproduce:_
1. Enable trakt.tv watched sync
1. Mark an episode as watched directly on the Calendar, without opening the episode
1. Check the status of the episode on trakt.tv: it will not have been marked as watched
1. Click on an episode on the Calendar, to have it opened on a sidebar
1. Mark the episode as watched on the sidebar
1. Check the status of the episode on trakt.tv: it will have been marked as watched

**Attach any DuckieTV statistics or Developer Console logs if available**
Please let me know if there's any log I could send to help debug this further

**Comment by garfield69** [comment]
Thank you for reporting.      
This should be fixed with e2fac2a which will be included in the next DuckieTV stable release, when ever that happens.      
If you want to get the fix sooner, the DuckieTV Nightly should be published by the buildbot in about 6 hours from now.     
To upgrade, I recommend taking a backup from the DuckieTV *Settings > Backup* side panel (safety first ;-) and then installing *Nightly 22-12-2017* or newer, from the https://github.com/DuckieTV/Nightlies/releases repo.
Thanks.

**Comment by marcelpaulo** [comment]
Wow, you guys are really swift, @garfield69, thanks ! I was at this very moment reading from your Wiki the instructions for building from source, which by the way are very clear. I'll follow your suggestion and get the nightly build.

**Comment by marcelpaulo** [comment]
I'm running `201712220130.nightly` now, and I can confirm that the bug was quashed: marking an episode as watched directly on the Calendar pushes a history update to trakt.tv. Once again, thank you so much for the swift solution, @garfield69 !
