### ISSUE TITLE
Duckie TV Window completely black but buttons still work

### ISSUE THREAD

**Issue by KevPat** [SchizoDuckie/DuckieTV#1028]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Standalone 1.1.5 Windows x64

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows 10 x64
![duckie](https://user-images.githubusercontent.com/7307508/35592993-47125330-05d4-11e8-983c-a7cce6a2c351.png)

**Describe the problem you are having and steps to reproduce if available**
... I start Duckie TV & its just blank including the consoles. Yet the buttons in the background still work.
I just finished re imaging Windows 10 and It's still not working

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Try installing a DuckieTV Nightly from https://github.com/DuckieTV/Nightlies/releases. This Development version has the *Development Tools* that include the logs. It installs over the top of your DTV 1.1.5 and uses the same DB and settings.      
So if you still get a black window when you start this standalone Nightly, then press the **F12** button to open the *Development Tools* page, and click on the **Console** tab to view the log. See if there is any thing there.
Also on the black screen, right click your mouse to open a submenu and select the *Inspect background page*, and check the *console* log for this background page as well.
![image](https://user-images.githubusercontent.com/6933240/35597211-35bd5220-0682-11e8-82df-5326034553ea.png)

**Comment by KevPat** [comment]
I've tried all of that. Also Admin permissions x32 & x64.
The browser edition works mostly. Still all the buttons are showing
function names instead of text. & none of the torrent networks comeback
with an answer for manual download
Again check out sysinfo. Its a new Win 10 install. If I'm having this issue
I have to think that its not unique to my situation.

**Comment by garfield69** [comment]
>If I'm having this issue I have to think that its not unique to my situation.

Well of the approx. 165,500 standalone downloads, and approx. 20,000 Chrome Browser extensions of DuckieTV out in the wild, you are the first that I can recall presenting such symptoms.       
And if you say that both the Standalone and the Browser Extensions are both broken, then that suggests that perhaps it is somethings with your particular local system or network setup, because I've never heard of both failing in this way at the same time.     

So you have looked at both the logs (foreground and background) from the Standalone Nightly, and  they are all blank?
What about the logs for the Chrome Browser extension (The same **F12** key and **Console** tab apply), are they empty as well?
That does not give us much to work with.

**Comment by KevPat** [comment]
I don't know what happened last night but I left Duckie running over night
and when I unlocked my computer today it was working fine except some of
the shows were duplicate.
I enclosed a database backup just in case it was corrupted and you were
curious.
Thank you for your time and quick response.

-Kevin
