### ISSUE TITLE
Cannot upgrade from v1.1.4 to v1.1.5 on Mac - high Sierra

### ISSUE THREAD

**Issue by Infallibleman** [SchizoDuckie/DuckieTV#1031]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Mac v1.1.4

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Mac v.1.1.4

**What is your Operating System (Windows, Mac, Linux, Android)**
High Sierra - Mac

**Describe the problem you are having and steps to reproduce if available**
Trying to upgrade from v1.1.4 to v1.1.5, have downloaded the v1.1.5 pkg file, have run the installer, but when I open Duckie TV, it still shows v1.1.4.  I am not clear on the upgrade process.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
I don't have a Mac so I cannot be sure what your problem is. The author provided the mac installation software, but no one else has had problems that I am aware of. 
But here is a suggestion you can try:
1. first start your 1.1.4 DuckieTV and use the *Settings > Backup* panel to make a backup of your series and settings
2. then shutdown DuckieTV and uninstall it
3. now install the 1.1.5 package
4. if it startups up then import your backup.

if this does not work, then install the mac version of the DuckieTV Nightly from https://github.com/DuckieTV/Nightlies/releases, I think that uses a slightly different installer package.
