### ISSUE TITLE
Feature Request: Disable subfolders

### ISSUE THREAD

**Issue by explor202** [SchizoDuckie/DuckieTV#1033]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Stable 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 8.1

**Describe the problem you are having and steps to reproduce if available**
When I manually add a magnet link to Utorrrent 3.3, I'm offered the option to not create a sub-folder. Could a similar option be added to DuckieTV? I would like to automate moving and renaming the torrents before they're sent to my NAS, but I haven't been able to find a file mover that can be set up sub-folders. It's even more difficult because DuckieTV grabs torrents from random sources, so I won't always know what name a folder and it's included media file will have. So I would rather have just the main torrent file go into my torrent folder, where I can then set up MoveOut.exe move anything with the appropriate file extension. 

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Sorry that is not possible. The reason is that while the uTorrent GUI allows the option to tick/untick the *create Subfolder* check box, the uTorrent WEBUI (nor the API) which are the two ways DuckietV interfaces with uTorrent, do not have such an option in their command set :-(
For an example of a file manager that can handle utorrent subfolders and moving just the video and deleting the other junk, I can recommend FileBot. see https://github.com/SchizoDuckie/DuckieTV/wiki/Pairing-DuckieTV-with-FileBot-for-a-fully-automated-media-center
