### ISSUE TITLE
Mac - Auto Downloader function not working

### ISSUE THREAD

**Issue by Infallibleman** [SchizoDuckie/DuckieTV#1035]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone mac

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
DuckieTV v1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac

**Describe the problem you are having and steps to reproduce if available**
auto downloader won't start any downloads.  either automatically, or via manual prompt.

**Attach any DuckieTV statistics or Developer Console logs if available**

Statistics
--
DuckieTV Web Based | 1.1.5
Current Date and Time | Thu, 08 Feb 2018 11:26:55 GMT
NWJS, Chromium | 0.25.0 , 61.0.3163.79
UserAgent | DuckieTV-Standalone v1.1.5 Macintosh; Intel Mac OS X 10_13_3
Platform, Vendor | MacIntel, Google Inc.
Screen (width x height) | 1280 x 800
Default Search Engine | ThePirateBay (Enabled)
Default Torrent Client | Transmission (Enabled but Not Connected to Host)
Auto Download Service | (Enabled but Inactive)
Last checked TraktTV for DB updates on | Thu, 08 Feb 2018 06:00:09 GMT

**Comment by garfield69** [comment]
The reason for this is that your DuckieTV does not have a connection with your local Transmission client.
From your Statistics: * Transmission (Enabled but Not Connected to Host)*
have you followed the setup guide at https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-Transmission-with-DuckieTV?

**Comment by Infallibleman** [comment]
Hello,

I am not sure why said that in the original copy/paste, but I have the two screenshots attached for your review below.  They both reflect the connected status.


<img width="166" alt="pastedgraphic-1" src="https://user-images.githubusercontent.com/36009107/36014631-6ffb8c7c-0d30-11e8-8c65-090b5a9febce.png">

<img width="735" alt="pastedgraphic-2" src="https://user-images.githubusercontent.com/36009107/36014633-73541f24-0d30-11e8-80cb-50e6cf44ba02.png">

**Comment by garfield69** [comment]
OK, so to confirm that you have set up the transmission webui config correctly, try and access the webui directly from your chrome browser. so:
1. shut down DTV
2. at the browser address box  paste `http://localhost:9091` and press enter.
 ![](https://i.imgur.com/tj6z76a.png)
3.  You should get the Login challenge followed by the Transmission torrent page if successful.
![](https://i.imgur.com/DT8um4w.png)
4. if it works close that tab and start DTV.
5. next show me a screen capture of the Auto Download Service Monitor, which should show you which episodes the ADS has process in that cycle, and the reasons why any of them may not have been selected.
You'll find the ADSM icon usually above the settings (cog) icon, on the left had side of the main DTV page.

**Comment by Infallibleman** [comment]
Hi,

I am getting the login/pass window for localhost:9091




Also, below is the ADSM Screen Capture

**Comment by garfield69** [comment]
>I am getting the login/pass window for localhost:9091

and did you login successfully?

>Also, below is the ADSM Screen Capture

um, no you forgot to attach it ;-)

**Comment by Infallibleman** [comment]
I was able to login successfully.

sorry about that, didn’t realize i missed the attachment.  please see below:

**Comment by garfield69** [comment]
nope still not seeing any links to your screen capture or any embedded pics in the email. :-(

**Comment by Infallibleman** [comment]
i just pasted directly to the website.  Can you please confirm you can see it now?


<img width="815" alt="pastedgraphic-2" src="https://user-images.githubusercontent.com/36009107/36015729-6ed9bbac-0d35-11e8-861c-b07744e92931.png">

**Comment by garfield69** [comment]
yes thanks. so I see that you are using RarBG as your search engine, and that all the episodes have been downloaded.
so what is the problem?

**Comment by Infallibleman** [comment]
attached screenshot is an example where shows should have downloaded but nothing happened.  Also, individual 

<img width="861" alt="untitled" src="https://user-images.githubusercontent.com/36009107/36016280-dd095fb8-0d37-11e8-8372-77804a446a34.png">

**Comment by garfield69** [comment]
ok. So all the *madame secretary* episodes that were broadcast prior to 21 days ago are not select-able for auto downloading by the ADS that runs every 15 minutes. We restrict the ADS to look back only 21 days because otherwise the overhead of searching your complete DB would cripple your mac processing power.
Since the last episode broadcast of madam secretary was 14th of January, and the next is not due until 11th march, there is nothing for the ADS to do for this series.
If you want to download those missing episodes you are going to have to do them manually.

**Comment by garfield69** [comment]
if you click on the auto download all, then view the ADSM, you should get a list of all the episodes that are being searched for and the reason why a download might not happen.
usually, it is because older episodes do not have enough seeders. so set your minimum seeders to 1 for the duration of your catchup.

**Comment by garfield69** [comment]
for any of the rest that you cannot find, use the find a torrent button for the individual episode, but then on the torrent search dialogue, select another search engine. They may have the missing episode.

**Comment by Infallibleman** [comment]
Ok, thank you very much for the clarification.  I assumed that when you click on "Auto Download All" then that would tell Duckie TV to download all episodes in the Season, regardless of the broadcast window set (e.g 21 days). 

The individual shows are downloading according to the 21 day window perfectly.  the "Auto Download All" doesn't and my understanding could be to blame here. :)

**Comment by Infallibleman** [comment]
BTW, you are awesome with support and turnaround time.  Very much appreciated!!

**Comment by garfield69** [comment]
Just to clarify. ;-)
The 21 day restriction applies only to the ADS when it is run automatically every 15 minutes.

If you manually click the *Auto Download All* button on a seasons' worth of episodes then all those episode requests are sent one at a time to the ADS for processing. 
The 21 day restriction does not apply to those episodes.

By  using the ADSM you should see them all show up as having been searched for.
They will stay on that list until the next 15 minute cycle, after which the scheduler runs the next ADS cycle and I think only the active ones remain on the list.

But if you are not seeing any torrents passed to the Transmission client, then check the reason why on the right hand side of each episode in the ADSM. 
As I said before, usually it will be because there were not enough seeders.

This is what I get when I did a manually click on *Auto Download All* for season 4 of *Madam Secretary* using RarBG as the default search engine and 30 seeders as the minimum.
![image](https://user-images.githubusercontent.com/6933240/36041070-4fdd4f8c-0e2c-11e8-9a29-e2d55d3c906c.png)
In the example above, episodes 1 to 7 don't have 30 seeders. So by setting the auto-download seeders minimum lower to say 10, and then retrying the *auto download all* you would get most of the episodes.

If you want season 3 you first would need to navigate to the season 3 list, then click on the *Auto Download All* again.
