### ISSUE TITLE
american dad s15 episodes are numberd wrong start whit ep2

### ISSUE THREAD

**Issue by kocka68785602** [SchizoDuckie/DuckieTV#1043]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... chrome browser action

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... 1.1.5 

**What is your Operating System (Windows, Mac, Linux, Android)**
... windows

**Describe the problem you are having and steps to reproduce if available**
... american dad s15 episodes are numberd wrong start whit ep2

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Yes, American Dad is a mess. 
The inconsistency was introduced early in the life of the series, and the torrent scene has struggled to cope with the correct episode references ever since.

The episode and season guides inside DuckieTV are pulled from [Trakt.tv](https://trakt.tv/), which uses data from [TVDB](http://thetvdb.com/) and [TMDB](https://www.themoviedb.org/).

DuckieTV also uses a 3rd party site called [thexem](http://thexem.de/) which attempts to cross reference the TVDB index system with the torrent scene indexing chaos http://thexem.de/xem/show/4153 as this has been so far the best way to get the correct episodes.

If you feel they have got it wrong, feel free to contact them by Joining #xem on irc.freenode.net.
