### ISSUE TITLE
End of season/series end icon.

### ISSUE THREAD

**Issue by outerspacepotatoeman** [SchizoDuckie/DuckieTV#1044]
Requesting new feature for an icon like the star on the first episode of the season, so I can know when the season is over.

**Comment by garfield69** [comment]
Unfortunately I do not believe this can be done in a timely manner, because the data we get from Trakt.TV does not include an end-of-season flag.
So the only time we would know that the last episode of a season was in fact the last episode, is when either the first episode of the next season shows up, or the series has ended/cancelled. :-(
