### ISSUE TITLE
[Feature Request] Set label of torrents added to client via DuckieTV

### ISSUE THREAD

**Issue by Eds1989** [SchizoDuckie/DuckieTV#1047]
It would be great if when DuckieTV adds a torrent to uTorrent (or any client that supports them), a label could be set for the torrent, e.g. "TV"

**Comment by garfield69** [comment]
I have researched this previously Oct '16 and discovered that only qBitTorrent supported setting a label via the WEBUI.
Using The WEBUI is the only way DuckieTV can connect and pass torrent requests to connected clients.
Some other clients supported labels but only if set via their GUI (such as uTorrent).

Enhancement ticket [#705](https://github.com/SchizoDuckie/DuckieTV/issues/705) was implemented since DuckieTV 1.1.4 to optionally add the *series name* as a label for qBitTorrent.
This is done via the *Settings > Torrent > Torrent Label* option, which only appears when DuckieTV is connected to qBt 3.2+
I haven't bother checking if any of the other clients have recently enabled setting a label via the WEBUI, but if you find any, and want it enabled, I will add it, but only for adding the series name.
A custom labels feature is just too much work for an option used by so few clients.

**Comment by Eds1989** [comment]
Been in uTorrent's webUI for a while now, as this is now my primary method of managing torrents remotely, and I couldn't have done this without the ability to manage labels:
![image](https://user-images.githubusercontent.com/37086102/37054358-88a4f57e-2176-11e8-8dae-4776df567aba.png)
Couldn't say when it was added, but I've been using the webUI for a good couple of years I think.

Would it be simpler to just have a single field in the settings, that we can specify a label name, and always pass that through? I only ever use the one label with DuckieTV ("TV"), so only having a single static label would be sufficient for someone in my scenario.

**Comment by garfield69** [comment]
I don't see an option to specify a label when you add a torrent via the webui
![image](https://user-images.githubusercontent.com/6933240/37054881-0a656198-21e5-11e8-91d8-485c94ed17d8.png)
does your utorrent look different?

**Comment by Eds1989** [comment]
I see, sorry, I misunderstood. I thought you meant in general and not specifically when adding a torrent.

My mistake.
