### ISSUE TITLE
Netflix button bug

### ISSUE THREAD

**Issue by therealvpatel** [SchizoDuckie/DuckieTV#1051]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Chrome Extension new Tab v 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac

**Describe the problem you are having and steps to reproduce if available**
Clicking on the netflix button does not do anything...do i need to set this up somehow?

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Schizoduckie set this up way back in april 2015, but since I don't have a Netflix account, I have never tested this for myself, so I've no idea if it still works or not.
do you mean this button?
![image](https://user-images.githubusercontent.com/6933240/37191731-555722a8-23c6-11e8-9869-a3fa1ede43f4.png)
when you press that button do you get the popup asking you to login to netflix, and do you get a new tab open on your browser to login to netflix
![image](https://user-images.githubusercontent.com/6933240/37191798-b1cc6304-23c6-11e8-85b8-9399d591d1d9.png)
once you are logged in and you click OK, then you can press the *watch on Netflix* button to presumably launch a search on netfilx to go watch the show.
So if it does not work at this point, press the **F12** key to open the *Development Tools* page, click on the **console** tab to view the log, and see if you get any error messages related to netflix.
let me know what you find.

**Comment by therealvpatel** [comment]
Yes, that is the button i am referring too. I just noticed it recently since i added a few Netflix shows. When i click the button i do not get a popup for a netflix login. 


i checked the developer console, did not find any errors pertaining to netflix.

**Comment by garfield69** [comment]
ok, so it appears something on the mac is blocking the popup. 

Have you got some kind of adblocker or maybe a chrome browser popup-blocking-setting enabled?      
On my win7 Chrome Browser Version 65.0.3325.146 (Official Build) (32-bit), its *Chrome Browser > settings > advanced > Privacy and Security > Content Settings > Popups*

what if you opened a tab to `https://www.netflix.com` and signed in, then from DuckieTV clicked on the *watched on Netflix* button, does that work?

**Comment by therealvpatel** [comment]
im on chrome version 64.0.3282.186 (Official Build) (64-bit)

I have ublock origin disabled on the duckietv tab. and im not getting a popup blocker notification in chrome. checked the blocked list and duckie is not listed.

i logged into netflix on a second tab, and went back to duckietv and click on the netflix button and nothing occured.

**Comment by garfield69** [comment]
Oh well, that's as far as I can help then. Sorry.
@SchizoDuckie  do you still use the *Watch on Netflix* option on DuckieTV and does it still work for you?
Have you any suggestions for resolving this issue on the OP's Mac?

**Comment by therealvpatel** [comment]
no worries, appreciate the help.

love the work you guys are doing here. thanks for creating such a great app.

**Comment by Js41637** [comment]
Watch On Netflix button no longer works, the code uses Netflix api to search for a show and if it does then get the page and parse its list of episodes except its no longer possible to parse the episodes as they are rendered client side, its technically still possible to replicate but hard and likely not worth it.

You can keep the button and just link to the show or remove it.

**Comment by garfield69** [comment]
In that case I'll remove it. No one but the OP noticed it was not working anyway.
