### ISSUE TITLE
[Request SceneNameResolver]

### ISSUE THREAD

**Issue by swojcik1** [SchizoDuckie/DuckieTV#1052]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... chrome extension (new tab)

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... stable 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
... windows 10

**Describe the problem you are having and steps to reproduce if available**
... Frontline does not auto search properly
Currenly it searches "Frontline US s2018e05"
what works is "Frontline s36e08"
**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by swojcik1** [comment]
If this is the wrong place for this I can submit a a request on r/duckieTV if that's more appropriate, thanks.

**Comment by swojcik1** [comment]
Post on r/DuckieTV
https://www.reddit.com/r/duckietv/comments/83j21h/request_scenenameresolver_for_frontline/

**Comment by garfield69** [comment]
Either GitHub or Reddit is fine. Both is a tad overkill ;-)

Unfortunately I do not have good news.
For reference on how DuckieTV gets its series data, and what services it uses to resolve the torrent scene names and episode cross referencing, refer to https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-make-corrections-to-shows-on-DuckieTV

So I can drop the *US* from the DuckieTV Frontline torrent searches, which I've done via the SceneNameExceptions table, and which your DuckieTV will fetch an update within the next 24 hours.

But the cross matching of s2018e05 to s36e08 is not currently possible because the XEM service does not track the series Frontline.
You could consider joining #xem on irc.freenode.net to see if the XEM support staff would begin supporting it, but given that the series has been around since 1983 and no one has done it yet, I suspect that no one at XEM is interested in providing a TVDB to Scene cross matching table for this series.
