### ISSUE TITLE
1337x has a new domain.

### ISSUE THREAD

**Issue by jakeferris13** [SchizoDuckie/DuckieTV#1054]
1337x domain used to be blocked in Australia but now they have a new main domain and was wondering when and if duckietv would start fetching from the new domain.
http://www.1337x.io/
http://89.163.245.52/home/
![website message](https://user-images.githubusercontent.com/32200745/37333238-ecf5a358-26fc-11e8-8a06-52c59ecd2726.png)

**Comment by lonelyfairie** [comment]
![image](https://user-images.githubusercontent.com/13501166/37347712-38cf707a-26b1-11e8-932d-286791cd690b.png)


My Duckie is using 1337x for downloads with no issues so I am not sure if it is using the old or new domain as both seem up still, is yours not working?

**Comment by garfield69** [comment]
DuckieTV 1.1.5's 1337x search engine uses the official 1337x.to domain. There are no plans to change this despite the fact that it may be blocked in certain countries.
 I don't know if 1337x.io is an official alternate or a clone or a fake, but if you really want to use this domain with DuckieTV then you can do so via the DuckieTV's Jackett interface.
Read https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV for details.
Just change the config on the Jackett  Dashboard's 1337x indexer's Sitelink to 1337x.io.
Once caveat: to use Jackett's 1337x with DuckieTV you will need to adjust the 1337x config on the Jackett Dashboard, and set the *Download link* to *itorrents.org* instead of *magnet*.

**Comment by Js41637** [comment]
Australia only uses ISP level DNS blocking, if you use an alternative DNS their blocking does not work. Google has a free DNS service that is probably better than your ISPs anyway https://developers.google.com/speed/public-dns/
