### ISSUE TITLE
Jackett search cannot be set as default search engine

### ISSUE THREAD

**Issue by Taronyx** [SchizoDuckie/DuckieTV#1062]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...Stable 1.1.15

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows 10

**Describe the problem you are having and steps to reproduce if available**
...When I set a Jackett search engine (IPTorrents) as the default, it keeps switching back to ThePirateBay.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Hmm. To progress this further we are going to need to have a look at the log, however the standalone 1.1.5 does not include the needed development kit.      
So I would suggest the following:
1. take a DuckieTV backup as a precaution, using the *Settings > Backup* panel and create a database backup.
2. download and install the latest DuckieTV Nightly from https://github.com/DuckieTV/Nightlies/releases
3. start the Nightly and set iptorrent as your default search engine
4. shutdown and start the nightly again
5. when you notice that TPB is back as the default then 
6. press **F12** to open the *Development Tools* page
7. click on the **console** tab to view the log
8. click on the **console settings** (the cog icon) and set *show timestamps*
![image](https://user-images.githubusercontent.com/6933240/37791109-374bad7c-2e6d-11e8-83a7-7bf3e48a78ef.png)
9. click on the cog to close the settings
10. scroll to the top of the log and on the left on a blank spot *right click* to open the submenu and select **save as...**
![image](https://user-images.githubusercontent.com/6933240/37791249-99b99ffa-2e6d-11e8-8fec-0d0c046eb65e.png)
11. once you have saved it, *drag drop* the log file here so I can take a look.

**Comment by Taronyx** [comment]
I've installed the nightly.  I'll post the logs if/when I see it switch back to TPB.

Thanks!

**Comment by Taronyx** [comment]
it reverted back to TPB.  Here are the requested logs.

[bagblfnohpiddokbpaacecffdboomafe-1522026420634.log](https://github.com/SchizoDuckie/DuckieTV/files/1846036/bagblfnohpiddokbpaacecffdboomafe-1522026420634.log)

**Comment by garfield69** [comment]
OK. So, during the DuckieTV startup, it waits for 2 seconds before checking that the default Search Engine specified in settings is available, and if not found in memory, then the hard-coded default TPB is used instead. This is to prevent, for example, processes crashing when attempting to use a SE that has been removed after an update, or when a Jackett SE has been disabled.

On my ancient development windows7 system, build in 2006 with a single core AMD processor and a 1GB harddrive, my test DuckieTV can load 16 Jackett definitions and still have 1 second to spare before the default SE check is performed.

Your log shows that just after midnight (which is when DuckieTV does it's reset to reload the calendar for the new day), your single Jackett definition was not loaded from Harddrive into memory until 0.477 of a second after the check was performed.
```
00:00:13.807 app.js:15649 Invalid search provider detected:  IPTorrents  defaulting to  ThePirateBay
(anonymous) @ app.js:15649
00:00:13.854 app.js:11720 qBittorrent 3.2+ connected!
00:00:14.284 app.js:15413 Jackett search engine loaded and added to activeEngines:  IPTorrents
00:00:14.284 app.js:15399 Updating Jackett search engine IPTorrents
```
I presume that the reason for this delay was because your C: harddrive was being trashed by a lot of activity... perhaps you're doing a lot of torrent activity at this time, or something requiring a lot of CPU or disk is going on?

If so, do you have a second drive you can offload that torrent workload to, so you can free up your C: drive response time?

If not, I suppose I could set up a customisation on the next DuckieTV Nightly, where you can adjust the SE check delay, from the default 2000 milliseconds to 2500 or 3000 or whatever delay you end up needing.
Just remember that the longer the SE check kickoff delay is, the more time you have to wait before using a manual torrent search dialogue after a startup, and also, the longer the AutoDownload Service needs to be delayed after startup, if your SE check kickoff gets beyond 5 seconds.

Let me know if you want this set up or if you're going to research what is causing your system to be so slow at this time and fix it yourself.

**Comment by Taronyx** [comment]
I can think of three or four things going on on that PC all night long.  If you could make the timeout customizable, even if it's a hidden registry or config file thing, I'd appreciate it.  Let me know what I can do to help.

**Comment by garfield69** [comment]
OK. so the DuckieTV build-bot is scheduled to generate the next Nightly packages in about 18 hours or so.
Here is what you would need to do:
1. make a DuckieTV backup as a precaution, using the *Settings > Backup > Create a Database Backup*, just in case.
2. shutdown/exit DuckieTV
3. download and install tomorrow's Nightly from https://github.com/DuckieTV/Nightlies/releases
4. after starting it, use the **F12** key to open the *Development Tools* page,
5. and click on the **console** tab to view the log and access the command line
6. at the `>` prompt paste the following
```
localStorage.setItem('custom_default_SE_providers_delay',2500);
```
and press enter. you will get a `undefined` response, this is normal.
7. Exit and start DuckieTV again to pick up the change.

if the *SE provider* kickoff delay is not long enough, bump it up as you need, browse the log for the messages I highlighted in a previous post to calculate your adjustment. Values are in milliseconds.
In the event you reach 5 seconds, then you will need to also adjust the *AutoDownload  Service* kickoff delay using
```
localStorage.setItem('custom_AutoDownload_delay',5250);
```
adding about a quarter second on top of your *SE provider* delay should be enough delay for the ADS.

**Comment by Taronyx** [comment]
I'll give it a try tonight!  Thanks!
