### ISSUE TITLE
New Nightly Default Folder Bug

### ISSUE THREAD

**Issue by jakeferris13** [SchizoDuckie/DuckieTV#1066]
[DuckieTV statistics.txt](https://github.com/SchizoDuckie/DuckieTV/files/1855438/DuckieTV.statistics.txt)

![Screencap of what it is now](https://user-images.githubusercontent.com/32200745/38022120-682ac1ba-32ca-11e8-8cbb-2180257babc4.png)
In the new update, it no longer allows you create a new folder inside what you select, it previously had an option that said Make New Folder, it also didn't say upload as the only option.

Just finding out if this is an intentional "feature" or a bug in the new version. or if it is on my end.

Am happy to offer any more info if I can :)

**Comment by garfield69** [comment]
This is most likely due to upgrading the Nightly to using a latest version of NWJS, the run time environment used for the Standalone, as the actual DuckieTV AngularJS code has not been changed.
You can still create new folders.
Simply select the parent folder and right click your mouse to open the sub-menu and then select the *New > Folder* option.
![image](https://user-images.githubusercontent.com/6933240/38049609-2e2592f0-3325-11e8-8443-25580663f0ba.png)
