### ISSUE TITLE
Auto Download all setup, find episodes but nevr kicking of download to Torrent Client

### ISSUE THREAD

**Issue by greaves68** [SchizoDuckie/DuckieTV#1080]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.15

**What is your Operating System (Windows, Mac, Linux, Android)**
OSX

**Describe the problem you are having and steps to reproduce if available**
My Auto Downloaded finds series, but always set status as "Downloaded", never downloads automatically. Followed everything and Wiki FAQ, still no go. Manually start download and works. Report "has torrent"

switched on Opt-In error Tracking
Unique tracking id: 21835c76-3ba4-2180-1b75-28f98b6625ae

**Attach any DuckieTV statistics or Developer Console logs if available**

Switched on Opt-In error Tracking
Unique tracking id: 21835c76-3ba4-2180-1b75-28f98b6625ae..

Sorry not sure how to get Console Log

**Comment by garfield69** [comment]
The Stable standalone does not come with the *development tools* package installed, so unfortunately the log recorder/viewer is not available.
I suggest you upgrade to the latest DuckieTV Nightly, which includes the *development tools* package, and incidentally, includes the latest fixes as well.
so
1. as a precaution, first make a backup using the DuckieTV *Settings > backup > create a database backup*, just in case
2. download and install  the latest Nightly from https://github.com/DuckieTV/Nightlies/releases

If the auto-download service (ADS) is not launching torrents for a series, then it will help if I get a picture of your set up and some examples of what you are trying to download. 
So to begin with, first access the *About* panel, scroll down to the *Statistics* section, and click on the *Statistics* header.
![image](https://user-images.githubusercontent.com/6933240/39016174-aa3f1262-4473-11e8-9386-60286329183f.png)

This should copy the stats to your clipboard.
Open a plain text file and paste your clipboard, save it to *statistics.txt* and drag and drop the file here so I can take a look.
OR paste your stats to a pastebin site and post the share link here.
Avoid pasting the raw statistics directly here, as GitHub may flag your user as a *spammer* and lock you out.

Next, take a snapshot (screen capture) of your Auto-Download Service Monitor (ADSM) so I can see your typical download attempts and paste the pics here for me to take a look.

I'll think up some further questions once I've got this basic information to start with.

**Comment by greaves68** [comment]
Firstly thanks for reply. OK I've installed new version as requested and setup everything. Basically every time a new show is available it picks it up but defaults to status as "downloaded". I tried the show "Young Sheldon" which I've never tried. Appears in ADSM (Young Sheldon S01 E18) available on 20th April. Show status Downloaded.
Hope you can help
Simon

<img width="775" alt="screen shot 2018-04-20 at 7 26 00 pm" src="https://user-images.githubusercontent.com/38531796/39048922-d197cef4-44d1-11e8-9503-b6387defdd82.png">

[statistics.txt](https://github.com/SchizoDuckie/DuckieTV/files/1931929/statistics.txt)

**Comment by greaves68** [comment]
Think I know what the issue is. I had the default Search engines as EZTV.AG and this caused the issue. When I've change to another (RARBG) is find it series. I thought it uses multiple search engines, but looks like the causes issue and set it as Downloaded and then never looks anywhere else! What are your thoughts

**Comment by garfield69** [comment]
The ADS uses *only* the default Search Engine for its torrent searches.
While the torrent dialogue has the ability to use multiple SE, this feature has not been implemented for the ADS yet.

I have tested on my development box auto-downloading a few of the recent *young sheldon* episodes, using a config similar to how you have set yours up: 7 day lookup, with *20 seeders* minimum, eztv.ag as the default search engine, *100-1000MB* file size restriction, quality *all*, and excluding all torrents with *HDCAM, Spanish and French* keywords in the torrent title.
The only difference was that I run my DuckieTV on a win7 platform and use uTorrent, but those difference should not interfere with how the ADS performs.
I had no problem finding a torrent for *young sheldon s01e19*, and having it processed correctly.

let me see if I understand what you are reporting, correct me if I get it wrong.
Are you saying that when you use eztv.ag as the default search engine, the ADSM only ever displays episodes that have already been *downloaded* previously, or are currently active on your Transmission client as *has torrent* ?
You don't see any of the latest episodes as *not found* or some other status?

What about when you use the multi-SE torrent dialogue for searching the latest episode, do you get results from eztv.ag or only from the other SE like RarBG, TPB etc ?

if this is the case, what happens if you use your chrome browser directly to access https://eztv.ag/ , does this work for you?

If DuckieTV cannot access eztv.ag, then the ADS will not get the torrent search response it is looking for, and depending on the error, may not be able to report back to the ADSM that it failed to get any results.
To check this, use **Cmd-Alt-I** on DuckieTV, which should open the *Development Tools* page. Then click on the **console** tab to view the log.
If there are problems accessing eztv.ag you should see some kind of http or other error messages on the log.

**Comment by greaves68** [comment]
Yep it's the search engine, obviously not an issue when manually looking as it uses multiple SE. The Australian government restrict who we can view apparently.

Info: 
**https://eztv.ag/** can't resolve URL. 
**http://eztv.ag provide a message** "_Federal Court of Australia has determined that the website infringes, or facilitates the infringement of, copyright_". The site is the issue. 

When I check the Console logs:

_eztv.ag/search/Young%20Sheldon%20s01e19 Failed to load resource: net::ERR_CONNECTION_REFUSED_
_eztv.ag/search/Suits%20s07e14 Failed to load resource: net::ERR_CONNECTION_REFUSED_

I've managed to get to EZTV.AG via **https://eztv.unblocked.mx/** but not sure if I can manually change the default address.

Thanks

Simon

**Comment by garfield69** [comment]
- Probably the simplest way to fix this is to change your DNS from the one that your ISP provides, to another such as from Google, see https://developers.google.com/speed/public-dns/ for details.

- An alternative option is to use the Jackett proxy with DuckieTV. See this [wiki](https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV) for set up details.
That would allow your to edit their eztv.ag indexer's site link to point it to your unblocked address, and replace DuckieTV's eztv SE with the one from Jackett.

**Comment by Js41637** [comment]
As Garfield mentioned, Australian ISP block is DNS only, setting your DNS to Google's or Cloudflare's free DNS resolver will bypass the issue, also it's generally way better than your ISPs DNS anyway.
