### ISSUE TITLE
tTorrent SSL

### ISSUE THREAD

**Issue by Pretzel40k** [SchizoDuckie/DuckieTV#1083]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...

**What is your Operating System (Windows, Mac, Linux, Android)**
...

**Describe the problem you are having and steps to reproduce if available**
...

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by Pretzel40k** [comment]
Android 7.1.2 on latest nightly build 201804250130

**Comment by Pretzel40k** [comment]
DuckieTV will not connect to tTorrent pro if SSL (https) is enabled.

**Comment by garfield69** [comment]
I haven't tested ssl with ttorrent. 
I presume that after you turn on the switch on ttorrent, you then changed the address on the duckietv ttorrent integration panel to https ?
I'll take a look when I next have time. maybe a couple days before I get to it.

**Comment by Pretzel40k** [comment]
Yes I have :) Please don't rush on my account as I run duckietv and tTorrent over LAN so SSL is not essential.
Https is working via transdrone and web browser. 
Thank you for the work you put in, it's really appreciated.

**Comment by garfield69** [comment]
I have tried using SSL between my android ttorrentLite 1.5.12 (Nov 2017) and my win7 DuckieTV development platform.
I am seeing a *net::ERR_CERT_AUTHORITY_INVALID* error during the connection attempt.
So then I tried connecting my win7 Chrome browser directly to the tTorrentLite WEBUI, but the browser complained the link was not secure and when I looked at the certificate I found that it had expired back in 2015. 
![image](https://user-images.githubusercontent.com/6933240/39391402-bb6a3614-4af6-11e8-9237-5d10b5a74c3d.png)
Since you are on tTorrent Pro, can you try to access the tTorrent WEBUI from a browser using https and see if you can connect with that.
If not, take a look at the certificate and see if it is invalid or not.
If it is not valid, then there is nothing DuckieTV can do, since the certificate is on the tTorrent side of the connection, and the tTorrent app makers are responsible for providing the certificate. 
I suppose that if you are really keen, you could raise an issue with them (since you've spent money on their app ;-)

On the other hand, if the certificate is valid for you, and DuckieTV cannot connect using https in the DuckieTV tTorrent Integration panel address box, then there is a problem on our side, and I will probably need your help to dig deeper to see if we can spot what the problem is.

**Comment by Pretzel40k** [comment]
Yes. Same problem here. I assumed the issue was with a self signed certificate but 'pro' also expired in 2015. I will try to contact the developers. Thanks again.
