### ISSUE TITLE
Tracking series dates in foreign country (as opposed to US air dates)

### ISSUE THREAD

**Issue by ssuess** [SchizoDuckie/DuckieTV#1094]

**Comment by ssuess** [comment]
I seem to have fixed the problem by manually searching for and downloading the first episode. The calendar is now restored to the previous dates. Hope this helps someone else.

**Comment by Js41637** [comment]
I saw that you resolved it, the air dates we get for content is the date it is meant to air on the original channel it broadcasts on which in most cases is American times. Times are converted to your local timezone however but it's not possible to get times content airs on other networks.

**Comment by 2635599** [comment]
for humans season 3 aired EVERYWHERE at the same time and date. the problem was they originally were to be aired mid 2018, then right after they made that announcement they changed the date to november, then out of nowhere they switched the air date back. i know this cause as i said they announced mid 2018, but when humans s03 first popped up in duckie s03e01 said it was going to air 11/??/2018. so there is the confusion with human explained. i'm only explaining this cause we do need away to edit the air date of shows. a way to pull the info of a show, but once it's in dtv change the air dates of the episodes. for instance "age of the living dead" aired in chinia in early january 2018, but the english version won't air to august 2018. i'm betting since the jan airing was already in dtv the aug aring won't be.
