### ISSUE TITLE
Episodes not being retrieved & torrent sites are "gone".

### ISSUE THREAD

**Issue by Genzzry** [SchizoDuckie/DuckieTV#1106]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
DuckieTV V1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10

**Describe the problem you are having and steps to reproduce if available**
Calendar is empty.  Series's were not being updated, so I clicked [Backup] > [Refresh all series now] ... it wiped the whole calendar.  I'm guessing its due to a change in formatting of the data it gets... or the site is blocked for me.  No idea what site, so no idea how to test it.

Most of the torrent search engines are also blocked now too.  I noticed the calendar stopped being updated about the same time that iDope stopped working and left me with just Zooqle.  Is there any way of setting a proxy on this, so I can send DuckieTV through TOR?

**Attach any DuckieTV statistics or Developer Console logs if available**
Sure... where are they?

**Comment by Genzzry** [comment]
Unique tracking id: 0e0fb5fd-10cc-a739-7a23-6deb75597b71

**Comment by garfield69** [comment]
>Unique tracking id: 0e0fb5fd-10cc-a739-7a23-6deb75597b71

Unfortunately I'm not seeing any data with your trackid :-(

>Attach any DuckieTV statistics or Developer Console logs if available
>Sure... where are they?

The standalone DuckieTV 1.1.5 does not contain the development pack that would allow you to access the console logs.

I suggest the following:
1. shutdown (exit) your standalone DuckieTV
2. locate the DuckieTV working-data folder `C:\Users\<username>\AppData\Local\DuckieTV-Standalone` and make a copy of it as a precaution
3. install the latest DuckieTV Nightly at https://github.com/DuckieTV/Nightlies/releases which contains the SDK pack so you can access the necessary development tools
Incidentally, the latest Nightly has the latest domain change for Idope, as well as a few replacement search engines for the other sites that have dissapeared since dtv 1.1.5 was published.
4. Start your Nightly, and wait for  activity to settle down (a couple minutes)
5. if the calendar is still empty or your preferred search engine is not working, access the log by pressing the **F12** key to open the *Development Tools* page, and clicking on the **console** tab.
If you want help making sense of the log content then: 
6. scroll to the top of the log and on the left on a blank spot *right click* to open the submenu and select **save as...**
![image](https://user-images.githubusercontent.com/6933240/37791249-99b99ffa-2e6d-11e8-8fec-0d0c046eb65e.png)
7. once you have saved it, *drag drop* the log file here so I can take a look.

**Comment by garfield69** [comment]
news about idope: the site appears to be down at the moment.
![image](https://user-images.githubusercontent.com/6933240/44551506-7628c700-a77b-11e8-9299-ed36670c402e.png)

**Comment by Genzzry** [comment]
[bagblfnohpiddokbpaacecffdboomafe-1535063999561.log](https://github.com/SchizoDuckie/DuckieTV/files/2316442/bagblfnohpiddokbpaacecffdboomafe-1535063999561.log)

**Comment by Genzzry** [comment]
Still no calendar... even if I try to force it to load (it's just empty)
I also tried removing the last series that I added... in case that was causing an issue... still nothing.

**Comment by Genzzry** [comment]
<img width="712" alt="capture" src="https://user-images.githubusercontent.com/24488589/44555741-8e262980-a72e-11e8-8284-a179d602fd75.PNG">

**Comment by garfield69** [comment]
the log does not show anything out of the ordinary :-(


in the picture you just uploaded, on the left hand side, under the **play** icon is the **ToDo** checkbox.
if you click on this does the calendar appear?

IF not, can you click on the **about** icon at the bottom left, and scroll down to the **statistics** section on the right side panel, click on the **statistics** header, which copies the stats to your clipboard.
Please paste into a plain text file and drag/drop here do I can take a look. Thanks.

**Comment by Genzzry** [comment]
Oh ffs.... now I feel soooo dumb - lol

**Comment by garfield69** [comment]
:-D
