### ISSUE TITLE
ISSUES with linux app and with chrome extensions. 

### ISSUE THREAD

**Issue by phoenixcomm** [SchizoDuckie/DuckieTV#1112]
**What build of DuckieTV are you using (Standalone / Chrome Extension (New Tab / Browser Action))**
... 

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...

**What is your Operating System (Windows, Mac, Linux, Android)**
... LINUX Debian  9.4  (uname -r 4.9.0.6-amd64 /w Cinnamon Desktop  
   From Debian 9.2 This worked fine!
   Chrome Version 68.0.3440.84 (Official Build) (64-bit)

Hardware:
- AMD Phenom II 555 x 2
- 7.8 Gb Memory
- Graphics: NIVIDIA G70 (GForce 7800GXT)
 
**Describe the problem you are having and steps to reproduce if available**
... I have two systems with the same problem they where both upgraded within a week of each other 
1. with the downloaded  '.deb' file from your website. It runs but when I click on a d/l ie Magnet Link Duckie HANGS and I have to kill it. 
2. Both Chrome extensions Fail and show "Corrupted" by Chrome. 
**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
#### standalone: 
I presume you have been using the DuckieTV 1.1.5 stable standalone package, so perhaps you could try installing from the latest DuckieTV Nightly package at https://github.com/DuckieTV/Nightlies/releases, and see if this make a difference. 
The 1.1.5 standalone package was built using NWJS 0.25 with Chromium 61, but the latest Nighly uses a newer NWJS 0.32 with Chromium 68 and might be more OS 9.4 friendly.  
but if this also fails in the same way, then you are probably missing some common library that was in the 9.2 build and got deleted or changed significantly with the upgrade to 9.4

#### chrome extensions: 
looks like your chrome browser did not survive your 9.4 upgrade intact, with the validation keys for the google store downloads either getting lost, or invalidated in some way.
Have you tried:
1. navigating to the `chrome://extensions/` page, 
2. using the *remove* link to trash-bin the DuckietV extensions, 
3. closing down the chrome browser completely (to clear/release dataspace and keys of the trashed extensions), and
4.  after starting up the browser anew, installing the extesnsions again?

if this does not work, then an alternative would be to load the extension locally instead of from the google store, as the validation process is different.
to do this you would need to:
1. download the Nightly chrome browser extension from https://github.com/DuckieTV/Nightlies/releases and unzip it to a folder of your choice
2. navigating to the `chrome://extensions/` page, 
3. turn on the *developer mode* switch (usually near the top right of the page)
4. use the *load unpacked* to load the extension from your chosen folder

good luck.

**Comment by phoenixcomm** [comment]
Whoopie, Stand-Alone and Tixati working now thank you! ( Nightly build fixed it)
