### ISSUE TITLE
No trakt.tv pin

### ISSUE THREAD

**Issue by Devil505** [SchizoDuckie/DuckieTV#1117]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...
stable and nightly

**What is your Operating System (Windows, Mac, Linux, Android)**
...

linux

**Describe the problem you are having and steps to reproduce if available**
...

Click on the button to authorize duckieTV to use trakt.tv account, this open trakt.tv dashboard on firefox but doesn't ask for a pin code.

**Comment by garfield69** [comment]
try reading this wiki https://github.com/SchizoDuckie/DuckieTV/wiki/FAQ#how-do-i-authorise-duckietv-to-sync-to-trakttv and see if you can complete the task.
I've tested this on my ubuntu 18.04 with the default browser set to both firefox and chrome and had no problems setting this up on my Nightly Standalone DuckieTV .
let me know how you go.

**Comment by Devil505** [comment]
I did the same way but I don't get the PIN popup.

**Comment by garfield69** [comment]
did you try using your browser directly to access https://trakt.tv/pin/948 ?
because if that does not generate the pin after logging on to trakt.tv then the problem is with your firefox setup, where possibly you are blocking popups with some form of security option in firefox settings, or an ad blocker extension or similar.

**Comment by Devil505** [comment]
Your link works, thanks :+1:
