### ISSUE TITLE
Can´t load backup  after update, cant add favorites

### ISSUE THREAD

**Issue by MaiaLara** [SchizoDuckie/DuckieTV#1133]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...
DuckieTV-Standalone v1.1.5 

*What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...DuckieTV-Standalone v1.1.5 

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows 7 Ultimate

**Describe the problem you are having and steps to reproduce if available**
...
Opened DuckieTv and a notification about the already installed new update appeared. Calendar empty. I go to back up, select the backup file from my pc and it gets stuck importing. Tried it 3 times, nothing changes. I wiped the data, tried again, nothing. Tried to load favorites again and it doesn´t load. I dont use the Chrome extension nor TrackTv.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Urg. It seems some event on your system (from a windows update? Or clean up tool? or antimalware?) has nobbled the duckietv data folder such that duckie has lost settings and/or other data points etc. 
So when duckie started and did not find the version timestamp it showed the upgrade popup, although no such upgrade took place.
Anyway, the best method for recovery is to delete that working folder so that when you start duckie it can do a propper first-time install and set up all the essential data points afresh.
So try the following:
1. shutdown/exit duckietv
2. locate and detele the data folder C:\Users\<username>\AppData\Local\DuckieTV-Standalone
3. start duckietv and wait a few minutes for the pre/post install tasks to settle/complete
4. import your backup
5. once the backup is complete restart duckietv to ensure all the restored settings hae been applied.

good luck. let me know how you go.

**Comment by MaiaLara** [comment]
It worked perfectly! Thank you very much!!
