### ISSUE TITLE
Lost all data after update

### ISSUE THREAD

**Issue by ghost** [SchizoDuckie/DuckieTV#1165]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Chrome Extension

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
OSX 10.14.3

**Describe the problem you are having and steps to reproduce if available**
Extension just auto-updated itself, all data seems to be gone including all favorited shows & torrent config

**Comment by garfield69** [comment]
we did not push out any updates to the chrome extensions version of 1.1.5 so this is something that google store must have done for some unknown reason.
so are you able to import from a duckietv backup or is that not working for you?

**Comment by ghost** [comment]
huh, okay disregard then!  Where are the backups?  I don't see any in the databases folder of my chrome config, just the current one for the extension

**Comment by garfield69** [comment]
um, usually the backups go where ever the default download folder is for your chrome browser, unless you chose a different location, after which chrome remembers that path instead.
if you cant find them, try using Finder to search for `.backup` and hopefully you will locate them that way.

**Comment by garfield69** [comment]
Another possibility just occurred to me. 

In the event you find that the import of the backup does not work (wheels just spin around but nothing happens), then this might indicate that it was not google store that pushed an update, but that some other event nobbled your Dtv data store. (mac or chrome cleanup, anti-malware or system upgrade or chrome browser upgrade or something).
I've had a few tickets before for the mac where something like this has happened before.

When Dtv starts, if it does not find the environment variable that indicates the current release, it posts the you've-just-been-upgraded notice. But because the rest of the EVs are missing, Dtv cannot access the DB or do any other useful functions. It's effective broken.
In which case you need to delete the data folder so that in the next Dtv start it can perform the pre-init to set up the DB and EV's.

You could try to access the Chrome extensions page, trash-bin the extension and shut down the chrome browser completely (so that it can clear the dataspaces on the next startup).
Then install the extension afresh and hopefully you should be good to go.

If that does not work, then consider using the Standalone version of Dtv. I would recommend one of the latest Nightly from https://github.com/DuckieTV/Nightlies/releases so that you can use the latest features and updated Search Engines.

Good luck, let me know how you go.

**Comment by ghost** [comment]
Thanks for the suggestions.  I couldn't find a backup file anywhere :(  I thought it was set to automatically backup since I didn't touch that setting and it seems to be set to monthly by default, but oh well.

I had to blow away the database to get it to save shows, so I think the data was actually there, it just got corrupted somehow, and I couldn't even open it in a 3rd party sqlite explorer.  I just spent a while re-adding all the shows so it's good to go now.

I did install the nightly though, thanks for your help!
