### ISSUE TITLE
how to find play button for downloaded shows on duckietv

### ISSUE THREAD

**Issue by borisbean** [SchizoDuckie/DuckieTV#1166]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...

**What is your Operating System (Windows, Mac, Linux, Android)**
...

**Describe the problem you are having and steps to reproduce if available**
...

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
There isn't one, as DuckieTV does not track where your downloads end up.
It's purpose is to track when episodes are due, and pass on torrent requests to your torrent client.
Dtv is not a media library manager.
The only exception to this is if you are using a Synology DS in which case once configured the episodes should have a play button when you visit the episode's details page.
This option was added by the author because he has one. There are no plans to support any other similar products.

**Comment by borisbean** [comment]
Thanks garfield69 much appreciated
