### ISSUE TITLE
DuckieTV does not start transmission

### ISSUE THREAD

**Issue by divcon71** [SchizoDuckie/DuckieTV#1168]
Hi,

I am using DuckieTV new tab mode 1.1.5.  I am on Mac.  I am using transmission. When I try to start a download through DuckieTV, I get a notification stating that download started on transmission but I do not see any torrent on transmission and it does not download anything.

I did not have this problem two weeks ago.  I am not sure why it has started to happen.

Thanks,

**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...

**What is your Operating System (Windows, Mac, Linux, Android)**
...

**Describe the problem you are having and steps to reproduce if available**
...

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Hmm. I started my win10 VB mojave image, and using Dtv tab 1.1.5 on Chrome 73.0.3683.103 with Transmission 2.94 I cannot replicate your problem.
So more info is needed.
From your Dtv click on the **(i) About** icon near the bottom left of the main page, and once the side panel is open scroll down to the **statistics** section. 
Take a screenshot that include at least the first 10 rows of info and paste it here.
Then, using **F12** (if that does not work use **Cmd-Alt-I**) open the *Development Tools* page, and click on the **Console** tab to view the log.
Repeat your test and tell me what your searched for, which torrent you chose to download, and look at the log for related messages to your activity.
Capture or take screen shots so I can take a look and try to replicate your test.

**Comment by thomassun** [comment]
I'm having the same issue here, by opening the dev tool in chrome, I found this url error when I click download for some torrent:
url: http://itorrents.org/torrent/xxx.torrent?title=[limetorrents.info]xxx%5Brarbg%5D
response: 503, the full context is in the attached file

[response.html.gz](https://github.com/SchizoDuckie/DuckieTV/files/3126186/response.html.gz)

**Comment by garfield69** [comment]
@thomassun  looks like your ip address is currently blacklisted by cloudflare on behalf of itorrents.org and is going through an  anti DDoS check. This intermediate page is being presented instead of the content of the .torrent that itorrents.org will eventually present after the cloudflare check is complete.
unfortunately there is absolutely nothing that we can do from DTV's side of the fence.

you have a few options:
1. wait for cloudflare to drop your ip address from their blacklist (which will happen eventually once the attacks from your IP block have stopped occurring after a while).
2. switch to using a different DTV search engine that does not use itorrents.org to provide the magnet hash to .torrent conversion. (or pick one that provides magnets on its results page).
3. If you are using DTV 1.1.5 then consider switching to DTV Standalone Nightly from https://github.com/DuckieTV/Nightlies/releases which has a larger selection of working native DTV search engines (1.1.5's SE are quite out of date)
4. use the DTV Jackett to add/replace search engines to your DTV collection. read this wiki for details https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV

**Comment by thomassun** [comment]
Thanks for reply,  it works now when using another search engine.
