### ISSUE TITLE
Only searching default search engine for Auto Downloads

### ISSUE THREAD

**Issue by jonnwhite1** [SchizoDuckie/DuckieTV#1175]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... Stavle 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
... Windows 10 1809

**Describe the problem you are having and steps to reproduce if available**
... Auto Torrent downloads are only coming from the default torrent search engine. It used to search all search engines. Workaround by setting to Zooqle (Most torrent's are there but not all) torrent's not auto downloading are downloaded manually. 

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
that is correct. 
the auto download service only uses **one** search engine, the one you have set as the default.
this has always been the case. the ADS has **never** used more than one SE.
You can override the default SE for a specific series by using that series' settings panel.

But more to the point, Dtv 1.1.5 has many native SE that are out of date, because the relevant sites have either changed domains, or closed, or changed their search results page.

I recommend you upgrade the the latest standalone Dtv **Nightly** which will have a full set or working native SE.  https://github.com/DuckieTV/Nightlies/releases

**Comment by jonnwhite1** [comment]
Fantastic thank you. I must of used a different engine before or just got lucky. I’ll try the nightly, do you have a recommended search engine?

**Comment by garfield69** [comment]
nope, it all depends on your preferences.
For my personal use, i use MagnetDL via Jackett.
you can add additional SE to your Dtv by using Jackett (Dtv 1.1.5 supports this too). 
see https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV if you want to explore this option.
