### ISSUE TITLE
Torrents auto-added to qbittorrent 4.1.6 instantly i/o error

### ISSUE THREAD

**Issue by msauers** [SchizoDuckie/DuckieTV#1176]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**

Chrome Extension Browser Action

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**

1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**

Windows 10

**Describe the problem you are having and steps to reproduce if available**

Recently upgraded my comp running qbittorrent (QB) from an old Ubuntu version to Windows 10. The computer running DuckieTV has always been Win10. Things worked exactly as expected under Ubuntu. As far as I can tell all my settings in the Win10 QB is the same as Ubuntu QB was.

Now, Duckie finds a new episode, sends the download command to QB via the Web UI and the download immediately reports an I/O error and stops. If I copy and paste the magnet URL in, the download works fine. Logs just say "An I/O error occurred" followed by the filename.

Torrent Parameters is disabled as mentioned in another thread.

**Attach any DuckieTV statistics or Developer Console logs if available**

Not sure where to find these. Happy to pull them if someone can point me in the right direction.

**Comment by garfield69** [comment]
As I mentioned in reddit I'm unavailable at the moment to properly help you investigate this, I don't have the time. But as soon as I get back I'll let you know.

but one thing just occurred to me just now that might have bearing.
you say you began on a linux platform and are now on windows10.

does that mean you imported a Dtv backup taken on ubuntu and used it to import your shows and settings to your Dtv on win10 ?

in which case, we you using the download folder path settings for any/all of the shows on your ubunto Dtv?

Because a likely explanation might be that the paths (which on linux use the forward slash as a separator) would be invalid on windows (which use the backwards slash as a separator).
Is this likely in your case?

If so, as a test, pick a show, edit the shows settings and change the path and see if the torrent is now accepted by qBt.

If this turns out to be the problem, the quickest way to fix would be to take a new Dtv backup on your'e win10 Dtv, and using a plain text editor, revert all the slashes on the path for the show settings, and import.

as for logs, the stable standalone 1.1.5 does not have the development tools package which allows for log browsing.
But if you install the Nightly version of Dtv from https://github.com/DuckieTV/Nightlies/releases then you can use **F12** to open the development tools, and click on the **console** tab to view the log.

you may want upgrade to a Nightly Dtv in any case, since it contains all the latest fixes and features.

**Comment by msauers** [comment]
I feel like a moron. Yep, the save paths needed updating. All is working as it should now. Thank you very much!
