### ISSUE TITLE
no download will launch 

### ISSUE THREAD

**Issue by bbrady5239** [SchizoDuckie/DuckieTV#1184]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
stand alone 

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...
v1.1.5
**What is your Operating System (Windows, Mac, Linux, Android)**
...
windows
**Describe the problem you are having and steps to reproduce if available**
... recently updated to utorrent  3.5.5 on accident and downloads quit working before i realized that i had updated utorrent i reinstalled duckietv v1.1.2 and everything worked except duckie would not load my backup and was missing torrent search engines so i installed v1.1.5 and it would not work with utorrent 3.5.5 so i uninstalled it and installed utorrent 3.5.1 and now no downlaods will launch even though it shows duckie and utorrent are connected 

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
if you were using the default utorrent connection setup with DTV, read 
https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-uTorrent-API-with-DuckieTV
to enable connection to utorrent 3.5.*.
or switch to using the utorrent webui, https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-uTorrent-Web-UI-with-DuckieTV which will work with any utorrent.

as for downloading, problems may be due to the 1.1.5 having old (outdated/expired/shutdown) search engines for sites, and you may wish to upgrade your Dtv to a Nightly from https://github.com/DuckieTV/Nightlies/releases so that you get the latest working Search Engines.

**Comment by bbrady5239** [comment]
Dtv and utorrent are connected everything is set up the way the post shows however no automatic downloads will launch in utorrent nor will any manual downloads it shows them launch in DTV but they never launch in utorrent

**Comment by garfield69** [comment]
are you using 1337x as the default search engine? 1337x changed their download links on thir website, and this broke the 1337x SE on Dtv 1.1.5
Hence my suggestion to upgrade to a Nightly.
Also, with the standalone Nightly you get access to the logs so you can see what the full error messages are that may help explain what is going on, access via the F12 key, followed by clicking on the Console tab to view the log.
