### ISSUE TITLE
Connection to uTorrent is lost after resuming from hibernate

### ISSUE THREAD

**Issue by explor202** [SchizoDuckie/DuckieTV#1192]
Standalone
...

V201906250130
...

W 8.1, uTorrent 3.3
...

I've recently started using a scheduling tool to automatically hibernate my torrent PC. After it's brought back online, Duckie is no longer connected to uTorrent, even though it shows in the settings it is. To restore the connection, I have to click uTorrent Integration, click Clear uTorrent Authorization, close Duckie, then restart it and add authorization back. 
...

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Dtv is not capable of handling a return from hibernation. The Dtv event timers and the calendar do not adjust for the change in the clock time.
This is because Dtv is written in AngularJS as a Chrome Browser Extension and the Standalone version is the same angularJS code running under the NWJS run time environment (that provides the same chromium browser engine internally as the Chrome browser).
I am not aware of any hibernation awareness API functions Dtv can tap into.

I recommend shutting down Dtv before hibernation and starting it up again on awake.

to restore connection to uTorrent simply shut Dtv down and start it up again.
you should not need to clear the authorisation.
