### ISSUE TITLE
uTorrent changing to web client on MacOS Catalina

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#1199]
Hi, I just got this notice on my Mac running uTorrent:
http://blog.utorrent.com/2019/08/01/important-mac-users-will-be-automatically-upgraded-to-%c2%b5torrent-web-for-mac-os-catalina-v10-15/

I am wondering how this will affect the current DuckieTV integration with uTorrent since it is using the web credentials to actually integrate with it. 

Thanks in advance!

**Comment by garfield69** [comment]
until uTorrent Web is released we do not know.
I cannot find a beta to download and explore.
if you find a download link for the beta let me know and I'll take a look.
otherwise we just wait for the official release and see whats what when it comes out.

**Comment by lonelyfairie** [comment]
I can't find it either but they already have a released web client for Windows:
https://www.utorrent.com/downloads/win

I am not sure if you can use that one as any kind of reference for integration but might be worth a look. 
I believe it would likely be that same web client running on Mac browsers after the update. 

Either way I am not married to uTorrent it was just the client I already had installed pre Duckie when I used RSS feeds instead, so if it turns out to be a hassle to integrate I'll just choose from any of the other compatible torrent managers instead.

**Comment by tedztar** [comment]
I have had a look at uTorrent Web, and as far as I can see there is no way to connect to it with duckie. As there are no options for a web interface.

**Comment by garfield69** [comment]
yeah, the windows utorrentweb is definitely a no goer.
It really is bare bones, with little torrent control or management. Really aimed at the streaming crowd.
Very likely the Mac version will be identical, since that's the advantage of a web app, its platform independent, relying on the browser to do the heavy lifting.

If Catalina users really really want to, they could still use Dtv with utorretnweb, but they would loose a lot of functionality.  https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-an-unknown-Local-BitTorrent-Client-with-DuckieTV should at least enable Dtv to pass magnets to it, but not monitor/manage the download progress. **(untested).**
IMO they would be better off switching to a more useful client, plenty to choose from.
I'll not close this until the mac utrrentweb comes out and can confirm suitability.

**Comment by garfield69** [comment]
MacOS uTorrent Web is finally available and as expected it is exactly like the Windows uTorrent Web app.
So this is goodbye to Catalina users as far as Dtv is concerned.
