### ISSUE TITLE
dtv standalone 1.1.5 for arch linux stopped working?

### ISSUE THREAD

**Issue by pjhalsli** [SchizoDuckie/DuckieTV#1207]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
...Liux

**Describe the problem you are having and steps to reproduce if available**
...When I search fortorrents and try to download it says it download but no file is in transmission nor in my download folder. I have tried all different sites with same result. 

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Most likely your Dtv Search engines (SE) on Dtv 1.1.5 are the problem.

The SE on that build are getting out of date with current sites' changed domains, changed search result html, or site closures, etc. I have been fielding quite a few questions like yours recently.

Your best bet is to upgrade to the latest Dtv Standalone Nightly from https://github.com/DuckieTV/Nightlies/releases

try it out and let me know how it goes.

**Comment by pjhalsli** [comment]
how do I do that. I installed from Aur as I'm on Arch. Should I build from source or which version should I choose?

**Comment by garfield69** [comment]
not sure.
if you can point me to where you downloaded the dtv 1.1.5 standalone, I could probably tell you which nightly is compatible.

**Comment by pjhalsli** [comment]
this was where I downloaed from - Arch user repository

https://imgur.com/a/ywGAetr

**Comment by garfield69** [comment]
oh i see. so you are using a customised package built for aur by some contributor.
the aur site https://aur.archlinux.org/packages/duckietv/ lists https://github.com/SchizoDuckie/DuckieTV/releases/download/1.1.5/DuckieTV-1.1.5-linux-x64.tar.gz as a source.
so that would make https://github.com/DuckieTV/Nightlies/releases/download/nightly-201909250130/DuckieTV-201909250130-linux-x64.tar.gz the closest compatible source.
but I have no idea if that package will work directly on your arch or if it needs to be modified in the same way as maintainer woosleyt did for the aur 1.1.5 package.

give it a go and see if it works
but if it does not, then your only recourse would be to try and get in touch with woosleyt and see if he will explain how he altered the package to work for arch, or maybe he could build you one out of the nighty linux package.

**Comment by pjhalsli** [comment]
got it to work againnow. thank you for this amazing program   :+1: 

closing

**Comment by pjhalsli** [comment]
I commented on the aur pkg and he took it down the whole page is gone now. As long as I use duckie in my browser (remote) it works just fine but just not in transmission.  Not a biggie really . But I'll try to build the package you linked to and also from source when I get the time. I'll leave this open again as some archers might be interested in taking on the task on maintaining a pkg
