### ISSUE TITLE
Unable to add TV shows, view favourites or shows in the calendar

### ISSUE THREAD

**Issue by Solo79** [SchizoDuckie/DuckieTV#1213]
Hi I'm on nightly-201910080130 and I can't add tv shows, view favourites or existing shows in the calendar. It just says loading and the calendar spins. See attached. Any help would be appreciated.
<img width="1307" alt="Screen Shot 2019-10-08 at 6 41 15 pm" src="https://user-images.githubusercontent.com/36140719/66380675-3a8ea200-e9fb-11e9-9b14-fd412b5494d1.png">

**Comment by garfield69** [comment]
Urg.
Seen this before.
Something has caused the data folder to loose its environment settings (systems update, data space cleanup, anti-malware security, or something) and Dtv no longer has the profile that describes the layout of the database.
which platform are you on (windows, linux, mac, android), and which flavour of Dtv are you using (standalone or chrome extension new-tab, chrome extension action-mode) ?
I need this info to determine which data folder you are using.
The solution is to delete the data folder so that when Dtv is started again the pre-init will set up the correct environment settings for the database, and after a couple on minutes when the dust settles, 
you can import a Dtv Backup (hopefully you have one of these) and restore your shows.
windows standalone data folder `C:\Users\<username>\AppData\Local\DuckieTV-Standalone`
linux standalone data folder `~/.config/DuckieTV-Standalone`
mac standalone data folder `~/Library/Application Support/DuckieTV-Standalone`

**Comment by Solo79** [comment]
Thanks for your quick response. I'm on a Mac (10.14.6) with a standalone Dtv. I've had a look and I don't seem to have that data folder. I've searched and can't find it. See screenshot of the Application Support folder attached. Any further thoughts?

<img width="744" alt="Screen Shot 2019-10-09 at 7 21 23 pm" src="https://user-images.githubusercontent.com/36140719/66468754-0cc45e80-eaca-11e9-9928-9f20eb92bf29.png">

**Comment by garfield69** [comment]
I'm not a regular macos user, I just have an image built under my win10 virtual box to test macos dtv.

but a Google has revealed the following:
Apparently there are two Applications Support folders.
One is in the /Library/ folder and the other is in the /Home/Library/ folder. 
The latter folder is hidden by default.
you may be able to reveal it by doing the following: 
1. Open the Terminal application in the Utilities folder 
2. and paste the following command line: 
`chflags nohidden ~/Library`
3. Press RETURN.

if that does not work then try google of `mojave library application support terminal hidden folder` or something similar, there appears to be plenty of info out there.

for me on my win10 VB mojave image, the following worked:
1. start a *terminal* from your *launchpad*
![image](https://user-images.githubusercontent.com/6933240/46275517-d18b7780-c5b9-11e8-95ae-b25f38a2f838.png)
2. access the *~/Library/Application Support* folder using `cd "Library/Application Support"`
3. check with the `ls` that the folder *DuckieTV-Standalone* is there
4. delete it with `rm -rf DuckieTV-Standalone`
5. check it is gone `ls`
![image](https://user-images.githubusercontent.com/6933240/46275886-e3214f00-c5ba-11e8-9ade-910e4abc8ab0.png)

**Comment by Solo79** [comment]
That worked! Thanks so much for your help!
