### ISSUE TITLE
DuckieTV stopped sending auto-donwload torrents to client

### ISSUE THREAD

**Issue by cjholowatyj** [SchizoDuckie/DuckieTV#1221]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
... Mac

**Describe the problem you are having and steps to reproduce if available**
... Just today DuckieTV stopped sending auto-download torrents to my torrent client. I usually use qBittorrent, but after this discovery I even tried switching to Transmission, and the issue persists. I'll get the notifications on my Mac that the torrents have started but they never appear in the client.

**Attach any DuckieTV statistics or Developer Console logs if available**
... Error Tracking ID: 4e4571bf-b258-7db3-e908-73aef60104ae

**Comment by garfield69** [comment]
Most likely your Dtv Search engines (SE) on Dtv 1.1.5 are the problem.

The SE on that build are getting out of date with current sites' changed domains, changed search result html, or site closures, etc. I have been fielding quite a few questions like yours recently.
Also, Dtv 1.1.5 standalone does not come with the Development Tools package included, so we cant look at the log for clues.
And unfortunately, the Loggr web site we use to catch errors (for which your error tracking id would be used to identify which errors were posted by your Dtv) has let their certificate expire on the 20th Oct, so that is no longer capturing events at the moment :-(

Your best bet is to upgrade to the latest Dtv Standalone Nightly from https://github.com/DuckieTV/Nightlies/releases which has the latest working SE and updated torrent client interfaces plus assorted bug fixes.
Plus, the Nightly comes with the Development Tools pack included, so we can browse to log if it becomes necessary.

Note that on the Mac, for the installer to work properly, you will first need to drag the DuckieTV app from your Applications folder to the bin, and then run the installer. Failing to do so will make it appear that the installer worked but the app will not be upgraded.

try it out and let me know how it goes.
