### ISSUE TITLE
Chrome Extension (Browser Action) Not Conecting

### ISSUE THREAD

**Issue by maazrasheed2000** [SchizoDuckie/DuckieTV#1232]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
. Chrome Extension (Browser Action)..

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
.Stable 1.1.5..

**What is your Operating System (Windows, Mac, Linux, Android)**
.Window7 64bit..

**Describe the problem you are having and steps to reproduce if available**
...

**Attach any DuckieTV statistics or Developer Console logs if available**
.Unable to connect to qBittorrent 3.2+ Retry in 15 seconds
app.js:379 GET http://admin:12345678@localhost:8080/version/api net::ERR_CONNECTION_REFUSED..

**Comment by garfield69** [comment]
You did not specify which version of qBt you are using, but I am going to guess that you have just recently upgraded to version 4.2.0

Dtv 1.1.5 cannot connect to qBt 4.2 because qBt have changed their WEBUI interface with this version.


My recommendation is that you upgrade to the Dtv Nightly Standalone from https://github.com/DuckieTV/Nightlies/releases

**Comment by garfield69** [comment]
I forgot to mention, I spotted a note in the qBt app changelog that you will need to re-enter the webui password at the qbt app settings panel, because they have changed their encryption method.
And after saving the password you also need to restart qbt.
