### ISSUE TITLE
Randomly loosing downloaded/watched status

### ISSUE THREAD

**Issue by lgmorand** [SchizoDuckie/DuckieTV#1235]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
stable 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
windows 10

**Describe the problem you are having and steps to reproduce if available**
For the last two weeks, sometimes I see an older watched serie for which 1 to 10 episodes are randomly (several season, random episode number) are unmarked as watched+downloaded. First time, I thought it was a minor bug, but that the fourth time in two weeks. I really have no idea what could cause this as it was working perfectly for the last two years. Could it be because I reached a too large number of watched TV shows ?

DB Series | 82
DB Seasons | 444
DB Episodes | 7917
DB Fanart | 2657

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
> Could it be because I reached a too large number of watched TV shows ?

Unlikely. I myself keep a Dtv with 305 series, 1308 seasons, and 18009 episodes, so far.

I think this is a byproduct of reorganisations that are happening at the Trakt.tv side of things.

Behind the scenes, when Dtv fetches episode details from Trakt.tv, Dtv stores them in its database using the Trakt.tv unique episode **id**. 
This way Dtv always knows which episode records to write to, when it fetches any updates that Trakt.tv may send to Dtv (changes to episode name, or viewer ratings, or broadcast date-time changes, etc). 

However, Trakt.tv occasionally reorganises some episodes by deleting an episode with a particular **id** and creating a replacement episode entry with a new **id**.

when this happens, Dtv deleted the old record since it is no longer associated with the series.
And unfortunately any flags such as the downloaded and watched status are lost.

There is nothing that Dtv can do about this, we are totally reliant on Trakt.tv for the series and episode data.

**Comment by garfield69** [comment]
BTW, I would recommend upgrading your Dtv standalone 1.1.5 to the latest Dtv Nightly from https://github.com/DuckieTV/Nightlies/releases to take advantage of bug fixes, new features, and replacement/fixed Search Engines, and updated torrent client interfaces.

**Comment by lgmorand** [comment]
Yes, but I always fear for nightly regressions especially because DTV is working smoothly for months (more stable app ever), that's why I'm eagerly waiting for version 1.1.6 :D 

I know that you and skyzo and hardly working, so I'll be patient
