### ISSUE TITLE
DuckieTV Window Opening Randomly

### ISSUE THREAD

**Issue by newcontender** [SchizoDuckie/DuckieTV#1238]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... V 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
... OSX Catalina

**Describe the problem you are having and steps to reproduce if available**
...Window keeps opening automatically even when minimized to tray. Seems to have at random intervals

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
have you tried Dtv > Settings > Window On Startup > Minimal

**Comment by newcontender** [comment]
Hello.

Yup, it is currently set as that.
![Screen Shot 2019-12-26 at 12 22 07 AM](https://user-images.githubusercontent.com/57878925/71464101-c223bb80-2775-11ea-8983-7118f14fda0c.png)

**Comment by garfield69** [comment]
no its not. ;-)
its currently set to Normalized.
click on the minimize button.
then just be sure close/exit Dtv and start it up again.

**Comment by garfield69** [comment]
better set the always show tray icon too.

**Comment by newcontender** [comment]
Ah, I see. For some reason I automatically associated the big coloured icon to be what it is currently set as. I have now restarted the app. I will see it happens again. Thanks :)

**Comment by garfield69** [comment]
BTW, I suggest upgrading to the latest Dtv Standalone Nightly from https://github.com/DuckieTV/Nightlies/releases

it contains all the latest bug fixes and fully working Search Engines and up to date Torrent Client Interfaces.

Take a Dtv > Backup > create database backup as a precaution.

And on macOS, you first need to move the DuckieTV app to the bin before running the installer, otherwise the installer will claim to have succeeded but it will not actually replace the app.
