### ISSUE TITLE
Calender is not being refreshed since start of 2020

### ISSUE THREAD

**Issue by xaviarnl** [SchizoDuckie/DuckieTV#1240]
I am running the Mac version of DuckyTV, version 1.1.5. I am running Mojave 10.14.6.

The calender of DuckyTV is not being refreshed for 2020. This already started to become visible in the last few days of December, but I thought that it might just be a 'new year' thing. But the calender is almost completely empty now. There are a few show episodes for January, but all of the remaining months of 2020 are empty. And I am following a lot of shows, many of which are still running in 2020.

**Comment by garfield69** [comment]
I have been seeing Trakt.tv server outages recently since the new year started.
this means that if Dtv fails to fetch updates, it could be another 12 hours (by default) before it tries again.
You could use the Dtv > **Settings** > **Trakt.tv** > **Trakt.Tv update period** and set this to 1 hour, to attempt fetching updates more frequently.

But perhaps you would also benefit from upgrading to the latest Dtv Nightly Standalone from https://github.com/DuckieTV/Nightlies/releases/download/nightly-202001020130/DuckieTV-202001020130-OSX-x64.pkg
the Nightly is essentially Dtv 1.1.6 with the latest bug fixes and working Search engines and Client interfaces.
The author is no longer publishing on the main stream, so this is the only way you can get a fully working version.

on the mac, before running the install, open your application folder and bin the DuckieTV app.
without this the installer will not replace the app despite saying its complete.
Also, as a precaution, take a backup using the Dtv > **Settings** > **Backup** panel.

let me know how you go.

**Comment by xaviarnl** [comment]
I am not using Track.tv, but I changed the period and the refresh rate, but the calender was still mostly empty after that.

I installed the nightly version (and the version info tells me that it was installed correctly). I also tried making an export of the database, and then do an import with the 'wipe all before import' option (and did a "refresh all series" after that, just to be sure). But the calender is still as it was: very full in 2019, but only filled a bit in January of 2020, and nothing after that.

**Comment by xaviarnl** [comment]
And just now, I did a total clean install of DuckieTV. First I removed it, and then searched my disk for any folders (incl. hidden ones) with "duckie" in the name, and removed those as well. But the problem still remains...

**Comment by garfield69** [comment]
ok.
Name a few series that you think should be there and I can dig deeper.

**Comment by xaviarnl** [comment]
"Chopped" is one that is always in it. And "Full Frontal with Samantha Bee" (starts on 15th of January), "Ink Master" (has just started), and "The Great Pottery Throw Down" (will start soon).

**Comment by garfield69** [comment]
Basically, Dtv gets all its data from Trakt.tv which in turn aggregates data from TMDB and TVDB
see https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-make-corrections-to-shows-on-DuckieTV#first-a-little-background for more details.

So if its not on the Trakt.tv API servers then there is nothing Dtv can do about this.

**Chopped**:  I see that Trakt.TV API servers delivered season 44 as 8 episodes (usually 13) ended 24 dec 2019
But it looks like TVDB have split the season 44 into 45, because there are 5 episodes and the next episode starts on 21 jan 2020 on my calendar, and this lines up with https://thetvdb.com/series/chopped/seasons/official/44
the next season https://thetvdb.com/series/chopped/seasons/official/45
looks like the trakt.tv api server has not loaded up the last 4 episodes if season 45 yet.

**Great pottery**:  i've got 2 episodes for season 3, 8th and 15th jan. this lines up with https://thetvdb.com/series/the-great-pottery-throw-down/seasons/official/3

**Ink Master**: I see season 13, eps 01 and 02 for the 7th and 14th on my calendar.
https://thetvdb.com/series/ink-master/seasons/official/13
but eps 3 to 8 do not appear to have made their way to the Trakt.TV API server yet.

**Full Frontal Samantha**: season 4 ended 17th Dec, and there is no new data for the next season yet.
this lines up with https://thetvdb.com/series/full-frontal-with-samantha-bee

Its likely the Trakt.TV API servers are struggling with an outage.  I am seeing lots of intermittent `Trakt tv error!  Search error! Error 502` messages in my log. 502 is a Bad Gateway error, so it does appear these servers have a problem delivering some data. 
This may well be the cause of the lack of data you are seeing on your calendar.

I'm starting to see the pattern. But I don't thing there is anything Dtv can do about this.

one thing you can do, is if you want to update/refresh a particular series from whatever data is available on Trakt.TV, you can manually kick off a **refresh** for that series from the Dtv > Series Details Page > Refresh button.

Hopefully now the holiday season is over, the Trakt.TV support staff can take a look and sort out their servers.
