### ISSUE TITLE
Torrent Integration Broken in OS X Catalina 

### ISSUE THREAD

**Issue by MisanthropikOne** [SchizoDuckie/DuckieTV#1242]
I'm having this issue with the most current Chrome extension and the DuckieTV Standalone v1.1.5 running macOS Catalina 10.15.3

At first it seemed like there was a problem with the transmission integration. Duckie seems to think its starting downloads but it doesn't actually start. I get the notification from Duckie that its started but no action on Transmission. I've since tried Deluge, and uTorrent. I've uninstalled and reinstalled everything (Duckie, Transmission, Deluge, and uTorrent) and still the same problem. I've given all of those apps, against my better judgement, full disk access. 

All of those torrent clients work great if I manually add a torrent or a magnet link. If I use Duckie to go to a torrent site and click the magnet link on that site, it works fine... but clicking download from within Duckie doesn't work. 

Duckie integration also works to delete or pause existing torrents... it just can't add them. 

I've been using it flawlessly for a long time. One day, a couple weeks ago, it just stopped working. From what I can see online, it may be that Catalina has imposed some permissions on a variety of folders that forces apps to ask for permission. Thats why I've given these things full disk access to avoid that. 

Any thoughts?

**Comment by garfield69** [comment]
I don't have catalina so I cant test this for myself, but I do have mojave and that works fine for me.

You could try upgrading your Dtv Standalone to the latest Dtv Nightly from https://github.com/DuckieTV/Nightlies/releases
this has all the latest bug fixes for torrent client interfaces, and the latest working search engines for searching, since many have changed their download links since 1.1.5 was published back in 2017.

It also includes the *Development Tools* pack, so after trying to send a torrent from Dtv to your connected client, click on the **Window** > **DevTools** menu (or **Cmd-Alt-I**) to open the page, and click on the **Console** tab to view the log. 
You may find a relevant error message there.

Before installing the Nightly, be sure to access your **Applications** folder and move the DuckieTV app to the bin. If you run the installer while the app in is the applications folder, the installer will silently fail to install (don't ask me why, its a macos thing).

**Comment by MisanthropikOne** [comment]
Is it wrong to fall in love with you so quickly? I don't think so.

I had tried the nightly build a couple days back but I didn't realize it had failed. I removed duckie from Applications and installed the nightly build.... opened it up... and Transmission went crazy with downloads! 

**Thank You Thank you!!!**

**Comment by garfield69** [comment]
\o/
