### ISSUE TITLE
A show which has a number in the title isn’t being found without adding “s to the title.

### ISSUE THREAD

**Issue by gaussey** [SchizoDuckie/DuckieTV#1245]
I’m trying to auto download Avenue 5 from Torrentgalaxy and only when I manually add  “ to the beginning and end do results come up. Is there any way to do this automatically or is this simply an issue with TGX and this show name?

**Comment by garfield69** [comment]
it's an issue with the TGX web site search engine.
if you browse the web site directly you will find that searching for `avenue 5` returns
![image](https://user-images.githubusercontent.com/6933240/74764306-575eae80-52e6-11ea-8379-ebb9c2c80778.png)
where as all the other sites return results.
Dtv does not have the ability to add quotes around a title for just one search engine (SE).
I thought we could drop the `5` but then we are also going to be picking up `Park Avenue`, so that is not going to be useful.
my suggestion is to use the alternate SE when searching for `avenue 5`.
click on that series and access the *settings for avenue 5* button, then select a **search provider for this show** from the pull down, such as `1337x` and **save**.
Now when you use the manual torrent search (or the auto download service), the 1337x SE will be used for that series and you will get results. Since 1337x usually has torrents from TGX you should be able to find a suitable episode.
the alternative is for you to continue adding the quotes by hand.
