### ISSUE TITLE
Magnet links from rutracker in DuckieTV

### ISSUE THREAD

**Issue by whtv** [SchizoDuckie/DuckieTV#1249]
Can it be done? Would be nice!

**Comment by garfield69** [comment]
It is far too much work to add non-English sites as search engines (SE) for DuckieTV (Dtv).
Most non-English sites have (obviously) non-English titles in their torrent names, which means you don't often get matches with the series titles coming out of Trakt.TV.
Although some have dual language versions of the title in the torrent name so that is not as big a problem these days.
Also, most non-English sites do not use the SxxExx episode naming scheme, which also complicates matching as Dtv does not support any other naming scheme (such as the Italian 1x6 for S01E06, or the Russian Серии: 1-​6 из 16 for S01E06).

So no, I am not interested in adding a native RuTracker SE for Dtv.

Having just said that, you can still add personal SE to Dtv using Jackett if you want to.

And this will work for manual searches (so for example, using the Find-Torrent button, search for `Babylon Berlin` and leave out the `S03E01`, and then select one of the results from RuTracker and click on the magnet download link). I just tested this and it works.

Read [this wiki](https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV ) for setting up a Jackett SE with Dtv.
