### ISSUE TITLE
Auto-Download Issue - American Dad Season 17 auto downloads Season 16

### ISSUE THREAD

**Issue by DJBreezey** [SchizoDuckie/DuckieTV#1255]
Standalone
...
V202001180130
...
Windows 10 x64
...
Season 17 of American Dad auto-torrents Season 16 instead. When searching manually, the text is also importing as S16

Although I just realized that I'm using an outdated nightly build. So I'll update that first.

**Comment by DJBreezey** [comment]
Just updated to nightly V202003180130 and the same issue is occuring.

**Comment by garfield69** [comment]
duplicate #1043 
Yes, American Dad is a mess. 
The inconsistency was introduced early in the life of the series, and the torrent scene has struggled to cope with the correct episode references ever since.

The episode and season guides inside DuckieTV are pulled from [Trakt.tv](https://trakt.tv/), which uses data from [TVDB](http://thetvdb.com/) and [TMDB](https://www.themoviedb.org/).

DuckieTV also uses a 3rd party site called [thexem](http://thexem.de/) which attempts to cross reference the TVDB index system with the torrent scene indexing chaos http://thexem.de/xem/show/4153 as this has been so far the best way to get the correct episodes.

If you feel they have got it wrong, feel free to contact them by Joining #xem on irc.freenode.net.
