### ISSUE TITLE
Build number for nightly

### ISSUE THREAD

**Issue by ekko20six** [SchizoDuckie/DuckieTV#1256]
Should the build number change when I install the nightly? I installed the latest and Duckie is saying 201907050130 - no errors on install though...

Cheers

**Comment by garfield69** [comment]
yes they should, as long as we are talking about the Standalone version.
The Chrome extensions are not getting published due to issues with the Google Web Store (see #1233 for details)

Are you installing a Nightly Standalone on the macos platform, by any chance?
I am aware that for macos, you first need to move the Dtv app in the applications folder to the trashbin, before running the installer, otherwise it does not replace the app and silently exits.
the current latest Standalone version is 202005051924

**Comment by ekko20six** [comment]
Suer was a standalone on Mac, followed your steps and now it is showing 20203180130

Thank you 🙂 

edit, oh just noticed my version is still lower, going to look for the latest latest.. jaj

**Comment by garfield69** [comment]
https://github.com/DuckieTV/Nightlies/releases
