### ISSUE TITLE
low priority bug fix

### ISSUE THREAD

**Issue by lapd87** [SchizoDuckie/DuckieTV#1257]
Hi there,
just saw a bug in duckieTV and wanted to let you know :)
When you start torrent download from the app and then close it, after the download completes but is not updated because duckie is not running and then you delete it from the torrent app the bar below episode name stays thicker. I would suggest removing it if duckie can not find the download in the torrent app or after marking the episode as watched. Currently the workaround is to unmark as downloaded and mark as downloaded/seen again.

Thank you for the good work and hope you are safe and healthy in this troublesome times!

**Comment by garfield69** [comment]
which Dtv version are you using (1.1.5 or a Nightly)?

**Comment by lapd87** [comment]
https://www.dropbox.com/s/zuo3ftrmktkscff/Untitled.jpg?dl=0

**Comment by garfield69** [comment]
That is quite an edge case you are describing.

Dtv shows the thick white bar because it believes the torrent download should still be in progress.
If you click the episode title you get the episode details side panel open which shows that the torrent is not available, indicating an unexpected event has occurred.
![image](https://user-images.githubusercontent.com/6933240/81265628-8be93780-9097-11ea-86a5-ce9f06b4e49f.png)
Rather than silently remove the torrent record from Dtv, which would leave no clue to the user that something unusual has happened, Dtv leaves it in place to highlight an event that requires attention.

On Dtv with the Auto-Download enabled, episodes that are within the auto-download period, would  get the ADS to auto start a fresh search for an episode torrent and start a new download automatically.

So your event only applies to Dtv that does not have the auto-download service active, or one whose episode is not within the the auto-download period.

I don't know if we need to do anything about this. I will think on this some more.

BTW, you are on a March 2019 release, there has been many updates to Search engines and torrent client interfaces plus a few bug fixes since then. Consider upgrading today's release from https://github.com/DuckieTV/Nightlies/releases

**Comment by lapd87** [comment]
I get your point maybe just remove highlight if user marks episode as watched?

**Comment by garfield69** [comment]
To remove the download progress bar (on the episodes list), and close the torrent download sub-window (on the episodes detail side panel), and remove the download progress bar (on the calendar), I just need to delete the torrent infohash from the episode record in the DB.
It is the only way to get the job done, and is a simple one line statement in the database markDownloaded(episode) routine.

But there is impact to doing this.
The scenario is where an episode's torrent download is in progress. Clicking on the mark-as-downloaded button would now remove the infohash, disconnecting Dtv from tracking the progress of the torrent on the torrent client.
Without the infohash, Dtv no longer keeps an eye on the torrent progress in the torrent client.
So the torrent on the torrent client continues to download, but does not get auto-stopped (if that setting is enabled) and cannot be removed via the Dtv remove button. The torrent stays active on the torrent client, and keeps seeding forever until the user notices the activity on the torrent client and does something about it.

Another scenario is when the download is completed. Dtv detects the completion, marks the episode as downloaded using the markDownloaded(episode) routine, which removed the infohash, and makes the progress bar and torrent control panel disappear.
But now the user has lost the ability to manage the torrent on the torrent client via Dtv. The user cannot restart the torrent for seeding, or remove it from the client using the Dtv torrent management window.

Things are starting to snow ball.
We've gone from fixing an edge case, to impacting regular downloading completion activity.
I'll mull this over the next few days and see if there is a safer way to manage this, but I'm not hopeful.

**Comment by lapd87** [comment]
if i understand you correctly based on infohash row in db you show or hide progress bar? If so why you don't just ignore infohash and set always hidden if episode is marked as watched?
When do you delete infohash entry from db? upon what condition? maybe if infohash is no longer in torrent client you can update row to 100% or delete only if missing as torrent?

The first scenario you describe I don't see a point of user manually marking episode as downloaded right after starting download... if user does it i believe he will not be interested in the progress anyway... I start download close Dtv then after watching it i delete it from torrent client and after that mark it as watched in Dtv. If meanwhile i have opened Dtv it will refresh torrent status as downloaded if not by marking as watched i mark as downloaded too. Thats why i ask if i mark it as watched to hide/fix/update progress bar.

I believe I have found a solution for my problem by disabling progress bar in settings. For me it will do the trick because I don't use Dtv for torrent start/stop/monitor.

**Comment by AlienProber** [comment]
Myself I click a episode, click find torrent, click the torrent I want, open Qbittorrent to check that it's a legitimate , if it's real I go back to DTV and mark it downloaded before it finishes downloading through QBT, and I never mark it watched in DTV.

**Comment by garfield69** [comment]
The infohash is at the core the way Dtv monitors the progress of the download.
It it not possible to do what you suggest and amend Dtv without a significant rewrite.
Basically it comes down to this: If you launched a torrent from Dtv to the torrent client, then do not delete the torrent while Dtv is shutdown. This is not something users normally do.
You can delete the torrent directly from the torrent app while Dtv is actively monitoring, and Dtv will handle that event. Or you can delete the torrent via the Dtv client monitor panel and Dtv handles that event.
But your scenario of removing a torrent from the torrent app while Dtv is not active is not something Dtv is designed to cope with and is not something I am prepared to spend any more time trying to support.
Sorry, but I am declining your request.
