### ISSUE TITLE
Mark all watched

### ISSUE THREAD

**Issue by EoniLeon** [SchizoDuckie/DuckieTV#1262]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Chrome Extension - New  tab.

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... Stable 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows

**Describe the problem you are having and steps to reproduce if available**
...Since a few weeks ago, one of my shows doesn't stay as "all watched" and a specific chapter, just keeps resetting. I've tried saving new manually backups after marking the chapter as watched even, selecting the show and marking all chapters watched. Next time I open the extension, it pops up unmarked. I've attached a picture of the issue itself.
Thanks!
![Show](https://user-images.githubusercontent.com/66319568/83534563-0fb10b00-a502-11ea-8031-a915946b1f28.jpg)

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
The issue appears to be with the Trakt.tv servers from where Dtv gets all its episode information.
As a control test, I added Rick and Morty to my test Dtv, accessed the series details page, and marked the series as all-watched, then clicked on the refresh button, and s04e07 was reset back to not-downloaded and not-watched.
It seems to be happening only to this one particular episode.
I've randomly added 20 other series, and repeated the mark-all-watched and refresh cycle, and they all remain watched.
So the issue is not with Dtv but with the servers at Trakt.tv and their records for this one series episode. Likely some kind of issue at their end.
If it bugs you you could try reporting the issue at Trakt.tv.
Or just wait and see if they sort the problem out at their end eventually.
There is nothing that can be done about this on the Dtv side.

**Comment by EoniLeon** [comment]
Thanks a lot. No it doesn’t bother me too much. I’ll report it to the, just in case they can do something about it.
Cheers!
