### ISSUE TITLE
uTorrent WebUI password autofills with wrong password

### ISSUE THREAD

**Issue by dukepeet** [SchizoDuckie/DuckieTV#1270]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone 

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Stable 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows

**Describe the problem you are having and steps to reproduce if available**
At uTorrent WebUI integration, the password field is autofilled every time from somewhere with an incorrect password, so if I click "Test and Save" without overwriting it with the password I set in uTorrent, it always fails.
If I put in the correct password in and then click "Test and Save", it connects successfully, but afterwards I still seem to be unable to send anything to uTorrent.
I have no idea where that password is coming from or what it might be, as it does not allow unhiding it even. I assume it might be a password I saved in Chrome or some other browser, but I am unable to track it down.

![image](https://user-images.githubusercontent.com/26721303/89210490-7c0ec000-d5c0-11ea-8537-3f9413683e34.png)

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Several issues here, 1. possible incorrect password, 2. unable to send torrents to client.

Dtv Standalone 1.1.5 is well out of date (publish back in 2017) with regards to its native Search Engines which need updating to handle the changes that most of the web sites the search engines are searching on have changed their domains, or changed their download links.
Also its torrent client interfaces are out of date.
And Dtv Standalone  1.1.5 does not come with the Development Tools package included, which makes diagnosing issues difficult, since you cannot access the log or to bypass the GUI to edit settings.
The author is unlikely to publish 1.1.6 any time soon.

For this reason, the first thing I recommend doing is to upgrade using the latest Dtv Standalone **Nightly** from https://github.com/DuckieTV/Nightlies/releases
This is built by the DuckieTV bot daily from the same DuckieTV repository and has working SE and client interfaces, as well as the DevTools pack which will be helpful in this case for problem research.

- take a Dtv Standalone  1.1.5 backup of your settings and shows using Dtv > Settings > backup
- shutdown Dtv Standalone 1.15
- install Dtv Standalone  **Nightly** which will replace Dtv 1.1.5 program but keep all the settings and shows
- start up Dtv Nightly and check the uTorrent icon on the left hand column of the Dtv page, mouse over it. 
- If it has a **red** dot, and the tool tip states `torrent client uTorrent WEB UI offline` then you are definitely not connecting to the uTorrent WEBUI successfully.
- If this is the case, then press **F12** on Dtv Nightly to access the DevTools, and click on the **console** tab to view the log.
IF you see errors such as
`Failed to load resource: the server responded with a status of 401 (Unauthorized)` or
`GET http://username:password@localhost:8080/gui/token.html 401 (Unauthorized)`
then you know its the password that is incorrect.

- confirm you know the correct password by opening your browser, using http://localhost:8080/gui/ and filling in the *sign in* popup
- if you passed the challenge then fill in the Dtv uTorrent webui interface panel credentials and **test  and save**

let me know how you go.

**Comment by dukepeet** [comment]
Thanks @garfield69 for the thorough instructions! It seems the newer build helped, so I'm closing the issue.
