### ISSUE TITLE
I followed directions/I swear!

### ISSUE THREAD

**Issue by ljhgeist** [SchizoDuckie/DuckieTV#1271]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... **Chrome extension** 

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...1.15

**What is your Operating System (Windows, Mac, Linux, Android)**
...
**Windows 10**
**Describe the problem you are having and steps to reproduce if available**
..**.I followed the directions step by step to connect Vuze and Duckie. It shows connected but when I click to download the show I want to watch it doesn't show up in Vuze. Not on the Vuze remote website either. I pasted in the port 9....something into the browser like it told me to and went to look. Nada**

**Attach any DuckieTV statistics or Developer Console logs if available**
...
<img width="960" alt="Vuze remote" src="https://user-images.githubusercontent.com/70830181/92317810-c2897d00-efb9-11ea-8771-4014eae070f7.png">
<img width="960" alt="Vuze Setup" src="https://user-images.githubusercontent.com/70830181/92317811-c3baaa00-efb9-11ea-815f-be159a6191b1.png">
<img width="960" alt="Vuze" src="https://user-images.githubusercontent.com/70830181/92317812-c3baaa00-efb9-11ea-851a-9b99d576f59f.png">

Those don't look like pics to me. I hope they are when you get them. 

And thanks for your help. I normally would just quit and uninstall everything but I really want this to work

Lyn

**Comment by garfield69** [comment]
Please navigate Dtv to the **About** side panel (click in the (i) icon near the left bottom of the main Dtv page).
On the **About** side panel, scroll down to the **Statistics** section header.
Please provide a screen shot of the first 10 rows or so of the stats.
Thanks.

**Comment by garfield69** [comment]
Hey Lyn, 
I think the issue is most likely with the **Dtv 1.1.5**  Search Engines (SE).

You see, Dtv 1.1.5 was released back in mid 2017, and its SE are now getting quite out of date with changes that the corresponding torrent web sites have made since that release.
For instance, the 1337x web site changed their download links, so the Dtv 1.1.5 1337x SE does not return a magnet when you use it.
Other SE have had their domains changed, or made other HTML changes that make nearly every Dtv 1.1.5 SE broken.
Also the Dtv 1.1.5 Torrent client interfaces (TCI) are out of date with the Torrent Apps  upgrades published since Dtv 1.1.5 was released.

So here is a set of instructions you can try out, to see if you can get things going again.

1. Start your chrome browser **Dtv 1.1.5** and do a Dtv **settings>backup** to save the current settings and shows
2. **Close** the Dtv 1.1.5 tab
3. Access the chrome browser **extension management** page at chrome://extensions/ and
4.  **disable** the Dtv 1.1.5 chrome extension (to avoid app launch confusion)
5. Download the **Nightly** Chrome extension zip file https://github.com/DuckieTV/Nightlies/releases/download/nightly-202007290130/DuckieTV-202007290130-chrome-browseraction.zip
(The Nightly is essentially **Dtv 1.1.6** pre-release. It has the latest working SE and TCI). 
6. Unpack (extract) the contents to a folder location of your choice
7. Access your browser
8. Go to the browser extension management page
9. **Enable** the developer mode switch (top right of that page)
10. Click on the **load unpacked** button (near top left)
11. Navigate the extension directory popup to wherever you put the files from step **5**

if successful, you should see an upside down DuckieTV icon near the right side of your browser address bar

12. **Shutdown** (quit) your Vuze app
13. Start your **Nightly** chrome extension app
14. Wait a minute of two for the pre-initialisation to conclude, then 
15. At the you-dont-have-any-series-yet! Dtv page,
16. **Import** your backup from step 1
17. Once the import is complete, **close** the Dtv tab
18. **Start** your Vuze app
19. **Start** Dtv Nightly
20. And once Vuze is connected, test to see if the Dtv Nightly can pass a torrent to Vuze.

Let me know how you go.

**Comment by ljhgeist** [comment]
Hi Garfield, Wow. Thanks for taking time to put all that in here. I will try putting it into practice a little later this evening it's currently, 5pm PST.  

I hope I manage to do it correctly. Also, I don't know if this will help my process or not, but I don't have my heart set on using Vuze. I have just used it for awhile and had no issues. If something else integrates better I'm all for that. Just lemme know.

**Comment by ljhgeist** [comment]
Do yo u still want the statistics screen shot or should I try what you said first?
