### ISSUE TITLE
Latest episodes not showing in Calendar

### ISSUE THREAD

**Issue by jcgamer60** [SchizoDuckie/DuckieTV#1272]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone (OSX)

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 201912260130

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac

**Describe the problem you are having and steps to reproduce if available**
Latest One Piece episodes not showing in Calandar

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
first thing to try is upgrade your Nightly 
1. drag the DuckieTV app from your applications folder to the trashbin then
2. download the latest from https://github.com/DuckieTV/Nightlies/releases/download/nightly-202007290130/DuckieTV-202007290130-OSX-x64.pkg
3. run the installer.
4. start Dtv. If upgrade was successful, then by cliking the (i) info icon on the main Dtv page near the bottom left should open the side panel and the banner at the top should show **202007290130**
5. then navigate to the One Piece series details page and click on the **Refresh** button. This will force Trakt.tv to send all the info it has for the series.

the latest One piece episode I have is **s21e49(940)**
![image](https://user-images.githubusercontent.com/6933240/92466777-bc4b0900-f224-11ea-9cfb-c9b903d16142.png)

6. something you can do to improve fetching info from Trakt.tv is to navigate dtv **settings>trakt.tv** and scroll to the bottom of that side panel and set the **Trak.tv update period** which defaults to once ever 12 hours, to **1** hour.
![image](https://user-images.githubusercontent.com/6933240/92467192-47c49a00-f225-11ea-9aef-a1b8df51ce84.png)
which will increase the chances of getting updates, in the situation where the trak.tv servers in your region are not responding because of overload or DDoS attacks or network issues, so you try again more regularly.

let me know how you go.

**Comment by jcgamer60** [comment]
It worked! Thanks.
