### ISSUE TITLE
New shows/episodes missing - (i.e. Masked Singer S04)?

### ISSUE THREAD

**Issue by jsmith100** [SchizoDuckie/DuckieTV#1274]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...
1.1.5 Chrome
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...

**What is your Operating System (Windows, Mac, Linux, Android)**
...
Windows 10
**Describe the problem you are having and steps to reproduce if available**
...It appears that some shows are not receiving the latest seasons (new season for Masked Singer, Filthy Rich season, perhaps some others, but haven't really compared yet).

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
This is most likely due to issue #1273 which has yet to be resolved. Follow that ticket for further notifications on solution.

In the mean time the best work around is to access the affected series details page and click on the **Refresh** button to manually fetch a complete data pack for the series.

Or for a more brute-force overkill method, access the Settings>Backup and use the **Refresh All Series Now**
