### ISSUE TITLE
Duckie tv is showing multiple entries on the calendar for the same show.

### ISSUE THREAD

**Issue by tdillabo** [SchizoDuckie/DuckieTV#1277]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...
new tab
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...
V1.1.5
**What is your Operating System (Windows, Mac, Linux, Android)**
...
windows 10
**Describe the problem you are having and steps to reproduce if available**
...
Showing multiple entries on calendar for same show - ...I've tried refreshing the individual show and refreshing all shows but they're still there, the only way I have found to remove them is to remove the show and then reselect it.
**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
its a common problem with trakt.tv's API server database.
Every so often, Trakt.tv changes the episode's trakt_ID (the unique ID for a record) and when you do a series update or refresh, the new records get added to Dtv's DB (since the trakt_ID was not in the DB before), and this leaves the old records as orphans.
While the new records get auto-added to the calendar display, the old ones hang around for a bit.
Usually the orphans are cleaned up. You may need to simply refresh the calendar by displaying another week or month and then back again, and the old episodes should be gone.
In any case, its nothing to be concerned about and there is nothing to fix.

**Comment by tdillabo** [comment]
It has happened to about 6 shows.....they have all got about 4 extra entries for the next few weeks.....I HAVE refreshed and then gone back into them and they are still there.....I have moved forwards and backwards on the weeks and they are still there.....I’m not concerned it just makes the viewing confusing as it looks like I’ve not watched shows that are watched.....I also have it on my laptop and the shows are not duplicated on there so if it is a trakt tv issue then wouldn’t they be duplicated on both??

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by garfield69** [comment]
OK. 
Well if the extra 4 episodes are sticking about, then perhaps these are special (non seasonal extras) episodes?
To help tell them apart from the regular episodes on the calendar,
navigate to the **Dtv > Settings > Calendar** side panel and scroll down 
and **enable** the **Episode Numbers on Calendar** option.
If the episodes all start with **S00**Exx then these are specials.
If you don't want to see these on the calendar then 
set **Dtv > Settings > Calendar > specials on calendar** to **Hide** specials.

If they are not on the laptop then is that because you have _hide specials_ enabled on that machine?

which series are you talking about anyways?

**Comment by tdillabo** [comment]
They are seasonal episodes......  I already had the specials hidden...   It’s ok, I will go into each one and delete it off duckie then re-add it, this seems to fix it but it is time consuming....   I guess it’s one of those bugs that there is no easy fix.   And it is 4 extra episodes for about 10 shows for this week, next week and so on.....   It did not add any extra episodes for past weeks....which I suppose is something to be thankful for.

Thanks for trying to help x

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tdillabo** [comment]
Hello

You helped me before with my Duckie TV and I'm hoping you can do it again.....I've been to github and found your latest upgrade (so I can link to Trakt tv) but I have no idea which of the options is for the standalone version of duckie.....or have you moved back to a browser one?   I'm 60yrs old and not tech savvy at all so if you can just send me a link to the upgrade I would appreciate it.   I use windows 11 and the standalone duckie but I'm happy to move to browser if that is how you do it now.....I hope you can help
Tracey
________________________________

**Comment by garfield69** [comment]
Only the standalone versions of DuckieTV are supported. ;-)
Install https://github.com/DuckieTV/Nightlies/releases/download/nightly-202601300451/DuckieTV-202601300451-windows-x64.zip for your win11 platform.

**Comment by tdillabo** [comment]
Thank you so much, it's worked and I'm linked back into Trakt TV.....you are the best x
________________________________
