### ISSUE TITLE
How to get DuckieTV to open up as new tab in Chrome

### ISSUE THREAD

**Issue by syphondog3** [SchizoDuckie/DuckieTV#1278]
I've used DuckieTV for years, but recently, it stopped updating new shows. I ended up uninstalling the extension and reinstalling with the latest one from Chrome store. Then re-synced with TraktTV...

I later discovered I didn't have to do all that and just had to resync with TraktTV...oh well.

Anyway, since uninstalling/reinstalling, I see that the latest version does not appear as new tab in Chrome. I really want that feature back. 

Anyone know how I can implement that? (that = where I press CTRL + T to open a new tab and the DuckieTV calendar appears...)

**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Chrome Extension

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Whatever the latest one is from the store (as of 10/31/20)

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 PC

**Describe the problem you are having and steps to reproduce if available**
See above

**Attach any DuckieTV statistics or Developer Console logs if available**
Can be provided if needed

**Comment by garfield69** [comment]
The chrome extensions web store is blocking updates from Dtv, so the versions that are currently in the Chrome extensions web store are frozen at whatever release was last allowed by Google. See #1233 for details. 

There are two flavours of the Chrome extensions, the **action-mode**, where an icon is added next to the browser address bar to launch Dtv manually, and the **tab-mode**, which launches Dtv when you open a new tab.

You installed the action mode. I can tell from looking at #1279 that the address is `chrome-extension://cdfkaloficjmdjbgmckaddgfcghgidei/tab.html#/` which is the Dtv 1.1.5 action mode version.

BTW, Dtv **1.1.5** is really out of date, with many Dtv search engines not working, and torrent clients out of date.
For this reason I recommend switching to using the Dtv **Nightly**, which has the very latest fixes, albeit there is a problem outstanding right now with all Dtv versions, where a Trakt.tv change to their API means Dtv cannot automatically fetch updates like it used to do. See #1273 for details.

I suggest switching to the **Standalone Nightly** Dtv from https://github.com/DuckieTV/Nightlies/releases
This is a browser independent version, which because of #1279 makes it the only version currently where you can get the latest fully working version of Dtv, with the #1273 fix when it finally becomes available.

If however you really want to continue using Dtv as a browser extension, then your next best option is to install the **Nightly tab version** as a Development install. see https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-DuckieTV-Chrome-Browser-Extension-NIGHTLY
The only problem with using the development mode on Chrome is the browsers annoying habit of regularly popping up a reminder that the extension you are using is not from the web store anytime you restart the browser.

The source code for all the Dtv versions comes from the same gethub source (this site) and the Nightly versions are built automatically by the bot and published at https://github.com/DuckieTV/Nightlies
The Nightly chrome extension in dev mode will not get pushed updates by the web store, so when you next need to update for the #1273 fix you will need to fetch the Nightly zip again and install over the top to update your code.

**Comment by syphondog3** [comment]
This issue was solved by installing  *.chrome-newtab.zip (newtab mode) from https://github.com/DuckieTV/Nightlies/releases as Garfield suggested.

Thank you and Happy Thanksgiving 2020. Please stay safe from COVID.

Raj
