### ISSUE TITLE
Can't Integrate Duckie TV 1.1.5  with qbittorrent v4.3.0.1

### ISSUE THREAD

**Issue by v643179** [SchizoDuckie/DuckieTV#1281]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows 10 64-bit

**Describe the problem you are having and steps to reproduce if available**
...
Status: Not connected
Error: qBittorrent 3.2+ Connect call failed. 

I set my port to 8090 because I have utorrent set to 8080 and haven't uninstalled it.  I can connect to the web gui using the username and password that I set, but cannot integrate

**Attach any DuckieTV statistics or Developer Console logs if available**
...
![DTV1](https://user-images.githubusercontent.com/74112559/98448892-5247c680-20e4-11eb-8db9-e14393f33f01.PNG)
![DTV2](https://user-images.githubusercontent.com/74112559/98448896-55db4d80-20e4-11eb-80e4-4a5951f0f8ee.PNG)
![DTV3](https://user-images.githubusercontent.com/74112559/98448901-596ed480-20e4-11eb-89cb-75d805f363e0.PNG)

**Comment by garfield69** [comment]
The Dtv Standalone 1.1.5 does not have the support required to connect to any version of qBt newer than 4.1

Your best bet is to upgrade your Dtv to the Nightly version which has the necessary support.
See https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-qBitTorrent-3.2-with-DuckieTV for details about setting up qBt 4.3.0.1 with Dtv Standalone Nightly

I have just completed testing Dtv Standalone Nightly 202009082200 with qBt 4.3.0.1 and I can connect, send magnets and so forth without issue.

Since I support all the torrent clients that Dtv can connect to, I have each one set up on a unique port while I do testing, so using alternate ports from the app defaults should not be an issue.
Let me know how you go.

**Comment by v643179** [comment]
Changed versions to Standalone Nightly v202009082200 Win 10 64 bit.  Shut down qBT and DTV and restarted both.  Re-input u/n and p/w to DTV and port number (I'm using 8090) - 
![DTV logs](https://user-images.githubusercontent.com/74112559/98449976-5d532480-20ed-11eb-80d3-95120589d5fd.PNG)

**Comment by v643179** [comment]
Changed to DTV Standalone Nightly v202009082200 Win 10 64 bit.  I shut down qBT and DTV, restarted both and input my u/n and p/w in DTV and also changed my port number (I'm using 8090) and still no luck.  I am attaching logs screen cap.
![DTV logs](https://user-images.githubusercontent.com/74112559/98450009-b8851700-20ed-11eb-9b89-4359b1725d23.PNG)

**Comment by garfield69** [comment]
Hmm. Strange.
I just tested again. First I set qBt to port 6060, then I shut down qBt and restart  it.
Then I started Dtv, accessed the qBt 3.2+ integration panel, changed the port to 6060 and clicked test.
The first connection failed (expected, because Dtv tries the old API first to determine the qBt version), but a little later it connected.
![image](https://user-images.githubusercontent.com/6933240/98450160-41a85680-219f-11eb-9b64-7a477c84a00f.png)
So I know it can work.
Now, to figure out why not for you.

you had it connected at one point, see 4th line from the bottom of that log you posted.
try again, wait at least 30 seconds after clicking test to see if it manages the connection before giving up and exiting the panel.
if after that it still does not connect, then we can try a brute force attack, by manually setting the config vars.

**Comment by v643179** [comment]
You're right - it worked.  It gave me an error at first but then I waited (something I have a hard time doing) and it popped up and said it was connected.  I tested it with a magnet link from DTV and it connected.  Of course I wouldn't have to do all of this if utorrent hadn't started crashing every few hours.  But that's a whole other story.  Thanks for your help.
