### ISSUE TITLE
can't add favorites

### ISSUE THREAD

**Issue by kartola** [SchizoDuckie/DuckieTV#1285]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
standalone
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly v202011212304

**What is your Operating System (Windows, Mac, Linux, Android)**
windows10

**Describe the problem you are having and steps to reproduce if available**
favorties disappeared (probably the disk run out of space)
i uninstall the program, delete the old folder (in \AppData\Roaming\DuckieTV"
I reinstalled latest nighty
still can't add favorites...

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Seen something like this before.
Either a system clean up, or a 3rd party clean up tool or security tools or something has crippled the data folder for Dtv and now Dtv cannot access its DB because the DB layout settings are gone.
The data folder on win 10 is at `C:\Users\<username>\AppData\Local\DuckieTV-Standalone`
shutdown Dtv, delete that folder and start Dtv again. After the pre-initialisations complete you should be able to add a series again.
