### ISSUE TITLE
FEATURE REQUEST: Limit DTV's poling for new episodes to 2 to 4 weeks

### ISSUE THREAD

**Issue by AlienProber** [SchizoDuckie/DuckieTV#1288]
Current DTV poles for every bit of information it can get from Trakt thus having in my case episode information for shoiws through April. I'm thinking if you can limit the number of weeks out DTV poles more current information can be populated in DTV.

**Comment by Js41637** [comment]
This is not how it works, we don't poll for information for a given number of weeks, we just get shows and all their episodes, whatever dates the episodes have on them is what will be shown on the calendar. Shows can have episodes added months in advanced for certain shows, it has nothing to do with how we get the data.

There is no way to 'limit' the amount of information we get, whenever you add a show we have to get all its seasons and episodes and then we add all of them and in order for DuckieTV to keep content up to date it has to check every show to see when it was last updated and if it was, update all seasons and episodes again. There is no way to limit how much information to get and until recently, Trakt provided no way to make this process easier. 

Previously DuckieTV used a changes system which told you what shows updated within a 24 hour period however they changed how it works and it was no longer possible for DuckieTV to use it which is why it now has to manually check every show which is why updates take much longer. However as I mentioned, recently Trakt did make some improvements which can make updates faster however we have not implemented it yet.

**Comment by AlienProber** [comment]
OK just a idea not know if you could or couldn't implement something like that. I don't mind that the updates take longer since from what I can see I am getting all of my information.
