### ISSUE TITLE
Changeing artwork?

### ISSUE THREAD

**Issue by ShadowDreamer1** [SchizoDuckie/DuckieTV#1290]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone 

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Stable 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows

**Describe the problem you are having and steps to reproduce if available**
Odd Images for some shows

**Attach any DuckieTV statistics or Developer Console logs if available**

![image](https://user-images.githubusercontent.com/75913375/101995534-86ee0580-3cc2-11eb-9244-cd7175aadcd0.png)
![image](https://user-images.githubusercontent.com/75913375/101995543-9705e500-3cc2-11eb-8edb-20aa4bcf9756.png)

As shown some of my shows after a refresh seem to be showing unhelpful or foreign images.  Is there any way of choosing or manually changing what image is shown for a series?  The season images show ok for some as well but not others.

I also experienced a wierd show appear in my list that I had never heard of before and said I had downloaded episodes.  Unfortunately I decided to just remove it from my favorites rather than posting.  Is there any way to see what it was?  I can't see that I am missing a different show.

**Comment by garfield69** [comment]
>As shown some of my shows after a refresh seem to be showing unhelpful or foreign images. Is there any way of choosing or manually changing what image is shown for a series? The season images show ok for some as well but not others.

Dtv fetches the pictures from the FanArt web site. As the name implies, this is posters loaded by volunteers. Sometimes, the only picture loaded for a series will be from volunteers from a particular country who get there first with their posters.
Once other posters get more popular they trickle to the top of the rankings and the next time Dtv does an update the latest most popular poster gets fetched. So to answer your question, no, there is not a manual override option and no intention to spend any time providing one.

>I also experienced a wierd show appear in my list that I had never heard of before and said I had downloaded episodes. Unfortunately I decided to just remove it from my favorites rather than posting. Is there any way to see what it was? I can't see that I am missing a different show.

This can some time happen when Trakt.tv decides to reorganize their API DB and allocate new ids. Its relatively rare but it happens. But once you have removed it from Dtv favourites then you have effectively **deleted** it from your local DB so  its gone.

If you are still on  a Standalone Dtv 1.1.5 then I recommend downloading the latest Standalone Dtv Nightly from https://github.com/DuckieTV/Nightlies/releases, because there is no way 1.1.5 can keep your shows up to date anymore since Trakt.tv introduced rate limiting on their API updates channel. Just install over the top of the old one and you should be good to go.

[edit] correction to punctuation and typos
