### ISSUE TITLE
Show misses episodes from 2,5 seasons and won't reload these

### ISSUE THREAD

**Issue by RAHsite** [SchizoDuckie/DuckieTV#1291]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly v202012132304

**What is your Operating System (Windows, Mac, Linux, Android)**
Win 10

**Describe the problem you are having and steps to reproduce if available**
The show Superstore misses multiple episodes. It stops now at S04E04 and the current episode should be S06E05. See image here:
![afbeelding](https://user-images.githubusercontent.com/75999100/102103478-570f4100-3e2d-11eb-976c-4b9cc2cf08e6.png)

For season 5 and 6 only "Fetching episodes" remark is listed. See image here:
![afbeelding](https://user-images.githubusercontent.com/75999100/102103750-a7869e80-3e2d-11eb-925b-2fbdb2c21bbd.png)

It did work with the stable Dtv version till the issue with the max 100 from Trakt. After that I installed this Dtv Nightly and this show stopt having episodes. 

Steps taken to try and resolve this:
- Refreshing the serie itself, nothing changed.
- Refreshing all series, nothing changed.
- Importing all series from Trakt again, nothing changed. (Trakt has all the current episodes and seasons available on the site)
- Leaving Duckie on for a night to see if the fetching would be done, no changes.
- I've put a back-up back from the end of Season 5 (From late April 2020), and no changes to the serie. It keeps missing the last 2,5 seasons.

I can't find any other series in my favorites that has the same problem, only Superstore.

**Comment by garfield69** [comment]
Its has to be a problem with Trakt.tv's API servers, which are not using the same DB as their Web Online servers.
I loaded superstore for the first time on my test Dtv, and it loaded all eps from S01-S03, but for S04 it loaded only the first 4 eps out of 22, and no eps for S05 (should have been 21) or S06 (should have been 5).

But I know it is not a problem with Dtv itself, since I can load Supernatural, which has 15 seasons and all eps for every season (with about 20 to 23 eps per season) loaded fine.

Therefore, the Trakt.tv API servers are not delivering all the superstore eps.
I fielded a similar report from a user on Reddit who reported similar issue with missing eps for  big mouth, Murder on Middle Beach, and Twilight Zone (2019). But all their other series were fine.

And all I can say is if you want to follow this up on Trakt.tv you could access https://support.trakt.tv/ and post a query. Make sure to specify the series and season episodes that appear to be missing, and that you are talking about the API servers data, and see if you get any confirmation that the data is genuinely missing or if there is a problem there.
