### ISSUE TITLE
[Feature Request] Add Custom Category

### ISSUE THREAD

**Issue by Brodieman** [SchizoDuckie/DuckieTV#1304]
I would like to be able to add a custom category (not the show name) to qBittorrent.  I have a PowerShell script that runs after completions that relies on specific categories.  Thanks for all your work!

EDIT: I would like to be able to do this per show as well.  Some of my categories are TV and some are KTV (kids tv).

**Comment by garfield69** [comment]
Passing a category to qBt was implemented with #705 back in May 2016

Since qBt was the **only** client that supported setting labels (category) via their webui api, and therefore since none of the other 12 clients did not, it was deemed too much work to provide a **custom label** option for just one client.

So the only option that Dtv supports for qBt category setting, is an automated one, where the **series name** is sent as a category if the label option is enabled.

There are no plans to add support for a custom label as there is no one left in the team that is willing to spend that amount of time adding such support.

To enable setting the series name as a label on Dtv, first start qBt, then Dtv and wait for the connection to be established.
Once Dtv is connected to qBt (green dot on the Dtv (qb) icon on the middle left side of the main page), then access 
dtv->**Settings->torrent->torrent label**  and enable that option.

**Comment by Brodieman** [comment]
Thanks!  I'll think of ways to adjust my script to compensate.  I've never really used another client, so I thought that was standard.
