### ISSUE TITLE
Duplicate magnet requests

### ISSUE THREAD

**Issue by IKEAMeatball** [SchizoDuckie/DuckieTV#1308]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 202103142304

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 Enterprise OS Build 18363.1316

**Describe the problem you are having and steps to reproduce if available**
Clicking "Magnet Link" on a torrent sends the torrent request to my torrent client twice. Tested with Transmission 3.0.0 and qbittorrent 4.3.3.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
A very odd event, one that I have not seen before.
After clicking on a magnet to send it to your torrent client, please access the log via **F12** and click on the **console** tab. 
then look for a message similar to
```
Firing magnet URI!  magnet:?xt=urn:btih:6F8CEAFCB8538C1A6C68AFC78377FCCE62981068&dn=Wynonna.Earp.S04E08.720p.WEB.x265-MiNX%5BTGx%5D+%E2%AD%90&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce 4878785 null Wynonna Earp
```
and confirm that you are indeed seeing that message twice, with exactly the same traktid (in my example 4878785)

If you have the Auto-Download-Service anabled, the also access the Auto-Download-Service-Monitor page and check if the ADS is launching the same episode torrent
![image](https://user-images.githubusercontent.com/6933240/111204524-150fba00-862b-11eb-8fc2-fa254c4bc7b0.png)

**Comment by ilike2burnthing** [comment]
I had this happen when I started using DuckieTV (standalone, Windows 10), but I just stopped using the `Magnet link` button (assumed it was a quirk, and wasn't causing any problems). Tried it there, still happens. I'm using uTorrent 3.5.5 (uTorrent Web UI in DuckieTV).

Clicking the name of a torrent, `Download magnet`, or `Download .torrent` (when only a magnet exists) all result in:
```
Firing magnet URI!  magnet:?xt=urn:btih:xxx&dn=xxx&tr=xxx 123456 null null
```
and reference chrome-extension://bagblfnohpiddokbpaacecffdboomafe/dist/app.js:16140

Clicking `Magnet link` results in:
```
Launched external handler for 'magnet:?xt=urn:btih:xxx&dn=xxx&tr=xxx'.
```
and references chrome-extension://bagblfnohpiddokbpaacecffdboomafe/tab.html#!/episode/12345:1

**Comment by garfield69** [comment]
Oh I see. 
You are not using the **magnet download** or **.torrent download** buttons, so you are not going through the **dtv-torrent**-client **interface**.

By using the **magnet link** button you are invoking the **chromium file association to the OS**, and what happens after that is up to the OS and the torrent client, Dtv **is not** involved.

Are you seeing in the Dtv log just the **one** entry for the external handler 
OR
are you getting **two** of them,
OR
**one of each** (launched-external and firing-magnet) entries every time you use the magnet-link icon?

If there is just the one entry, then I can't see what can be done about this, its nothing to do with Dtv as far as I can make out.
But if you get two log entries per click in the Dtv log, then yes, there is something going on in Dtv and I can dig deeper.

**Comment by ilike2burnthing** [comment]
Just the one external handler, nothing else.

**Comment by garfield69** [comment]
Yeah. So that message is from the chromium browser embedded in NWJS (the run time environment that allows our Dtv JS code to run standalone), which posts the info message `Launched external handler`, which means that Dtv is not in control at this point. If Dtv was responsible, you would see the `/dist/app.js` reference.
And since there is only one launched message, this confirms that Dtv only provided the request once to chromium.

What happens after that is between chromium, the OS file association, and the torrent client.

I also see this quirky event, now that I know what buttons to press.
I see my utorrent client receive a magnet, and then I get a chromium popup on the Dtv page asking me if its ok to open the utorrent application, and when I click the open button, I see the utorrent client popup stating it already has this magnet and would I like to add trackers from it.

I have no idea why there are two handovers of the link to the torrent client.
But since Its not Dtv doing it, there is nothing I can do about it.

**Comment by garfield69** [comment]
Did some more digging.
Found #834 which details a problem we had for the standalone, where we had issues using the open-via-chromium in an iframe, and had to switch to using the NWJS submit-via-OS function **nw.Shell.openExternal()** instead to make it work.

But the open-via-chromium in an iframe on nwjs has since been fixed, and switching back appears to submits only once!
So I'll amend the Dtv code and we shall see if that sorts out the problem for all!

**Comment by garfield69** [comment]
[Nightly release for 16-03-2021 23:35:15](https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202103162304)

**Comment by ilike2burnthing** [comment]
Working fine here!

**Comment by IKEAMeatball** [comment]
New Nightly is working fine for me too, thanks a lot for the quick fix!
