### ISSUE TITLE
Search string does not match the season/episode for some TV shows

### ISSUE THREAD

**Issue by ggervais5** [SchizoDuckie/DuckieTV#1318]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 202104262304

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 Pro N

**Describe the problem you are having and steps to reproduce if available**
I noticed this with 2 TV shows:  American Dad! and Black-ish.  For American Dad!, the automatic search and the manual Find is 2 seasons behind.  For the S19E01 episode, the automatic search and the manual Find is two seasons behind (search string is S17E01 and the torrents found match the search string, instead of S19E01).  For Black-ish, the season is correct, but the episode searched for is 2 episodes behind.  Instead of searching for S02E12, the app searches for S02E10.  I have my TrakTV account set up with DuckieTV. 

**Attach any DuckieTV statistics or Developer Console logs if available**
Not unless you want them.

**Comment by garfield69** [comment]
Both of these series are problematic, because the tmdb/tvdb episode broadcast seasons names do not match what the torrent scene uses when representing the same episode.
To try to handle this problem Dtv uses a 3rd party service thexem.de which provide a cross reference for the tvdb versus scene episodes
black-ish http://thexem.de/xem/show/5107
american dad! http://thexem.de/xem/show/4948

Dtv fetches update from thexem.de daily to keep its cross reference table up to date
but if either Trakt.tv is behind with episodes or thexem.de is behind with its cross references then Dtv will not come up with the best match and there is nothing can be done about this.

**Comment by garfield69** [comment]
IF you feel that thexem.de is out of date for these series consider joining #xem on irc.freenode.net and see if you can get them to update.

**Comment by ggervais5** [comment]
Thanks for the explanation. Trakt.tb seems to be OK, but thexem.de is out of whack.  Black-ish season 7 is fine up to episode 4.  Then, starting at episode 5, it shows it as episode 3 and increments from there by 1, creating the offset.  AmericanDad is wrong for all of Season 18, showing them as Season 17 (bad cut-and-paste from the previous season).  I’m not sure how to report this to thexem.de – registrations are closed, so I cannot edit these two shows.  I guess I’ll just wait for someone to fix it.
