### ISSUE TITLE
TV Show Wipeout

### ISSUE THREAD

**Issue by timothymaietta** [SchizoDuckie/DuckieTV#1322]
I'm sure its not Dtv at fault, But Wipeout is listed in th tvdb as s01 of a new show. However the torrent communite has decided to label it as s08 of the original series. I already did the work on my end to manually find them. Just basically want to know if there is something I can do when I see this problem so others dont have to deal with it. Thanks

**Comment by garfield69** [comment]
Dtv gets all its data from the Trakt.tv API servers, which aggregates data from TMDB/TVDB.

And to bridge the gap for when the torrent scene does not match the TVDB/TMDB listings, Dtv uses thexem.de which provides a cross reference service. 

However I just checked and thexem.de do not have the **Wipeout US** series on their DB, so there is not a way for Dtv to automate a Season 1 to Season 8 rename during searches.

I see that there are lots of flavours of `wipeout` in the torrent wilderness, `wipeout Canada`, `wipeout AU` and even `total wipeout` just to name a few series, which will make searching for just `wipeout` quite a problem.

The best I can do to improve matters a little is to add `US` to the `wipeout` default search string to help avoid the chaff, but this will not solve the auto-download automation.
You could consider joining #xem on irc.freenode.net and asking them to add `Wipeout US` with a cross reference for S01 -> S08 , because until that happens (if ever), the only way to download with Dtv will be to use the manual search method :-(

[edit] corrections, add a missing `not` to a sentence.
