### ISSUE TITLE
Duckie no longer works in any  form for macs

### ISSUE THREAD

**Issue by poodleboy** [SchizoDuckie/DuckieTV#1323]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Chrome extension and stand alone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... v202007140130

**What is your Operating System (Windows, Mac, Linux, Android)**
...
mac
**Describe the problem you are having and steps to reproduce if available**
...none of my shows download anymore

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
You are running an old version of Dtv Nightly. 
It is time to update so that you can pick up the new method to fetching shows from the Trakt.tv API servers that changed back in February.
Download the OSX package from https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202107162304
And before running the installer, remember to drag the DuckieTV app from the Applications folder to the trash-bin, otherwise the Nightly installer will silently fail and you will continue running the old version.
Let me know how you go.

**Comment by garfield69** [comment]
closing, presumed resolved without feedback.
