### ISSUE TITLE
Calendar not syncing all favorites

### ISSUE THREAD

**Issue by dajacobs2677** [SchizoDuckie/DuckieTV#1330]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Stable v1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Win10

**Describe the problem you are having and steps to reproduce if available**
Favourite shows are not populating in the calendar (i.e. CBS The Equalizer). This has happened with last season too.

**Attach any DuckieTV statistics or Developer Console logs if available**

**Comment by garfield69** [comment]
Dtv 1.1.5 is extremely out of date, due to changes to the Trakt.tv API (August 2020), which now implements a limit of 1000 calls every 5 minutes, so DuckieTV 1.1.5 packages will not reliably be able to fetch updates for episodes.

Upgrade to the latest supported Dtv Standalone Nightly from https://github.com/SchizoDuckie/DuckieTV/releases/latest
and you should be good to go.
