### ISSUE TITLE
Episodes missing 

### ISSUE THREAD

**Issue by EoniLeon** [SchizoDuckie/DuckieTV#1337]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... 202103162304

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... DuckieTV-Standalone  Nightly v202103162304

**What is your Operating System (Windows, Mac, Linux, Android)**
... Windows NT 10.0; Win64; x64

**Describe the problem you are having and steps to reproduce if available**
... There are missing episodes in the list. I checked on The Movie Database, and they do have them correctly, just not showing on my calendar.

**Attach any DuckieTV statistics or Developer Console log
![TMDB 1](https://user-images.githubusercontent.com/66319568/149666198-25a806ef-abb7-4845-9828-f4a6a0898969.jpg)
![Duckie 2](https://user-images.githubusercontent.com/66319568/149666199-9af85e16-5715-4c7e-af1b-1e4dfbb0710b.jpg)
s if available**
![TMDB 1](https://user-images.githubusercontent.com/66319568/149666198-25a806ef-abb7-4845-9828-f4a6a0898969.jpg)

...

**Comment by garfield69** [comment]
At one point, the Trakt.tv data servers (which is where Dtv gets all its data from) had 3 different entries for the series **Dexter: New Blood**.
```
href="https://www.trakt.tv/shows/191064" href="https://thetvdb.com/?tab=series&id=412279" href="https://www.themoviedb.org/tv/131927"
href="https://www.trakt.tv/shows/191158" href="https://thetvdb.com/?tab=series&id=412366"  href="https://www.themoviedb.org/tv/131927"
href="https://www.trakt.tv/shows/187026" href="https://thetvdb.com/?tab=series&id=412366" href="https://www.themoviedb.org/tv/131927"
```
If you added the series and picked up one of the first two in the list then you will see only 8 episodes.
Only the last entry in the list has the 10 episodes.

So, access your Dtv **series detail** side panel and **remove** that series from your favourites.
Then access the **add a new series** and add the now single remaining **Dexter New Blood** series.
You should see all 10 episodes after that.
You will need to manually set the episodes as downloaded/watched since you are effectively beginning afresh on Dtv with the status of that series.

If you are interested to confirm which trakt.tv version of the series you actually have, access the Dtv **series detail** side-panel, **right click** on the **Trakt** link and select **inspect**, and cross check the trakt.tv show id. if its 191064 or 191158 then you are using the obsolete trakt.tv records. You want to be using **187026**.

Let me know how you go so I can close the ticket or if you need more help.

Also consider updating your Dtv Nightly to 202201131657 to pick up the latest fixes.

**Comment by EloyFarina** [comment]
Hi, I faced this issue with multiples shows. It's very hard to identify which links were added before and are corrupted now because track.tv or thetvdb.com changed the links. users discover this when they already saw more shows than the available.
I would like that developers add an option to check this and fix, or at least indicate which shows require manual user intervention?

**Comment by garfield69** [comment]
>Is there any way to develop a way to check this and fix, or at least indicate which shows require manual user intervention?

Not really. Most methods for determining which series records are valid is by the grey cell method, there are no automated methods which are practical, can keep traffic to trakt.tv manageable without exceeding its rate limit and getting locked out.
Data entry on trakt.tv is a combination of automation and manual correction, and Dtv is reliant on the data from Trakt.tv. 
Trying to build an automated comparison engine using other sources defeats the whole point of using Trakt.tv, which is itself an aggregator of tv show data.
Besides which, there are no developers for Dtv any longer. The author abandoned the project 5 years ago, and I just keep the lights on by fixing what breaks. I do not have the time, interest or ability to re-write or add additional functionality.

Alternate tv trackers are available, such as Sonarr for example.

**Comment by EloyFarina** [comment]
Thanks for your quick response ;)

**Comment by EoniLeon** [comment]
@garfield69 Thank you very much for your fast reply. Indeed, following your instructions the issue has been fixed.
Regards!
