### ISSUE TITLE
Why is it only showing the first three episodes of Hell's Kitchen S20?

### ISSUE THREAD

**Issue by zvit** [SchizoDuckie/DuckieTV#1341]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone 202011202304
...

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Stable 0.49.1, 86.0.4240.111
...

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 Pro
...

**Describe the problem you are having and steps to reproduce if available**
Hell's Kitchen S20 has 16 episodes but DUCKIETV is only showing the first three - why?
...

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Dtv gets all its data from the Trakt.tv API server, which in turn aggregates its data via automated TMDB and manual curation from volunteers.

Alll the TV show trackers that I have checked agree that there are only 16 episodes ATM.
https://en.wikipedia.org/wiki/Hell%27s_Kitchen_(American_season_20)
https://www.imdb.com/title/tt0437005/episodes?ref_=tt_eps_sm
https://www.themoviedb.org/tv/2370-hell-s-kitchen
https://thetvdb.com/series/hells-kitchen-us/seasons/official/20
https://trakt.tv/shows/hell-s-kitchen-2005/seasons/20

**Comment by garfield69** [comment]
Dtv is showing 16 episodes for season 20 for me.

IF you are seeing only 3 listed for season 20, try accessing the Dtv series details page for that series and using the **Refresh** button to force an update.

If the episode list for Seasoon 20 still only remains at 3, then check that the show record you are using the the correct one by right clicking on the Trakt link and selecting Inspect.
The link should show a Href=`https://www.trakt.tv/shows/2356` if you are using the correct show.
If this is the show, then click on the **Console tab** and check the log for errors
If it is the wrong show, then I use the remove from favourites on the series details page, and then go to the add-a-show and search for the hell's kitchen and select the first show with the poster of Gordon.
There are many hell's kitchen shows loaded on Trakt.tv (I see 13 in total :-( and you may be using one of the obsolete records.

**Comment by garfield69** [comment]
You are using Dtv **202011202304**, released in November 2020.
This version precedes a Trakt.tv update to their API server around February 2021 that introduced rate limiting.
This means that the version of Dtv you are using will get blocked by Trakt before it can complete fetching all the show data because it does not have the rate limiting logic included.
Upgrade over the top of your existing Dtv with the current latest Dtv nightly from https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202201301134 and you should be good to go.

**Comment by zvit** [comment]
Updated. Still showing only the first three:
https://bit.ly/3L8K5LL

https://bit.ly/3smY1cc

**Comment by zvit** [comment]
Forget it, I just had to click "refresh" in the series details. Now it shows it all. Thanks.

**Comment by garfield69** [comment]
Good.
you can additionally improve your chances of getting the latest data from trakt.tv by accessing your **Dtv>settings>trakt.tv>Trakt.tv Update Period** and setting to **1 hour** instead of the default _12 hours_.

**Comment by zvit** [comment]
It was already set to 1 hour. I wish there were a way to know that the DTV app had an update. I was two years late to update! Never got any notifacation

**Comment by garfield69** [comment]
The nightly was not set up for notifications because it originally was published daily as a canary release, and you would not want a pop up every day.
When the stable release got broken by google, the nightly became the only source of updates.
Then the author left the project and I've been keeping the lights on with irregular updates, usually when things get broken enough that my Dtv stops working.
I don't have the time or expertise to properly maintain the code, just enough skills to keep the nightly working for now.
