### ISSUE TITLE
"Find a Torrent" button does nothing

### ISSUE THREAD

**Issue by v643179** [SchizoDuckie/DuckieTV#1349]
This issue only appears to be happening with one particular show - "Rich And Shameless" which premiered on 2/18/22.

**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...Nightly v202104302304

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows 10

**Describe the problem you are having and steps to reproduce if available**
...When I try to find a torrent of the 2/18/22 episode of "Rich And Shameless" (s01e01) nothing happens.  Tried using the "Find a Torrent" button and the "Search for a Download" button.  Tried quitting and restarting DTV.  Problem does not occur with other shows.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
As you may know, Trakt.tv stopped using thetvdb as their primary source of show data, and use themoviedb.
however plenty of services still require thetvdb id as a reference, such as thexem which Dtv uses to provide alternate titles and episode numbers, for when the torrent scene differs from thetvdb schedule.
Usually trakt.tv still include thetvdb id in their records, but not in this case.

No worries. I have added the id to the Dtv TraktidTvdbidXref table which I manually curate just for this purpose.
Your Dtv should fetch the latest table within the next 24 hours.
To check, use your Dtv to access the series details page for the rich and shameless series, and look at the info links on the top line on the right side panel. They should contain links to imdb, tmdb, tvdb, trakt.
If tomorrow the tvdb is still missing, click on the series **refresh** button to force an update cycle.

However this is not going to help much , since doing free form search using the Dtv manual torrent search  I cannot find any torrents related to this series or episode :-(
I don't think anyone is uploading for this series.

BTW  I see you are still on v202104302304 you may benefit from fetching the latest Dtv version from https://github.com/DuckieTV/Nightlies/releases/latest to pick up some bug fixes and search engine domain updates.
