### ISSUE TITLE
Duckie refused to execute script

### ISSUE THREAD

**Issue by dadrepus** [SchizoDuckie/DuckieTV#1358]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...
Stand alone build 202206140857
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...
 Nightly build 202206140857
**What is your Operating System (Windows, Mac, Linux, Android)**
...
Mac 
**Describe the problem you are having and steps to reproduce if available**
...
 ducky refused to execute script because of a security issue
**Attach any DuckieTV statistics or Developer Console logs if available**
...
[Develeper Log.txt](https://github.com/SchizoDuckie/DuckieTV/files/8919858/Develeper.Log.txt)
[Develeper Log.txt](https://github.com/SchizoDuckie/DuckieTV/files/8919860/Develeper.Log.txt)

**Comment by dadrepus** [comment]
The end result is no transfer to folders where I have duckie pointed to for each saved show. I end up having to do that manually. A window pops up in transmission asking where to save download, where before it automatically moved it to the folder Duckie assigned it.

**Comment by garfield69** [comment]
So you are running a mac Dtv nightly and you are connected to transmission.
What version of Transmission are you running?
Was it working previously and if so what has changed recently (new OS, new transmission, something else) ?
And you have set up for each Dtv series a download path, which Dtv will send to transmission along with the torrent meta file.
You understand that it is not Dtv that is transferring the actual download? Transmission does the work.
Have you checked the Dtv logs (cmd alt i to open the devtools page, and click on the console tag to view)
can you see any errors during the step where dtv sends to transmission the torrent meta file?
I don't run a mac so I'll try to get my windows VB running so I can start up my Big Sur development image and see if I can get Dtv talking to transmission 3.00 and using file paths to try replicate your issue.

**Comment by dadrepus** [comment]
Transmission is up to date 3.0
It was working before this current update.
I did renew every download path and checkmark with a yellow background, thought it was previously green but who remembers exactly?
Checked DevTools what DuckieTv. It show a 409 conflict with :POST ***@***.***:9091/transmission/rpc ***@***.***:9091/transmission/rpc>
Since I am on a VPN shouldn’t all inquiries be https? Even internal? So, my guess it is sending an enquiry to Transmission and is failing because it is not “https" inquiry? If so, is this something I can fix in DevTools?

**Comment by garfield69** [comment]
>Since I am on a VPN shouldn’t all inquiries be https? Even internal? 

I presume that transmission and dtv are running on the same mac, so if you are using localhost or 127.0.0.1 as the address for dtv to find transmissions' port, then you should not be getting routed through your vpn.

>Checked DevTools what DuckieTv. It show a 409 conflict

just the one time when you first start dtv, or constantly repeating every time dtv tries to send a torrent meta file to transmission?

I'm still working on getting my Big Sur image working properly.
But on my windows10, I can use Dtv 202206140857 with transmission 3.00 and have successfully  tested that dtv can connect and pass on the filepath requests along with the meta file, and track from the dtv calendar or the dtv episode details page the transmission progress to completion, and find the file at the file location specified by the dtv series settings.
So either its a mac thing, or its a configuration issue on your particular mac.

So what is happening on your mac right now is that since dtv cannot talk directly to transmission anymore, dtv will submit the torrent meta file to the mac OS and it passes this on transmission for processing. The mac OS interface with transmission does not support including file path details.
And I would expect that dtv will not be seeing the transmission progress or completion states, and auto set the dtv episode downloaded state either.

so, a 409.
here is my dtv transmission integration page
![image](https://user-images.githubusercontent.com/6933240/174668574-b1da383b-baec-4429-bab1-cd8d638184c0.png)

how does yours compare?

**Comment by dadrepus** [comment]
So, I spent some time looking and the developer console and looked at security. It showed connection to transmission fine, the connection to a site ( not on my desktop so I can’t access the console) that grabbed images for each show did not like http, unable to connect. So the issue for me must be in transmission?  somehow the parameters got changed so what happened is additional pop ups ask me to accept the magic link and determine where it will go. I don’t remember where, when or how that happened. But also once it is downloaded it is suppose to deposit the file into the destination that Duckie chose. It does not. I noticed that after restarting DuckieTv after relinking the folder and checking the link, it may not be saving the link info. I will send you an image.

**Comment by dadrepus** [comment]
New experiment: Downloaded new client qBittorent and did all the things in the tutorial to get it to link too DuckieTv. Turned off Transmission but did not remove yet. Restarted DuckieTv and it shows it is linked to qBittorent both in the left hand column ask well as the admin section. Clicked on a link to download “chopped”. DuckieTv started Transmission instead of qBittorrent. Qbittorrent was already open at the time. Transmission was not.
Any thoughts?

**Comment by garfield69** [comment]
>Clicked on a link to download “chopped”. DuckieTv started Transmission instead of qBittorrent. 

Ahh. This rang a bell, an option I should have thought to get you to check at the beginning of this ticket!
Please access **Dtv>Settings>Torrent>Torrent Parameters** and make sure that this is **disabled**
looks like this when disabled:
![image](https://user-images.githubusercontent.com/6933240/175114300-6f6599ac-de17-4724-826a-6915f70defe2.png)
If enabled it would explain your results.

**Comment by dadrepus** [comment]
Well, I’ll be damn! Had an issue with qBit but worked just as before with Transmission, my preferred client. So…RESOLVED..! Thanks again. You’re the BOSS!

**Comment by garfield69** [comment]
\o/
