### ISSUE TITLE
Feature Request: Override min seeders per series

### ISSUE THREAD

**Issue by winfij** [SchizoDuckie/DuckieTV#1361]
Some of the series I watch have very few seeders (<10), but I don't want to lower the global min seeders too much so I still get decent downloads for popular/current shows.

Would it be possible to add a min seeders override to the series setting screen?

Maybe there's already a way to achieve this I've just not discovered?

**Comment by garfield69** [comment]
What you propose may seem a trivial feature, but in reality this will require a large commitment of my time to complete, as there will be a significant number of components that will need updating, such as: database layout change to the series record, one time migration suite to transfer old records to new the new DB at pre-startup, alterations to the html, css and js to support the series settings page, updates to the 13 language translators, alterations to the auto-download suite, the manual single and multi SE torrent search pages, and probably some other modules I will only discover need updating as the project progresses.

Dtv  has not been supported by the author for over 5 years now, and as the remaining volunteer I don't have the interest and time commitment in my current caretaker role to do more than fix urgent bugs that crop up to keep the app going for my personal use and coincidentally for others when I publish an updated release.

I will put this on the enhancement queue, but the reality is that this is not likely to get implemented due to #1351 which sets a likely end of life date for Dtv at around mid 2023.

**Comment by winfij** [comment]
Right, I figured as much - I was kinda hoping there was already a way to do it I hadn't discovered.

Thanks for the work you're doing to keep it running though!

**Comment by garfield69** [comment]
https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202209031611 
the autodownload service can now use the series custom seeders

**Comment by winfij** [comment]
Awesome - thanks!
