### ISSUE TITLE
TV SHOW EPISODE NOT LISTED IN DUCKIE

### ISSUE THREAD

**Issue by geordon49** [SchizoDuckie/DuckieTV#1378]
DUCKIETV STANNDALONE V202206140857 WINDOWS 10

The show HUDSON AND REX S05E11 is listed in TVMAZE being televised Jan 17 but it is not listed in DUCKIETV.  It is not even listed as upcoming. Is there any way I could go to  HUDSON AND REX  and enter it ?
...

**Comment by garfield69** [comment]
There is no way for you to add an episode manually.
The reason for this is that in order for a record to be added to Dtv you must first have a Trakt_id, and since Trakt.tv does not have s05e11 episode yet, if you make up a trakt_id number you could inadvertently pick an id for some other show altogether.
In any case, any record you manually add to Dtv would eventually be removed by Dtv when it cannot reconcile the record with its daily Trakt.tv update/refresh cycle.

As for a possible reason why the s05e11 episode is not on trakt.tv yet, I note that the broadcaster for this series is CityTV, and their streaming service only goes up to s05e10 ATM. https://www.citytv.com/show/hudson-rex/season/5/
I cannot find any suggeston that the series has been cancelled, so I expect it should show up at some point.

Also, of interest is that TVDB has s05e11 scheduled for Jan 31 so perhaps the broadcast has been delayed for some reason?
https://thetvdb.com/series/hudson-and-rex/seasons/official/5

In any case, if you want to fetch a torrent you can manually search for the episode (I see that there are a couple torrents loaded about 5 hours ago), or you can wait until trakt.tv record the cityTV broadcast whenever that happens and let Dtv automation fetch it.

**Comment by garfield69** [comment]
looks like trakt.tv is up to date now.
