### ISSUE TITLE
Create notification service that checks aired episodes' availability on for download via a configurable service (tpb by default)

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#14]

**Comment by garfield69** [comment]
looks like chrome is about to ditch chrome.notifications [http://mashable.com/2015/10/15/chrome-notification-center/#p6dqhMnlRuqw](http://mashable.com/2015/10/15/chrome-notification-center/#p6dqhMnlRuqw) if this article is correct.

**Comment by SchizoDuckie** [comment]
Nope. They're ditching the annoying notification center that makes you miss
notifications afaict
Op 15 okt. 2015 19:38 schreef "garfield69" <notifications@github.com>:

**Comment by garfield69** [comment]
>Create notification service that checks aired episodes' availability on for download via a configurable service (tpb by default) #14      

I am thinking that this ticket is pretty much obsolete right now.     
The idea raised 3 years ago, was to provide a notification to the user that an episode had become available for download on the default search engine.     
Presumably the user would then proceed to manually search and download the episode in question.     

But since this time we have implemented the auto-download service, which takes care of the whole downloading process automatically.     

Any objections to closing this ticket as `enhancement declined` ?

**Comment by SchizoDuckie** [comment]
Yeah, this is obsolete now. The actual downloaded notification is okay. I'd go nuts if it told me that 7 shows aired yesterday.
