### ISSUE TITLE
Release 20241202 is broken

### ISSUE THREAD

**Issue by ggervais5** [SchizoDuckie/DuckieTV#1434]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 202412021058

**What is your Operating System (Windows, MacOSx, Linux)**
Windows 10

**Describe the problem you are having and steps to reproduce if available**
DuckieTV shows a black screen when run.  Dev tools revealed an issue, but I removed this version and went back to Nightly202411081331 - that works.

**Attach any DuckieTV statistics or Developer Console logs if available**
Uncaught TypeError: Cannot read properties of undefined (reading 'AutoConnect')
    at app.js:11973:34
    at Object.invoke (deps.js:2267:62)
    at deps.js:2269:18
    at r (deps.js:2230:76)
    at fb (deps.js:2268:499)
    at c (deps.js:2244:84)
    at Tc (deps.js:2244:397)
    at xe (deps.js:2243:48)
    at deps.js:2567:241
    at HTMLDocument.b (deps.js:2260:444)

**Comment by garfield69** [comment]
Lets take a look at the logs in full.

- **Right click** and select **inspect**
- **Click** on the **console** tab
- **Click** on the **settings** (cog icon top right next to the three upright dots) , and scroll down to the **console timestamps** and check that box.
- To the right of the filter box is the **default level**s, select the pulldown and **tick verbose** so that it joins info, warnings and errors
- Move your mouse away from the bottom line with the **>** prompt, and over any other blank spot and **right click**.
- If you are on a good spot the options should include a **save as**
- Change the filename to **log.txt** and **save**
- back to the black page
- **Right click** and select **inspect background page**
- Click on the **Console** tab
- if there is anything there then **save** as background.txt
- Email to garfieldsixtynine [at] gmail [dot] com

Thanks.

**Comment by garfield69** [comment]
Also, I take it you are using qBt 5.0.2 ?

**Comment by ggervais5** [comment]
Yes I am using qBt 5.02.  I will have to install dtv 1202 and collect this
info later this afternoon. No screens load at all in 1202.

**Comment by garfield69** [comment]
I've reworked the qbt41+ integration to remove a dependency and tested it on my **win10+qBt502** and **ubuntu24+qbt467** systems without problems. I still cannot replicate your issue.

Please try out https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202412031239 and let me know if you still get the black screen with the _uncaught typeError_ on the console.

In the even it still fails then I can only conclude that it must be Dtv setting that you use differently from my preferred setup, so in that case I'd appreciate if you could email me your settings.

The simplest method for **win**10/11 users is to go back to your working Dtv version, click on the **about** icon bottom left of the main screen, scroll down to the **statistics** section, and **click** on the statistics header. This will **copy** the settings to the **clipboard**. **paste** to a plain text file **settings.txt** and Email to garfieldsixtynine [at] gmail [dot] com
Thanks.

**Comment by garfield69** [comment]
Hold the phone!
I have been able to reproduce the issue, and am working on a solve. I'll post again when done.

**Comment by garfield69** [comment]
https://github.com/DuckieTV/Nightlies/releases/latest should solve the issue.
