### ISSUE TITLE
Distinguish series that have all episodes marked as watched

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#213]
A feature request from my girlfriend (that could add onto the show/hide individual shows / ended shows feature) : She would like it if you can automatically see what shows have all the episodes marked as watched with for instance a status icon in the favorites overview.

Mockup (picture this in the regular favorites view ofcourse)
![image](https://cloud.githubusercontent.com/assets/111710/3576630/53ffa522-0b94-11e4-8920-d8e61101ef86.png)

**Comment by Js41637** [comment]
So how are you currently thinking of doing this garfield?

I started thinking about this when I finished watching a season on my HTPC and it marks the whole season (and show) as watched. So the watched variable obviously needs to be stored. Dynamically checking if everything is watched requires way to much work. The problem I see with it being saved is there needs to be a lot of checking to make sure everything is actually watched in a season to mark as watched and then if all seasons are watched mark the serie as watched but then be able to handle new episodes getting added.

So if a function gets fired when you mark an episode as watched that just checks if other episodes in the season are watched and then mark that as watched and check any other seasons and if they're watched set the serie as watched. This still seems a bit heavy however we don't need to check all episodes (unless they're all watched). As long as one episode isn't watched we know the season hasn't been watched yet.
And when episodes are being added just remove the watched flag on the serie and season updating however this may be tricky if things change. Just limiting it episodes that are added not updated should hopefully not cause problems.

**Comment by garfield69** [comment]
@Js41637 yes, that is pretty much the logic.
If its useful, this is my original logic flow diagram and some pseudo code starters
![ticket-213](https://cloud.githubusercontent.com/assets/6933240/7555290/9387dbea-f79a-11e4-9e0f-d2ed7b2a59ab.jpg)
My first attempt failed because it caused too much IO, written before Schizoduckie created the entity cache in memory.
My next attempt  to calculate it all dynamically failed because it used too much CPU.
I suppose the next attempt would be to resurrect the first one, and make use of the cache and see what happens.
But I am not keen to try again just yet, so by all means, have a crack if you want to :-)

**Comment by SchizoDuckie** [comment]
Awesome :) will test this tomorrow!

**Comment by garfield69** [comment]
5f9a398c0c1508738ce4c6f03935a56f47b61d3e handles user input of the watched/notWatched episode buttons.
TODO: figure an efficient way to set the season/serie watched states during settings/backup refresh, settings/backup import, library trakt.tv add, etc.

**Comment by garfield69** [comment]
This implementation is not 100% with regards to 
- its impact on performance to DB writes during large volume updates (13000 IO have never taken so long before)
- when the series-watched checks are invoked during series updates (import or refresh).
- the side-panel series summary `refresh` button invokes the spinner and never completes. looks like there may be a bottleneck some place, which I don't understand since the settings/backup `refresh all` seems to work just fine, and the code is pretty much identical.
@SchizoDuckie, I think you may need to work your magic over #213, sorry.

**Comment by SchizoDuckie** [comment]
I think that should about do it :)

I'm catching the episode watched events in the episodeWatched monitor, queuing them up until all other database operations are done (by re-setting a setTimeout every time the queryMonitor's done queries != queryMonitor.queuedQueries) and recount all stuff after that. 

Also made the whole thing a bit more readable and found my first use for array.reduce <3

**Comment by garfield69** [comment]
Awesome. The magician strikes again! :grinning:
