### ISSUE TITLE
New trakt.tv v2 API

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#248]
Trakt.tv has a new v2 API coming out soon - boom it's out. Apparently end of October. - was horribly wrong

Changes include;
* oAuth
* API keys and versions sent as headers (cleaner endpoints)
* ETags for less data transfer
* ISO dates with a UTC baseline for everything
* Better min/extended methods and chaining
* Improved organization and standardized output
* Misc fixes and complete website redesign

Apparently they are still supporting most of the API calls from the V1 API but will not include all the features it use to.

For instance, the trending list, cause it obviously needed to be changed

**Comment by Js41637** [comment]
Hmmt not sure.

Weird actually. I tried some stuff to remove the ?xxx however in my logs its showing the urls are empty

![image](https://cloud.githubusercontent.com/assets/6258213/5591801/d97d4a42-91e0-11e4-8e09-822bb38a60db.png)

**Comment by Js41637** [comment]
Ahh my thingy worked though :)
![image](https://cloud.githubusercontent.com/assets/6258213/5591812/26e212b2-91e2-11e4-924d-c9b1035e3795.png)

Also getting a lot of 404s of images on the `http://slurm.trakt.us` image cdn(?)

**Comment by SchizoDuckie** [comment]
Note to self: Get an API key for the new API and get it going a.s.a.p. as I have the feeling that the V1 api is going to stay severely degraded

**Comment by garfield69** [comment]
note: Trakt.tv API v1 is currently not returning the serie.ended boolean so all our serie are marked as `Continuing`. There does not appear to be an alternative to this flag yet... may show up later IDK.

**Comment by SchizoDuckie** [comment]
I'm looking into the v2 api right now. It has some more info on serie
statusses like also when they're still in production. Also, the v2 api has
the season images again. It does however require a lot more http requests
to get to the level of detail that the exended api v1 call, since all
episode details are hidden under a details call for the episode. We'll have
to see how that performs.

The v2 api also has timezone information on airdates airs so that i can
properly solve the problem with finding the correct precise airdates for
daily shows.

**Comment by Js41637** [comment]
Can't you set the level of detail returned when making a call?

Extended Info
By default, all methods will return minimal info for movies, shows, episodes, people, and users. Minimal info is typiclly all you need to match locally cached items and includes the title, year, and ids. However, you can request different extended levels of information by adding `?extended={level}` to the URL.

`min`	Default Returns enough info to match locally.
`images`	Minimal info and all images.
`full`	Complete info for an item.
`full,images`	Complete info and all images.
`metadata`	Collection only. Additional video and audio info.

**Comment by garfield69** [comment]
Does this closure mean Duckietv 0.83 beta is ready for real world tests re: adding/updating series via API v2, or is it still a WIP?

**Comment by Js41637** [comment]
I think it's all working pretty well atm however he hasn't done anything with Syncing with trakt and such as we need OAuth for that and SchizoDuckie doesn't want that so we are awaiting trakts reply to see if we can get token access.

**Comment by garfield69** [comment]
Js41637 said:
> I think it's all working pretty well atm however he hasn't done anything with Syncing with trakt and such as we need OAuth for that and SchizoDuckie doesn't want that so we are awaiting trakts reply to see if we can get token access.
@Js41637  OK, thanks.
@SchizoDuckie  Let me know when you want me to perform some real world tests against the latest beta `angular` repo. I'll stay out of your hair until then :wink:

**Comment by SchizoDuckie** [comment]
I've got one more little bug i believe in adding seasons, then I believe my full import works again (I'll make some tests to verify that each and every property gets set properly based upon the doctor who fixture)

It'd be awesome if you could help think of some tests. They don't even need to be filled yet with the code that actually tests them, but if we can already make a list of scenario's in describe/it form that'd be sweet.

**Comment by SchizoDuckie** [comment]
As of commit 9e883c2057fbc937643c31a9fc6c24124b344bf8 I can successfully import my 'huge' backup without any SQL errors. Please confirm that the database part of this is ready!

**Comment by garfield69** [comment]
Installed DuckieTV 0.83 as a fresh chrome local extension and ran an import on an empty DB. Success! :grinning: 
```
Timers	171
DB Series	171
DB Series Hidden From Calendar	0
DB Seasons	770
DB Episodes	11148
DB EventSchedule	171
```
Browser through the data via the chrome DuckieTV pages, and looked via sqlitebrowser3 all records in the DB look valid and interconnected correctly.
(Shame the series-actors data is missing, may turn up at Trakt.TV eventually).

Any missing TVDB_ID's (Dollhouse s2, simpsons s24, AHS s0) are due to missing data at Trakt.TV.

only other error is the eventSchedule records, whose `data` entities are all similar to:
```
{
  "ID": false,
  "TVDB_ID": 255316
}
```
but since you are going to do away with timers it's not worth pursuing :smile:
