### ISSUE TITLE
Auto Downloads Timer (user being able to change when it goes off)

### ISSUE THREAD

**Issue by ghost** [SchizoDuckie/DuckieTV#293]
I would love to be able to see the option to change when the auto-downloads timer goes off for torrents  and I think it would be nice to be able to change how many seeders it checks for before hand as well just in case some users don't care and having a good 10-15 seeders is usually enough to get a download done in 5 minutes or less anyways.

(this is for both the standalone and the extension)

**Comment by SchizoDuckie** [comment]
would be nice if we had a check every <li-repeat weekdays> and <every <x> hours here.

**Comment by garfield69** [comment]
The option to adjust the seeds was implemented with #360.
and the auto-download kicks off every 15 minutes with e736fdab50568ee0517cb163daf072850ddd3b3a.
Therefore I don't think there is a need to provide an option to adjust the auto-download frequency any longer.
I propose to close this ticket.

**Comment by lonelyfairie** [comment]
I was thinking that maybe not an option to select the autodownload frequency but a requirement to wait X time after release date to look for the episode?
I normally don't leave duckie open overnight due to the fact that sometimes it will download a past episode instead of the newly release one due to looking for the episode too early... for example on the day after SeriesXSeason01Episode10 is to be released I have seen SeriesXSeason01Episode09 downloaded instead when I check my torrent client in the morning, forcing me to delete that episode, unmark it as downloaded in duckie and having to manually look for a new torrent. 
I understand this is a limitation of the torrent search that brings up not only matching season/episodes but sometimes incorrect ones, so setting a "delay" timer on the download after release would probably minimize those occurrences.

**Comment by garfield69** [comment]
The intent is that the auto-download will only pick a torrent if all the keywords in the search list are met, and the number of seeds exceeds the limit set in settings.

If the auto-download is incorrectly downloading (for example) s01e09  instead of s01e10, then that is a bug that needs fixing.
If it is working properly, then a delay timer option should be redundant.

So, if you have evidence that the wrong episode is being downloaded by DuckieTV DEV, then please open a ticket and we will investigate and suqash that bug. Thanks.

**Comment by lonelyfairie** [comment]
Sure, I will be leaving duckie open overnight and document anything I find, I don't have any recent evidence since I have limited download space and was shutting down duckie at night and opening it in the mornings to avoid incorrect downloads. :)

**Comment by garfield69** [comment]
@lonelyfairie  you don't need to leave it up overnight. The Auto-download kicks off every 15 minutes so just start it up when ever its convenient.

**Comment by lonelyfairie** [comment]
Garfield, I know, but the downloading of incorrect files seems to kick off at night due to the fact that it is searching for the episode that just aired before it has been uploaded so the easiest way to see if the issue occurs is leaving duckie open at night so the autodownload can kick off before the episode is uploaded :) 
If I open it in the morning, then it picks up the correct episode as that is already uploaded.

**Comment by garfield69** [comment]
I see. Thanks for the update.
