### ISSUE TITLE
SYNCING!!!

### ISSUE THREAD

**Issue by lola-l** [SchizoDuckie/DuckieTV#315]
Seriously I have no idea what you guys have done with this thing but none of my shows are syncing anymore to my trakt.tv having to do this manually is very exhausting please fix this!!!

**Comment by garfield69** [comment]
Sorry, but It's out of our control.
Trakt.TV have been through a complete renewal, upgrading their server hardware, their web services, and implementing their v2 API, but have accidentally broken their v1 API  in the process.
Since DuckieTV is not ready to start using API v2, we and all other v1 API apps are stuck waiting on Trakt.TV to fix their problems.
Switching to v2 API is not a trivial change, so we are dependent on Trakt.TV resolving their v1 API issues ASAP.
  ----- Original Message ----- 
  From: lola-l 
  To: SchizoDuckie/DuckieTV 
  Sent: Tuesday, January 06, 2015 2:09 PM
  Subject: [DuckieTV] SYNCING!!! (#315)


  Seriously I have no idea what you guys have done with this thing but none of my shows are syncing anymore to my trakt.tv having to do this manually is very exhausting please fix this!!!

**Comment by lola-l** [comment]
Wow!! That is terrible! They just left you all out in the cold! Well you guys should make a major complaint about to them because its messing up business.

**Comment by Js41637** [comment]
As mentioned, this is a trakt.tv issue and their v1 api. The next release of DuckieTV should fix most of the problems trakt has caused us.
