### ISSUE TITLE
Black-ish Not Adding

### ISSUE THREAD

**Issue by kuriakosesaju** [SchizoDuckie/DuckieTV#325]
I've been trying to new Lawrence Fishburne comedy Black-ish for a week now but it never updates. Instead, the yellow wheel just keeps spinning and spinning.

**Comment by garfield69** [comment]
what version of DuckieTV are you using, and on which version of Chrome?

**Comment by kuriakosesaju** [comment]
DuckieTV 0.82
Chrome Ver 39.0.2171.95 m

**Comment by kuriakosesaju** [comment]
This is on Win 8.1

**Comment by garfield69** [comment]
OK thanks for that.
You may not be aware of the issues that DuckieTV's data service provider Trakt.TV has been having since the start of the year. see [Trakt.tv upgrade] (https://www.reddit.com/r/duckietv/comments/2rywub/traktv_503/)  and [Trakt.tv API] (https://www.reddit.com/r/duckietv/comments/2rxbxi/tvdbs_database/) for more details.
Very likely your Black-ish problem is due to one or both of the above.
The guys at Trakt.TV are working hard to fix all their problems, and in the mean time Schizoduckie is busy coding DuckieTV to use the new v2 API. 
That is all we can do for now. :-(

**Comment by kuriakosesaju** [comment]
Thanks buddy! The quick support was not something I expected! DuckieTV
rocks!

**Comment by garfield69** [comment]
No worries. You just happen to be posting while I was online at GitHub :-)
