### ISSUE TITLE
KAT Mirror doesn't work

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#352]
KATs .so domain recently went down and has reverted to .to, updating the KAT mirror in the settings saves it however searching KAT still uses the .so domain.

**Comment by garfield69** [comment]
:-D
In order for your change https://github.com/SchizoDuckie/DuckieTV/commit/3f8e31ce21adae7f56136af0566c53276c7e9cd6#diff-15e82d6f03b49c1e031c1e8242c6b184 to actually take effect, you first have to go to the DuckieTV Settings page and switch the default search provider out of KAT and back again.
That's because while you have may changed the settings code, your DuckieTV instance has yet to change its local storage ;-) 
  ----- Original Message ----- 
  From: Js41637 ftw 
  To: SchizoDuckie/DuckieTV 
  Sent: Tuesday, February 10, 2015 1:54 PM
  Subject: [DuckieTV] KAT Mirror doesn't work (#352)


  KATs .so domain recently went down and has reverted to .to, updating the KAT mirror in the settings saves it however searching KAT still uses the .so domain.

**Comment by Js41637** [comment]
Oh I'm not talking about the commit, In the public version of DuckieTV, saving a new KAT mirror works but searching KAT still uses the original one in the code.

**Comment by SchizoDuckie** [comment]
the search provider grabs it's settings from file now. I believe i've
phased out the localstorage solution for this exact reason

**Comment by garfield69** [comment]
%-| 
Don't understand.
How does settings kickasstorrents.mirror interact with torrenting.genericClients ?

**Comment by garfield69** [comment]
So if I understand this right, with the implementation of TorrentSearchProviders.js we lost the ability to override the kat mirror via the settings page.
Was that intentional?

**Comment by SchizoDuckie** [comment]
yeah I agree that the showrss injection is a bit of a hack. i need to refactor this in a decent way. Todo list is getting longer and longer though, we could really use another experienced coder on this project
