### ISSUE TITLE
performance: one-time bindings throughout and for translations 

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#357]
Reload page on changing languages. then we can use one-time-bindings for the translations

**Comment by Js41637** [comment]
c35ace4ab76a4a44ca371bb121ed4651307fc4da & https://github.com/SchizoDuckie/DuckieTV/commit/7a8dbef3ed79b90725ede73015f85c4214ed9e7c apply one-time bindings throughout.

**Comment by Js41637** [comment]
Just a few notes, things such as ng-repeats should be under an ng-if where possible because we don't need them doing anything until they are needed. Things where the data changes like the trakt-sidepanel which updates for each serie you hover cannot be one-time binded as the data is constantly changing. Most things inside ng-repeats can be one time binded as each repeat is it's own thing and they are unlikely to change. Also these can only be applied on things inside {{}} that make direct references to data. like `{{::serie.name}}`. They cannot however be inside functions like `if (serie.name)`. They can however be inside the functions that fetch a name like `{{::getTooltip()}}` however in the case of tooltips they can change like the mark as Watched/Downloaded so a one-time binding cannot be used.

**Comment by SchizoDuckie** [comment]
I haven't noticed any problems. Anybody against closing this?
