### ISSUE TITLE
search strings for specials

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#373]
as suggested in [Reddit](https://www.reddit.com/r/duckietv/comments/2wajz3/feature_request_or_help_search_for_and_display/), for specials, load the search string to use just the episode title, as series name and s00eNN does not apply in almost all cases.
>TomTom131313 
>Search formats are a very good idea, the other thing I have noticed is that the special episodes do't show up searching for the format S00E11 for example.
Would it be possible to substitute the search string to include the title of the special episode but only for this type of content ??

**Comment by SchizoDuckie** [comment]
I'm wondering if this applies to all shows, or just a few, and i'm worried about the amount of spam you'll get when search by episode title. This is definitely not something i'd pass to the 'perform magic' function

**Comment by Js41637** [comment]
I think most specials use the names but some don't. Not sure if this is within our control to try and support. And the numbers can change sometimes as well if the tvdb rearranges some stuff which does happen with shows that have tonnes of specials such as Top Gear. 

Could just have a setting or maybe make it a little smarter and search the special number and if there is no results have it try the special name.

**Comment by tomgould** [comment]
I haven't done enough testing myself to have a good enough view as to whether this applies in enough cases to make it worth while to be honest.

The case I notices was with the latest GoT special, When I searched last week using the default functionality "Game of Thrones S00E11" produces no (incorrect) results so I added the title instead of the episode id "Game of Thrones  A Day in the life",  this got me what I wanted but this is not always successful, eg Fast N' Loud, I tried the same logic on a few of the specials for this show and still have no results.

Probably not worth exploring too deeply as there is no defined standard for the specials ;(

**Comment by SchizoDuckie** [comment]
Yeah I figured as much. I'm going to close this as a wontfix because it's an edge-case and you're still helped with just typing a custom query in most cases :)
