### ISSUE TITLE
Add support for uTorrent WEBUI client

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#428]
I believe WEB API docs are [here](http://help.utorrent.com/customer/portal/topics/664593-web-api/articles)

**Comment by garfield69** [comment]
[Reddit](https://www.reddit.com/r/duckietv/comments/3644ab/utorrent_connection_running_on_another_pc/) cross-reference.

**Comment by Js41637** [comment]
Gonna post this here instead of new issue also not sure if its just related to uTorrent but it's all I use and also not sure if this has been fixed but does the 'Show Files' thing in the TorrentClient work for uTorrent now cause it is currently broken and needs work. It current (attempts) to list files by default ignoring the 'Show FIles' button.

It attempts to show some files or something even though the numbers don't add up;
![image](https://cloud.githubusercontent.com/assets/6258213/7877317/a6f0f38e-061c-11e5-8d4d-c218166456a7.png)
but it still doesn't include any file names.

**Comment by SchizoDuckie** [comment]
Add magnet, fetching files and upload torrent from file works. closing and fixed!.
