### ISSUE TITLE
New show title not loading to favorites when clicked. 

### ISSUE THREAD

**Issue by dogsivu** [SchizoDuckie/DuckieTV#442]
Dead End Express shows up when I type it in, but fails to load as a new favorite. See link: 
chrome-extension://cdfkaloficjmdjbgmckaddgfcghgidei/tab.html#/favorites/add/search/dead%20end%20%20express  
So far this is the only bug I have encountered and I am using (and loving) this app every day! Thanks (again)  !  Mike (dogsivu on reddit)

**Comment by garfield69** [comment]
I get this too.
The problem is with Trakt.TV's database which DuckieTV fetched data from.
Their Series header record for `Dead End Express` is missing the TVDB_ID, which is critical for DuckieTV to have for its own internal use.
Therefore DuckieTv rejects the fetched data.
![image](https://cloud.githubusercontent.com/assets/6933240/7717717/01ba0b40-fefa-11e4-806f-405417ca8a4d.png)

**Comment by garfield69** [comment]
Trakt.TV now have two entries for discovery channel's DEAD END EXPRESS.
The one with the poster is the original, and still missing the tvdb_id, so is no good to us.
However, the second one, without the poster does load on DuckieTV and has all the episode data so far.

**Comment by dogsivu** [comment]
Thanks!



 - Mike Owens

------------------------------
*Harvey's Paint and Body*
desk: 214.526.1363
fax::  214.526.8559
mail: mike@harveyspaintandbody.com
web: harveyspaintandbody.com <http://www.harveyspaintandbody.com/>
