### ISSUE TITLE
clever track.tv update

### ISSUE THREAD

**Issue by lamaresh** [SchizoDuckie/DuckieTV#447]
every day when i open trakt.tv i have a looong db update. Is it possibile to enhance update system to only push to trakt.tv series and episodes changed ofter the last update?

Maybe some of that time is also spent to upgrade episode list, maybe series should be downloaded only if they were updated on track.tv since last application check (can this be useful? http://docs.trakt.apiary.io/#reference/shows/updates/get-recently-updated-shows )

**Comment by SchizoDuckie** [comment]
Acually, this is what we already do. the reason you are seeing so many updates is that it's fetching the updated episode list and updating properties stored locally

We're still tweaking the values updated, most of them are new ratings coming in. I'll relax the filter on those limits a bit so that it ignores the next 100 or so coming in. This should help things die down a lot.

Also, in the next update you can choose to completely ignore the ratings, that should work even better if you're not using them anyway.

**Comment by lamaresh** [comment]
i only use duckieTV, i never open trakt.tv
