### ISSUE TITLE
Add a show Trakt Trending/Search/Sidepanel issues

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#449]
When adding a show to the library using the trending search box, Dtv behaves a little peculiarly.
It happens after the user has filtered the trending list via the search box, and clicked on the series to add it to the library.
[shot just before the click]
![image](https://cloud.githubusercontent.com/assets/6933240/7845616/22aa8358-050c-11e5-8c21-b07b3921731c.png)
[shot after the click]
![image](https://cloud.githubusercontent.com/assets/6933240/7845646/44e5b8f2-050c-11e5-9a7d-9f771074bcf8.png)
So Dtv returns to the library list view, but leaves the preview sidepanel up with a `loading` header.
IMO, It should either:
a. stay on the filtered list page and show the clicked poster has having been added (with the green tick)
or
b. having switched back to the library list, close the preview panel.

**Comment by Js41637** [comment]
Can you verify if this is still a bug with the current Github version. I believe I might have already fixed it or something similar.

**Comment by garfield69** [comment]
![image](https://cloud.githubusercontent.com/assets/6933240/7850877/d0daae4c-053b-11e5-8c46-158c0704bc2a.png)

**Comment by garfield69** [comment]
Yup, on the latest schizoduckie/DuckieTV version of the angular branch. Last commit is 8d6c6da0ddfef6861192310fb89c2a0ba6f0529a.

**Comment by Js41637** [comment]
So clicking a serie goes back to the library. I don't get this issue.

**Comment by Js41637** [comment]
There are some other weird things that I don't quite understand.

**Comment by Js41637** [comment]
There are some other things I don't quite understand either.
* The trakt sidepanel doesn't hide when returning to library, can be fixed by manually closing it by putting an ng-click on the back button to close sidepanel although I imagined it should already do this via the states.
* Once the trakt sidepanel has been opened (and closed). Opening it again is no possible despite it going to the 'trakt-serie' state it refuses to open again. It can however be tricked if you open a serie in the library view and then click Add a Show it remains open and the panel works as normal.
* Turns out I still don't really understand states because from what I see this stuff shouldn't be happening because of what's meant to happen in the app.routes when favourites or trakt-serie are loaded.

**Comment by garfield69** [comment]
The sequence is:
go the the add-a-series page
enter something in the search box
click a found series to add it to the library
watch what happens.
 


  _____

**Comment by Js41637** [comment]
Yeah clicking a serie already added just glitches the sidebar to show the 'Loading' thing on top but that's all that happens for me.

**Comment by Js41637** [comment]
EDIT: ok it just started doing it, weird. Anyway, I know the issue, I fixed a similar issue for the trending, `no-button="1"` needed to be added although it use to default to 1 anyway so not sure what changed.

**Comment by garfield69** [comment]
well maybe its a chromium 43 on XP thing.
@schizoduckie, what happens to you when you add a new series via the trending search box?

**Comment by Js41637** [comment]
Ok so I just fixed this issue with it going back to the library. Also fixed the sidepanel not closing when returning to the Library using the back button but I did it the manual way, not sure how to do it the prober way with the states.

**Comment by garfield69** [comment]
nice one.
Can you figure out why, from the library page or trending page, when you click on the ABOUT icon, all that happens is you get the calendar?

**Comment by garfield69** [comment]
@Js41637. An unintended consequence of your change 5691622f21b6081ba424c5de262515883798f24d  to the sidepanel not closing when returning to the library, is that if you subsequently revisit the trending list the sidepanel with the preview does not open again.
Also, while all the other preview details change as you hover over each poster, the preview description does **not** change.

**Comment by Js41637** [comment]
Actually that bug already existed just not really noticeable before because going back to the library didn't close the panel but if you went to the Calendar and then tried to add a show again, it won't open and I mentioned it above, not sure what is stopping it from opening because it is meant to open.

Also I will fix that overview not updating as well. Ma bad.

**Comment by Js41637** [comment]
Cause of the bug is because trakt-serie is stickied so it doesn't get 'refreshed' (resolved again) because it's a child of Favourites and a sticky doesn't get cleared until the parent is closed. Although why it still doesn't work when the favourites list is closed and opened again i'm not sure.
