### ISSUE TITLE
Shows not updating

### ISSUE THREAD

**Issue by Spudguy1** [SchizoDuckie/DuckieTV#466]
I've got a weird one, running the latest version on Chrome and shows aren't fetching the latest episodes unless I manually hit "Refresh" under series details?

**Comment by garfield69** [comment]
I think that to help diagnose the problem you may need to keep an eye on the ABOUT page statistics and the console logs.
Click on the ABOUT icon (i) and scroll down to the statistics section, and make a note of the `DB Episodes` count.
Then press the `F12` key to bring up the `Development Tools` window, and then click on the `console` tab to view the console logs.
Keep an eye out for the following messages:
if you get `Not performing trakttv update check. already done today.`  then you will not get an update. Another update could take up to 24 hours to occur.
if you get `TraktTV update check completed. <n> shows updated since <date>` then check back with the statistics to see if the `DB Episodes` count has increased.
If it has not changed, then upload a screen capture of the statistics page, and the console log, especially if it contains any error messages.
If however the `DB Episodes` count has increased then everything is operating as expected.

**Comment by Spudguy1** [comment]
Hi,

Thanks for your help. This is the screenshot. http://puu.sh/iyaMu/67def1875a.png

It looks like it's got an invalid date in there somehow?

**Comment by Js41637** [comment]
Last checked 6 days ago? oh boi

**Comment by garfield69** [comment]
@Js41637  ah no, that is the trending update stamp. ;-)
we are interested in the trakt.tv update stamp which the ABOUT statistics indicates is null.

@Spudguy1 You have fallen foul of the 'missing trakttv.lastupdated' bug which commit 738173945156f67946162e8fb18faddbe216c5af fixes in the next release of DuckieTV.

to fix manually, you need to go to the console (F12 and select the console tab) and issue the following command at the command line prompt ( >  ):
`localStorage.setItem('trakttv.lastupdated', new Date('2015-06-16').getTime())`
then close DuckieTV and start it up again.
This should kick off the Trakt.tv update cycle and you can put this issue behind you.
Please Let me know how it goes.

**Comment by Spudguy1** [comment]
Fixed! Thank you so much. I love you guys.

**Comment by Spudguy1** [comment]
Whilst I'm here, does anyone have any idea why the same episodes are being added multiple times? Specifically to Big Brother right now:

http://puu.sh/iyhtC/1ea934b9c1.jpg

**Comment by garfield69** [comment]
If you hover your mouse over each Big Brother UK event in the same calendar day box, you will see that they have a different season number. ;-)
For instance, for June 17 (NZDT) the first Big Brother is S16E36 and the second is S17E36.
So the Trakt.TV database contains a fractured season 17 whose episode dates line up with season 16.
Nothing DuckieTV can do about that.
