### ISSUE TITLE
DuckieTV 1.1.0 DEV episode list eye-close glyph tooltip issue

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#479]
Clicking on the eye-close glyph on an episode in the episodes list is near impossible because the tooltip gets in the way.
This does not happen for the open-eye, or the floppy-disk and floppy-saved glyphs.

related templates: episodeWatched.html episodeDownloaded-html sidepanel.episodes.html

tootip OK
![image](https://cloud.githubusercontent.com/assets/6933240/8439295/3b90071c-1fbf-11e5-9ca8-aaa254c2b3dc.png)
tooltip in the way
![image](https://cloud.githubusercontent.com/assets/6933240/8439314/52a18bd8-1fbf-11e5-84f5-4a6d3b703d4c.png)

**Comment by SchizoDuckie** [comment]
Assigning this one to @Js41637 since it's probably one of his manual tweaks that are now conflicting with the improved handler

**Comment by Js41637** [comment]
Interesting, this appears to another one of those lovely tooltip issues, and it's not my fault for a change. My best guess is either the size of the tooltip or the way it gets its text loaded which is slightly delayed because after receiving the text it needs to update its position again.

Anyway, found a fix.

**Comment by Js41637** [comment]
I don't really know why this fixes it. Confirm?

**Comment by garfield69** [comment]
Confirmed. Thanks.
