### ISSUE TITLE
Store DuckieTV's Window position

### ISSUE THREAD

**Issue by phoenixcomm** [SchizoDuckie/DuckieTV#509]
I have a two monitor set-up.. and it likes to come up between monitor 1 & 2. If you drag it, that's ok.
but if you change to monitor 2 (on the left) you cant get to monitor 1 with out the window from going away. then you have to get in a terminal and kill the 4 or 5 possesses.
My system is LinuxMint 17 based on Ubuntu. why cant you put in the settings.. my monitor preference.

**Comment by SchizoDuckie** [comment]
That's a feature we haven't implemented before simply because we didn't have any request for it. But I think it can be a good one :)

Even better would be, I think, if we store the window position that you close DuckieTV at, and reopen it at that position with the same window size (I believe this should be possible)

That way, after the initial run, your problem is solved, and we don't have to create code that enumerates how many monitors you have.
