### ISSUE TITLE
Integrate XEM into DuckieTV

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#520]
Xross Entity Map

> The Xross Entity Map for TV shows
> xem helps you keep an overview of your shows on different websites.
> Many websites use different numberings, names and season titles for the same show.
> xem lets you create a map for an easy overview of all the different counting and naming systems.

Example API call for American Pickers:
http://thexem.de/map/single?id=141181&origin=tvdb&season=2015&episode=2&destination=scene

Mirror (much faster): http://thexem.de.rajatorrent.com/xem/shows

**Comment by SchizoDuckie** [comment]
> <ll> i think the idea is to query http://thexem.de/map/havemap?origin=tvdb
> <ll> and cache that

We can cache that list on github pages and update it regularly to offload their API.

**Comment by SchizoDuckie** [comment]
Sweet stuff. Just tested this with Pawn stars and it's awesome.

We may need to tweak some things. there's scene and sometimes scene_2 exceptions, because the scene is not a perfect matrix brain yet. 

I requested an account for Xem on IRC so we may be able to help enrich the data by stuff that's reported by duckietv users (for instance, treehouse masters was only added last week, no mappings yet, so the default getFormattedEpisode is returned for each show)

To remove the load from the scenameresolving (it doesn't have to actually do a lookup until a torrentdialog is launched for an episode) 

I changed the templates to always just return episode.getFormattedEpisode for where we show them on screen and made the torrent search itself resolve the actual SceneName and XEM mapping. There shouldn't be any problems with that other than that the data shown to the user is consistent with what's in the DB until a torrent search is executed.

![image](https://cloud.githubusercontent.com/assets/111710/9262975/83faabca-4219-11e5-925f-6a7a92fe2db8.png)
