### ISSUE TITLE
DuckieTV Standalone 1.1.3 DEV Uncaught TypeError: Cannot read property 'setItem' of null

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#524]
I am still getting issues from within the app.standalone, when I try reading or writing to localStorage.
It starts off perfectly fine, but after an undetermined amount of time, eventually I start seeing these `setItem` or `getItem` property errors.
![image](https://cloud.githubusercontent.com/assets/6933240/9081548/36d8b7ec-3bb1-11e5-8b29-c7393c309366.png)
They began with the changes I made for #509, and I thought 6837adfb3defef77f0caa5e05a30f1f0753c993b had resolved the issue, but clearly that is not the case.
I am not sure how to go about debugging this, as I don't understand why the standalone code should suddenly loose access to the localStorage object.
@SchizoDuckie  Any thoughts on this?

**Comment by Js41637** [comment]
Why don't you just save the position on application close?

**Comment by SchizoDuckie** [comment]
You're probably losing the localStorage as soon as you open the about page?
Ergo, you're modifying or replcing localStorage with somethiinig that's not
localStorage.

Look for assignment operators instead of double equals (bla = blerp instead
of bla == blerp) and typo's like that.
Will take a deeper look for you tonight!

**Comment by SchizoDuckie** [comment]
Allright, I refactored some stuff here since I couldn't really wrap my head around what was happening and app.standalone.js was really getting too big. I implemented @Js41637 's solution by just storing the window position on app exit, removing the need for the window resize/move handlers and chose to completely ignore the window maximized state.

I made this code run as early as possible so that the window jumps into position nicely (we could possibly run even earlier now by embedding it in package.json' s [inject-js-start](https://github.com/nwjs/nw.js/wiki/manifest-format) but i wanted to make it work first :)

On top of that I removed the angular dependencies for all of this code except for the update check (since we need $http and $dialogs there anyway)

This also means that the controller that was used in tab.html is now gone and it's just some simple DOM manipulation that only gets attached on DOMReady

Haven't seen any unexpected behavior yet, so please give it a shot!

Oh yeah, I also possibly fixed the issue reported on Reddit where DuckieTV for mac creates additional duckies in the systray :+1:

**Comment by garfield69** [comment]
*      Allright, I refactored some stuff here since I couldn't really wrap
my head around what was happening

I'm glad because I was starting to feel stupid ;-)

 

  _____

**Comment by SchizoDuckie** [comment]
Working sharp. thanks for catching my errors

**Comment by SchizoDuckie** [comment]
note on multiple duckies

We should execute that code from node instead of chrome so that window.location.reloads are not affecting them.
https://groups.google.com/forum/#!topic/nwjs-general/eDxaz_EbvHs
