### ISSUE TITLE
Request to add custom scheduling

### ISSUE THREAD

**Issue by roshavagarga** [SchizoDuckie/DuckieTV#535]
As mentioned in #534, some shows do not appear to have their proper timeslots even if they are correctly set in thetvdb.com. Since the creation of protocols to use a custom API  is too troublesome as seen in the previous ticket, my current suggestion is to implement an option to turn off the automatic scheduling for a specific show and give the users the option to set the dates and time for that series' future episodes.

This would be a dirty way of fixing the scheduling problems with thetvdb. Theoretically it could also include a limit of episodes that can be turned off for scheduling. I think that doing this for a number of episodes is the best way, as some shows (One Piece for instance) generally push out episodes throughout most of the year on a weekly basis, so it will be impractical to use an "set this schedule for X season's episodes" option. 

An added bonus of this feature would be giving the ability of users to switch over their episodes' autodownloading to select days. (i.e. TV Series 1, 2 and 3 come out on monday, wednesday and thursday, user X watches them on saturday afternoon. User x changes their scheduling to saturday morning, they autodownload then instead of during the week when somebody else may be using user X's internet, while he is at work).

A part of this feature's needs would be to have the option to set a TV Series Custom Title Search, as torrent creators do not always follow the exact naming scheme or episode/season numbering as seen in thetvdb and trakttv.

**Comment by Js41637** [comment]
This isn't really my area and I'm not sure exactly how the current stuff works but to my knowledge DuckieTV just uses the air date it gets from Trakt.tv (which gets its data from (mostly) TheTVDB) and implementing a feature to be able to edit the dates and times of episodes air dates sounds like it will make things overly complicated and complex because of data we receive that it outside our control.

However more control over AutoDownload for series is something we want to work on and improve as well as custom search strings for series which we already try to handle for series with different naming conventions but being able to manually specify a search string for a serie would be a good idea as we won't be able to add correct naming schemes for all series.

**Comment by SchizoDuckie** [comment]
Turning off the autodownload for specific shows and custom searchstrings has been implemented recently in the latest dev builds:
  
![image](https://cloud.githubusercontent.com/assets/111710/9442385/0695992c-4a7c-11e5-8c58-76884e5d3274.png)

Scheduling options per show or globally could be added in the future indeed, but i'm not really feeling the complicated options you mention like turning it off for x episodes.

I'm really not in favour of setting custom download dates per individual episode as a hacky workaround though. That would be a very limited use-case feature (basically we would build it for you)

If you have a perfect bridge between the thetvdb and anidb, somebody should put effort into automatically pushing data to thetvdb from anidb. That solves the problem at the source.

**Comment by roshavagarga** [comment]
Happy to hear the custom search string has been implemented. Out of pure curiosity, does it feature adding just a new release group/name or will I be able to also set a new season/episode string (for animes, since they do not conform to the S01E15 format as previously mentioned). Without that autodownloading won't work for shows that don't follow the above-mentioned format. 

I am not really interested in autodownloading of shows or custom download dates, I do my downloading myself. My personal problem is the scheduling slots not being correct - they are correct in thetvdb, but duckietv does not always take them from there (some are taken from trakt I guess?). That is why I am interested in the option to manually change the schedule for a show - the other was just suggestions why it could be a useful feature. 

Honestly, anidb/myanimelist/anilist's sources would only theoretically fix the problem for animes. I have encountered numerous regular tv shows that come out a full 1 or 2 days earlier in torrent websites compared to the data I'd gotten at the time from duckietv. As far as I remember, most of them had correct timeslots in thetvdb, but not in trakttv, while some were just "refresh" issues that were cleared away at a later version. This would honestly not be a problem, but if the show isn't out yet in duckietv, the download button is gone, as it logically should be, since duckietv has a later schedule timeslot for that show. 

If adding the custom scheduling can't be handled, would adding the option of setting where the timeslots are gotten from be an option? That way, if users correct them in thetvdb, and know they're okay, there will be a change in their duckietv calendar also, if they specifically set the updated show to only get its scheduling time from thetvdb.

I am not a programmer, but I will personally look up if there is someone able to bridge the AniList API to send data to thetvdb. I highly doubt that will happen, but I will try nonetheless.

**Comment by garfield69** [comment]
a few points of info that may help clarify things for readers... or not :-b
- DuckieTV uses just the one API with Trakt.TV to fetch its episode and series data. Fetching data from multiple sources ourselves is very problematic, as it would be up to our code to somehow determine whose's data we should accept as being correct when there is a conflict in scheduling details.
- The custom search string feature implemented recently simply appends any additional search data to the torrent search string.
- by default the search string prefix is based on the trakt.TV series name and season/episode. 
- For those episodes whose Trakt.TV series names don't match the names commonly used by the torrent providers, DuckieTV uses the SceneNameResolver script, which provides the alternate torrent name prefixes, and we amend this list based on feedback from DuckieTV users. DuckieTV 1.2.0 will be able to fetch this table from GitHub directly so that table updates can be used immediately, instead of waiting for the next release as is currently the case.
- for those episodes whose torrents names don't use the SxxExx season/episode naming convention, the SceneNameResolver also keeps a table to provide date string replacements, such as DD MM YYYY instead of SxxExx. We update the table based on user feedback as needed.

**Comment by Js41637** [comment]
Yeah as @garfield69 said, we only pull data from Trakt.tv. The exact information about how Trakt.tv exactly works is a bit iffy but trakt.tv gets it's TV and Movie information primarily from TheTVDB and TheMovieDB however Trakt.tv itself only updates its data every few days as it just isn't possible for it to be constantly pulling data so if it's correct on TheTVDB it might be a couple days before Trakt.tv updates. 
And as for actual airdates, while most of TheTVDB is community managed air dates can be wrong depending where it was aired, it depends on the show with most being American but maybe the people adding these particular shows aren't aware of it airing elsewhere at an earlier time.

**Comment by SchizoDuckie** [comment]
One update to @garfield69's comment here is that we now also integrate with www.thexem.de, where season/episode mapping exceptions are indexed and fixed. Some (not all) anime shows are listed there too and are linked from anidb.

I've just tried to add One Piece http://thexem.de/xem/show/2352 and it corrrectly looks up the xem mapping for it, to return episode numbers in the S01E706' format. The only option needed then is an exception into the seriestorrentsettings that allows to customize the search string to exclude the SXXE string, which should be possible.

**Comment by roshavagarga** [comment]
With the exclusion of that SXXE string, the custom search bar would be complete for my needs.

If I undestood correctly, the table offers alternative namings, which would fix what the custom search string can not. (Example: Wagnaria!! has the same name in trakt, but the three seasons are called Working!!, Working'!! and Working!!! for S01, S02 and S03 by torrent creators). I will send up some info for the table to garfield for future such cases whenever I encounter name problems. 

@Js41637 - the shows I'm having trouble with have been off for - 1x for 9 weeks, 1x for 3-4 weeks since its air date shifted, they put the new date wrong, another one for 8 weeks. I'm guessing they just don't map it out precisely or update once a every 3-6 weeks maybe? I'm not sure why this is the case, some shows were off and were fixed within the period I mentioned, others have typically always been fine or sometimes they lag behind a day or so, which is nothing new.

The above has brought me to the idea that trakt doesn't solely update from thetvdb or that it has some sort of a priority system based on usage. I don't use trakt, so I don't know whether problems are reported by users or not. If it did reliably always update 1x time per every week, the problems I've been seeing would have resolved themselves faster, since dub versions of animes in English come out on DVDs and are picked up way after an anime has ended in most cases. The timeslots should be defined entirely by the first japanese tv station to air the anime as most animes are ripped and uploaded via simulcast sources like FUNimation and so on. 

Anyway, XEM might be an option to fix the problem, but it's not one I can directly influence and trakt don't always pull the data from thetvdb fast or properly, so the scheduling problem will probably stay a permanent problem unless some workaround is figured out. Hopefully I'm one of the few people who runs into it as a problem.

**Comment by garfield69** [comment]
having read through this ticket I think all questions have been answered so I am going to close it.

**Comment by garfield69** [comment]
ticket [664](https://github.com/SchizoDuckie/DuckieTV/issues/664) looks into how we could support some Anime titles by using thexem.de database, which we already plug in to for scene name support.
