### ISSUE TITLE
make search quality a preference rather than a requirement

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#552]
as raised in this [Reddit](https://www.reddit.com/r/duckietv/comments/3ll923/feature_request_multiple_preferred_quality_choices/)
 bytemaster67
>i have a preference to quality choice when downloading but if the show is only available in another format I'm willing to download it. Could you make quality a "preference" versus a requirement?

So we currently search and then filter the returns, and present only those containing the words in the search string, which includes the quality setting (other than *all* obviously).
The idea here would be that if the filtered array becomes empty after filtering out the quality, we drop the quality from the search string filter and return what ever is left instead.

**Comment by garfield69** [comment]
For those users that are waiting for torrents to show up with that requested quality (auto-download), then perhaps a setting to select quality as a requirement rather than a preference would be useful.

**Comment by bytemaster67** [comment]
I have actually encountered it in reverse. I typically request HDTV as my choice and shows will be 720p as an example.

**Comment by garfield69** [comment]
That's likely because most 720p torrents also have the HDTV keyword in their torrent titles at the same time :-)

**Comment by bytemaster67** [comment]
I just posted what might be a related feature request. My aim is to exclude MKV files. I have a slow computer and transcoding is a pain in the butt to say the least. So my preference is for mp4. As well, when I download TV episodes my preference is for the smallest file size as I track a lot of shows. So that is why I choose HDTV. Again, choosing 540p or otherwise pigeonholes me to where I am not likely to download the episode at all. But I definitely don't want 1080p Brooklyn nine-nine lol

**Comment by garfield69** [comment]
#548 would cover this scenario ;-)

**Comment by bytemaster67** [comment]
Just a thought on the subject, one way to look at the programming could be to focus on the file size of the torrent. In other words my preference is for less than 200 megabytes vs, say,  1.6 gigs. Most often there are choices for both within a series. I am always inclined to choose the smaller one and yet if I leave it up to duckie I may get the larger episode.

**Comment by garfield69** [comment]
@bytemaster67  the completion of ticket #548 implemented global include and exclude word lists, which I think may make this ticket #552 redundant.

I believe that your torrents needs are for MP4 files, that have HDTV quality, but not 720p, 1080p or MKV.

In the next official release of DuckieTV you would be able to set a global include for MP4 HDTV, and a global exclude for 720p 1080p MKV.

However, with the project on hiatus, the next production release of DuckieTV could be some time away.

But you can try out this feature now by trying out a development nightly release from [here](https://github.com/DuckieTV/Nightlies/releases)

a guide for installing nightly released can be found at this [wiki](https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-install-development-versions-of-DuckieTV) by following option 2 in the guides.

Feedback welcome.

**Comment by bytemaster67** [comment]
I am honored to have received contact from you. I must say that I'm
surprised that the project is on hiatus. I was just telling a friend that
your program is on the forefront of what I believe to be the trend in HTPC.
By far you have the most professional looking and easy to use application
out there. I hope that you realize how successful this program can become
and that this industry is in its infancy. Anyways, I thought I might share
with you my global exclude list as my needs have slightly changed since our
last discussion. I now have a Roku and it has a wider range of codecs. But
these are the terms that I would incorporate into the global exclude list:

TS FRENCH SWESUB HC HDCAM CAM TELESYNC

I think you can see my reasoning and it makes the subsequent search results
more usable. I will be honored to provide feedback anywhere I discover it.
Good luck and I hope to see a new version soon.

**Comment by SchizoDuckie** [comment]
Thanks for the kind comments :)
And thanks @garfield69 for picking up some of the slack!

**Comment by bytemaster67** [comment]
A giant homemade lasagna goes out to @garfield69!
