### ISSUE TITLE
Allow multiple show selection for an action (e.g remove from favorites)

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#571]
I recently uses the sync with trakt feature and ended up with a bunch of ended shows as well as shows I have abandoned populating my favorites page. Since you can filter by status (eg. Ended) on the favorites list it would be awesome to be able to select multiple shows at once to delete from favorites, or set the auto download feature on an off for shows you might not watch regularly. Removing "unused" shows is a great way to optimize the db update time in my opinion, since less shows are being updated for no reason.

**Comment by Js41637** [comment]
Well ended shows aren't updated very often.

**Comment by lonelyfairie** [comment]
I am not sure how the update works, but I assume it is not tvdb pushing updates to duckie rather than duckie requesting updates from tvdb (or other source) so it doesn't matter whether the show is updated often or not it will still generate a request right?

**Comment by garfield69** [comment]
Basically, the update process goes something like this:
- check the local trakt.tv-last-updated date stamp.
- has duckietv asked for an update today yet?
- no: then ask trakt.tv for a list of show ids that have been updated on trakt.tv since the last time duckietv asked
- if duckietv has any shows on that list, then fetch from trakt.tv that show's data, and update just the elements that have changed in duckietv database
- set the local trakt.tv-last-updated date stamp.

**Comment by lonelyfairie** [comment]
Thanks for the explanation, going by what you said then having ended or cancelled shows should affect db update performance from the app, that is great to know. 
I still think multiple show selection to either delete or set autodownload status on and off would be something great to have in the app :)

**Comment by garfield69** [comment]
@lonelyfairie  If you are looking to reduce the volume of updates significantly, then the biggest improvement will come out of turning the ratings off. This will reduce the traffic considerably, (especially for ended and cancelled shows, since that is pretty much all that ever changes with this category).
Find the option in the settings/display panel, under Download Ratings.
![image](https://cloud.githubusercontent.com/assets/6933240/10407270/3950b8e0-6f45-11e5-9413-ad08a3f8fadb.png)

**Comment by lonelyfairie** [comment]
Thanks garfield, I didn't know that was the case, I have disabled the ratings update :)

**Comment by SchizoDuckie** [comment]
I'm going to close this. Not seeing this happen any time soon and the original problem seems mitigated by toggling the update setting

**Comment by garfield69** [comment]
hur?

**Comment by SchizoDuckie** [comment]
accidental reopen
