### ISSUE TITLE
First documentation report for DuckieTV

### ISSUE THREAD

**Issue by Nutil** [SchizoDuckie/DuckieTV#576]
Hi there!

Sorry for the delay, we thought we could've had our report analyzed by our teacher by now, but it turns out it'll only be reviewed by next week, so we're sharing it now.

https://github.com/Nutil/DuckieTV/blob/documentation/ESOF-docs/Report%201.md

Regards.

**Comment by SchizoDuckie** [comment]
I had secretly already found it in your repo because I was checking up on progress. I must say, I'm pretty proud of your conclusions :)

Finding a reviewer with the right skills and the amount of knowledge required will be a challenge for such a small team though, even getting more regular contributors to chime in is a challenge as any open source maintainer will probably tell you.

Very much looking forward to what your teacher has to say about it and what the next steps will be. great work, keep it up!
