### ISSUE TITLE
Second documentation report: System requirements

### ISSUE THREAD

**Issue by Nutil** [SchizoDuckie/DuckieTV#582]
Hey duckie,

we're working on our second report for DuckieTV, which is all about analyzing your system's requirements and structuring it so you can explain it to anybody who needs to know them.

We are, however, missing just abit of information, which we hope you could provide.

What are your hardware and performance requirements? As in, what kind of resources does the server-side application use (RAM, memory space, processing power, etc) and the same for the client-side appliaction.

Also, since you can now access our second report, could you please take a brief look at it and check if it goes according to what you want/need?

While we await your answer, we'll be working on the use cases diagram of DuckieTV, however we know you love to make graphs explaining your program, so if you've already made one, we'd be saving work :p

Best regards, 
FEUP team

**Comment by SchizoDuckie** [comment]
Ah, excellent question! an neglected part of the docs.

First off, let me touch the serverside specs: There are none. Zip, Nada :)
DuckieTV runs completely on the client side. 

DuckieTV fetches resources (due to relaxed CORS restrictions) from many API's like Trakt and the torrent clients, scrapes torrent sites from plain HTTP and recently there's some fetching from JSON files that are cached on http://github.com/DuckieTV/ but other than that there's nothing and DuckieTV can run when any of these services are down.

As for minimal system specs on the client side:

- When running as a chrome extension: Any version of chrome that supports extensions and the v2 manifest
- When running as standalone app via nw.js, [this applies](https://github.com/nwjs/nw.js/issues/3249)
- When running on Android at least API version 15. (4.0.3)

I'll have a look at the report and comment on that :) There are no diagrams of use cases that already exist.

Good luck!
