### ISSUE TITLE
Request for proxy option for rarbg.com in the Torrent Search Engines settings

### ISSUE THREAD

**Issue by bobi1024** [SchizoDuckie/DuckieTV#586]
In the "Torrent Search Engines" there is a setting for adding proxies for Kickass Torrents and The Pirate Bay. Can you add option for rarbg.com because it is blocked in my country and I'm accessing it trough proxy. I see that there is "My Custom Search Engines" setting, but I'm still trying to figure out how I can edit it and add custom search engine.

**Comment by garfield69** [comment]
As far as I know, the custom search engines settings is a work in progress, refer #18. I don't think it should have been made available in 1.1.2 release, @SchizoDuckie may comment.
As for adding a proxy for rarbg.com, we can certainly look into this.

**Comment by garfield69** [comment]
research notes:
DuckieTV's [js/services/TorrentSearchEngines/RarBG.js](https://github.com/SchizoDuckie/DuckieTV/blob/angular/js/services/TorrentSearchEngines/RarBG.js) uses rarbg's API `endpoint = 'https://torrentapi.org/pubapi_v2.php?app_id=DuckieTV&';` 
Are there any reverse proxies for `https://torrentapi.org` out there?

**Comment by SchizoDuckie** [comment]
As far as I can tell, he's just asking for a way to manually input a mirror. But this is indeed best solved with the custom search engine settings. (which is nearly done, just needs permanent storage and UI touchups)

**Comment by bobi1024** [comment]
SchizoDuckie you are absolutely right. I've said proxy because the setting is called that way. Actually it is more like a mirror. I'm using a custom domain forwarded to rarbg.com with CNAME record trough Cloud Flare and I just want to put that custom domain main in the app, because the actual domain is blocked in my country.

**Comment by SchizoDuckie** [comment]
For a quick fix you're probably best off just forking DuckieTV and patching
the file manually.

I'm currently working on storing all the search engines in the database so
that we can easily edit these properties in the future with the new search
engine editor that you spotted

**Comment by garfield69** [comment]
Yeah but hang on, correct me if I have miss-understood.
for kat or tpb we search and scrape results from their main web server, and are able to use mirrors because they present the same info, and reverse proxies because they simply redirect back to the original web servers via routing, both methods defeating regional blocking, yeah?
But rarbg is a special case, because we are using their API server accessed via https://torrentapi.org. 
We are not using search scraping out of the rarbg.to web server.
So unless the API server has mirror or reverse proxies available, its a bust.
In this situation, we would need to first enable search scraping on the web server (via the yet to be completed custom search engine interface), after which mirrors and reverse proxy adrressed can be plugged directly in.
Or have I missed something?

**Comment by SchizoDuckie** [comment]
I'm making sure that all search engine endpoints can be configured by the
user via the db, even if we need a custom implementation :)
Op 24 okt. 2015 00:54 schreef "garfield69" <notifications@github.com>:

**Comment by scriptzteam** [comment]
https://www.dropbit.in/category/Other - indexes all rarbg torents

**Comment by garfield69** [comment]
With the latest Nightly starting with 31-05-2017 01:55:49 at https://github.com/DuckieTV/Nightlies/releases you can now access RarBG on DuckieTV via the Jackett proxy. On Jackett you can edit the RarBG URL to whichever RarBG address you require.     
https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV      
The next Stable Release of DuckieTV 1.1.5 will also include the option to use Jackett proxy.
