### ISSUE TITLE
No peers no seeds

### ISSUE THREAD

**Issue by mTcgo** [SchizoDuckie/DuckieTV#593]
When i choose a torrent through DuckieTV UI, the file shows in uTorrent, but it never finds any peers. Little magnets in Dtv keep on turning to infinity. I use uTorrent 3.4.5, I've tried with 3.4.1. , same result. I've also tried Dtv 1.0.1 and 1.1.2, with same results. This problem appeared a few day ago, maybe a week, before it worked fine. I really like Dtv and would like to continue using it. Tnx 4ur answer.

**Comment by SchizoDuckie** [comment]
This is not something duckietv can fix unfortunately. Since demonoid or
demonii is down an important part of the torrent infrastructure is blown
out of the water.

The only advice I can give you is to enable DHT (peer discovery) or find
another torrent that has different trackers listed.
Op 17 nov. 2015 10:16 schreef "mTcgo" <notifications@github.com>:

**Comment by mTcgo** [comment]
Oh. I see. Tnx

**Comment by mTcgo** [comment]
I forgot to mention that these same torrents work when directly downloaded from KAT

**Comment by mTcgo** [comment]
I guess switching on DHT resolved the issue:)
