### ISSUE TITLE
Vuze integration need paring #

### ISSUE THREAD

**Issue by raykai** [SchizoDuckie/DuckieTV#600]
can the Vuze integration be updated as vuze now needs a paring number and the set-up instruction are outdated.

**Comment by garfield69** [comment]
Hmm. Vuze for windows 5.7 does not **force** you to use *pairing* for the Web Remote, and we don't intend to support connection pairing with Vuze at this stage (unless Schizoduckie decides otherwise in the future).

**So you have two choices:**
- disable pairing in Vuze globally:
![image](https://cloud.githubusercontent.com/assets/6933240/11705520/65010482-9f55-11e5-964e-2d68efa6b6e5.png)
by un-ticking the **enable pairing of Vuze and remote applications/interfaces** check box
- OR disabling pairing for the Web Remote interface plugin
![image](https://cloud.githubusercontent.com/assets/6933240/11705554/ac0ab954-9f55-11e5-90c1-e68083160369.png)
by un-ticking the **enable pairing for this plugin** check box.
