### ISSUE TITLE
Window size changes after minimizing

### ISSUE THREAD

**Issue by SushiLover** [SchizoDuckie/DuckieTV#605]
I upgraded to standalone v1.1.3 yesterday and have noticed that now when I maximize DuckieTV then minimize it to the toolbar, it is no longer maximized when I restore it. I have to manually maximize it every time, and this did not happen with the previous version I ran. I am currently running a 22" Acer with a resolution of 1280x1024.

**Comment by garfield69** [comment]
I'm seeing this too on my standalone win32 dev version. 
Supposition: Rather than issuing a Maximize command, the code is now trying to restore window size from previously stored w,h dimensions.
Theory:  The problem is that using the method is not successful because nwjs appears to be measuring w,h from some inner rather than outer frame (possible an artefact from using frame-less windows?) so the window slowly shrinks with every operation.
Research and further testing is required to get to the bottom of this one.

**Comment by SushiLover** [comment]
How do I install the fix?

**Comment by garfield69** [comment]
Officially the fixes will be included in the next release, whenever Schizoduckie decides to release it.

However, if you are keen, you could choose to switch to a development build, and pick up the changes sooner.

The caveat is that development builds are work-in-progress and could contain surprises and bugs.

The nightly builds [here](https://github.com/DuckieTV/Nightlies/releases) contain all the fixes gathered up that night (server time).
The next nightly in about 5 hours should contain the 605 fixes.

**Comment by SushiLover** [comment]
Okay, thanks for the info.
