### ISSUE TITLE
DuckieTV Android App 

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#616]
Can you publish DuckieTV android app on the F-Droid store or Google Play.

**Comment by SchizoDuckie** [comment]
Sorry, chrome store says no, f-droid wants to be able to build the whole thing from scratch (something we've outsourced to phonegap build, so we don't have to worry about it)

I'd have to put in significant effort to reproduce all of it outside of phonegap build. 
I've enabled the phonegap build hydration so that the app will ask you to update when a new nightly is built. This should solve the update issue. 


Please try the latest nightly from https://github.com/DuckieTV/Nightlies/releases/tag/nightly-01122017
