### ISSUE TITLE
[Feature Request] Updates

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#620]
Can there be a clear notification or popup to show when there Is a new update out or just an auto install function for new updates.

**Comment by Js41637** [comment]
Ahh yes this is a good idea, we actually have a very old ticket, one of the first ones, about creating a Notification Service. This will be very easy to add anyway.

**Comment by Js41637** [comment]
As for auto install, i'm not sure about that, Chrome versions obviously don't have this issue but for Standalone, a proper updater is something that would be nice.

**Comment by Js41637** [comment]
Actually Standalone already shows a notification I believe when there is a new version, you just have to download and manually install

**Comment by zero77** [comment]
O I guess I haven’t seen it yet then, and the Tor Browser had the same thing where you manually downloaded and install it but, they changed it although I don’t know how they did it.

**Comment by zero77** [comment]
Also if you add DuckieTV to app stores then the auto update should happen automatically except for the windows standalone one as there's no app store.

**Comment by Js41637** [comment]
DuckieTV isn't able to be put on the Google Play Store, and because of the nature of how our Standalone works, i'm not sure how hassle some it would be to get an auto-updater working.

**Comment by zero77** [comment]
So I guess the android edition is the only one that is able to be published in an app store like Google Play or F-Droid store although the Linux edition may be as well. If I find out how tor managed, it and if it is relatively straightforward then I will post it hear.

**Comment by SchizoDuckie** [comment]
This has been resolved with the UpgradeNotificationService

**Comment by zero77** [comment]
Dues the Upgrade Notification Service support nightly if not can you add support for this if users enable it.

**Comment by SchizoDuckie** [comment]
It Doesn't, because a new nightly is available every night :)
Op 16 jun. 2016 14:38 schreef "zero77" <notifications@github.com>:

**Comment by zero77** [comment]
Good point, but you could add a pop up prompt that says there is an update available and asks the user if they want to install it. With a yes or no option if they click yes the program could close and then the exe silently download and install using the silent command line installation parameters. For both nightly and main build updates.

**Comment by SchizoDuckie** [comment]
An auto-updating nightly is wáy too risky imo.

As are daily notifications of exactly the same message, this will annoy
people within 2 days.

But, i'd like to hear the rest of the team's opinions on this.

**Comment by zero77** [comment]
Yes that's true, but you could give the users the option between automated completely silent update for both nightly and standard updates, and another option for update with a yes/no message.

Also I may be able to make an example script in vbs which could be converted into an exe but I can't code in java so I wouldn't be able to build this strait in to DuckieTV.

**Comment by garfield69** [comment]
My 2 cents worth.
Firstly, I believe that notification of updates and auto-install of updates are two separate processes.
Notifications can run within DuckieTV's angular code, and thus are available irrespective of platform or distribution (standalone versus chrome extension, mac v. linux vs. android vs. windows).
And I'm with schizoduckie on this: for production we regularly check if a new version is available (and provide a popup with a link to the download site), and for nightly we don't, since by definition, a nightly is a development daily, and notifying uses that the new daily is available is pointless.

secondly, automatic updates. There are a multitude of problems to overcome.

- update to the production chrome browser extensions are handled by the chrome store. (excellent).
- updates to the nightly chrome browser extensions are managed by the user, since they are loaded via the chrome browser development extensions panel which does not allow for automation. (for obvious reasons).
- Standalone's are just the same DuckieTV angular code, packaged to run under NWJS. I don't think performing updates to the NWJS package can be done by DuckieTV's angular code running under NWJS. (can angular submit an executable for instance?) I have yet to come across documentation on the NWJS support site that allows us to auto-update a NWJS package. (is there such a facility that I have missed?)
My point is that automatic updates for NWJS standalone packages may not be a straight forward process.
Other issues for consideration: platform specific gotchas that NWJS package updates may not cope with, standalones that are run 24/7 by some users, automated migration of data and settings for when NWJS changes (such as 0.12.3 to 0.14.6 which we are researching in #638).

**Comment by Js41637** [comment]
Basically, there's no point auto updating for nightly because we don't
actually have an auto update, you'd still need to download it, if you
really want to use dev your better off just running source and automating a
script to pull new changes every night
