### ISSUE TITLE
[Feature Request] Pinch to Zoom

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#626]
Can you add the ability to pinch to zoom in the android version like in google maps as it can be very hard to read some things.

**Comment by garfield69** [comment]
I'm going to leave the question of adding touch screen features to DuckieTV for @SchizoDuckie  to answer.

In the mean time, in case you were not aware, using your keyboard you can use the **ctrl +**and **ctrl -** key combos to zoom in/out, and **ctrl 0** to reset back to default zoom.

**Comment by zero77** [comment]
I ment adding this to the android app or is there a way to zoom in already.

**Comment by garfield69** [comment]
We don't maintain separate source code for each platform. Rather, we have the one source code written in angular javascript, and use nwjs's engine, which runs the ajs on each standalone platform.

So, going to back to what I said earlier, touch screen features on android platforms such as pinch and swipe and whatever other gestures, would require special coding which only SchizoDuckie  as the author can decide if we will get into.

So since pinch for zoom is not currently available on DuckieTV, as I said earlier, assuming that your android device has a touch screen keyboard popup, and has the **ctrl** key available, then using the key combos I specified earlier, **ctrl +**, **ctrl -**, **ctrl 0** you can zoom in and out to make the fonts larger or smaller. :-)

**Comment by zero77** [comment]
O I understand, I will have to find the keys you mentioned on the phone then.

**Comment by garfield69** [comment]
To provide some touch support for DuckieTV we would could include angularjs [ngTouch](https://docs.angularjs.org/api/ngTouch) module.
However, there are only 3 functions available currently:
- ngClick
- ngSwipeLeft
- ngSwipeRight

it does not appear that we could a provide a pinch/stretch function.

**Comment by SchizoDuckie** [comment]
Nah, the pinch to zoom on android is a bit hard to get right. It depends on
the API version you name in the package when building the cordova app. I
chose this api v14 because then i can at least get things to scale right.
Upping the api level introduces other behavior, and may also introduce
pinch-to-zoom (which will have to be webkit meta-tag zoom parameters
(initial-scale, max-scale and that whole shebang) but that' s hard to get
right. So for now: I'm not gonna touch that because it works and i have no
time to test the gazillion combinations possible :)
