### ISSUE TITLE
torrent search name is not the name of the series

### ISSUE THREAD

**Issue by macst34** [SchizoDuckie/DuckieTV#635]
I added "The Venture Bros" to my list of followed series, when I search for related torrents the search field is misapplied as "The Venture Brothers" and, of course, no torrents are returned.

Not sure if this is actually a duckie issue or perhaps a trakt.tv issue. It doesn't seem to be a tvdb issue though I dunno enough about the underpinnings of duckie to confirm.

-m

![capture](https://cloud.githubusercontent.com/assets/5762387/12753604/c6515e44-ca02-11e5-8863-b09ddcd76c5d.PNG)

**Comment by garfield69** [comment]
implemented https://github.com/DuckieTV/SceneNameExceptions/commit/e96eed08679f5cd5945f5f942757f95d7c0512a8.

THE VENTURE BROTHERS was the scene name of torrents for earlier seasons.
but almost all those torrents are now dead.
removed it from the sceneNameExceptions since THE VENTURE BROS is the current scene name now.

Your DuckieTV checks every 24 hours for updates to the scene name exceptions server, so you should see it using the new name soon.

**Comment by macst34** [comment]
wow dude, that was quick. thanks!
