### ISSUE TITLE
Watched count not updating after syncing trakt

### ISSUE THREAD

**Issue by KsaRedFx** [SchizoDuckie/DuckieTV#640]
The "Episodes left to watch" Count doesn't update if you've already added a movie to DuckieTV then sync trakt. 

Replication: 
Add show to DuckieTV, 
Tell DuckieTV to sync a show you've got marked as watched on Trakt
Go to "Favorites" and look at the "Episodes to Watch" count.

**Comment by KsaRedFx** [comment]
With testing, issue still happens

![image](https://cloud.githubusercontent.com/assets/1790490/12964256/31429de2-d01d-11e5-83d3-2e6eb7774330.png)

**Comment by KsaRedFx** [comment]
From @SchizoDuckie: Using this in console correctly recalcs. `angular.element(document.body).injector().get('$rootScope').$broadcast('series:recount:watched');`

**Comment by garfield69** [comment]
it looks like 55db177135d40b5baac201b88668f2e04dd7d6c3 does not work, because while the *watchedCounter.recountSerie* routine is called *after* the trakt.tv import has completed, it runs *before* the actual DB I/O writes for series and episodes has started.
Since the *watchedCounter.recountSerie* routine itself performs the count using an CRUD.executeQuery, it then misses out on seeing the updated records.

We need to delay the $broadcast or find some other place to invoke it.
