### ISSUE TITLE
Shutting down / minimising DuckieTV disconnects from uTorrent

### ISSUE THREAD

**Issue by sockgolem** [SchizoDuckie/DuckieTV#642]
Using uTorrent 3.4.5. and DuckieTV 1.1.3

Fresh install on Windows7, DuckieTV connects to uTorrent (shows connection key and OK'd through uT) however when it is minimised or closed, will lose connection and need to be reconnected every time before using.

**Comment by garfield69** [comment]
a little more info please. 
* which DuckieTV uTorrent interface are you referring to: **uTorrent API** or **uTorrent Web Ui** ?

* what indicates you have lost connection?

* what do you do to reconnect ?

* by **closed** you meant you shut down DuckieTV?  Therefore you imply that on the subsequent DuckieTV start up, it does not reconnect with uTorrent?

* Do you keep uTorrent running all the time? 

* if you don't, then do you start up uTorrent before starting up DuckieTV ?

cheers for your feedback.

**Comment by sockgolem** [comment]
My apologies, I am new at using Git for feedback.

- I am using the uTorrent API not the Web Ui
- The uT link on the DuckieTV home page has a Red indicator and magnet links dont load into uT correctly
- I manually get DuckieTV to reconnect from settings
- Shut down as in Exit the program and when minimised to the taskbar.
- I do keep uT running, however I have tried shutting them both down and restarting and it does not fix.
- I have tried starting uT before DuckieTV, have even tried after DTV and does not make a difference.

**Comment by garfield69** [comment]
OK, that's terrific, it helps me get a better picture.

1. DuckieTV works best if uTorrent is started up first.
2. If DuckieTV's uTorrent icon on the left of the main DuckieTV page has a red dot, then clicking on that icon will start a reconnection. (saves you navigating to settings etc.)
3. DuckieTV does have a reconnection retry that is supposed to kick in every so often, I haven't checked recently that its all still working as it should. I'll try make some time and set up my test image to check that stuff is still working as it should.
4. Since 1.1.3 there have been lots of bug fixes. I wonder if you would consider trying out a nightly and seeing if the uTorrent connectivity works better for you on the latest version.

If you are interested, you can fetch the latest nightly from [here](https://github.com/DuckieTV/Nightlies/releases), and if you need a guide on installing a nightly, you can reference this [wiki](https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-Windows-DuckieTV-Standalone). Follow option 2 of the guide for nightly installs.

**Comment by garfield69** [comment]
@sockgolem  hold off fetching the nightly until after tomorrows build, so you get the latest version with the fix I added to auto connect torrentCLient at startup.
