### ISSUE TITLE
Hi my duckie tv is not updating the programs i have watched please help 

### ISSUE THREAD

**Issue by babyboya187** [SchizoDuckie/DuckieTV#651]
Hi my duckie tv is not updating the programs i have watched please help I have included a screen shot it shows i havent watched the night manager and cooper barrets but I have and it does this allot with other programs it takes about 3 or 4 days to update even though i log on daily please help or advise what i am doing wrong.

**Comment by garfield69** [comment]
> I have included a screen shot

- there is not screen shot in this ticket.     Assuming you are using a Windows system, then take a screen shot using the **Print Screen** key, or the **Alt** and **Print Screen** keys at the same time if you only want to capture the active window.     Then simply paste the shot into an open box below using the **Ctrl** and **v** keys at the same time.

> i log on daily 
>duckie tv is not updating the programs i have watched 
> it takes about 3 or 4 days to update

- What are you logging into daily?    Are you perhaps using a Trakt.TV account and synchronizing with DuckieTV?
- So the problem is that you update your shows on Trakt.TV and those changes are not showing up on DuckieTV?
- OR are you setting shows as watched on DuckieTV and those changes are not showing up on Trakt.TV?
- OR something else entirely, please explain in more detail.

- It would also be helpful to us if you could provide some additional basic information.    Would you please start up DuckieTV and click on the **(i)** icon on the left of the main DuckieTV page.    This opens the **About** page.     Scroll down the page until you get to the **Statistics** section, and screen capture the statistics and paste them below.    Thanks.

**Comment by garfield69** [comment]
to be re-opened when OP replies.
