### ISSUE TITLE
option to select min and max size for searching

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#659]
as requested in this [Reddit](https://www.reddit.com/r/duckietv/comments/41b5xt/notice_duckietv_development_is_currently_on_hiatus/d11vihy):
>i would like to see an option to select the maximum and minimum size of the show your are searching for.

**Comment by wolfkin** [comment]
size determined by file size or size determined by resolution?

**Comment by SchizoDuckie** [comment]
Resolution sounds unlikely to me. How do you want to guesstimate that
before downloading?
Op 21 mrt. 2016 15:10 schreef "wolfkin" <notifications@github.com>:

**Comment by wolfkin** [comment]
I think file size might be even more unlikely. You'd have to be pretty familiar with file size variations right? Most of which I think could be better selected for by choosing file type or the already available (add which scene group) or picking your preferred resolution.

Resolution I would presume to mean I want to download 480-720 or 720-4k. Not necessarily any random range of resolutions.

**Comment by garfield69** [comment]
I've asked the OP the following in the Reddit thread:
>Can you confirm that by size you are talking about the total bytes in a file? So you would want to restrict search to, for example, min=200MB, max=2000MB ?

awaiting response.

**Comment by lonelyfairie** [comment]
I was just about to post this request lol
Mainly what I would like would be a filesize cap when searching for files, I mean do I really need to alocate more that 1GB of space in my downloads drive for an episode of Family Guy? An ignore setting for shows which I do find worthy of that much space in my drive would be optimal, currently I have duckie set to find the preferred quality of 1080p and some of my shows are set to Ignore this, still I sometimes get this in a file size above 1gb and that bugs me as I have limited free space on my downloads drive (usually under 6GB), I find myself deleting torrents and re adding them manually in smaller sizes due to this more often that I would like.

**Comment by zero77** [comment]
I also find myself re-downloading torrents if they’re too big though this is usually when 1080p has been selected. It would be useful to have a maximum and minimum size filter.

**Comment by garfield69** [comment]
reply from OP lotn2635599 on Reddit
>exactly, 100mb to 200mb etc... thanks guys for links to the items i asked about. very much appreciated.
