### ISSUE TITLE
[Feature Request] Anime Features (Alias) (Numbering)

### ISSUE THREAD

**Issue by wolfkin** [SchizoDuckie/DuckieTV#664]
I noticed this problem with an Anime I found via the discoveryfeatured called 'Erased'. It wasn't downloading. 

![erased1](https://cloud.githubusercontent.com/assets/6678474/13906949/608410d0-eeb9-11e5-88df-9391ff8a7b84.png)

Today i decided to check something and see if maybe the name was the problem. After all the group I watch doesn't releast Attack on Titan as Attack on Titan but as Shingeki no Kyojin

![image](https://cloud.githubusercontent.com/assets/6678474/13906963/bac6251a-eeb9-11e5-9a6c-cc5f5d24c3c0.png)

This is what I typically get when I would attempt to search for an episode of erased

![erased2](https://cloud.githubusercontent.com/assets/6678474/13906971/d414de12-eeb9-11e5-920d-ae6cb0678817.png)

However after searching for the original language name I was able to get hits

![erased3](https://cloud.githubusercontent.com/assets/6678474/13906982/001f8732-eeba-11e5-8c7b-5ace700b8bd5.png)

You'll note I not only had to change the name but change the episode number search S01E11 got me nothing.

---

My request is as follows

1) Alias - provide a means give a show a search alias. This also happens with a UK show called "Raised by Wolves" whereas in the first season it was released as **Raised.By.Wolves.UK.S01E##**, it is in it's season reason released as **Raised.By.Wolves.S02E##**. The search still uses the UK suffix which means no results.

2) Anime Mode numbering - I haven't used Duckie for much anime but I'm not unfamiliar with Anime release tropes and it's my understanding that typically they are numbered without Season and Episode quantifies. **%Title%** - **%EpisodeNumber%** rather than **%Title%** - S**%Season%**E**%EpisodeNumber%**. If it's possible if we could in the TV show settings label a show as Anime which would then change searches to Anime style numbering it would get better results.

Thanks for the time.

**Comment by garfield69** [comment]
In the past we have resisted providing anime specific features because of the chaotic inconsistencies of anime naming standards, which made automations such as our auto-download impractical to implement.

However, the demand for anime support for DuckieTV is growing, so perhaps it is time to look at this topic once again, especially since we plugged DuckieTV into thexem.de a few releases ago, which helps track episodes for the more popular anime titles.

>1) Alias - provide a means give a show a search alias.

We maintain a SceneNameResolver table which provides the most commonly used alias for a series. Your DuckieTV fetches this table once a day to keep itself up to date.
So if you are aware of shows that need to be searched with an alias, then simple raise a ticket and we will update the SceneNameResolver accordingly.

>This also happens with a UK show called "Raised by Wolves" whereas in the first season it was released as Raised.By.Wolves.UK.S01E##, it is in it's season reason released as Raised.By.Wolves.S02E##. The search still uses the UK suffix which means no results.

I have amended the SceneNameResolver table to drop the UK from searches. Your DuckieTV should fetch the updated table within the next 24 hours or so.

>2) Anime Mode numbering - I haven't used Duckie for much anime but I'm not unfamiliar with Anime release tropes and it's my understanding that typically they are numbered without Season and Episode quantifies. %Title% - %EpisodeNumber% rather than %Title% - S%Season%E%EpisodeNumber%. If it's possible if we could in the TV show settings label a show as Anime which would then change searches to Anime style numbering it would get better results.

So at the moment we currently support two methods of season/episode formats
- season and episode SxxExx
- SceneDateExceptions which replaces SxxExx with a date format such as "EEE, MMM D, YYYY" or "YYYY.MM.DD" or "DD MMM YY".

Current anime release regime appears for the first season to use just the episode number, such as `world trigger 40`, and for following seasons to prefix the season number, such as `ace of diamond S2 23`.

I propose creating a SceneAnimeExceptions table. The table will be a list of tvdb_id entries, which will indicate that the anime episode regime is to be used. 
It will live in the https://github.com/DuckieTV/SceneNameExceptions repo and be fetched by DuckieTV is the same manner as the SceneNameExceptions and SceneDateExceptions tables.
We can use the already plugged in thexem.de to lookup the season/episode number, or fall back to using the season/episode from Trakt.TV.

@SchizoDuckie:  yay or nay?

**Comment by SchizoDuckie** [comment]
I'd say you are correct, and we can probably do this for the ones that thexem supports, which are some 680 shows in total (including regular series). However, I believe the anime ecosystem is *a lot* larger than that, plus there will be probably other challenges in finding the right search terms.

If you're up for it, I won't hold you back, but it'll be quite some work for a feature that created a lot of specialized software.

**Comment by wolfkin** [comment]
I'm not necessarily married to using Duckie for my anime needs. as someone who generally gets his anime post season completion from other sources this whole watching simulcast or whatever it's called is fairly new. That said it sounds like the scenenameresolver sounds like it'll solve most of my issues.  Anyway thanks for the work you have done.

**Comment by RiderSx** [comment]
Unfortunately due to really **large** anime ecosystem you can not rely just on files names to determine what show or episode it is, also you can't be 100% sure if parsed show name is first season or it is second second because anime has really weird naming system, or it would be better to say they do not have naming system at all, ie Tokyo Ghoul  - is a first season, when Tokyo Ghoul √A - is a second, and you also have OVA's, ONA's, bonuses, spin-offs and side stories which sometimes included in realese with names like `Tokyo_Ghoul[10.5][BDRip].mkv` or even worse bonuses can be name like 13-th episode out of 12. More to say it's not often but very possible that folder containing anime in release and even episodes files names will be named in a very fucked up way (i personally saw it 2-3 times, but the most recent was that they called folder files this way: `Veljzepuz.(01.serija).2011-2012.x264.HDTVRip.(720p)`).

So the only solution which still not 100% good is to detect anime in fs in some intelligent way and assign real show name semiautomatic. And yeah, there are no problem to track new episodes or even download it with subs/dubs when you have correct show name and correct numbers of downloaded episodes.

**Comment by garfield69** [comment]
Well that was interesting feedback. And it looks like my very first comment in this post:

>In the past we have resisted providing anime specific features because of the chaotic inconsistencies of anime naming standards, which made automations such as our auto-download impractical to implement.

is still valid. So I am withdrawing my intention to try and cater for anime in DuckieTV at this time, since my proposed solution would deal with only a small subset of anime.

**Comment by SchizoDuckie** [comment]
Some more research on this..
it doesnt look like we will have to do voodoo to fetch the correct names after all (for at least those that are supported by thexem, this will always be a requirement imo)

I noticed on thexem.de that they also show the information for all the shows that have aliases here:

thexem.de/map/allNames?origin=tvdb

and additionally there is a detailed list for a show here:

http://thexem.de/map/Names?origin=tvdb&id=281249
(ghoul season 2 is nicely defined here, otherwise it can fall back to the regular name)

so, technically this *is* our full mapping, and we would not have to keep our own SceneAnimeExceptions, but we can rely fully on TheXem.

We don't process the releases afterwards anyway, so @RiderSx's comment about the filenames doesn't apply to us, as long as we can find the torrents.

This would ofcourse also require caching all that info and preparsing it a bit, but it looks slightly more possible to do this with minimal regular maintenance and hacky coded exceptions than i thought

**Comment by garfield69** [comment]
additional notes from this [Reddit]()
>hmm.
>I do notice that one piece is featured on thexem.de, it has an 'anidb' entry there:
http://thexem.de/xem/show/3039 it could be that if we fix the XEM mappings and parse the anidb section there too we can resolve this generically, if we add it to the list at https://github.com/DuckieTV/xem-cache/blob/gh-pages/81797.json and make a check there if there's an anidb index on the xem-cache. Then we support at least those supported by thexem.

**Comment by roshavagarga** [comment]
Just my 2 cents on this problem, if there are any problems with how an anime's torrents are called, the naming by HorribleSubs torrents is the one to go with. Even groups that aren't simulcast, rather fansubbing tend to follow the naming pattern used by HorribleSubs, so that their torrents pop up more often. So yeah, if you're wondering which thexem alias to use, double check with HorribleSubs' naming in their website, and that one will probably have the best search yield.

Also the stuff mentioned by RiderSx is outlandish to say the least. No serious fansubbers use dots or underscores in their naming, I'm guessing he was talking about his local fansub groups, as one of the torrents he talks about is in Serbian/Bosnian. He is correct about the Tokyo Ghoul second season being called "Tokyo Ghoul Root A". 

ONA is not the same as OVA, can be googled more extensively, basically ONA can be an anime that is only shown online, a.k.a. Netflix or whatever the equivalent is. OVA episodes as mentioned are side-story episodes, or episodes that were not in the original airing scheme. Basically, they didn't have the money or decided that part wasn't interesting enough, so they make the animation later, put it as a DVD Exclusive and push up sales that way. Again, those shouldn't concern you, as they can come out months after the anime has finished its regular season.

**Comment by garfield69** [comment]
there has been some improvements to Trakt.tv regarding anime. the following blog https://blog.trakt.tv/all-about-anime-f10519c5c5b details.     
I've yet to confirm if any of the details in the blog are reflected in changes to the data we fetch from their API, but if there is now additional data there what we can use (for instance: absolute numbering in combo with anime tag) then I will see if we can make use of it.

**Comment by cajeiri** [comment]
@garfield69 - Their pages seem to have new information, as seen here (https://trakt.tv/shows/one-piece). If you could share more information on this additional data you can extract via the API I'd be very thankful.

Arguably, just the absolute numbering should be extremely helpful for some of the longstanding anime series. And this would be a hefty boost if you decide to promote DuckieTV within the anime community.

**Comment by Js41637** [comment]
We don't even do any promoting lmao

**Comment by Js41637** [comment]
Episodes now return an `abs_number` when `extended=full`

**Comment by cajeiri** [comment]
@Js41637 - hence the "if you decide to" part. Most facebook groups, forum communities and websites would probably be okay with promoting the program for free. Although in my mind, we're still missing a crucial function, for which I'll open an issue in a bit.

**Comment by Js41637** [comment]
Even though this is off topic I doubt it. This was only initially made to fill a need, first most by SchizoDuckie and then myself and garfield. The reason I don't really work on it anymore is it does everything I require of it and probably the same for SchizoDuckie. garfield has been gracious enough to keep it maintained and updated and has done a great job but I don't see much happening on a large scale for a while. 

These absolute numbers might help a *bit* with Anime but Anime has always been historically very hard to properly map to a standard format and I wouldn't say not properly supporting Anime is a crucial function and if your primary goal is to track Anime than this might not the best program, not that I know of any others.

Anyway.

Episodes now return an `number_abs` when `extended=full` in both episodes and seasons calls so you should be able to use that.

**Comment by garfield69** [comment]
### checklist:
- [x] set default handling of Anime to use absolute episode numbering      
    criteria: if Trakt.tv flags a series as anime then     
    - when searching for episode, use thexem.de absolute override if present     
    - else use the trakt.tv absolute if present      
    - else use the standard SxxExx        

    for the absolute number, if single digit then add leading zero, else leave as is.     
- [x] set up xem-cache bot to fetch updates of the anime alias map      
- [x] make the sceneXemResolver cache the alias map and refresh as part of the xemMappings cycle.
- [x] add support for Anime Alias     
    criteria: if thexem.de has an alias list for a series then present list as a pull down on the series settings dialogue
    - if an alias has been selected this replaces the sceneName in searches.     

This takes care of the bulk of the anime requests for now.

### testing
- [x] set up jackett Search engines: Anidex, Anime Tosho, AniArena, Horrible Subs, Nyaa.si (basically all the public sites that Jackett supports that specialise in Anime).
- [x] grab a selection of anime and test searches
    Detective Conan, Dragon Ball Super, Naruto Shippuden, Pokémon, Fairy Tail, One Piece,Dragon Ball, Hunter x Hunter, Attack on Titan, Digimon: Digital Monsters, Naruto, Cowboy Bebop, Bleach, Fullmetal Alchemist: Brotherhood, Tokyo Ghoul, ERASED
