### ISSUE TITLE
[Feature Request] Remove torrent button

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#666]
Can you add a clear button to the torrent details page. As I have some old torrent that seem to be stuck although I have downloaded and watched them a long time ago.

![untitled](https://cloud.githubusercontent.com/assets/16563034/13984693/c1b48136-f0ef-11e5-8218-95df3b775fa6.jpg)

**Comment by garfield69** [comment]
The latest DuckieTV development version will only try to show torrent details *if* the torrent is still on the TorrentHost.

If you have finished with the torrent on the TorrentHost, and are not planning on seeding, then remove the torrent.

DuckieTV will eventually discover the torrent is gone and will stop trying to display its details.

I am going to assume that by using the term clear, you mean you want to be able to remove/delete the torrent from the torrentHost (just the entry not the files).
Correct me if I have got this wrong.

So to implement a remove-torrent button, I first need to research how many of the torrentHosts we interface with support remote torrent removal. If I find a majority then I will work on implementing it, otherwise I will decline the feature.

**Comment by zero77** [comment]
That wasn't the feature I meant but this would be useful.

The torrent has been removed from Utorrent ages ago but for some reason it still appears In the torrent details page like above and it doesn't seem to remove itself automatically. 
I've restarted DuckieTV and Utorrent and the entire computer but nothing has works.

**Comment by garfield69** [comment]
Well that is very strange. DuckieTV does not store PERSON.OF.INTEREST.S04E20.HDTV.X264-LOL[ETTV] any place. That name can only have come from uTorrent.
If as you say, uTorrent does not display that torrent in it's list of torrents any place (Downloading, Seeding, Completed, Active, Inactive) then that suggests corruption in the uTorrent database.

Anyway, All the DuckieTV torrentClients support remove-torrent, so I shall be able to implement this feature.

**Comment by garfield69** [comment]
Implement checklist
- [ ] torrentRemoteControl
- [ ] torrentClientDetails
- [ ] uTorrent API
- [ ] BaseTorrentClient
- [ ] uTorrentWebUI
- [ ] deluge
- [ ] qBitTorrent/qBitTorrent+
- [ ] transmission/vuze
- [ ] Tixati
test checklist
- [ ] uTorrent API
- [ ] uTorrentWebUI
- [ ] deluge
- [ ] qBitTorrent/qBitTorrent+
- [ ] transmission/vuze
- [ ] Tixati

**Comment by zero77** [comment]
Okay thanks I'll have a look at utorrent.If you're going to add this feature can you also add the option for auto remove after a certain period of time has passed or a certain seed ratio has been reached.

**Comment by garfield69** [comment]
nope. Make a separate request for those features, they are not within scope of this feature.

**Comment by SchizoDuckie** [comment]
![image](https://cloud.githubusercontent.com/assets/111710/14125955/3eb9f832-f60e-11e5-89e0-84b38109e6aa.png)

**Comment by SchizoDuckie** [comment]
Dude, you're on a roll. You make me very proud and filled with feelings of rainbows and fluffyness

**Comment by garfield69** [comment]
Cheers.

 

  _____

**Comment by Js41637** [comment]
Yeah you're making us look bad, slow down a little would you.
