### ISSUE TITLE
Standalone version data refresh time issues

### ISSUE THREAD

**Issue by Sunabubus** [SchizoDuckie/DuckieTV#676]
Hello!
I'm using the standalone desktop version, and I've noticed that if I leave my computer on for overnight, with the client running in the background, it does not (always?) refresh the shows, I need to restart the whole thing in order to force the data pull, and in addition, the calendar does not refresh itself for the new day, it stays on the previous date even tho it's 4:00 am the next day. 
I guess it's not an issue in the browser client, as you tend to close it and reopen it when you go for the new episodes, so you force it to pull new data, but in the desktop version it's kind of annoying.

**Comment by garfield69** [comment]
What version of DuckieTV standalone are you using, and on which platform?

**Comment by Sunabubus** [comment]
Windows 10, as for the version, I've just installed the latest beta, so I don't exactly know what version I had before, it was a beta from 3-4 days ago. But this is not a new issue, I've noticed it months ago.

**Comment by garfield69** [comment]
ok. thanks.
DuckieTV is supposed to do a internal reload one second after midnight, in order to refresh the calendar and everything. 
I'll set up a dev DuckieTV for an overnighter and see if that is still working for me in the morning.

**Comment by Sunabubus** [comment]
Hm. For the desktop client only, a refresh-rate setting would be really good. Europe gets the new episodes around 4:00-6:00 am (that's USA 8:00-10:00 PM), and I've noticed that when I stay up for the night, duckietv needs to be restarted to pull the data, and after restart, it finds the new episodes right away.
I'm guessing it's because at midnight in Europe there is no new episode, since it's still the previous afternoon in the USA.

**Comment by garfield69** [comment]
Oh wait. Some miss understanding has occurred.

There a two distinct processes we are talking about there.

1. at a second past midnight, a browser reload is issued. This is only to refresh the calendar, to get it to adjust to the new days date, so it can reload the calendar for the new day.

2. every day, once a day, at a set time (base on when you first started DuckieTV for the very first time), DuckieTV goes out and fetched from Trakt.TV all the episodes that it has accumulated since the last time DuckieTV checked.

Which issue are you having problems with ?

I have noticed recently, a problem with Trakt.TV episode data for some series documented in ticket #675.
I think this problem prevents DuckieTV from saving the daily-fetched time stamp, which in turn could cause problems the next day... unverified and untested theory, research is ongoing.

**Comment by garfield69** [comment]
if you want to know at what time DuckieTV last did a fetch from Trakt.TV successfully, (24 hours from which the next update will occur), then press **F12** to open the development tools panel, click on the **console** tab, and at the **>** prompt paste `new Date(parseInt(localStorage.getItem('trakttv.lastupdated')))` and press Enter.

**Comment by garfield69** [comment]
or even simple, click on the (i) icon on the bottom left of the main DuckieTV page, then scroll down to the statistics section. look for **Last checked TraktTV for DB updates on** which will have that date/time stamp.

**Comment by garfield69** [comment]
I've edited my previous two posts to correct some errors, so please re-read online, if you were relying on the emailed original posts.

**Comment by Sunabubus** [comment]
The calendar issue happened as I wrote my ticket today. It was Wed. 4:00 am but it still showed Tuesday. After restart it was OK. 

As for the other thing. I think my issue is really more like a shortcoming then. Like, if you use the browser version, I guess you expect it to open up many times a day, maybe, depending on the show, to see if it's available, and in general, as you open and close your browser, and with that, force duckietv to check for new episodes. But with the desktop client, it can be up and running for DAYS without shutting it down and reopening, thus, the daily one "look for new shows" seems a bit low. I picked the desktop client because I want everything to be automatical. So for the desktop client only, a "check for new episodes every x time" that starts with 30 mins/1 hour would be really cool.

**Comment by garfield69** [comment]
I've raised a feature request #677 to explore the option of a trakt.TV updates frequency setting.

There may be a practical reason it is currently set to 24 hours, but if not, a range between *x* hours to 24 hours, may be possible. (*x* may need to be set to a practical minimum if Trakt.TV only generates updates at a certain hourly rate).

BTW, I ran my dev standalone overnight as promised, and at 2 seconds past midnight the calendar was reloaded as expected. So that is working on my win7 platform. I dont have a win10 to test on, so I can not eliminate win10 being a cause.

However, there is one possible explanation for the calendar being out of date:
If you are using DuckieTV in conjunction with uTorrent, and in particular, with uTorrent API (as opposed to uTorrent WebUi or any of the other WebUi torrent Clients), then I have come across a situation where if DuckieTV lost its connection to Utorrent API for whatever reason, then, after a day or more, the log gets choked with connecting errors/retry connection messages, to the point where DuckieTV is practically frozen, and a restart is the only way out. (May be some sort of Storage/memory constraint issue).

So the next time you come across the calendar being out of sync with the day (identified by looking for the yellow day number in the calendar not being todays day number), then press **F12** to open the development tools page, click on the **console** tab, and browser the log looking for errors. 

If you come across the calendar being out of date in this way again, then please open a fresh ticket, and include a dump of the log for us to take a look at. Thanks.

**Comment by garfield69** [comment]
regarding your recent edit:
>Edit: As for the trakt fetch. I don't really give a damn about trakt, other than marking my watched episodes in it, I mean when today duckietv did the fetching and one of my shows' name suddenly showed up in spanish I was like huh? but other than that it's just cosmetic stuff. I'm more concerned about not getting my shows ASAP, without bruteforcing the client to look for it, because the daily one refresh.

Just in case, for clarification, Trakt.TV is where DuckieTV get **all** its episode information from. The episode updates are fetched from Trakt.TV, currently every 24 hours.

The trakt.TV sync features in settings are optional, and have no impact on DuckieTV fetching episode updates, show details etc.

**Comment by Sunabubus** [comment]
Yeah just wanted to be on the same page that my refresh issue is not with trakt, but rather with the new episode searches.

Hm, what you say about duckietv getting freezed by errors is probably what happens here. I mean duckietv basically acts as if it was frozen. 
I just shoved utorrent and duckietv into the startup folder, so when I start up my pc in the morning, they automatically start doing the magic together, but yeah, explains why my problems happen after long runtime, esp. the calendar issue. I will keep an eye on it and report back if I find something.

Thanks for the #677, and everything. I think this ticket can be closed now.
