### ISSUE TITLE
Web Server mode for Standalone

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#678]
as per this [Reddit](https://www.reddit.com/r/duckietv/comments/4ch14c/feature_request_web_server_mode_so_duckietv_can/) thread:
Embed a web server inside DuckieTV to be able to access it's data from a remote computer, perhaps with the use of express, for standalone only.

**Comment by zero77** [comment]
It may or may not be easier but instead of embedding a Web server you could just integrate XAMPP portable or the installed version with DuckieTV.

**Comment by Js41637** [comment]
Yeah no, DuckieTV isn't designed as a server, while DuckieTV theoretically can run on it's own like a server, it's still not designed that way and would creating a webserver is actually really easy for Standalone, it's just a few node modules, it's setting up the actual API that will hard.

**Comment by SchizoDuckie** [comment]
unfortunately this requires a ton of work and will most likely have some concurrency issues. Since all the websql tech is currently designed to run on a WebSQL database via window.openDatabase, which always opens a local copy of the database.

Bypassing that will require an internal API change that forwards all the CRUD.* calls to the background page, where it can execute a query and return the result, god knows what else.

It would definitely be cool though, pushing it to 2.0 for now

**Comment by lozbrown** [comment]
I like a lot of people have a home server with a webserver (nginx) that is predominately used to reverse proxy and https secure/encrypt the UIs for things like torrentclients / kodi web etc to a URL where i can access them fairly securely from work. 

Installing stuff on work PCs is not a good idea. 

I'd love to be able to install duckieTv to that home server, either served up by or reverse proxied by the webserver to the PC's I access regularly with a mouse or keyboard. I would be able to check my DuckieTV calendar and maintain shows etc. 

Its the machine that is best suited to being always on and handling stuff like automatic downloading etc. 

Webserving this is clearly possible as is demonstrated by http://duckietv.github.io/DuckieTV although i take he point above that some significant work is required to store the settings server side rather than local to the accessing browser. 

This would provide a nice integrated replacement to my usage of the following sites
pogdesign.co.uk/cat/
showrss.info

**Comment by phalox** [comment]
Would be very interesting indeed... but I guess that's never going to happen.

**Comment by lozbrown** [comment]
@SchizoDuckie is this still as difficult as ever? how is http://duckietv.github.io achived?

**Comment by SchizoDuckie** [comment]
Yes. It's still ad difficult and requires a total rewrite of DuckieTV since
all DuckieTV instances use your browser's local WebSQL storage instead of
some form of backend storage (which would require user accounts, a
database, etc etc)

DuckieTV.github.io/DuckieTV is unsafe since it proxies all your requests
through a hacky proxy to enable CORS. Do not use this for daily use. It's a
demo.

**Comment by acosaburca** [comment]
Any news? Maybe in the near future?

**Comment by SchizoDuckie** [comment]
*sigh*
No. It won't happen people.
Not unless somebody jams in a massive PR that does this.
