### ISSUE TITLE
chrome extension connection by uTorrent client not async?

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#686]
When the chrome extension is started, but the default uTorrent Host is not active, the uTorrent client Connection attempts don't appear to be synchronous, holding up processing until it times out on the last port tested out of 20.   
This causes about a 40 second delay at start up for various services. (20 ports with a 2 second timeout for each port).

This does _not_ happen if one of the Web torrent clients is used.
Also does _not_ happen for _any_ torrent client on standalone.

needs research.

**Comment by SchizoDuckie** [comment]
This is probably because it fires request that are queued and then time out.

Since there can only be 2 http threads simultaneously, in the worst case scenario when nothing is listening there will be 2 secs times 20 (port range for the algorithm) delays before other http requests can work

Suggestions:

- change http timeouts on the port scan to some 400ms
- figure out a queueing mechanism with some breathing time

Ohai from the new house by the way!
