### ISSUE TITLE
favorites posters picture don't always show up since 22464bd9937682dfc803bdc13b0b6800d845a3e0

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#687]
Example
![image](https://cloud.githubusercontent.com/assets/6933240/14551544/8fad622a-0328-11e6-95ee-3fdd3fc8844c.png)
no errors in the log or anything that indicates what the problem might be.

[edit] the problem is most evident when using the sort menu.

**Comment by Js41637** [comment]
Ah yes, I forgot about the filters and categories. I've already got the categories fixed but, because these posters (by default) transition to their location, I have to account for the possible delays.

**Comment by Js41637** [comment]
See if you can do some of your performance monitoring magic before and after this new loader. If it's too much hassle it might be better to just remove it, it was just an idea I was trying out.

**Comment by garfield69** [comment]
you asked for statistics, so here you go.   
I ran the development tools timeline and gathered some data.    
Ran it 3x3, that is, started chrome browser 3 times, and for each session ran the timeline 3 times each one after the other.   

result example from the timeline:
![image](https://cloud.githubusercontent.com/assets/6933240/14578678/860765bc-03e2-11e6-9420-4cc4056ff1cf.png)

Statistics:
![image](https://cloud.githubusercontent.com/assets/6933240/14578685/9ee79c14-03e2-11e6-8ba0-602a674faa94.png)

I tried to minimise interference, by shutting down most of my other processes, but there is always going to be events that kick off on my PC that I cant control, as these stats are not taken in laboratory conditions.   
So take the data with a huge pinch of salt.   

The stats seems to suggest to me that the lazy loader you introduced is not an huge improvement, very little to tell between the two, one side or the other of the ledger.   

On my two old PCs, (single CPU AMD, and Dual CPU Intel), the new image loader still does not render the favorites after a sort.   But it is likely that for most users on faster machines this works properly? I don't know.

**Comment by Js41637** [comment]
Oh wow, I try to use the chrome dev tools but, I can't even understand how to properly read the data lol. It is safe to assume the lazy-loader would be a bit more _processor_ heavy as it is monitoring for scroll events and fired every 120ms or so while scrolling but it also cuts down network usage by not loading all posters at once which is 75 when adding a show and possibly more in your library. This also lets the more relevant posters load first instead of getting delayed overall by all other posters. The main issue I think is the edge cases where posters don't load which is expected considering it wasn't really designed for this use case which is filtering and moving about. Without filtering it should work perfectly, but with the case of filtering, it should just be a case of adjusting the delay before fireing a refresh or increasing the offset so it will still detect if even if it isn't completely in view.

**Comment by garfield69** [comment]
so I suppose I could tinker with the timings a bit and see if I can get it to reliably render sorts on my computer, then that can become the default minimum timing that should work on most others?
The timings to adjust would be the ones you adjusted in your latest commit?

**Comment by Js41637** [comment]
Indeed, you can up the offset a bit, which will give it a bit more leniency just be sure not to go greater than the actual height of the poster otherwise it will load another whole row and upping the delay will obviously set how long to wait before it rechecks their position, really this should be just a bit higher than the transition time which I think is 350ms.
