### ISSUE TITLE
Backup won't load (Windows Chrome backup loaded into Linux Standalone, 1.1.3)

### ISSUE THREAD

**Issue by roshavagarga** [SchizoDuckie/DuckieTV#688]
Encountered a problem with loading a backup from my windows chrome tab plugin into my standalone linux version (both 1.1.3). 

Unique tracking id = f3f349bd-a053-a9f3-a485-3de7f085c82d 
The backup: http://www59.zippyshare.com/v/BXwcpdId/file.html
Duckietv stats = https://gyazo.com/9548d12e70723c7c27f0f83ff3b09554

Wiped duckietv, enabled tracking (this is on the Linux side), then settings > backup > import a backup. Enabling the opt-in issue tracking bugs out duckietv on the linux laptop - I can't click on yes/no or X buttons once every 1/2 restarts. Anyway tried loading a backup both from settings and from the "You have no series yet" part, just says _loading, please wait_ and nothing happens.

**Comment by garfield69** [comment]
unfortunately the default Tracker is not working at the moment. We did not consider filtering error messages, and the tracker is currently stopping after the 100 per day limit is reached (this is the free service limit).

Your errors did not make it to the tracker :-(

I've switched to a development tracker for now, which will be included in the next nightly build 04-15-2016.   
If you grab the linux nightly 04-15-2016 when it becomes available and use this to import the backup you previously created, we can see if the Tracker is useful or not.   

Alternatively, you could just open the log and take a look directly. **F12* key to open the development tools page, and click on the **console** tab to view the log.

**Comment by garfield69** [comment]
Also possible this is related to #675.

**Comment by roshavagarga** [comment]
Log from the Linux Standalone:
http://pastebin.com/bRaSDd0z

**Comment by garfield69** [comment]
Ah. Its the Linux SSL Protocol Error.
This DuckieTV Reddit thread [TraktTv SSL Protocol Errors](https://www.reddit.com/r/duckietv/comments/4be51b/trakttv_ssl_protocol_errors/) is a match for your problem.

It has to do with TrakT.TV refreshing their SSL certificate when it expired back in March. However the new certificate they are using now uses a protocol which on some Linux platforms, the DuckieTV Standalone 1.1.3 cannot handle.
More correctly, its not DuckieTV, but some flavours of Linux chromium that runs inside the Standalone.

Two options at the moment:
- use a Linux Chrome Browser and install DuckieTV 1.1.3 Chrome Browser Extension which the Reddit users found works
- install the development standalone DuckieTV with NWJS 0.14, which is untested but should work since it is using chromium 50m. If you are keen to try this let me know I will cook up some instructions.

**Comment by roshavagarga** [comment]
Hey, @garfield69 

The Linux Chrome Browser isn't an option for me - I'm running Lubuntu on a 10 inch samsung mini-laptop. Firefox barely works, let alone Chrome. 

Thus, I am keen on testing the development standalone, so you can send me some instructions. I will probably wait a bit (until maybe the 25th?) to give you an answer. I'm currently using Lubuntu 15.10, and the new LTS version of Lubuntu 16.04 should be released on the 21st.

**Comment by garfield69** [comment]
OK then. So I am going to have to assume that you have good knowledge of how to use the lubuntu tools, commands, and whatnot, and are able to interpret what are essentially instructions for a windows 7 platform, and convert them to the equivalent for your lubuntu system... otherwise you are in trouble :-b   

- go to this [https://github.com/SchizoDuckie/DuckieTV/tree/NWJS-0.13+](https://github.com/SchizoDuckie/DuckieTV/tree/NWJS-0.13+) address
- and click on the **Download Zip** button to grab the latest archive of the DuckieTV development source code
- extract the archive to your favourite development folder (which I am going to call *dtv114nwjs014* for future reference in this guide).
- go to this [http://nwjs.io/downloads/](http://nwjs.io/downloads/) address
- and download the **SDK** archive of the latest NWJS for your platform (0.14.1 at last check)
- extract the archive to the dtv114nwjs014 folder.
- run the NW program and import your 1.1.3 duckietv.backup

good luck.

**Comment by garfield69** [comment]
Closing ticket based on assumption OP resolved SSL protocol error on his linux platform by switching to NWJS SDK 0.13+ .
Will re-open should OP require further assistance.
