### ISSUE TITLE
uTorrent connection issues

### ISSUE THREAD

**Issue by methos237** [SchizoDuckie/DuckieTV#696]
I keep the stand-alone version up-to-date with git pulls, and for the last couple of weeks I have noticed that every day I have to re-authorize the token for Duckie to talk to uTorrent.  My guess is this happens some time after midnight as the highlighted date in the Duckie calendar does not update either.  My current work-around is to close uTorrent and Duckie, restart uTorrent, then Duckie, and then clickon "Clear uTorrent authorization".  Sometimes I have to go through this cycles three or four times before it connects.  My current uTorrent version is 3.4.6 (build 42094), and I leave Duckie running pretty much 24/7.

Last but not least, I love this program and applaud you guys for the tremendous work! Keep it up!

**Comment by garfield69** [comment]
I will update to the latest stable uTorrent (3.4.6 42178 at the time of this writing) and leave my DuckieTV standalone running overnight to see what happens on my system.

In the mean time, it would be very useful if you could do the following for us:
The next time you get this problem, before doing anything else, from the DuckieTV main page, mouse over the uTorrent icon on the left hand side, and let us know what the tooltip has in it.
It will be something like: 
`Torrent Client Utorrent: Connected` or something else.

If it is *NOT* connected, then press the **F12** key to open the *development tools* panel, click on the **console** tab to view the log, and screen capture the last page (press the **Print Screen** key, then use **Ctrl-v** to paste into the body of the open box below here.

Thanks.

**Comment by garfield69** [comment]
thinking about what you reported, and especially the line:
>Sometimes I have to go through this cycles three or four times before it connects. 

This sounds to me more like a connectivity issue rather than a token issue.   
looking back at what might have changed to impact connections to uTorrent in this way I see change #686  reduced the time-out from 2 seconds to 400 ms, and which I subsequently had to increase to 600 ms with 6660be65119f575b7d5343aae5b18bf47c1b69bd in order to help my system connect more reliably.
I wonder if you are experiencing fallout from this change done on April 15 which lines up with your
>for the last couple of weeks 

in your report.
So what we can do is bump this time-out up a bit more until you get connected reliably.

**Comment by methos237** [comment]
So it did it again, and when I was gathering the info you requested, I found the button on the info screen that says" Opt-In error tracking".  So I enabled it, Duckie did its refresh, and then connected to uTorrent and started downloading.  I'll keep it enabled and see if it makes a difference, and here's the Tracking ID if it helps: bd166633-0fef-4ed0-c1c2-630a7f9a0b6b

![log](https://cloud.githubusercontent.com/assets/5730632/15041012/eb6631ba-1286-11e6-9db7-139318f46661.jpg)
![ss](https://cloud.githubusercontent.com/assets/5730632/15041011/eb63090e-1286-11e6-829c-ae5c8303f9f7.jpg)

and here is the Statistics from the info screen:
DuckieTV Web Based	1.1.4
Current Date and Time	Thu, 05 May 2016 09:59:37 GMT
UserAgent	DuckieTV Standalone v1.1.4
Platform, Vendor	Win32, Google Inc.
Screen (width x height)	1920 x 1080
Active Torrenting URL	https://thepiratebay.se
Last checked TraktTV for DB updates on	Wed, 04 May 2016 23:13:09 GMT
User Preferences on Local Storage	{ "KickAssTorrents.mirror": "https://kat.cr", "ThePirateBay.mirror": "https://thepiratebay.se", "application.language": "en_us", "application.locale": "en_us", "autodownload.minSeeders": 50, "autodownload.period": 1, "background-rotator.opacity": "0.4", "calendar.mode": "date", "calendar.show-specials": false, "calendar.show-downloaded": true, "calendar.startSunday": true, "client.determinedlocale": "en_us", "lastSync": -1, "library.smallposters": true, "qbittorrent.server": "http://localhost", "qbittorrent.port": 8080, "qbittorrent.use_auth": true, "qbittorrent.username": "admin", "qbittorrent.password": "*****", "series.displaymode": "poster", "standalone.zoomlevel": 6, "storage.sync": false, "sync.progress": true, "tixati.server": "http://localhost", "tixati.port": 8080, "tixati.username": "*********", "tixati.password": "*****", "topSites.enabled": false, "topSites.mode": "onhover", "torrenting.autodownload": true, "torrenting.autostop": true, "torrenting.client": "uTorrent", "torrenting.directory": true, "torrenting.enabled": true, "torrenting.progress": true, "torrenting.searchprovider": "KickAss", "torrenting.searchquality": "720p", "torrenting.streaming": false, "transmission.server": "http://192.168.0.14", "transmission.port": 9091, "transmission.use_auth": true, "transmission.username": "methos237", "transmission.password": "*****", "trakttv.passwordHash": "*****", "trakttv.sync": true, "trakttv.username": null, "utorrentwebui.server": "http://localhost", "utorrentwebui.port": 8080, "utorrentwebui.username": "********", "utorrentwebui.password": "*****", "utorrentwebui.use_auth": true, "download.ratings": false, "autodownload.lastrun": 1462441391447, "standalone.width": 1645, "standalone.height": 883, "standalone.x": -1920, "standalone.y": 392, "library.seriesgrid": true, "main.viewmode": "calendar", "torrenting.global_exclude": "HEVC [hevc]", "torrenting.global_exclude_enabled": true }
Other significant Local Storage keys	{ "1.0migration": "Fri Jun 26 2015 09:06:04 GMT-0400 (Eastern Daylight Time)", "1.1.4cleanupOrphanedSeasons": "Fri Mar 25 2016 14:41:03 GMT-0400 (Eastern Daylight Time)", "1.1migration": "Mon Jul 06 2015 03:53:36 GMT-0400 (Eastern Daylight Time)", "autobackup.lastrun": "1460557762744", "database.version.Episodes": "12", "database.version.SearchEngines": "1", "database.version.Seasons": "5", "database.version.Series": "12", "database.version.WatchList": "1", "database.version.WatchListObject": "1", "github.lastupdatecheck": "1435323962373", "optin_error_reporting": "true", "optin_error_reporting.start_time": "1462442376976", "snr.lastFetched": "1462358393472", "standalone.closeSystray": "N", "standalone.height": "1016", "standalone.position": "{\"width\":1910,\"height\":942,\"x\":-1920,\"y\":382,\"state\":\"normal\"}", "standalone.preWinState": "Minimized", "standalone.prevWinState": "Minimized", "standalone.width": "1631", "standalone.winState": "Minimized", "standalone.x": "-1920", "standalone.y": "308", "standalone.zoomlevel": "6", "torrenting.client": "uTorrent", "trakt.token": "ic8sgBKcKfs3MrThJDiM", "trakt.username": "methos237", "trakttv.lastupdated": "1462403589100", "trakttv.lastupdated.trending": "1462171745611", "trakttv.refresh_token": "719944f209ef35a73b8f843f9eeb053a0cf0c6627774b82d3de31ad656248c74", "uniqueId": "bd166633-0fef-4ed0-c1c2-630a7f9a0b6b", "upgrade.notify": "1.1.4", "utorrent.port": "10000", "utorrent.token": "6CFF1B857D712C5A23D78BEE03432D31906936DE", "xem.lastFetched": "1462358393546" }
DB Series	126
DB Series Hidden From Calendar	0
DB Seasons	462
DB Episodes	6214

**Comment by garfield69** [comment]
Thanks for the info you gathered.
If you fetch the latest GitHub source you will pick up e5c1f82 which bumps the uTorrent client connection time-out from *600 ms* to *800 ms*. 

The way it works is that DuckieTV pings uTorrent on each of 20 ports, waiting for 800 ms on each port for a response. If it does not get a connect from any, it then waits 15 seconds and tries those 20 again, looping forever.

You can test it by shutting down uTorrent and DuckieTV, starting uTorrent, and then starting DuckieTV.
If everything is working as it should, DuckieTV should connect to the uTorrent client within 30 seconds or so.

To test it without waiting for midnight to roll-over, you can keep uTorrent running, and just shut-down and start DuckieTV again. Repeat until you are satisfied that DuckieTV always manages to connect to uTorrent after a restart. (The midnight date roll-over is an internal restart, similar to a shut down and start-up sequence).

If it does not connect, or does so intermittently between tests, we can bump the time-out value by another 50 ms and try again.

Since you are using the source code, you could change the value yourself if you want speed up the process. Using your favourite plain text editor, **edit** `../js/services/torrentClients/uTorrent.js`, scroll to **line 117**, and change the **800** to **850**, **900**, etc. **Save**, restart DuckieTV and check the connection. *Rinse* and *repeat*.

In any case start with 800 ms, and let us know how it goes. If you need to change it higher then let us know what value finally worked for you so we can update the source on GitHub.

If you get to 2000 and it still is not connected then we are in trouble and something else is wrong :-(

**Comment by methos237** [comment]
I'm going to test it out for a week and see how it goes.  Right now I'm at 850ms and it'll go through one iteration saying connection refused, and then it'll connect on the next pass. It's still not updating the day highlighted on the calendar when it passes midnight, unless I restart Duckie.  Case in point, I last restarted the prog on Friday and left it running all weekend. Friday was still highlighted until just now when I restarted Duckie again.

**Comment by garfield69** [comment]
Well that is excellent progress. I don't think you will get any further improvements by changing the time out past 850 ms. As long as it connects withing the first two passes then I would say that the first problem is solved.

The issue of the calendar date not shifting after midnight however, is a separate problem that needs research. What version of windows are you on?

**Comment by garfield69** [comment]
Also, what version of NWJS are you using to run your DuckieTV standalone code under?

**Comment by methos237** [comment]
I'm updating to 0.14.4 now to see if that helps with the calendar 
issue.  I'm running Windows 10 x64 with the latest updates.

**Comment by methos237** [comment]
Ok, here's what I just did: I updated NWJS to 0.14.4 (x64), downloaded 
and ran the latest official Duckie x64 release, and then scraped the 
latest changes from github. I'll let you know if anything changes 
tomorrow.  I may need to do a fresh reinstall of Duckie, and if so, what 
files do I need to keep to retain my show history, settings, and such?

**Comment by garfield69** [comment]
Ahh. So now I understand why your calendar is not being updated at midnight. :grinning: 

The GitHub source code in the [angular](https://github.com/SchizoDuckie/DuckieTV/tree/angular) branch of DuckieTV is only certified for running under NWJS up to version **0.12.3**.

This is because NWJS 0.13+ made some significant changes under the hood, and this broke some of  the DuckieTV standalone support code, as well as the window reset code that is used to update the calendar at midnight for the new day.

See ticket [638](https://github.com/SchizoDuckie/DuckieTV/issues/638) for all the details on the NWJS changes and how they impact DuckieTV.

The way I see it you have two choices:

**(1) using NWJS  0.13+**
If you want to run DuckieTV development source under NWJS 0.13+, you need to switch to the [NWJS-0.13+](https://github.com/SchizoDuckie/DuckieTV/tree/NWJS-0.13+) branch of DuckieTV. 
This code contains all the amendments that support NWJS 0.13, 0.14 and even the 0.15beta versions. 
I keep this source branch up to date in parallel with the angular branch for testing, as this is the version I am also using for my personal use.

>Ok, here's what I just did: I updated NWJS to 0.14.4 (x64), downloaded and ran the latest official Duckie x64 release, and then scraped the latest changes from github.

Ah. The Latest official DuckieTV x64 release is built using NWJS 0.12.3, which will not help you set up the environment for running the DuckieTV development source under NWJS 0.13+.

To run DuckieTV under NWJS 0.14.4,   
- grab the latest zip archive from the DuckieTV [NWJS-0.13+](https://github.com/SchizoDuckie/DuckieTV/tree/NWJS-0.13+) branch by clicking on the **Download Zip** button on that page.
- Extract the archive which will create a **DuckieTV-angular** folder.
- Then copy the contents of that folder to the NWJS 0.14.4 folder.
- Finally, rename NW.exe to DuckieTV.exe and you are nearly there.  

>I may need to do a fresh reinstall of Duckie, and if so, what files do I need to keep to retain my show history, settings, and such?

The simplest way would be to perform a backup on the DuckieTV version that has your current shows.  
- Go to the DuckieTV **settings,backup** sidepanel and click on the **Create a Database Backup** button.
This will also backup your current DuckieTV preferences.
- On the NWJS 0.14.4 DuckieTV build, use the **Import** a backup option from the **You have now shows yet!** page, 
- **OR** go to the **Settings,Backup** sidepanel and click on the **Choose a Backup to Load** button.


**(2) Alternatively**
If all this is just too much trouble for you, then switch back to using the NWJS 0.12.3 builds with the latest DuckietV angular Development source code, or using the latest DuckieTV Nightly builds which contain the NWJS 0.12.3 and latest DuckieTV angular source code.


Good luck, let me know how you go.

**Comment by shadycady** [comment]
Is there an option for stand alone nighties to choose the nwjs build?
I haven't made any changes to nwjs explicitly but did reformat and do a clean install.
how do i find what nwjs build i have?

I have had the same problem described above as far as the calendar not updating itself to the correct date.  Started around April 15 like stated above.

i love this software and loved the way you start it and let do her thing.... but right now she is like grandma.   No duckie its not Monday anymore, its Tuesday 2016!

**Comment by garfield69** [comment]
@shadycady 
>Is there an option for stand alone nighties to choose the nwjs build?

No there is not. The Nightly builds should be created by combining NWJS 0.12.3 with the primary [angular](https://github.com/SchizoDuckie/DuckieTV/tree/angular) tree of DuckieTV.

>how do i find what nwjs build i have?

Both the Production version of DuckieTV standalone 1.1.3, and the nightly builds should be using NWJS 0.12.3 and chromium 41m for their core service.

Which platform flavour of the nightly standalone are you using? (eg. win32,win64,linux32,linux64,osx32,osx64,android)

And which version of the OS are you in? (eg win7, win8.1, win10, etc)

>I have had the same problem described above as far as the calendar not updating itself to the correct date. Started around April 15 like stated above.

This is very odd. Have you upgraded to the latest nightly 05172016? Which version of Nightly are you running? (Check by clicking on the (i) icon on the main DuckieTV page. The top line should have something like `About DuckieTV v20160517`

**Comment by shadycady** [comment]
OK sorry this got lost in my inbox...

So I have found a solution but not sure what the problem really is.

If I leave duckietv standalone dev just running it will not update the date
to the next day in the calendar. But if I just clear utorrent auth. After
selecting yes in utorrent it updates the date correctly.

It's been a problem a maybe a month noticed when I left for a long weekend
and came back and duckietv was like "still the day you left"

I've been shutting everything down then starting everything up again. To
get the date to update.

So I believe it's a bug not sure whos?

**Comment by garfield69** [comment]
@shadycady  grab the latest nightly and let me know if you still have this problem

**Comment by garfield69** [comment]
@methos237  did you get your NWJS 0.14.0 (now 0.15.0) problems sorted and have a working DuckieTV now?

**Comment by garfield69** [comment]
@shadycady  did you upgrade to the latest nightly, are you still having issues with the DuckieTV Calendar?

**Comment by methos237** [comment]
Yes, I got the connection issues fixed by updating to the latest nightly.
Sorry for the lack of communication, work and school has been a bit hectic
lately.
