### ISSUE TITLE
Trakt.TV Import does not respond

### ISSUE THREAD

**Issue by SysQuo** [SchizoDuckie/DuckieTV#697]
Using DuckieTV - 'New Tab' mode	v1.1.3 on Chrome (up to date) on Windows 10 Ultimate x64 (up to date)  When I click on Import Shows From Trackt.TV nothing happens, nothing gets pulled. I often update seen episodes but this is not being reflected back on DuckieTV (it used to work a while back)

May be unrelated but when I download a torrent, line turns reddish while downloading then green after the download is complete. After a few hours or the next day all download info is gone and the calendar is as before downloads.

May also be unrelated but, whenever I run CCleaner all series information is wiped out, I can can restore from a previous BackUp.

Thx, for any help.  SysQuo

**Comment by garfield69** [comment]
lots of different problems reported here, I'll try to cover them all 

>Using DuckieTV - 'New Tab' mode v1.1.3 on Chrome (up to date) on Windows 10 Ultimate x64 (up to date) When I click on Import Shows From Trackt.TV nothing happens, nothing gets pulled. I often update seen episodes but this is not being reflected back on DuckieTV (it used to work a while back)

two possible reasons for this:
- the trakt.tv token has expired or been deleted. (likely cause is CCleaner). Try renewing the token. From the DuckieTV settings,Trakt.TV side panel, click on the clear credentials, and then enter your trakt.tv username and click on the *authorize duckietv* button.
This should take you the the trakt.tv signon page, and after login in, you will be given a new pin, which you can copy and paste into the duckietv trakt.tv pin box. After clicking the duckietv  *login to trakt.tv* button, you should have a new token.

- or you are having trakt.tv connections issues. I have seen lots of error 500 (server error) from trakt.tv these last two days, so it possible this is affecting you. To confirm this, then after you try the Import, press the **F12** key to open the *development tools* panel, click on the **console** tab to view the log and look for error messages from trakt.tv
If you need help interpreting the messages, copy and paste them in the box below and we can take a look.

>May be unrelated but when I download a torrent, line turns reddish while downloading then green after the download is complete. After a few hours or the next day all download info is gone and the calendar is as before downloads.

You might want to consider switching to the latest development version of the DuckieTV TAB chrome extension. We have made some changes/improvements to the torrent client interfaces, which may benefit you. You can find a guide on how to install the **nightly chrome extension** at this [wiki](https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-DuckieTV-Chrome-Browser-Extension) (follow option 2 in the guide for *Nightly* installs).

This may also improve your trakt.tv experience as we also made some changes to that code since 1.1.3 was released.

>May also be unrelated but, whenever I run CCleaner all series information is wiped out, I can can restore from a previous BackUp.

The default settings for CCleaner for the *applications tab,Google Chrome* section, is to wipe pretty much all temporary data on the browser. So either stop using CCleaner, or change its settings (you will have to experiment on which settings blow away duckietv's data), or put up with having to restore from a DuckieTV backup as you are already doing. Self inflicted, nothing we can do about this.

**Comment by SysQuo** [comment]
OK Wow! On the nose.
Reset The connection with Trakt.TV - It Works! (at least there seems to a communication)
Uploaded latest nightly chrome extension: DuckieTV - 'New Tab' mode - Canary 20160506, looks good, but I haven't seen any changes to current episode status, will give it a few days and trials to see.
I will be re-configuring CCleaner to avoid further issues (exclude Chrome)
Thank you for the prompt and insightful comments. S.

**Comment by garfield69** [comment]
Closing ticket on the assumption problem has been resolved, based on no further feedback received from OP. Will re-open should OP require it.
