### ISSUE TITLE
location of database

### ISSUE THREAD

**Issue by no1adamg** [SchizoDuckie/DuckieTV#704]
can you tell me the location of my database, i still have duckie in windows old after a win8 reinstall lost my backup like a dk was wondering if it would still be around so i can move it into the app once again

cheers

**Comment by garfield69** [comment]
for the DuckieTV standalone 1.1.3 on my win7 system, the location to the database is
`C:\Users\<currentUserName>\AppData\Local\DuckieTV-Standalone\databases\file__0\1`
You will probably need to enable the 'show hidden folders' settings on your system's control panel folder options in order to view the hidden users folder.

Note that copying the database directly like this, will only work if you are going to use the same version of DuckieTV that created the original database.
If you have miss-matching database and DuckieTV versions, you are going to need to do additional preparations. Let me know if you need this information.

**Comment by no1adamg** [comment]
ok thanks ya thats what i have also i didnt think of versions not matching though.
cheers m8

**Comment by no1adamg** [comment]
thanks that worked great just installed version i was running, moved the file and bam

cheers m8
