### ISSUE TITLE
Keep search dialog open after clicking "download magnet link"

### ISSUE THREAD

**Issue by smeijer** [SchizoDuckie/DuckieTV#719]
When searching for torrents, It would be convenient if the "Torrent Search" dialog stayed open when clicking on any of the "download" links. 

This way it becomes easier to download multiple episodes at once.

**Comment by ShedDweller** [comment]
+1

**Comment by garfield69** [comment]
If the torrent search has been initiated from a series' episode list, then the torrent dialog is pre-loaded with that episode's search parameters and is linked internally to that episode's DB so that the magnet is recorded when it is launched.
This is done so that DuckieTV can track the progress of the torrentClient download, and when it has completed downloading the episode, DuckieTV can mark that episode as downloaded.
In this scenario, keeping the torrent search dialog open so you can change the search dialog to look for a different episode will cause the original's episode DB entry to be associated with your new episode search magnet.
This would cause the original episode to be marked as downloaded when the alternate episode(s) have been fetched.... chaos.

However, if the torrent search dialog has been initiated from the action bar on the left hand side of the main DuckieTV page, then this dialog has no such associations, so it would not cause any downstream impact to leave the dialog open for further searches. So we can certainly do that.

**Comment by garfield69** [comment]
[nightly 06-14-2016](https://github.com/DuckieTV/Nightlies/releases/tag/nightly-06142016) contains this enhancement which will also be included in the production release, whenever that happens.
