### ISSUE TITLE
Update to qBittorrent 3.3.5

### ISSUE THREAD

**Issue by emzero** [SchizoDuckie/DuckieTV#724]
qBittorrent 3.3.5 [api version is 10](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#get-api-version) and `/json` was replaced with `/query/` and so DuckieTV 1.1.3 doesn't work with it.

Haven't looked at the source code myself but I'm pretty sure the change is pretty straightforward.

**Comment by garfield69** [comment]
Try using the DuckieTV TorrentClient qBitTorrent 3.2+ instead of qBitTorrent.
![image](https://cloud.githubusercontent.com/assets/6933240/16328014/a260be48-3a29-11e6-911f-7775f9f860da.png)
If this does not work for you let me know so I can dig deeper into the code.
And if it does work let me know so I can close this ticker :-)
Thanks.

**Comment by garfield69** [comment]
Closing ticket on the assumption that OP solved the problem by switching to qBitTorrent 3.2+
Should the OP reply to the contrary we will reopen the ticket.

**Comment by emzero** [comment]
Yes, sorry, I was using qBittorrent settings instead of 3.2
