### ISSUE TITLE
Adding a show not possible 

### ISSUE THREAD

**Issue by Troutking** [SchizoDuckie/DuckieTV#730]
The tv show "The Night Of" can't be added. It shows up in the search result with correct poster, but can't  be added to favorites/calendar.

**Comment by garfield69** [comment]
It's a problem with the Trakt.TV data that DuckieTV fetches.
DuckieTV uses the **IMDB_ID** stored in the Trending show's record, to fetch the full show details from Trakt.TV servers.
The trending record for **'The Night Of'** has a IMDB_ID of **tt2401256**, which is the correct  id for that show on the IMDB web site.
However, when DuckieTV asks Trakt.TV to fetch full show details for tt2401256, it is given 
records for  **"Criminal Justice (US)"**.
This causes DuckieTV to store "Criminal Justice (US)" in its database. You will find it in your DuckieTV favorites if you go looking.
But because "The Night Of" data is not fetched, the add-a-show progress monitor is left running forever.

Unfortunately there is nothing that DuckieTV can do about this. The only way this will get fixed is if someone raises an issue with the Trakt.TV people to have the "Criminal Justice (US)" record fixed to use the correct IMDB id.

**Comment by Troutking** [comment]
Ok. Bummer.

**Comment by garfield69** [comment]
This [Reddit](https://www.reddit.com/r/duckietv/comments/4s5bco/i_cant_add_a_show/) from a user that cant load *Stranger Things* and *The Night Of* because of conflicting IMDB ids.    

While the ideal solution would be to get the Trakt.TV people to fix the records at their end, this could take some time. So I have coded a temporary bypass to get around the problem for now.    

@Troutking, If you download the latest DuckieTV development nightly at https://github.com/DuckieTV/Nightlies/releases/tag/nightly-07102016 when it becomes available in a couple hours, you should be able to fetch *The Night Of*.    
Let me know how it goes.

**Comment by garfield69** [comment]
A permanent solution to #730 may come out of #675 once it is fully implemented. It changes DuckieTV's requests for series from Trakt.TV, by using trakt_id instead of imdb_id.
