### ISSUE TITLE
[Feature Request] SSL With Torrent Clients 

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#734]
Can you add support for https when connecting to torrent clients, because at the moment it doesn’t work if https is enabled in the torrent client.

**Comment by SchizoDuckie** [comment]
Great idea. I have no way to currently test this though.

**Comment by garfield69** [comment]
research results:
I've looked into this on my win7 sandbox with all the torrent clients that DuckieTV supports, by first seeing if I could connect my chrome browser to each torrent host via their web ui support, with whichever torrent hosts had the option to enable https or ssl in their settings.
I note that windows uTorrent and TransmissionQt do not have https or ssl options in their WebUi settings. 

For the rest however (deluge, vuze, qBittorrent and tixati), all the host failed to connect via my chrome browser through https after changing the host web ui settings to use https or ssl.

Digging deeper, I found that all the torrent hosts are using certificates with either SHA1 or MD5 encryption. 

Chrome since stable 41 has been quietly deprecating support for CA's that use SHA1 or MD5 by classifying them as untrusted. Basically the idea is that SHA1 and MD5 are so weak these days that certificates don't expire past 2016 are a danger to web security and are not better than just plain http.
I expect most platforms are also doing this since web security is at the forefront of hot topics these days.

Therefore, until all the torrent hosts update their certificates to more secure encryption, (which has not happened yet as I'm using the latest version of all the torrent hosts), I don't believe there is any point pursuing this.

Finally, regarding changes to DuckieTV to support https connections, I don't believe there is any. One simply has to change the torrent integration address field from `http://localhost` to `https://localhost`.

**Comment by zero77** [comment]
Yes, when I had a look I found that the default certificates were not trusted by the web browser, although some torrent clients allow users to add their own certificates. 

So is it still possible to add support for users who use different certificates and a head of time for when the developers bring out new certificates, 
because if you add this I could start asking the torrent client developers to add new certificates support as free trusted certificates are available from hear https://letsencrypt.org

**Comment by SchizoDuckie** [comment]
The more i read about what you guys are discussing here the more i think that indeed, for duckietv there is nothing to do. You just switch the endpoint from HTTP to HTTPS, (which is what i thought was hardcoded, that would be the change to make) but for the rest it's all up to the torrent clients and for instance letsencrypt.

So i'm with @garfield69 here. No change required for DuckieTV, IMO.

**Comment by zero77** [comment]
O ok, I see so if the certificate is trusted it will automatically work with DuckieTV, I will see if I can get the torrent client developers to use trusted certificates.
