### ISSUE TITLE
Series are duplicated in calendar after updating to latest comit

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#737]
Updated duckie via github desktop, after opening duckie series populated on calendar, then re populated while the db update was being performed. 

![screen shot 2016-07-21 at 19 14 30](https://cloud.githubusercontent.com/assets/13501166/17040802/35c92bda-4f78-11e6-8247-217a3542cd0e.png)

**Comment by SchizoDuckie** [comment]
Yeap. my bad, sorry for that.

I accidentally committed a stupid half-patch for reindexing the tv shows using TRAKT_ID instead of TVDB_ID, which caused DuckieTV to think it had to re-add shows.

Please update again, @garfield69 already reverted my commit.

Unfortunately you will have to create a backup, and then wipe and re-import to solve the problem.
