### ISSUE TITLE
implement fetching details page to get Magnet and/or other data From search engines

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#741]
As far as I can see extra torrent dues support magnet links but they aren’t in an obvious place, so can you add support for this when downloading torrents.

As an example this torrent has a magnet link:
https://extratorrent.cc/torrent/5054615/12+Monkeys+S02E13+Memory+of+Tomorrow+1080P+WEB-DL+DD5+1+H+264.html

**Comment by SchizoDuckie** [comment]
We are aware. This is a pattern that happens often, magnet links are on the details page for a torrent. 

This means the torrent dialog needs to have a patch to include support for that, (which means an extra request to get the magnet link) for which i believe we already have a ticket somewhere.

**Comment by garfield69** [comment]
we'll make this ticket stand in for the internal todo that is in [GenericTorrentSearchEngine.js](DuckieTV/js/services/TorrentSearchEngines/GenericTorrentSearchEngine.js#L30)

**Comment by garfield69** [comment]
Trying to come up with the most efficient strategy regarding when to fetch a torrent details page in order to fetch the magnet URL. The goal is to reduce network traffic and speed up result presentation in the TorrentDialog.    

So currently, for each query we pull and parse the search page results.    
Then we discover that magnets are not available in the results (or there is a setting in the SE config that states this already).    
So for torrents that passed the filters, (which already reduces the work load), we drill into the details page for each torrent and fetch its magnet.    
For even better performance (in subsequent searches), we could cache the magnets so we don't have to do more network traffic.     
How long do we keep the cache? In memory that lasts as long as the session, or in storage so its always available? If in storage, to we keep forever, or expire them with a regular clean up cycle?     

Does this seem like a reasonable approach? is there better ways of doing this?

**Comment by SchizoDuckie** [comment]
I've been going over this in my mind and I think we should adopt 2 strategies perhaps.

when you think about it, we have only one situation where the whole interaction process actually *requires* the magnet to be available: in the torrent dialog. The autodownload doesn't care if it's a torrent or a magnet, wether it's remote or a local client, so that can just ignore the magnet and then grab what it can get and send that off.

It gets more difficult for search engines that potentially hide both the magnet and the torrent on a details page, or users/leechers even. we should maybe investigate what situations we will encounter.

For resolving the magnets, i've been thinking on doing that in the UI only, when clicking a 'fetch' link of some sort on a row. that way we won't have to fire hundreds of useless requests, but only fetch it when needed.

**Comment by garfield69** [comment]
So are you saying that on the TorrentDialog, we show the magnet icon for each row, and when the user actually clicks on the magnet link, that's when we fetch the magnet from the details page if it is not already available from the search results page?
Nice.

**Comment by SchizoDuckie** [comment]
Yeah, that would be the idea :)

**Comment by garfield69** [comment]
@SchizoDuckie I would like to have a go at adding the details page support for the current SearchEngines system.    
And I know that your customeSearchEngine WIP is going to *eventually* replace the functionality of the SE profiles sitting in js/services/torrentSearchEngines, but I am not at all confident in tackling that monster to integrate the details page support.    
So I am proposing that I go ahead and add details page support to the existing SE system, and leave it up to you to *eventually* integrate what I come up with into the CustomSearchEngine project.    
So, can I go ahead, or am I wasting my time because your CSE is coming out tomorrow ;-) ?

**Comment by garfield69** [comment]
checklist:
- [ ] add detailsSelectors group to SE configs that have magnets on the details page.
  - [ ] ExtraTorrents (magnets only in details)
  - [ ] 1337x (magnets only in details)
  - [ ] TPB (supports magnets)
  - [ ] IsoHunt (supports magnets)
  - [ ] Zooqle (supports magnets)
  - [ ] nyaa (no magnets)
  - [ ] ShowRSS (non generic SE, supports magnets)
  - [ ] RarBG (non generic SE, supports magnets)
- [ ] add parseDetails to GenericTorrentSearchEngine
- [ ] alter torrentDialog template to handle new SE configs
- [ ] alter torrentDialog directive to get details page when needed
- [ ] alter auto-download to use details page when needed
