### ISSUE TITLE
Issue with Transmission and DuckieTV

### ISSUE THREAD

**Issue by RandmTask** [SchizoDuckie/DuckieTV#746]
DuckieTV and Transmission were working fine until a couple weeks ago, now DuckieTV cannot connect to the Transmission app

It just keeps saying "Connecting". The settings of the transmission and duckietv apps have not been changed

I updated to the latest version of DuckieTV (DuckieTV-08022016-OSX-x64) and Transmission but that has not helped.

Checked the log but not sure how to attach it here

Any suggestions?

System is Mac Mini running El Capitan

**Comment by garfield69** [comment]
I am going to need a look at the log, whether its from the DuckieTV console or the transmission message log, to have any change of diagnosing what might be going on.    
 
To take a screenshot in Mac OS X, you can press Command + Shift + 4 and drag a box around the screen portion you wish to capture, or press Command + Shift + 3 to capture an image of your entire screen.    

You can then paste the pic directly into the ticket.     

Or you could just use the mouse to select the console log text and copy and paste that text into the ticket.     
Whatever works best for you.

**Comment by RandmTask** [comment]
Thanks, here is a screenshot of the log:

![image](https://cloud.githubusercontent.com/assets/7912017/17551879/aaceccec-5f0d-11e6-80fb-0f4f90f072c6.png)

If I search for a torrent manually in DuckieTV eg in isohunt it works and I can open a magnet link in Transmission, but otherwise it cannot connect to Transmission

**Comment by garfield69** [comment]
The snapshot of the log you have provided does not show me any DuckieTV activity with Transmission.   

There should be a *Transmission connected!* message if DuckieTV has connected with Transmission, or some kind of regular error message at least every 15 seconds if DuckieTV cannot connect to Transmission.    

If DuckieTV has connected to Transmission, then on the main DuckieTV page, the *Transmission icon* in the left hand side should show a green dot, and the tooltip should read *torrent client transmission: connected*.     

Also on the *Transmission integration* panel you should see something like *Status: Connected to Transmission API @ http://localhost:9091* as shown below:
![](http://i.imgur.com/Z9qv575.png)

Can you confirm that you are seeing any of the above?     
And if you are seeing any Transmission error messages, a snapshot of the log with that message may be useful.     

>If I search for a torrent manually in DuckieTV eg in isohunt it works and I can open a magnet link in Transmission, but otherwise it cannot connect to Transmission

OK. I am missing a piece of the puzzle here. Are you really talking about a communication to Transmission problem (that is, DuckieTV unable to establish a two way conversation with the Transmission host), or are you talking about the Auto-Download service, and the fact that for a couple of weeks you are not seeing the auto-download pass any magnets on to Transmission for downloading?     

Because it appears from what you just said above, that DuckieTV is in fact *connected* to Transmission, as that the problem is that while you can send magnets from a manual search using the IsoHunt search engine, the Auto-Download service is not working?

**Comment by RandmTask** [comment]
Hi

Sorry if I was not clear. In DuckieTV it is not connecting to Transmission *and* the auto-download is not working. It does however pass the magnet links for a manual search to Transmission if that makes sense?

I havent seen any error messages in Transmission 

Here is a picture of it saying Transmission connecting:
![image](https://cloud.githubusercontent.com/assets/7912017/17585542/7d17e2fa-5fcd-11e6-946e-a3d7a4318b97.png)

And my Transmission settings in DuckieTV (pressing test and save seems to have no effect):
![image](https://cloud.githubusercontent.com/assets/7912017/17585543/81807e60-5fcd-11e6-82cb-7a01ceb84675.png)

Thanks for your help!

**Comment by garfield69** [comment]
OK. That makes more sense. If DuckieTV is not connecting to Transmission, then the auto-download will not be activated, since it only starts up if there is an active connection to Transmission.    

And manual searches can pass torrents to Transmission, since there is a escape clause that allows for a torrent to be passed via the chromium interface (which is basically like you double clicking on a torrent file in a folder and having the OS pass it to transmission). But this escape clause is not used in the auto-download because torrents passed this way don't return the torrent hash, which the auto-download needs to keep track of the torrent progress and completion.         

But the big news for me is that picture of the *Transmission Integration* panel. I think I have spotted your problem. For some reason, your **Base Path** is set to *false*. This should be */transmission/rpc*.     
Change it and see if that makes a difference.

**Comment by RandmTask** [comment]
Unfortunately that didnt help

Pressing test and save seems to have no effect and when I go out and back into Transmission Integration it is back to False

![image](https://cloud.githubusercontent.com/assets/7912017/17593779/10975f2c-5ff8-11e6-97ec-9fcae80132be.png)

**Comment by garfield69** [comment]
I see that in the latest picture of the integration page you used a *Base Path* of */transmission/rpc/* . That will not work. It needs to be `/transmission/rpc`.     Please try again.     

Also note that when the *test and save* fails to establish a connection to Transmission, it resets the fields back to what they were before the attempt. Hence the Base Path going back to false.    

If you cannot get that to work, then I have another method of setting that field that we can try. :-)

**Comment by RandmTask** [comment]
Hi,

No that didnt work either!Please let me know how to set the field and we can try that :)

**Comment by garfield69** [comment]
OK.     
So what we are going to do is edit the user preferences directly, so proceed with caution carefully.    

Start DuckieTV and press the **F12** key to access the *development tools* panel, and click on the **Resources** tab.    
Next, click on the arrow to the left of the **Local Storage** entry, and then click on the **file://** entry just below it.    
This should bring up a table of **key** and **value**.     

This next bit is best done in combination with a plain-text editor.    
Scroll down to the **userPreferences** key, and double click on the corresponding value field to open it for editing.    The whole field should be already selected. So use the mac *Command-C* to copy the contents and *Command-V* to paste it into your open plain-text editor.    
look for the parameter ` "transmission.path": false,` and change it to `"transmission.path": "/transmission/rpc",`     
Copy and paste the whole edited userPreference string from your plain-text editor back into the field you found it in on DuckieTV's table, and press enter to save it.     

If you've done it correctly then the next time you go to the *Transmission Integration* you should see that the *Base Path* is now loaded with `/transmission/rpc` so press the **test and save** and see what happens.    
If it does not connect, look in the DuckieTV log for an error message.      
Good luck, let me know how you fare.

**Comment by RandmTask** [comment]
Awesome! 

Thanks that fixed it!

Cheers for taking the time to problem solve :)
