### ISSUE TITLE
Nightly; any chance of adding

### ISSUE THREAD

**Issue by no1adamg** [SchizoDuckie/DuckieTV#754]
http://www.btstorrent.cc

your doing great work
Thanks

**Comment by garfield69** [comment]
Unfortunately the BTStorrent.cc site is not currently compatible with DuckieTV's search engine.    
I coded an SE profile easily enough, but during testing I discovered that all the magnet links that the site serves are delivered with an info-hash in base32.    
Why is this a problem?    
Because while most torrent hosts accept these magnets, they automatically convert the info-hash into the more common base16 equivalent.    
Which means that DuckieTV cannot identify the torrent once it has been delivered to the torrent host, and so cannot track it's progress or completion.    
This effectively defeats the auto-stop, mark-as-downloaded, and torrentClient progress graphics features.    
So until a solution is found for this, this SE is not suitable for general use. :-(

**Comment by no1adamg** [comment]
ok m8 thanks for taking a look

**Comment by SchizoDuckie** [comment]
Is this still an in-progress thing?

**Comment by SchizoDuckie** [comment]
site died. closing issue.
