### ISSUE TITLE
TorrentDownloads SE

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#755]
Can you add torrent downloads (https://torrentdownloads.unblocked.live) as another search engine.

Thanks

**Comment by garfield69** [comment]
Now that we have got the magnet-from-details-page working, we can now add torrentdownloads.me, as this is a popular official site.    
torrentdownloads.unblocked.live is just a proxy of the official site.    
If you cannot reach torrentdownloads.me in your region, then you will have to either:    
- wait until the CustomSearchEngines feature is finished so you can override the primary path     
or    
- use the source development version of DuckieTV and edit the TorrentDownloads.js SE code directly.    

Side note: this is probably the last public SE will will accept until the CustomSearchEngine code is finished, because we have now nearly filled up the row of SE in the torrentDialog. (There is room for maybe one more, depending on how long its name is).     
Once the CSE is finished, users will be able to add/remove SE as they please.
