### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#761]
Can you get DuckieTV to check back and download previous episodes, that haven’t been downloaded yet.

Can you also stop DuckieTV from downloading new seasons if the previous hasn’t been watched yet.

Thanks

**Comment by garfield69** [comment]
>Can you also stop DuckieTV from downloading new seasons if the previous hasn’t been watched yet.    

I don't think this is a good idea.  The auto-download works best when the torrents are fresh and popular. As the torrents age the seed numbers drop, and it gets harder to meet the seed quota.  You end up with the auto-download service processing a huge list of torrents every 15 minutes, and none of them can be downloaded automatically because they are no longer current.    
I think most users would want to fetch the torrents while they are hot.     

>Can you get DuckieTV to check back and download previous episodes, that haven’t been downloaded yet.    

Similar issue with this. We set the auto-download period to a max of 21 days to keep the number of torrents processed down to a manageable level.     
And the user can use the auto-download-all-episodes in a season list, or even the auto-download-a-season buttons to go looking for torrents, if they need to for a just added show that has lots of old seasons.    
But to automatically do this for every show is a lot of processing for little gain, as previous episodes are more likely going to have fewer seeds, like in the first request above.     

So that is what I think, do the other DuckieTV team members have an opinion?

**Comment by zero77** [comment]
Could you add an exception for the tv shows that didn’t have torrents available when they first came out, in this case DuckieTV would continue to look for available torrents.

**Comment by SchizoDuckie** [comment]
Closing issue.

If you want to download something missed that's not covered by the autodownload days and min-seeders settings, grab them from the series overview by hand.

Keeping track of this, and configuring options for this is imo too complicated a task for an edge case usecase.
