### ISSUE TITLE
Duplicated instances in status bar (OSX)

### ISSUE THREAD

**Issue by rmvz3** [SchizoDuckie/DuckieTV#767]
I have DuckieTV added to my startup items. Many times DuckieTV creates another instance of itself in status bar and I need to close and restart it. Also, if I enable "Minimize button minimizes Duckie TV to tray" it creates another copy too when minimized.

**Comment by garfield69** [comment]
Are you using the *Mac DuckieTV standalone* version **1.1.3** ?     
Duplicate Mac systray icons should have been fixed by https://github.com/SchizoDuckie/DuckieTV/issues/701, and will be included in the next release of DuckieTV 1.1.4, whenever that happens. I don't have a release date for you sorry.      

If you do not want to wait, then I recommend installing the latest development nightly from https://github.com/DuckieTV/Nightlies/releases as it contains many bug fixes and improvements.     

If the latest nightly does not fix this problem for you, then please let us know so we can look into this further. Thanks.

**Comment by rmvz3** [comment]
Thank you for answering garfield69.

In fact I was using mac standalone 1.1.3. However Nightly build works like a charm. Thank you for your work. It rocks!
