### ISSUE TITLE
Cannot connect DuckieTV and Vuze

### ISSUE THREAD

**Issue by forumguy** [SchizoDuckie/DuckieTV#771]
I am using a VPN client with Vuze bound to local IP (utun1). I am also trying to integrate DuckieTV and Vuze; however, the integration is not working and I cannot solve the issue.
Here are the details of my configuration:
* I tested the web remote with my browser and it works on: http://10.22.0.6:9091/
* I completed the Vuze integration setup using http://10.22.0.6:9091 along with a user/password however; DuckieTV is not connecting to Vuze even after restarting both applications, retrying the connection and the integration setup.

Any assistance would be appreciated.

**Comment by garfield69** [comment]
Please navigate to the DuckieTV *About* side panel by clicking on the **{i)** icon on the left bottom of the main DuckieTV page, and scroll down to the start of the *Statistics* section.    
Assuming you are on the windows platform, then take as many screen captures using the *Print Screen* key as it takes to capture all of the stats and *Paste* them here in an open box below using *Ctrl v*    Thanks.

**Comment by forumguy** [comment]
Apollogies, forgot to mention, it's a Mac. 

Sent from my Mobile device.  
 
  On Sat, Sep 24, 2016 at 2:32 PM, garfield69<notifications@github.com> wrote:   
Please navigate to the DuckieTV About side panel by clicking on the {i) icon on the left bottom of the main DuckieTV page, and scroll down to the start of the Statistics section.

Assuming you are on the windows platform, then take as many screen captures using the Print Screen key as it takes to capture all of the stats and Paste them here in an open box below using Ctrl v Thanks.

**Comment by garfield69** [comment]
Ah, then, press the Apple key ⌘ + Shift + 3 all at the same time to screen capture, and Apple key ⌘ + V for paste :-)

**Comment by forumguy** [comment]
As requested, let me know if you need anything else:

![statistics 1](https://cloud.githubusercontent.com/assets/22416260/18811227/c8c8b8d8-8277-11e6-9767-887bd30958c2.jpg)
![statistics 2](https://cloud.githubusercontent.com/assets/22416260/18811230/cdb7c604-8277-11e6-8838-402dad7e3782.jpg)
![statistics 3](https://cloud.githubusercontent.com/assets/22416260/18811233/d6fcf66c-8277-11e6-9896-d3e2833df3d2.jpg)

**Comment by garfield69** [comment]
I see you are using the May 17th release of the nightly.    
Since that release there have been some fixes to the client integration code that may be helpful in your case, so I would recommend upgrading to the latest nightly at https://github.com/DuckieTV/Nightlies/releases/tag/nightly-09242016.     

Also, try the following once you have upgraded:     
Start up DuckieTV and press the **F12** key to open the *Development tools* page and click on the **console** tab to view the log. Click on the **preserve Log** check box so that the log is not lost after a soft reset.      
View the DuckieTV *Settings, Vuze Integration* side panel, re-enter the address *http://10.22.0.6*, and the username and password that you configured in the *Web Remote Plugin* on the *Vuze Host* and press the *Test and Save*.     
If it does not connect, view the log and look for any error messages related to Vuze.    
Let me know what you find.

**Comment by forumguy** [comment]
I loaded and configured the 20160923 release of DuckieTV and now the Vuze integration works.

Thanks for the assistance.
