### ISSUE TITLE
1.1.3 apk unable to be downloaded

### ISSUE THREAD

**Issue by macst34** [SchizoDuckie/DuckieTV#772]
For some reason, I can't download the 1.1.3 apk from github.

**Comment by garfield69** [comment]
If you are talking about https://github.com/SchizoDuckie/DuckieTV/releases/download/1.1.3/DuckieTV-1.1.3-Android.apk then the problem is local to you, as I had no problem downloading it just now.

**Comment by garfield69** [comment]
@SchizoDuckie Found a second DuckieTV android user (on Reddit) that is having problems installing a nightly... 
https://www.reddit.com/r/duckietv/comments/55jnjk/couple_of_queries/

>knowair     
>Tried to use the android version (latest nightly) and doesn't seem to work... Is it an active version? Does it need a rooted device?

can you verify? I don't have an android.

**Comment by knowair** [comment]
Thanks for this, 

Just to confirm, I can download and install it, but i cannot connect to anything from it, which is why i wondered if it needed a rooted phone?

ie.
cannot connect to trakt (the pop-up page to get auth-code does not appear), 
cannot manually add shows to the calendar either just get the [ :( ] (Also no show pictures load on this page)
won't connect to a client either, I'm using Justseed.it so the connection is just https on port 443 

Also search via any of the sites instantly does not produce any results (just says no results found), 

using android 6.0.1 btw

**Comment by Bennieboj** [comment]
Make seperate issues for the problems you encountered, this issue should be closed.

**Comment by macst34** [comment]
I was able to download and install. Previous issue was probably network related. Consider this issue closed for me

**Comment by knowair** [comment]
I can open a new issue if you prefer..... i only followed garfield's lead updating this ticket.

Does it need a rooted phone?

**Comment by SchizoDuckie** [comment]
It does not need a rooted phone, it should work by default with phonegap.
Something may have been broken though, I haven't had the time to check the phonegap build.

**Comment by knowair** [comment]
Thank you, You want me to put the query in a separate issue?

**Comment by SchizoDuckie** [comment]
Yes please!  Thanks

Op 15 nov. 2016 3:26 p.m. schreef "knowair" <notifications@github.com>:

**Comment by knowair** [comment]
Done
