### ISSUE TITLE
Letter is being dropped of a series name when it has a ‘ eg. fiancé

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#777]
When duckie searches for the series 90 day fiancé it is dropping the "é" and hence not finding any results.

Screenshot attached.

![screen shot 2016-10-05 at 1 07 32 pm](https://cloud.githubusercontent.com/assets/13501166/19125024/dc53e41c-8b0b-11e6-9c23-dc1c88e1c29b.png)

**Comment by garfield69** [comment]
It's an oversight (bug?) in the sceneNameResolver. It intends to strip special characters (such as !@#$%&* among others) from the series names, since most torrent names don't use them. But this means it also drops letters with accents.    
I'll amend the code to replace them with their normal equivalents, since most torrent names don't use accented letters either.
