### ISSUE TITLE
writing to db stuck

### ISSUE THREAD

**Issue by gillthunder** [SchizoDuckie/DuckieTV#782]
i accidentally closed duckietv while it was writing to db and when i relaunched the program it was stuck at 1/20 and i can't use the program at all
here is a picture of how it looks like: http://prntscr.com/ctosll

**Comment by garfield69** [comment]
Start up DuckieTV and then press the **F12** key to open the *Development Tools* page.     
Then click on the **Console** tab to view the log.     
Look for an error messages, ignoring any from trakt.tv similar to `Failed to load resource: the server responded with a status of 403 (Forbidden)https://walter.trakt.us/images/shows/000/001/394/posters/thumb/3b6113aed4.jpg`.

**Comment by gillthunder** [comment]
i found 2 errors in the Development Tools page.
here is a picture of it: http://prntscr.com/ctxess

**Comment by garfield69** [comment]
Darn, that does not look good, looks like a record has been corrupted and is preventing DuckieTV from continuing with the database updates. The way I see it you have two choices:    
- (1) you can delete the working directory and start over with a fresh clean database.    
  the DuckieTV app data folder is located on most windows systems in a folder similar to `C:\Users\<username>\AppData\Local`. Shut down DuckieTV, delete the folder called `duckietv-standalone` and start DuckieTV up again. If you cannot see the folder, you may need to go to the *Start, Control Panel, Folder Options*, click on the *view* tab, and click on the *show hidden files, folders and drives* radio button.    
**OR**
- (2) navigate to the `C:\Users\<username>\AppData\Local\duckietv-standalone\databases\file__0` folder and upload the file called **1** to a cloud service such as DropBox for instance, post the share link here, and I can take a look at it with my development tools and see if I can repair it for you.     

In either case, I can also recommend you upgrade to the latest version of DuckieTV. Since version 1.1.2 came out there have been many fixes applied, and even though I don't have a release date for version 1.1.4 yet, I think it is worth while for you to upgrade to the latest development nightly, which is essentially version 1.1.4 WIP (Work in Progress :-)    
You can find the latest nightly at https://github.com/DuckieTV/Nightlies/releases, and a guide to installing nightly at https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-Windows-DuckieTV-Standalone-NIGHTLY     

But before upgrading you need to sort out your 1.1.2 database, so choose option 1 or 2 and let me know what you decide.

**Comment by gillthunder** [comment]
I decided to start over with a clean database i'll download the new version and thank you for the great help.

**Comment by gillthunder** [comment]
http://prntscr.com/cv7u3q it happened again.

**Comment by garfield69** [comment]
> it happened again     

wait, what :-( ?    
I thought you were going to upgrade from 1.1.2 to the latest nightly, did that not happen?     
Or has the problem happen while you were on the latest version?     

>so i created a backup database     

you mean you used the DuckieTV *Settings, Backup, Create a Database Backup* ?      
And the backup was made before the problem happened, right?     

>and wiped clean     

What did you use to wipe the db clean?     

>and now i'm using that backup database that should be okay right?     

Should be alright, try it and see.

**Comment by gillthunder** [comment]
yea the problem happened before i get a chance to upgrade and i did use the the DuckieTV settings, Backup, Create a Database Backup to create a backup before i solve the problem and i used the DuckieTV settings, Backup, Wipe Datebase and Settings to wipe the db and i upgraded now and the latest version got a bunch of nice features and it's working just fine
