### ISSUE TITLE
Feature request - Browser button to add series to duckie TV

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#784]
Is there a way we could get a browser add on/button to allow to directly send a show to duckie?
E.g. I am watching a trailer on imdb or any other services that handles a show ID like the TVDB and can send that show to be added to my duckie calendar without having to actually go to the app and manually searching for it.

I had the idea while browsing trailers for upcoming shows, since I also use couchpotato and use their browser button to do exactly what I suggest but for movies I thought it might be possible for Duckie as well.

**Comment by SchizoDuckie** [comment]
I think it's a nice idea, but it will pose some technical challenges since communication between different chrome extensions is not really possible.

It would need to be a separate extension that sends a signal to duckietv somehow, requiring either an API or some form of inter-process communication. 

A probably better option for you would be something like https://chrome.google.com/webstore/detail/trakttv-everywhere/haogccejmloicihdocopcddefdcphfei that can DuckieTV can pick up in the future when the 2-way trakt sync is finished.

Closing this as wontfix for now, sorry.

**Comment by lonelyfairie** [comment]
Ok, I stopped using trakt after I started using duckie, since there was no two way synch it didn't make sense using both after the initial import of shows. I will look into that extension once the two way sync is fixed, since adding shows specially on mac where no Copy Paste works on nwjs is kinda of a pain.

**Comment by SchizoDuckie** [comment]
The copy/paste issues should also be solved with the next standalone as i'm upgrading to the latest and greatest nwjs.io :+1: Hold on tight!
