### ISSUE TITLE
Unable to link TraktTV to DuckieTV online - "Error! undefined - undefined"

### ISSUE THREAD

**Issue by warthog3** [SchizoDuckie/DuckieTV#790]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
DuckieTV Online - http://duckietv.github.io/DuckieTV/

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
v20161101

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac - Google Chrome

**Describe the problem you are having and steps to reproduce if available**
Trying to connect account. Click 'Yes' on Trakt website asking if I want to connect DuckieTV. Copy the PIN and get the following error in TraktTV online:

"Error! undefined - undefined"

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
The DuckieTV online DEMO is just a demonstration model.     
Not all the features are available, because the DEMO has to go through a proxy for security, and the proxy can prevent certain features from working.    
If you intend to actually *use* DuckieTV to track your TV shows, then we recommend using the published version at https://github.com/SchizoDuckie/DuckieTV/releases, *or better yet*, if you want the latest features, then a Development Nightly which you can find at https://github.com/DuckieTV/Nightlies/releases.
