### ISSUE TITLE
Having '24' in shows lists results in adding 'Presido med' when using 'refresh favorites' from settings/backup

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#794]
Just came across this while testing the new Fanart system:

- Settings -> Backup/Restore
- Refresh database
- Observe 'Presido Med' is added
- Open search list
- Add '24'
- Observe 'Presido Med' is added

**Attach any DuckieTV statistics or Developer Console logs if available**

![image](https://cloud.githubusercontent.com/assets/111710/20248816/12d9cdd6-a9ec-11e6-8ffa-78d72af4812d.png)

by the way, kudo's on the issue templates, that's awesome!

**Comment by Js41637** [comment]
Yeah they're really good for people who submit issues and Garfield always
asks them the same questions so we know what were dealing with with

**Comment by garfield69** [comment]
Using the latest *development source*, I have followed the steps you have detailed but **cannot duplicate** your findings. :-(    
However, since I *did not* have *Presidio Med* previously, my tests may well not be performed under the same conditions.    
I added *Presidio Med*, then did a *refresh all series now*, the added *24* without problems.     
I also had no problems removing *24*, doing a *Backup*, an *Import with Wipe*, a *refresh all series now*, and then added *24* again.     

*24* and *Presidio Med* in favourites afterwards
![image](https://cloud.githubusercontent.com/assets/6933240/20254963/bce383ce-aa9d-11e6-8af9-9863e96353e3.png)    
*24* details
![image](https://cloud.githubusercontent.com/assets/6933240/20254992/f39c3898-aa9d-11e6-87e2-4de6b434a40b.png)     
*Presidio Med* details
![image](https://cloud.githubusercontent.com/assets/6933240/20255009/1a153380-aa9e-11e6-87fc-450640cbbec3.png)     

I think your issue may stem from a prior development-change incident that caused your *Presidio Med* to be duplicated in the database?    
I suspect that if you were to do a *Backup* followed by an *Import with Wipe*, you would find that you could subsequently remove and add either *24* and/or *Presidio Med* with *refresh all now* in between, all without incident. :-)

**Comment by SchizoDuckie** [comment]
I do know for sure that i have had 24 in my database before and removed
presido med from my database after fixing the bug related to that.

I'll do a backup / restore just to make sure

Op 14 nov. 2016 7:42 a.m. schreef "garfield69" <notifications@github.com>:

**Comment by SchizoDuckie** [comment]
unable to replicate.. I dunno where they came from then.
