### ISSUE TITLE
Zero functionality with Android version

### ISSUE THREAD

**Issue by knowair** [SchizoDuckie/DuckieTV#797]
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
nightly-20161114 - (have tried previous releases too)

**What is your Operating System (Windows, Mac, Linux, Android)**
Android 6.0.1

**Describe the problem you are having and steps to reproduce if available**
Cannot connect to trakt (the pop-up web page to get the trakt auth-code does not appear), 

Cannot manually add shows to the calendar either, just get the :( 

Search via any of the sites does not produce any results (just says no results found),

Cannot connect to a torrent client - I'm using JustSeed.it via the Transmission client connection. It's just just https on port 443 - This works brilliantly with Win10 Standalone and Browser Action

**Attach any DuckieTV statistics or Developer Console logs if available**
Sorry don't have these just yet, if you need them tell me how for android!

**Comment by SchizoDuckie** [comment]
Confirmed.

I've checked to see if i could debug it on my phone but unfortunately i'm not getting any connection to the outside world. Probably something phonegap related. I will take a deeper look at this before het next release.

**Comment by zero77** [comment]
The same issue occurs for android 5.x

**Comment by SchizoDuckie** [comment]
Just tested the latest android release after patching the buildbot that failed to find a crucial file, it works again \o/

Please try the latest nightly: https://github.com/DuckieTV/Nightlies/releases/tag/nightly-01122017

I've also enabled phonegap build hydration so that you don't have to download apk's over and over, but just update from the app. It may take a while on first run, but workedforme.

**Comment by zero77** [comment]
wow, That's excellent thanks
