### ISSUE TITLE
DuckieTv not adding series in favorites on webserver

### ISSUE THREAD

**Issue by harix786** [SchizoDuckie/DuckieTV#806]
**What build of DuckieTV are you using (DuckieTV-Standalone))**
...

**What version of DuckieTV are you using (DuckieTV-Standalone v1.1.4)**
...

**What is your Operating System (Windows)**
...

**I have a problem with DuckieTv, it is not adding series in favorites and search engines not working properly on the web hosting but when i set it up on localhost in my computer all works great i dont know where is the problem i also checked some files and edited them but nothing works please help me**
...

**Comment by SchizoDuckie** [comment]
Due to CORS restrictions DuckieTV cannot work on a webserver (without modifications like a CORS Javascript proxy). Even then that would not help you much because the database you work with is not shared between computers. It's a WebSQL database that only runs on your local machine.

**Comment by harix786** [comment]
but how did you setup it on github.io ? i also tried to host it on github.io
but same problem occurred there.

**Comment by harix786** [comment]
can i setup it on my github.io profile ? can u guid me to setup on github.io
?

**Comment by SchizoDuckie** [comment]
There's a PHP CORS proxy running on a third party domain that's whitelisted from within the duckietv code. On top of that there are some restrictions that prevent you from using the torrent clients from there. (since I don't want to proxy any requests that have credentials on them)

Sorry, I'm not going to provide any support on that because there could be other unforeseen things that will not work and require more support.
