### ISSUE TITLE
KickAss is Back! Can't add...

### ISSUE THREAD

**Issue by Jayshua83** [SchizoDuckie/DuckieTV#810]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...  CHROME

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
...   1.1.3 ??

**What is your Operating System (Windows, Mac, Linux, Android)**
...  Windows 10

**Describe the problem you are having and steps to reproduce if available**
...  Can't Add KAT's new site. https://katcr.co/new/

**Comment by garfield69** [comment]
This is because the new site is KAT in *name* only; behind the scenes, the presentation html is not the same as the original site, so DuckieTV 1.1.3 cannot process it.     

At this stage you ave two choices:     
1. You can wait for *DuckieTV 1.1.4* to be released, which will have the updated support for the new KAT. However, I don't have a release date for you at this time, sorry.     
2. OR you can grab the latest *DuckieTV Nightly*. This is Development DuckieTV, essentially 1.1.4 Work in Progress. It has a working version of the new KAT Search Engine.     
However, unlike DuckieTV Standalone, the Nightly Chrome Extension package is not as straight forward to install, so you may first want to read this Nightly Installation Wiki https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-DuckieTV-Chrome-Browser-Extension-NIGHTLY before proceeding.    
If you decide to go ahead, then you can find the latest Nightly download at https://github.com/DuckieTV/Nightlies/releases/tag/nightly-01052017
