### ISSUE TITLE
Unable to fully load backup

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#817]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**

apply contain to sidepanel serie poster #809
commit 049c8c474ad159714f9d9d32d0be2e0756e36cf1 
@garfield69 garfield69 committed 3 days ago

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac OS Sierra
**Describe the problem you are having and steps to reproduce if available**
I had to install another version of NWJS since the old one kept saying it closes unexpectedly every time I tried to open duckie, I installed NWJS v12 as well as v14 (several builds, currently using v0.14.7) with 12 I was not able to load duckie at all, I got a grey window saying NWJS but no duckie, when I installed 14 I was able to open duckie and import one of my backups, it takes a really long time saying it is loading the back up and when it is finally done I can see the settings where imported (it can connect with uTorrent UI using a personal username and password) but no series show up. Calendar is empty and trying to go to my favorite shows it shows empty and says Loading on top but nothing happens for hours.

I have tried several back ups without wiping, I have tried manually wiping and loading, I have let duckie wipe before loading the back up, still get the same result.

I downloaded DuckieTV-1.1.3-OSX-ia32.pkg installed it and loaded a back up succesfully so I don't think it has to do with the back up being corrupted. I make weekly back ups so I have saved:
DuckieTV Dec 7, 2016.backup
DuckieTV Dec 15, 2016.backup
DuckieTV Dec 23, 2016.backup
DuckieTV Dec 31, 2016.backup
DuckieTV Nov 14, 2016.backup
DuckieTV Nov 21, 2016.backup
DuckieTV Nov 29, 2016.backup

**Attach any DuckieTV statistics or Developer Console logs if available**
I can't seem to find any duckietv logs (if you can tell me where they should be or how to enable logs on dev mode I will gladly provide them)
I did enable the Error tracking option available and did a Wipe, load back up again, here is my unique tracking id: 3b447508-9cb9-2324-5885-0c0da3a44ca0

Attaching screenshots and backups.
![screen shot 2017-01-12 at 9 30 40 am](https://cloud.githubusercontent.com/assets/13501166/21894785/3259d9ec-d8bf-11e6-8e7b-0c84d1329a39.png)
![screen shot 2017-01-12 at 9 32 04 am](https://cloud.githubusercontent.com/assets/13501166/21894786/325d68c8-d8bf-11e6-88e3-6b2560299ce4.png)

[DuckieTV Backups.zip](https://github.com/SchizoDuckie/DuckieTV/files/702031/DuckieTV.Backups.zip)

**Comment by Js41637** [comment]
There does seem to be an issue loading backups from December, the stuff i'm getting is inconsistent, sometimes it adds, it loaded for like 20 seconds then started adding them, other time it worked fine, not sure what the problem is, there is no errors or exceptions.

**Comment by lonelyfairie** [comment]
@Js41637 At the time of my posting (2hs ago) I set duckie to load my earliest backup available which is from November... it is still going so it does not seem to be December specific at least not for me. 
Could be due to the huge amount of shows it has to add?
I remember I posted a feature request some time ago asking for the ability to select multiple shows to be removed from the favorites (clean up of cancelled/finished/abandoned shows) as when my shows imported from trakt.tv it effectively imported every series I ever watched. I did disable the ratings update as to speed the series refresh at the time since no such feature is still available.

Is there a way to "edit" the backup db? Specifically remove shows manually from the back up without compromising its integrity?

**Comment by garfield69** [comment]
@lonelyfairie  I have loaded your December 31 backup on my windows sandbox without problems, so I do not have any concerns about the integrity of your backups.     

You cannot use nwjs 0.12.3 in combination with the latest GitHub DuckieTV source, since they are no longer compatible, the minimum nwjs version is 0.13.x.     

Unless you are using Mac OS X 10.6 or older, I would not recommend using nwjs LTS 0.14.x    
If at all possible, use the latest stable nwjs available for mac, 0.19.5 at the last check. Also, make sure you download the **SDK** version, which contains the *Development Tools* suite, so you can browse the log, which is not included in the *Normal* downloads.      

To view the log, you would usually press the **F12** key to open the *Development Tools* page, and click on the *Console* tab to bring up the log. On the Mac, **Control-Command-i** (⌘+⌥+i) may work if* F12* does not.     

During my sandbox trials, I import regularly. I find that my old computer cannot keep up with the graphics presentation. I can speed up the import by at least x10 by using this trick:     
The moment I've started the import, I click on the calendar icon (1), then the month header (2), and leave the page in the select a month to view. In this mode, imports are over in a couple of minutes).

![image](https://cloud.githubusercontent.com/assets/6933240/21902233/ff2eee30-d95f-11e6-8527-8b5b436fec5c.png)
![image](https://cloud.githubusercontent.com/assets/6933240/21902274/245cb2b4-d960-11e6-8394-23c6ac766151.png)
![image](https://cloud.githubusercontent.com/assets/6933240/21902303/485762d6-d960-11e6-8435-4bb7cbdae186.png)

Also, to be sure that previous failed tests have not left anything behind that might interfere with an import, I also delete the complete DuckieTV local storage area, so I can start from scratch.
On a mac you should find a folder in `~/Library/Application Support/` by the name of `DuckieTV-Standalone`. delete this folder, to ensure a fresh start.

**Comment by lonelyfairie** [comment]
@garfield69  you are the man! I used your trick and went into month select view right after I started loading the back up and it took less than 5 minutes to import. I also noticed that doing it this way instead of leaving the settings panel open while doing the back up showed that duckie was writing to the DB so it was easy to determine wether progress was being made or not.
I am currently downloading nwjs sdk v0.19.5 as per your suggestion so if I have any more issues I should be able to pull up logs. 
I would also suggest this be included in the wiki, I was under the impression that duckie was specifically be used with the listed 12.3 version and from seeing the commit titles noticed you released a version that "added support for nwjs v14", so again I was under the impression that v14 was the only option supported not higher versions. 
As always thanks for the amazing support, you guys rock! 🎉

**Comment by garfield69** [comment]
@lonelyfairie  Thanks for the reminder about the wiki. I'll go update this shortly.

**Comment by lonelyfairie** [comment]
mmm so I updated to nwjs-sdk-v0.19.5-osx-x64 and after copying all contents to the duckie tv dev folder as usual when I try to open I only get a grey window saying NW.JS, see screenshot attached.
Any pointers?
![screen shot 2017-01-13 at 5 47 30 pm](https://cloud.githubusercontent.com/assets/13501166/21945221/d3d2bb1e-d9b8-11e6-8e6b-932043d55c2f.png)
