### ISSUE TITLE
series covers not working 

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#822]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
 Standlone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
Nightly 2017-01-12

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows

**Describe the problem you are having and steps to reproduce if available**

Some TV series cover artwork is not displayed it just shows up black with the name underneath also, the artwork displayed behind the calendar is out of date.

**Comment by garfield69** [comment]
The next windows nightly that gets built will include fix ea66de2a223fce5e8b55a48fbfc2615811050678 . When it becomes available, please check to see if this fixes your problem.     
If it does not, then provide a screenshot of an example of your problem so we can take a closer look.

**Comment by zero77** [comment]
Thanks, whenever the next Windows update is out I will try that.

**Comment by zero77** [comment]
I have just updated to the newest version (05-02-2017) but the same problem is still accruing and I keep get ting this error.

Unless I am mistaken, I think duckietv keeps trying to resolve the wrong domain when trying to get the tv show covers, it is resolving trakt.us when it should be trakt.tv, this may be the same for the art work behind the calendar as well. 


![Uploading Capture.JPG…]()

**Comment by garfield69** [comment]
>So it may be worth using trakt TV for artwork as well also, fanart.tv supports https.    

The whole point of switching to FanArt for artwork was because Trakt.TV *stopped providing* pictures through their API.     
Also, thanks for spotting the missing https prefix, I've updated this now.     

>Unless I am mistaken, I think duckietv keeps trying to resolve the wrong domain when trying to get the tv show covers, it is resolving trakt.us when it should be trakt.tv.     

No, The walter.trakt.us were the old Trakt.TV images links that are now no longer available.    
The log was useful.     
It shows that the migration (from Trakt.TV images links to FanArt links) that was kicked off when you upgrade to Nightly 2017-01-12 was interrupted, for what ever reason. Some of your old Trakt.TV  picture links were not replaced with FanArt ones, or set to *null* when their equivalent were not found.     

The new Nightly can now refresh the FanArt image links. Several ways this can happen:    
1. You can let DuckieTV update the image links on its own over time, as during the regular daily Trakt.TV data update cycle, we now also include a FanArt update. This was missing in the earlier Nightly.     
2. Or for older series whose data does not change frequently on Trakt.TV, you can force an update by  manually refreshing DuckieTV by using that series' Refresh button on the series' *Details* side panel.      
3. OR if you want,  you can also do a *Bulk* refresh by visiting the DuckieTV *Settings, Backup* side panel, and using the *Refresh all Series Now* button.     
4. In the unlikely event that the bulk refresh did not do the job, the final method guarantied to blow away the old Trakt.TV image links is to do a *Settings, Backup, Create a Database Backup* followed by a *Settings, Backup, Import a Backup* with the *wipe before Import* check box ticked. But I don't think you need to resort to this method ;-)

**Comment by zero77** [comment]
Most of the covers are working now although, a few still are not working, but this time I am getting a different errors though, I am not sure if they are related.

![capture](https://cloud.githubusercontent.com/assets/16563034/22855290/bf07a626-f075-11e6-8a60-8e077e171adc.JPG)

**Comment by garfield69** [comment]
the ERR_CONNECTION_REFUSED for the `http://localhost` messages are a result of DuckieTV trying to contact your uTorrent Host which is not currently running.    If you are not planning to connect to any host then visit the *Settings, Torrent* side panel and click on the *Disable all torrent functionality*.    
There is nothing in the segment of log you provided that indicates any problem with covers.

**Comment by zero77** [comment]
Ok thanks, I wasn’t sure if they were relevant I will have a look to see if I can find any errors relevant to the problem.
