### ISSUE TITLE
Problem Getting Magnet 2nd time

### ISSUE THREAD

**Issue by shaqer** [SchizoDuckie/DuckieTV#834]
**What build of DuckieTV are you using (Standalone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
Nightly 20170112

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 x64

**Describe the problem you are having and steps to reproduce if available**
Click on any show, choose 'Find a Torrent', then click 'Download magnet'.  Everything works fine.  Repeat again, nothing happens after clicking 'Download magnet'.  Using uTorrent 3.4.5.  Have tried this on multiple trackers, different days, same result.

To work around, right-click empty area of app and choose 'Reload app'.  Repeat steps above and works the first time, but not after.

**Attach any DuckieTV statistics or Developer Console logs if available**
No logs to share atm.

Thanks!

**Comment by garfield69** [comment]
Have you by any chance enabled the DuckieTV *Settings, Torrent, Torrent Parameters* option?    
I can only replicate your problem by enabling this option, when it is disabled the *download magnet* links work fine every time for me. Please confirm? Thanks.

**Comment by garfield69** [comment]
OK. Did some research and testing. Turns out that nwjs has problems opening a magnet url via an iframe to chromium.     
Using nwjs 0.20.0 with chromium 56.0.2924.76, you can get the *First* open of a magnet to work straight away, but subsequent opens of the same magnet work only after some random time has passes.     
When using the same code in a Chrome (56.0.2924.76) extension, it works *Every* time.      
Fortunately the solution is simple. On Standalone, we can open the magnet straight to OS via the Shell.openExternal api. This works reliably *Every* time.     
Patch will be available shortly.

**Comment by SchizoDuckie** [comment]
Excellent research m8. Should we open a bug report on nwjs too?

Op 1 feb. 2017 7:06 p.m. schreef "garfield69" <notifications@github.com>:

**Comment by shaqer** [comment]
Hello, Yes, under settings, Torrent, Torrent Functionality, it is enabled and uTorrent is selected.
Thanks!

**Comment by garfield69** [comment]
Yeah, I'll open a nwjs ticket, but first I've got create a proper simple
reproducible test example for the nwjs guys to use.

 

  _____

**Comment by garfield69** [comment]
ticket https://github.com/nwjs/nw.js/issues/5680 opened with nwjs team.

**Comment by garfield69** [comment]
@shaqer  https://github.com/DuckieTV/Nightlies/releases/download/nightly-11112016/DuckieTV-11112016-windows-x64.exe should resolve your reported problem. Thanks you for raising the ticket.
