### ISSUE TITLE
Zooqle magnets not working

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#844]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
Nightly release for 14-02-2017

**What is your Operating System (Windows, Mac, Linux, Android)**
Os X Sierra

**Describe the problem you are having and steps to reproduce if available**
Trying to add magnets from zooqle doesn't work, it just doesn't add anything.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
I am not have any trouble adding a random Zooqle magnet to my torrent host with DuckieTV on my win7 platform at the moment.    
Can you add that magnet using another search engine on your DuckieTV?     
Does downloading that same magnet from Zooqle directly from their web site on a browser work?     
If you specify the full torrent name (you could supply the browser link to the torrent page on Zooqle), I can then try to download that particular torrent via my DuckieTV to see if I can replicate your problem.

**Comment by lonelyfairie** [comment]
I was trying to download The Sky At Night - S2017E02 , I downloaded using a magnet from the pirate bay when zooqle didn't work. The torrent link is:
https://zooqle.com/the-sky-at-night-s2017e02-720p-webrip-aac2-0-h-264-vm7ka.html

Magnet from the website worked, duckie was also able to start that same torrent when I used the download torrent option instead of the magnet.
I tried other series magnets from zooqle with duckie and none of them started the torrent client download.

Can I get logs from the nightly version that might help?

**Comment by garfield69** [comment]
I have examined the magnet that comes from Zooqle
```
magnet:?xt=urn:btih:EB2377C38BE29F58C48081E9F0CDCEFDAE2ABD7F&dn=%5Bzooqle.com%5D%20The%20Sky%20at%20Night%20S2017E02%20720p%20WEBRip%20AAC2%200%20H%20264&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://tracker.leechers-paradise.org:6969&tr=udp://tracker.opentrackr.org:1337&tr=http://mgtracker.org:2710/announce&tr=http://tracker.mg64.net:6881/announce&xl=515094777&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=http%3A%2F%2Fannounce.xxx-tracker.com%3A2710%2Fannounce&tr=http%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=http%3A%2F%2Fmgtracker.org%3A2710%2Fannounce
```
and compared it to the one that comes from TPB
```
magnet:?xt=urn:btih:eb2377c38be29f58c48081e9f0cdcefdae2abd7f&dn=The.Sky.at.Night.S2017E02.720p.WEBRip.AAC2.0.H.264&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fpublic.popcorn-tracker.org%3A6969
```
As you can see, the Zooqle magnet has extra parameters, &xl, as well as duplicate trackers (coppersurfer for instance).     
My win7 uTorrent (3.4.8 build 42449) host has no trouble accepting my magnet submission via my DuckieTV uTorrent WEB UI client.     
So it could be that the torrent-host that you are using is choking on the Zooqle magnet, probably over the &xl parameter (xl (eXact Length) – Size in bytes), or the duplicate trackers.    

Unfortunately this is not a problem with DuckieTV, so ther eis little we can do.     
You have several choices:     
- upgrade your torrent host (it could be that the lates version can hnadle the &xl parameter)     
- switch to some other torrent host     
- stop using Zooqle

**Comment by garfield69** [comment]
Oh, wait.    
I just re-read your last post. You said that submitting the Zooqle magnet from the web site worked.     
So which DuckieTV torrent client are you using ? I can test and make sure that that client's interface is defined correctly....

**Comment by lonelyfairie** [comment]
I am using uTorrent Version 1.8.7 (41986) (Mac version) via the uTorrent web UI.

**Comment by garfield69** [comment]
Hmm. So I can use my win7 uTorrent with my DuckieTV uTorrent WEBUI client to submit the Zooqle magnet, but you can't use your OSX uTorrent with your DuckieTV WEBUI client to submit the same Zooqle magnet.    
Obviously there is a difference in the WEBUI interface between the OSX version and the Windows version.    
Not sure I can do anything about that, since there is only one DuckieTV WEBUI client.     

I wonder what happens if you tried using the uTorrent WEBUI from your browser to submit the magnet?      
So first, visit the DuckieTV uTorrent WEBUI Integration side panel in Settings, and check the address and port. Its usually address `http://localhost` and port 8080.    
Then start up a browser, type `localhost:8080/gui` to connect to your uTorrent via the browser WEBUI.    
Then click on the *Add Torrent from URL* button and paste the following magnet in the *Torrent URL* box
```
magnet:?xt=urn:btih:EB2377C38BE29F58C48081E9F0CDCEFDAE2ABD7F&dn=%5Bzooqle.com%5D%20The%20Sky%20at%20Night%20S2017E02%20720p%20WEBRip%20AAC2%200%20H%20264&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://tracker.leechers-paradise.org:6969&tr=udp://tracker.opentrackr.org:1337&tr=http://mgtracker.org:2710/announce&tr=http://tracker.mg64.net:6881/announce&xl=515094777&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=http%3A%2F%2Fannounce.xxx-tracker.com%3A2710%2Fannounce&tr=http%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=http%3A%2F%2Fmgtracker.org%3A2710%2Fannounce
```    
and click on the *OK* button. Does it work?     
![image](https://cloud.githubusercontent.com/assets/6933240/23030808/bdb353da-f4d3-11e6-9652-ff22d66946b3.png)

**Comment by lonelyfairie** [comment]
Hi Garfield, I did that and the magnet link added correctly.

**Comment by garfield69** [comment]
@SchizoDuckie a recap: the OSX version of DuckieTV connected to OSX uTorrent via the DuckieTV uTorrent WEBUI is unable to submit magnets from the Zooqle Search Engine. They are rejected by OSX uTorrent as invalid or containing errors.     
However, I can submit the same magnets from my windows and ubuntu DuckieTV using the uTorrent WEBUI client.     

Since I do not have an OSX platform (or emulator) I cannot pursue this further.     
Given that there are abundant other search engines that do work, I am inclined to write this one off as *bad luck OSX user, use another search engine* and close the ticket.    
OR you may want to investigate personally since you do have an OSX emulator ;-)
Your opinion please?

**Comment by SchizoDuckie** [comment]
Since 99% of the rest of the magnets work on uTorrent for windows i'm going to close this as a wontfix because of the crappy OSX uTorrent client (which is known to be lightyears behind of the regular uTorrent for windows)

Either change to one of the other decent torrent clients for your platform or use a different search engine to mitigate the problem.

**Comment by lonelyfairie** [comment]
I use multiple search engines, so not a big issue that one doesn't work. Thanks for trying though :)
