### ISSUE TITLE
Last update affecting RealDebrid extension.

### ISSUE THREAD

**Issue by PylotLight** [SchizoDuckie/DuckieTV#857]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... 
New Tab

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... 
Was working on whatever the last one was.
v1.1.4 - current

**What is your Operating System (Windows, Mac, Linux, Android)**
... 
Windows 10

**Describe the problem you are having and steps to reproduce if available**
... 
The most recent update stopped showing the RealDebrid extension which sends the magnet straight into RD.

**Attach any DuckieTV statistics or Developer Console logs if available**
...
http://imgur.com/a/9QjSu
http://imgur.com/a/ZXJdw

**Comment by garfield69** [comment]
We changed the function of the torrent-dialog buttons in order to support more search engines and in particular, the way that some of them only provide magnet details after visiting a secondary page.     
Unfortunately, since we don't present the raw magnet url in the torrent-dialog like we used to, (because for some Search Engines the magnet is not available on the primary search page results), your RealDebrid extension is not going to work with DuckieTV any longer.

**Comment by SchizoDuckie** [comment]
@garfield69 I disagree. This is possible. (and the sole reason the magnet link icon exists. otherwise it's a duplicate)

**Comment by SchizoDuckie** [comment]
If the magnet link doesn't show on hover, click it once to fetch the details page and update the item with the link. Your extension should now work again with duckietv :+1:
