### ISSUE TITLE
Its stuck initializing forever on my Samsung Galaxy S6

### ISSUE THREAD

**Issue by gofirst2220** [SchizoDuckie/DuckieTV#864]
**What build of DuckieTV are you using (Standalone / Chrome Extension (New Tab / Browser Action))**
Android

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 201603040030

**What is your Operating System (Windows, Mac, Linux, Android)**
Android 7.0

**Describe the problem you are having and steps to reproduce if available**
Its stuck initializing forever on my Samsung Galaxy S6

**Comment by garfield69** [comment]
probably related to https://github.com/SchizoDuckie/DuckieTV/issues/848

**Comment by garfield69** [comment]
It was probably a problem with the google hydra service.     
I downloaded the duckietv*.apk on my bluestack win7 android emulator 30 minutes ago, and I too was seeing the initialising spinning wheel.     
But I just tried it again now, and that has progressed to *Hydra has detected a new update* page, with the *update and restart* button available.     
so @gofirst2220 try again and see if it works now, and let us know what happens.

**Comment by SchizoDuckie** [comment]
You may need to shut it down and restart it. Ive had it too. A restart
helps

Op 4 mrt. 2017 9:08 a.m. schreef "garfield69" <notifications@github.com>:

**Comment by gofirst2220** [comment]
@SchizoDuckie Got it And now the UI is so tiny on my phone. Would it be better if i file another issue about the UI being tiny?

**Comment by SchizoDuckie** [comment]
Sorry, the UI will not scale for the foreseeing time unless somebody sends
a pull request.

Op 4 mrt. 2017 5:42 p.m. schreef "Luke Davies" <notifications@github.com>:

@SchizoDuckie <https://github.com/SchizoDuckie> Got it And now the UI is so
tiny on my phone. Would it be better if i file another issue about the UI
being tiny?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/SchizoDuckie/DuckieTV/issues/864#issuecomment-284163378>,
or mute the thread
