### ISSUE TITLE
Deluge Connection Issue

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#866]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Android and Windows: both are the newest nightly build 

**Describe the problem you are having and steps to reproduce if available**

When trying to add a new deluge client the test and save button doesn’t do anything when clicked on I don’t know if this is the same for the others.

will try and submit some relevant logs soon.

**Comment by garfield69** [comment]
Have you read https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-Deluge-with-DuckieTV?     
Have you tried the all the steps in https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-Deluge-with-DuckieTV#problems?     

To begin with, please provide the following: address of the Dulege Host on the LAN or WAN, and the address used on the DuckieTV Deluge integration panel for both the android and windows versions (a screen capture of both will be helpful).     

Also, have you tried connecting your chrome browser to your Deluge Host, by using http://`<ip address of deluge host>`:8112 ?     

I have test the android Nightly 200703070130 using the bluestacks emulator and connected it to a Deluge Host on my LAN successfully.
![image](https://cloud.githubusercontent.com/assets/6933240/23682237/a86d1212-03f7-11e7-92e4-3fc4c3c16519.png)
Same goes for the windows DuckieTV Nightly 200703070130 running a deluge host on the same machine.
![image](https://cloud.githubusercontent.com/assets/6933240/23682303/ec0cc904-03f7-11e7-82eb-57558fbd0d8d.png)

So what ever the problem is, its most likely local to you and will just require some finessing of your configurations or security.

[Edit: corrections to markdown]

**Comment by zero77** [comment]
Thanks for the help, but you where right it was at my end not DuckieTV.
