### ISSUE TITLE
When duckieTV starts its stays dark most of the time/doesn't mark episodes downloaded and doesn't always turn off the torrent.

### ISSUE THREAD

**Issue by ZerkerEOD** [SchizoDuckie/DuckieTV#879]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...I believe the newest one but it will not let me check since It stays dark

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows 64

**Describe the problem you are having and steps to reproduce if available**
...Most of the time when I restart the application it does a write to a file and the screen is dark. but then it stays dark. I have to restart it several times before it decides to work.

I restart it because it stops marking completed downloads as downloaded, and I have the option in the settings to automatically stop completed downloads. But that option will stop working after a little bit also for some reason.

**Attach any DuckieTV statistics or Developer Console logs if available**
...I do not have access since I am still locked out.

**Comment by garfield69** [comment]
Sorry to hear about your troubles with DuckieTV.    

Are you able to tell me if you are using *Stable* or *Nightly* version of DuckietV Standalone?     
You would have downloaded the *Stable* version from https://github.com/SchizoDuckie/DuckieTV/releases or by using the DuckieTV home page http://schizoduckie.github.io/DuckieTV/.    
The *Nightly* you would have downloaded from https://github.com/DuckieTV/Nightlies/releases    
Do you recall how long ago you downloaded the Standalone version you are currently using?      

In general, if you start DuckieTV and you are shown a black screen straight away, then usually this means that something is broken and causing Javascript or nw.js to crash before the calendar is displayed.     
Once broken in this way, it is unusual to find that some restarts succeed, unless you have deleted the Standalone local data folder in order to startup from scratch again.     

A suggestion: Before restarting DuckieTV after a crash, you might want to check with the Task Manager that all the DuckieTV processes have been terminated. Starting DuckieTV again while some of the previous processes are still active will prevent a clean startup the next time.     

If you do manage to get DuckieTV running again, consider doing a backup by visiting the DuckieTV *Settings, Backup* panel, and clicking on the *Create Database Backup* button. This will be useful later, should we need to start from scratch.     

If you cannot get DuckieTV started, then I may be able to help if you uploaded a copy of your database here. You should find the database file along a path similar to `C:\Users\<username>\AppData\Local\DuckieTV-Standalone\User Data\<profile>\databases\chrome-extension_bagblfnohpiddokbpaacecffdboomafe_0`     
Zip it and drag and drop it here and I can examine the database and determine how to best proceed.     

>I restart it because it stops marking completed downloads as downloaded, and I have the option in the settings to automatically stop completed downloads. But that option will stop working after a little bit also for some reason.      

Hmm. This is odd behaviour. The only time I have seen this happen is when the console log is so full of messages that the DuckieTV region runs out of storage. This usually only happens if you leave DuckieTV running for weeks and weeks, or if there is some sort of log message that is being posted repeatedly.    
But we will only be able to figure this out once we get your DuckieTV starting properly again. :-)

**Comment by ZerkerEOD** [comment]
I now have to log off my computer and log back in for it to work, I am using version 1.1.4. I believe it is the stable. 

I do keep my computer on and usually just leave that running but it happens after about a day, not weeks.


For some reason it keeps telling me that my .zip is not supported but then tells me that zip is supported...

**Comment by ZerkerEOD** [comment]
https://www.dropbox.com/s/6ivxt8xkjxtxbq4/databases.zip?dl=0 I just uploaded it to dropbox and sending you the link to the zipped database.

**Comment by ZerkerEOD** [comment]
![screenshot 2017-03-22 17 30 36](https://cloud.githubusercontent.com/assets/26573385/24223674/4640bf24-0f25-11e7-8300-73810fcedc5b.png)


Also as you can see the U is only showing for the fosters, not the other two on the 21st. I had to manually download because the auto download wasn't working.

**Comment by garfield69** [comment]
OK. Well the good news is that your DB is fine, so we can eliminate that from the equation.     
That still leaves the unexplained *dark screen* you reported.    

What I would recommend is for you to download the latest Development Nightly version of DuckietV.    
The advantage with the Nightly is that it comes with the *Development Tools* package, which is ideal for problem solving.     
Also, The Nightly contains all the latest fixes, so that brings you up to date, especially since you are using Tixati, as there have been several fixes since 1.1.4 came out for the DuckieTV Tixati Client.      
But be aware that the Nightly is Work in Progress (WIP), so there may be surprises or new features that are broken or incomplete.     

You can find the Nightly packages here: https://github.com/DuckieTV/Nightlies/releases     
It installs over the top of 1.1.4 and uses the same DB. I recommend making a backup of the DB as a safety precaution, in case things go wrong.     
 
Once you have the Nightly running, I would like you to visit the DuckieTV *About* page by clicking on the (i) icon near the bottom left.    
Scroll down to the Statistics section, and click on the Statistics header to copy the stats to your clipboard.    
If you paste that here that will be useful.     

Finally, regarding your problems with the auto-download. Before I dig into this deeper with you, you may find reading the following wiki useful: https://github.com/SchizoDuckie/DuckieTV/wiki/Auto-Download-FAQs

If afterwards you still feel that the auto-download is not behaving as you expect then let us know and we can go deeper into this with you.

**Comment by ZerkerEOD** [comment]
![screenshot 2017-03-23 15 25 51](https://cloud.githubusercontent.com/assets/26573385/24268791/028a0d0e-0fdd-11e7-8e7a-d42f668c18bb.png)

this is the dark screen that I am talking about. If i log off my computer and or shutdown and open it on a fresh start it starts perfectly, if I close it and reopen it, this is what I get every time. I haven't had time to download the nightly but will do so today at some point.

**Comment by ZerkerEOD** [comment]
I downloaded the nightly and it started right up, but it is still not tracking on the calendar that it is downloading. 
![screenshot 2017-03-23 15 57 16](https://cloud.githubusercontent.com/assets/26573385/24270077/b7aeb8d4-0fe1-11e7-8612-e98c54ea28cb.png)

And here is a screenshot the the settings I currently have. 
![screenshot 2017-03-23 15 58 52](https://cloud.githubusercontent.com/assets/26573385/24270098/c2bc7b58-0fe1-11e7-8a14-2f13696587c9.png)

**Comment by ZerkerEOD** [comment]
Okay so I saw that in some photos you have around about the auto download that you had utorrent checked, so even though I have always used taxiti, I downloaded utorrent and that seemed to have fixed all my issues as of now. I am waiting to see if my download autostops now to find out. Also if I close my issue can I reopen it if it breaks again if the info here is still relevant, or would I need to make a new issue? I have never used github for this type of stuff.

**Comment by garfield69** [comment]
>this is the dark screen that I am talking about. If i log off my computer and or shutdown and open it on a fresh start it starts perfectly, if I close it and reopen it, this is what I get every time.     

So this *Dark screen* is like an unfocused window. I take it that clicking inside the window does not activate it?      
I wonder if it is a windows 10 clash of some kind. I don't have a win 10 sandbox to play with so I cannot test this. But I have never seen this on my win 7.    
And with the Nightly you have not had a repeat of this so far?     

>I downloaded the nightly and it started right up, but it is still not tracking on the calendar that it is downloading.      

The uTorrent is the first and oldest DuckieTV client we have so it is probably the one that is the most robust and has well tested features.      
The Tixati client is much newer and by the looks of your reports, is in need of further development and testing.     

> if I close my issue can I reopen it if it breaks again if the info here is still relevant, or would I need to make a new issue?      

If you close the issue and you do not see a *Reopen Issue* button afterwards, then you can always just add a comment (which should remain available at all times, unless we *lock* the issue) so you can always ask us to re-open the ticket for you.     
In general, we would prefer one issue per ticket, so we can track, resolve and close it separately from other issues.
You can refer to prior issues by just including the hash number of the ticket. For example #879.

**Comment by ZerkerEOD** [comment]
Well thanks, this is an amazing program and its working very well for me now since switching to utorrent and the nightly.
