### ISSUE TITLE
writing to db stalls.

### ISSUE THREAD

**Issue by nickthesick123** [SchizoDuckie/DuckieTV#885]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... 20170328 nightly

**What is your Operating System (Windows, Mac, Linux, Android)**
...windows 10

**Describe the problem you are having and steps to reproduce if available**
...when it goes to check for updates, either automatically (such as upon start up) or when manually (such as when I go into settings - back up - refresh all series) it will start the update process, but then when it's around 80% or so of the way complete it will just stall and wont complete the check. 

**Attach any DuckieTV statistics or Developer Console logs if available**
...
https://www.dropbox.com/s/vih22ew1f2c1anf/1?dl=0

**Comment by garfield69** [comment]
Hmmm, your DB looks to be good, no problems there...     

Please repeat the *refresh-all* and when it stalls again, do the following:      

- press **F12** to open the *Development Tools* page      
- click on the **console** tab to view the log      
- over the *Quack* message at the top of the log,     
- (1) *right click* and      
- (2) *save as...* and upload the log so we can take a look.     
![image](https://cloud.githubusercontent.com/assets/6933240/24478515/95310d42-1537-11e7-989a-4feafc77bcd5.png)      
- Back on the main DuckieTV page, please click on the *Info* icon near the bottom left 
![image](https://cloud.githubusercontent.com/assets/6933240/24478573/d4ea8d8c-1537-11e7-8fea-a55ae78f260b.png) to open the *About* side panel,      
- scroll down to the *Statistics* section.      
- Click on the *Statistics* header to copy the statistics to your *Clipboard*,      
- and either *paste* straight into the body of this ticket or into a text file and upload it.      

Thanks.

**Comment by nickthesick123** [comment]
https://www.dropbox.com/s/xy7sk1mjsy2pk87/duck.txt?dl=0

https://www.dropbox.com/s/pcls9rruy1wi7w2/bagblfnohpiddokbpaacecffdboomafe-1490825057556.log?dl=0

**Comment by garfield69** [comment]
Terrific, thanks.     
I have set up Nightly 20170328 on my win7 sandbox with your settings and database, and by going to the *Settings, Backup* panel and clicking on the *refresh all series now* button, I get the following 2 out of 3 times:     
![image](https://cloud.githubusercontent.com/assets/6933240/24480188/7bcf32ea-153f-11e7-9802-9709a672c771.png)     

If I wait for the *progress monitor* to close on its own, nothing further appear to happen, as you reported.     

But by clicking the mouse over the free area below to calendar  to close the side panels, or by doing any sort of mouse activity over the panels, the *progress monitor* closes.     
Examining the log afterwards does not show any error messages of import.     

So I don't think there is anything wrong with your database or setup, it looks to me like there is an issue with the *progress monitor* updates, which I will get @SchizoDuckie to look into, since the latest change of significance in this area was his switch to using the background adaptor for the database updates.      

@nickthesick123  when the progress monitor appears to hang again, try performing any kind of activity on DuckieTV, such as moving your mouse over the calendar, or clicking on the free space below the calendar, etc, and see of the progress monitor closes for you as it does for me.     

BTW Thanks for reporting.

**Comment by SchizoDuckie** [comment]
Hmm so it looks like this is an effect of removing the angular
$scope.$digest call in the query monitor. the easiest solution will be to
add back a $scope.$applyAsync() whenever outstanding queries count is zero.

**Comment by garfield69** [comment]
@nickthesick123  the next Nightly 20170401 which will come out tomorrow, should fix your reported problem. I've tested it against your DB in my sandbox and it closes the queryMonitor 5 out of 5 times when all the DB writes are completed.

**Comment by SchizoDuckie** [comment]
Thanks. I've been quite busy this week

**Comment by nickthesick123** [comment]
Cool, I'll download the newest one once I get the chance.
