### ISSUE TITLE
Auto download not working

### ISSUE THREAD

**Issue by adaptiveshawn** [SchizoDuckie/DuckieTV#891]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... Stable 1.1.4

**What is your Operating System (Windows, Mac, Linux, Android)**
... Windows 7

**Describe the problem you are having and steps to reproduce if available**
... Auto download not working. Have to manually click each show and manually force download. uToorent is linked and working. All settings are correct. All shows set to auto download. Had this problem from previous build as well. Can provide my database backup.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Please zip the following data folder `C:\Users\<username>\AppData\Local\DuckieTV-Standalone` and drag & drop into the body of this ticket.     
I will load it into my sandbox and take a look for you.

**Comment by adaptiveshawn** [comment]
File is too large to post on here. I'll provide link for direct download. 
~~https://my.pcloud.com/publink/show?code=~~
[edit] thanks. downloaded and removed link for security

**Comment by garfield69** [comment]
OK. here is what I would like you to try out:      
- go to the DuckieTV *Settings, Auto-Download Torrents* sidepanel , and turn off auto-download by clicking on the *Disable auto-downloading torrents* button     
![image](https://cloud.githubusercontent.com/assets/6933240/25067874/c199a784-22a4-11e7-9707-8864cc1d2f52.png)
- then go to the *Settings, uTorrent Integration* sidepanel and click on the *Clear uTorrent Authorization* button      
![image](https://cloud.githubusercontent.com/assets/6933240/25067885/19e6ca8e-22a5-11e7-87c2-ebab9e3ad7f5.png)
- then click on the *Connect to uTorrent* button      
![image](https://cloud.githubusercontent.com/assets/6933240/25067902/80596556-22a5-11e7-846f-30e96bdc4150.png)
- and click on the *yes* button on the uTorrent *DuckieTV has requested access* pop up window      
![image](https://cloud.githubusercontent.com/assets/6933240/25067915/d68b2d9c-22a5-11e7-9995-01bd270f3979.png)
- and enable to auto-download service again      
![image](https://cloud.githubusercontent.com/assets/6933240/25067921/15f63bc0-22a6-11e7-820e-e7f7595aa4bb.png)
- and finally, take a look at the auto-download monitor and watch for activity, which should start like it did for me on my sandbox test with your data folder. :-)     
![image](https://cloud.githubusercontent.com/assets/6933240/25067940/a9e80b38-22a6-11e7-8af5-16c10cbd43e4.png)


If this does not work for you then please upload a screen shot of the auto-download monitor so I can take a look.    
Let me know how you go.

**Comment by adaptiveshawn** [comment]
First off, I wanted to say that I really appreciate all the help thus far. I've tried that before I posted here, however not in that exact order. So I went through the process as you had documented. There was no change for me.  Here's what I see:

![image](https://cloud.githubusercontent.com/assets/27560948/25068194/1f334f3c-2221-11e7-94e3-e1f95a687809.png)

![image](https://cloud.githubusercontent.com/assets/27560948/25068198/3a67ecf4-2221-11e7-971d-f907e8b913ee.png)

![image](https://cloud.githubusercontent.com/assets/27560948/25068201/4b7a9d02-2221-11e7-95a5-f7d963796812.png)

**Comment by adaptiveshawn** [comment]
I don't understand the autoDL disabled HS under the status. All my settings are set to auto download. 
-Edit: NVM. That's because there's no torrent I am guessing....

**Comment by adaptiveshawn** [comment]
Here's another for instance. Live PD - S01E31 Not downloaded. Was on yesterday. 
![image](https://cloud.githubusercontent.com/assets/27560948/25068277/1828cf0c-2224-11e7-823e-24a9d7302c35.png)

Clicking on find a torrent provides this result:
![image](https://cloud.githubusercontent.com/assets/27560948/25068280/2d470b92-2224-11e7-9290-502a7e77e49a.png)

The show will not download unless i manually click on a link to force the download. This happens now with all my shows for the most part.

I've also tried to do a refresh all shows. In the past this worked. Now it does not seem to make any difference. Wondering if it's a corrupt database issue.

**Comment by garfield69** [comment]
>I don't understand the autoDL disabled HS under the status. All my settings are set to auto download.      

Have a read of this wiki https://github.com/SchizoDuckie/DuckieTV/wiki/Auto-Download-FAQs and in particular, the section on auto-download monitor details https://github.com/SchizoDuckie/DuckieTV/wiki/Auto-Download-FAQs#auto-download-monitor-details     

So the episodes that show *autoDL disabled HS* are all **specials**, as designated by the *season 0*, and because you have *Show special on Calender* set to *Hidden*, the auto-download does not download them. The logic here is that if you are not interested in seeing a special episode on the calendar, then you are not likely to be interested in downloading them either.      
![image](https://cloud.githubusercontent.com/assets/6933240/25068441/042f7cb4-22b8-11e7-855b-3e2fe9ae59c0.png)

This is not a big deal since specials can hardly ever be auto-downloaded anyway, since the torrent names for specials almost never match the series season/episode naming scheme. You almost always end up searching and downloading specials by hand.     

>Here's another for instance. Live PD - S01E31 Not downloaded. Was on yesterday.      

OK. The auto-download service only uses the default search engine to do it's searches.     
The manual search defaults to using the default search engine, but you have enabled multi-engine manual search mode, a *new feature* that has not yet been implemented for auto-download (that feature will be implemented in the near future).     
So the current default search engine  is *TorrentDownload*, (which you set in Settings, Search engines), and the auto-download is using this SE for all its searches.

When you do a manual search for *Live PD S01E31*, you will find that the only hits are from *1337x*, *Idope* and *Zooqle*.  So the auto-download cannot find this episode with TorrentDownload SE.      

But you can make the auto-download use *Zooqle* for searching *Live PD* by setting the *Live PD* custom search engine setting as shown below      
![image](https://cloud.githubusercontent.com/assets/6933240/25068389/20d04530-22b6-11e7-9808-3660e85a82a2.png)

> Wondering if it's a corrupt database issue.     

It looks to me like everything is working as it should be, and my check of your data files shows that everything is OK :-)

**Comment by adaptiveshawn** [comment]
I understand now, however I must admit it is confusing without explanation. If you can click find a torrent by searching all providers, I'd imagine you should be able to download a show that's there. I can't see any real advantage to lock it to only one torrent source unless you really wanted to do that. Personally I don't care where it comes from as long as it matches the criteria and is available to download.

Again, I appreciate all the help. Maybe going forward if this could be implemented so that you don't have to rely on a single provider source for the torrent. I will make changes to all my shows.

Thank you.

**Comment by garfield69** [comment]
Yes, the plan going forward is to implement the multi-search-engine feature of the manual downloads for the auto-download service as well.
