### ISSUE TITLE
Search cancels automatically after brief delay

### ISSUE THREAD

**Issue by MWPollard** [SchizoDuckie/DuckieTV#893]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
v1.1.4

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 Pro

**Describe the problem you are having and steps to reproduce if available**
I click the Search box and type something, say, "Star Trek". I mouse-over items and select some. Then the search results reset. The selection from the last mouse-over is still listed, but the seach results have reset.

**Attach any DuckieTV statistics or Developer Console logs if available**
![image](https://cloud.githubusercontent.com/assets/27873704/25299739/22eedcaa-26d0-11e7-935c-3777528bd2ac.png)

**Comment by garfield69** [comment]
Thanks for reporting.    
On my sandbox I managed to replicate your report only once in a dozen attempts.     
It may have something to do with a search kicked off during type-ahead that fails, and the subsequent error/retry recovery that kicks off another search but without the query.... or something like that.      
Schizoduckie is due to complete an upgrade to this panel (ticket #861) at some point, maybe he can look into this ticket when he makes those changes.

**Comment by lgmorand** [comment]
I can repro one almost 50% of my attempts. My only fix ? being fast, because after few secs, it reset the results
