### ISSUE TITLE
Cannot remove from favorites

### ISSUE THREAD

**Issue by lgmorand** [SchizoDuckie/DuckieTV#898]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
DuckieTV Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
version 1.1.4

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10

**Describe the problem you are having and steps to reproduce if available**
I added a lot of series to the favorites and one by mistake. When I delete it, it disappear but it comes back later (not after a reboot, but later, sometimes the same day, sometimes few days later. 
I have standard settings except I linked my account to Track.tv but for this specifc serie, nothing has been marked as watched

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
I've not been able to replicate this issue in my testing so far.     
I've been thinking about ways in which a series would re-appear in your calendar, and it would be useful if you could confirm/reject the following for me:     
- to remove the series you are using the *remove from favourites* button at the bottom of the series details panel, and replying *yes* to the *delete series?* prompt ?      
![image](https://cloud.githubusercontent.com/assets/6933240/25775963/bc7cee66-3305-11e7-8985-248738b03d6e.png)

- are you performing a Trakt.TV *import* at any time, to update your DuckieTV data with any changes from your Trakt.TV account?     
![image](https://cloud.githubusercontent.com/assets/6933240/25775955/86d53dd6-3305-11e7-937c-c3278cad1b63.png)

- what is the name of the series that keeps coming back?     

- the only other possibility I can think of is that somehow the delete series is not removing the series in question, so I would like you to do the following as a test:      
    - go to the *About* page and scroll down to the bottom of the *Statistics* section and note the number of *Series*, *Seasons* and *Episodes* in your DuckieTV Database.      
![image](https://cloud.githubusercontent.com/assets/6933240/25776027/e61c065c-3306-11e7-91d3-1a1463834d25.png)
    - then delete the series in question, and revisit the statistics. You should see a decrease in those counts?     
    - if you zip your DuckieTV data folder and load it in the cloud (via Google Drive for instance) a post a share link here, I can validate your database and do some tests which might prove useful. The path to your DuckieTV data file should be `C:\Users\<username>\AppData\Local\DuckieTV-Standalone`     

- do you keep DuckieTV running all the time, or do you shut it down regularly ?

**Comment by lgmorand** [comment]
Hi garfield69, sorry for the delay (vacations :))

> to remove the series you are using the remove from favourites button at the bottom of the series details panel, and replying yes to the delete series? prompt ?

Yes, exactly


> are you performing a Trakt.TV import at any time, to update your DuckieTV data with any changes from your Trakt.TV account?

nope. I just created a track.tv account and linked it in the settings I believe


> what is the name of the series that keeps coming back?

presidio med

> the only other possibility I can think of is that somehow the delete series is not removing the series in question, so I would like you to do the following as a test:

I just came back from few days off and the serie is back but I deleted it again before doing the test. will do when it will come back

> do you keep DuckieTV running all the time, or do you shut it down regularly ?

run on startup automatically and normally I never kill the process



BTW:
- first for your help
- pretty clear assist on how debug it :-)

**Comment by lgmorand** [comment]
version on 9th May after deleting the serie 
42-0-267-4502

version on 9th May (1hour later) the serie is back
43-0-268-4518


version of 9 may after deleting again
42-0-267-4502

here is the backup of this version (9thMay) ~~https://1drv.ms/~~
[edit] downloaded file and deleted link for security

version of 12 may (serie is back....)
44 0 272 4545


the last I added a serie while Presidio Med was deleted, which means it is not just a rollback, it is just coming back, but it take sometimes one day.

I really don't understand what could cause this because closing duckietb, changing the system date does not make the serie come back. It comes back at some time without reason

**Comment by garfield69** [comment]
Thank you for the data, it proved useful.      
So I now know what is going on.     

It all begins with the regular Trakt.TV *update cycle* that DuckieTV kicks off (by default) every 12 hours. This fetches from Trakt.TV a list of all the series that have had updates since the last time it was checked.     
The list includes an update for the series **24** which you have in your favourites.     

At this point, it is useful to note that when one makes a request from Trakt.TV for series information, one can supply the series *slug_id, IMDB_id*, or *Trakt_id* as the **ID** parameter on the request.     

So DuckieTV then intends to fetch from Trakt.TV all the data it has on the series **24**, using the series *slug_id*, in the following request: `https://api.trakt.tv/shows/24`     
However, Trakt.TV interprets the *24* as the *Trakt_ID* of the series, which happens to be the ID for *Presidio Med* !!     

And thus, instead of receiving the latest data for the series *24* for DuckieTV to update any differences, it is instead presented with the latest data for *Presidio Med*, which it dutifully adds as a new series to your favourites.     

The obvious solution is to change the way we perform updates, by requesting from Trakt.TV the series using the *Trakt_id* instead of the *slug_id*.     
But first I need to do some research into why we are using the *slug_id* in the first place, and what impact there may be to changing it to using the *Trakt_id* instead.

**Comment by lgmorand** [comment]
so fast analysis!! I'm a dev myself by this one was tricky, good job :)

I'm happy to have find a real bug, even minor, at least you did'nt lose your time.

Now, I know that I'm not crazy and I'll wait a for a bug fix one day, and will leave it as it for the moment. Thanks for your help @garfield69! I love duckietv!

ps: have a nice day
