### ISSUE TITLE
Duckie 1.14 and nightly builds, clicking on auto download all episodes launches magnet links using default program instead using rtorrent as configured.

### ISSUE THREAD

**Issue by gk1** [SchizoDuckie/DuckieTV#906]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...stand alone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...Both 1.14 and latest nightly 6-11

**What is your Operating System (Windows, Mac, Linux, Android)**
...windows 10

**Describe the problem you are having and steps to reproduce if available**
...trying to get auto download to work correctly. I went to my favorite show, clicked episodes, and then autodownload all. I get notifications that duckie is launching torrent. And i get a popup to select my default app, or select one from the app store. I have configured rtorrent intgration, and it says that it is connected to the api and ready. Torrents never start on my rtorrent seedbox.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Hmm. I think the first setting we should take a look at is to make sure that the *Torrent Parameters* option is turned off. If *Enabled* this launches any magnets via the OS shell instead of passing it to the client via the API, so set it to *Disabled*.            
![image](https://user-images.githubusercontent.com/6933240/27017198-cddc0d40-4f7a-11e7-9a9a-4107fc972759.png)

**Comment by garfield69** [comment]
The other likely possibility is that your connection to your seedbox is not working, despite the *is connected* status.     
This is because *connected* simply means that DuckieTV found an open port at the end of the link, but that does not necessarily imply that communication is occurring.     
When DuckieTV submits a magnet via the API, it looks for a valid response back, and if it does not get it, it then falls back to using the OS shell instead.      
Have a read of this wiki https://github.com/SchizoDuckie/DuckieTV/wiki/FAQ#how-to-connect-with-a-rutorrent-seedbox which should help you set up your DuckieTV rTorrent client correctly.     
If you are still having problems, let us know and we can try to assist you diagnosing the problem further.
