### ISSUE TITLE
FEATURE: Rename the episode with a particular format after the download

### ISSUE THREAD

**Issue by kevincaradant** [SchizoDuckie/DuckieTV#913]
Hi

I developed a little software in JAVAFX to rename under a particular format all my tvshows, it's cool  but I have to use it for each downloaded episode...
and I would to know if you can add a feature which after each downloaded episode, can rename under a format your episode. The most simple is to suggest some pre-defined formats as NAME_SERIE_SXXEXX etc and then for the advanced users, a regex to maximalized the powerfull feature :)

Regards

**Comment by garfield69** [comment]
DuckieTV is constrained by the rules of a Chrome Browser Extension. It does not have access to the file system because of security.      
If you are looking to do file management post download I can recommend Filebot. see https://github.com/SchizoDuckie/DuckieTV/wiki/Pairing-DuckieTV-with-FileBot-for-a-fully-automated-media-center for an example.
