### ISSUE TITLE
Ktorrent integration stuck on loading

### ISSUE THREAD

**Issue by pitzpitz** [SchizoDuckie/DuckieTV#918]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
V1.1.4

**What is your Operating System (Windows, Mac, Linux, Android)**
Linux (Kubuntu 17.04)

**Describe the problem you are having and steps to reproduce if available**
After setting torrent client to Ktorrent and clicking on KTORRENT INTEGRATION, a loading float appears and nothing happens. This problem does not occur with other torrent client selections.

**Comment by garfield69** [comment]
Ah yes, sorry about that.     
The template used for the Ktorrent Integration panel was originally named Ktorrent.html but it should have been named ktorrent.html      
This was not picked up during the February build of 1.1.4 because testing was performed on a windows platform which  is not case sensitive. However Linux is, so it cannot find the required html page.       
I discovered the error in April and fixed the source for the next build.      

You should be able to fix this by starting a terminal shell and pasting the following command `sudo mv /opt/DuckieTV/templates/settings/Ktorrent.html /opt/DuckieTV/templates/settings/ktorrent.html`

Let me know how you go :-)

**Comment by pitzpitz** [comment]
Nice catch, the fix worked. Thank you!
