### ISSUE TITLE
Feature Request: Improvements to Auto Backup

### ISSUE THREAD

**Issue by MFKDGAF** [SchizoDuckie/DuckieTV#925]
If possible it would be nice if the auto backup could auto download the backup file instead of prompting to download it. 

I ask for this feature because I will go days or weeks without actually connecting to the computer that duckieTV is running on to find out no torrent files have auto downloaded because I need to accept the download for the backup.

I don't know if this is possible with chrome extensions but if it were to be implemented in the standalone version then I would make the switch.

As a side request: it would be nice if I could designate where to save the backups instead of just having them saved in the user's download folder.

**Comment by garfield69** [comment]
>If possible it would be nice if the auto backup could auto download the backup file instead of prompting to download it.     

I'm sorry, I don't think this is possible.      

First a little background information:     
DuckieTV is a Chrome Browser Extension app, written in JavaScript using the AngularJS framework.
The standalone version of DuckieTV is exactly the same code encapsulated by the nwjs run time environment.     

So, Chrome Browser security mandates that an app cannot silently save a file without user intervention, otherwise the browser (and your PC) is open to exploitation from malware, virus etc.      

Given the way you currently use DuckieTV, your next best option would be to set the auto-backup to *Never* and manually do a backup yourself when/if you remember to do so.     

>As a side request: it would be nice if I could designate where to save the backups instead of just having them saved in the user's download folder.      

The DuckieTV auto-backup simply passes the to-be-saved backup-file to the Chrome Browser for downloading, and the Browser uses your Browser **Download Settings** for the save location.      
You control this by changing your Browser download settings:     
![image](https://user-images.githubusercontent.com/6933240/28386408-8cafeb3a-6d1f-11e7-82b9-af186545dba6.png)
