### ISSUE TITLE
Jackett Not Working 

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#931]
When adding torrent SEs from Jackett I get a 404 reason unauthorized error also in the developer console I am seeing an error saying GET method is not supported.

I have duple checked the API key and torznab link, and tried with and without the use torznab API instead also, I have checked under the Jackett console and it appears ok in Jackett.

Thanks

**Comment by garfield69** [comment]
which jackett indexer are you attempting to use?

**Comment by garfield69** [comment]
running on which platform?    

can you show me a screen capture of the messages from the log?     

did you follow https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV?

**Comment by garfield69** [comment]
which version of jackett are you using?

**Comment by garfield69** [comment]
Have you by any chance set a Jackett Admin Password?      
In which case you will bee seeing `Failed to load resource: the server responded with a status of 401 (Unauthorized)` in the DuckieTV console log, correct?      
In which case, to access the jackett indexers from DuckieTV you will need to set the *use the torznab api instead of the default admin api* check box by editing each of your DuckieTV jackett entries.      
DuckieTV does not support logging into the jackett server with a password.     
Also the DuckieTV jackett test will not work when you are using a jackett admin password.

**Comment by zero77** [comment]
Thanks for your reply, I am using the newest nightly of Duckie and Jackett versions on Linux, to my knowledge it is happening with all indexers.

yes, I have changed the Jackett console password, so it should work if I select “use the torznab api instead” even though the test fails in Duckie.

**Comment by garfield69** [comment]
OK. I'll set up Jackett on my linux sandbox and see if I can replicate your problem. All my testing/setup has been on windows so far.     
did you follow the linux jackett setup at https://github.com/Jackett/Jackett#installation-on-linux?

**Comment by zero77** [comment]
Thanks, yes I have it fully installed and working as I use it with Radarr and its working ok.

**Comment by garfield69** [comment]
On my Ubuntu 17.04 sandbox, I have tested both Jackett 0.7.1581 and the latest pre-release Jackett 0.7.1650 against DuckieTV Nightly both the standalone 201708060130 and the chromium extension Nightly 3007.8.6.91      
For all 4 permutations, I tested the Demonoid Indexer on Jackett, First with no Jackett Server Admin password in combo with the DuckieTV Jackett *use-admin API* definition, and secondly, with the Jackett Admin password set in combo with the DuckieTV Jackett *use the torznab* defined,      
and I had no problem performing searches on DuckieTV using the demonoid search engine.      

This leads me to conclude that what ever problem you are having is local to your personal setup.       

In your DuckieTV Jackett definitions, does your torznab look something like this: `http://127.0.0.1:9117/torznab/demonoid` ?      
note the use of http, and the 127.0.0.1 address.     
Also, confirm that the *use torznab* checkbox is ticked as shown below:
![image](https://user-images.githubusercontent.com/6933240/29007462-f0548a7e-7b57-11e7-9c2c-3ba532373fab.png)

**Comment by zero77** [comment]
After more investigation I have found that its now working when the box below is ticked, thanks.

Although, the test keeps failing as before, I have tried both localhost and public IP and double checked all the settings at both ends all to no avail.

So it looks like there may be a problem with the DuckieTV Jackett SE test, as everything else is now working ok.

**Comment by garfield69** [comment]
Yeah. The DuckieTV Jackett *test* is essentially the same test that Jackett performs when the user click on the *test* button on the Jackett dashboard.     
Since this is performed via the admin api, if you are using a jackett server with password protection, then DuckieTV will not be able to access this test.     
I am not inclined to writing a custom test routine within DuckieTV that uses the torznab api, too much effort IMO.

**Comment by garfield69** [comment]
I will disable the test button when the torznab option is used, to clarify this.

**Comment by zero77** [comment]
Ok, thanks for the help.
