### ISSUE TITLE
"All" versus specific resolution when searching for torrent

### ISSUE THREAD

**Issue by jandreaucodes** [SchizoDuckie/DuckieTV#932]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Chrome plugin

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.4

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac OS 10.12.6

**Describe the problem you are having and steps to reproduce if available**
When manually searching for a torrent, the "ALL" doesn't find specific torrents it should, based on my keywords.

For example, this is ALL:
![ctb9u](https://user-images.githubusercontent.com/12860371/29024588-bf5bdd1c-7b40-11e7-9d92-3f4210df1063.png)

However, if I pop over to the 720p filter:
![bc9cy](https://user-images.githubusercontent.com/12860371/29024595-c5d094d0-7b40-11e7-9e5a-e1e94d09cd16.png)

The ALL view should be all torrents that match any of my keywords. Since I have 720p in my keywords, this torrent in the 720p section should show up, but doesn't.

This happens with a lot of torrents. I'm just using this for an example of the issue I'm reporting.

If I'm missing something, I'm very happy for this to be user error, but it seems like a bug to me.

**Comment by Js41637** [comment]
Ok so as I understand it the require keywords only filter based on results available. So if you search with All and there is nothing that meets the requirements nothing is shown however if you select 720p it appends it to the search string which will return different results. So when you search with all it might have only returned 20 results none of which included 720p however when you specifically search for 720p, all the results returned will be 720p related. At least that's what I think is going on? I had a similar issue but I don't know if this is the same.

**Comment by jandreaucodes** [comment]
@Js41637 That's logical. But ALL should show everything, shouldn't it? You mentioned it would return 20, but that wouldn't be _all_, right?

So if something shows under 720p, theory dictates it should also show under the ALL section, which my keywords should then filter, no?

**Comment by Js41637** [comment]
ALL would search for your query without any modifications. So its theoretically possible for the results that were returned to not include a 720p at all, like there might be a lot of results and the search was too vague. Whereas when you search for 720p directly you will only get 720p results however it does seem unlikely in this case as I use to include `x265` however there is usually a lot more `x264` results returned and i wasnt finding any because my search wasn't specific enough.

**Comment by jandreaucodes** [comment]
I don't think that's it.

As a test, I took the required keywords out entirely. The ALL shows nothing for this show, but the 720p still shows the one I ended up downloading.

![pgq8x](https://user-images.githubusercontent.com/12860371/29025586-737cf674-7b45-11e7-9cea-ef721a129532.png)

**Comment by Js41637** [comment]
Try going to the pirate bay to see what is actually being returned?

**Comment by jandreaucodes** [comment]
The right results that *do* show up under the proper filters if I go through them manually.

![bs59f](https://user-images.githubusercontent.com/12860371/29025669-e5ed7792-7b45-11e7-811e-2492b00032a7.png)

Maybe I'm misunderstanding the ALL filter, but I assume it means "all torrents on the torrent site you've specified", and then my keyword filters are applied to narrow the results.

**Comment by Js41637** [comment]
Nah it definitely should, I've not encountered this issue and it correctly returns results. Does it work with ignore keywords disabled?

**Comment by jandreaucodes** [comment]
Nope.

Even with no keywords, nothing comes back on ALL for this episode and a few others I looked at.

![dnptc](https://user-images.githubusercontent.com/12860371/29025877-e15afeb0-7b46-11e7-9bb3-2d58b51073a8.png)

**Comment by Js41637** [comment]
¯\\_(ツ)_/¯ beats me. Works for me

![image](https://user-images.githubusercontent.com/6258213/29025897-51662e3a-7bbc-11e7-80c4-af0d9868f811.png)

**Comment by Js41637** [comment]
You don't have any weird settings enabled do you?

**Comment by jandreaucodes** [comment]
Anything specific I should look at?  The only thing I can think of is that I'm using a proxy since TPB is blocked here occasionally, but if I go to that proxy directly, I get the right results.

**Comment by jandreaucodes** [comment]
Weird. I just toggled "Torrent dialog multiple search engines" on then off and now it seems to work fine.

¯\_(ツ)_/¯

**Comment by jandreaucodes** [comment]
This is happening to me again.

"All" shows a very limited subset of what I see under 720p.

In _some_ cases, it shows the same torrents, but with far less seeders, ie;

ALL:
![azgl9](https://user-images.githubusercontent.com/12860371/29168641-c20d421c-7d9d-11e7-8c01-d1d8e496c71d.png)

720p:
![1qsqr](https://user-images.githubusercontent.com/12860371/29168643-c68fda84-7d9d-11e7-95c4-94a8837629a6.png)

Note the first torrent, it's the same, but ALL shows 1 seeder. 720p shows over 3000.

That's with no keywords on either filter.

**Comment by garfield69** [comment]
please visit the *Settings,Torrent Search Engines* sidepanel and scroll down to *The Pirate Bay* and take a look at what the TPB mirror address is set to. The official site is `https://thepiratebay.org` but `https://thepiratebay.se` works just as well.      
![image](https://user-images.githubusercontent.com/6933240/29188459-386d0a40-7e67-11e7-8914-ff6c24e01c22.png)
I've installed DuckieTV 1.1.4 standalone on my win7 x32 sandbox and this is what i get when I repeat the two searches you recently performed:     
ALL:
![image](https://user-images.githubusercontent.com/6933240/29188550-868072bc-7e67-11e7-88d0-2711e26340d2.png)
720p:
![image](https://user-images.githubusercontent.com/6933240/29188569-9a0837de-7e67-11e7-84d5-3bdc75acbbf8.png)

**Comment by jandreaucodes** [comment]
The Pirate Bay is blocked by my ISP, so I'm using a mirror.

If I go to the mirror and then go to TPB on my mobile phone, the torrents are identical, so I don't think the torrent site is to blame.

I also see the _correct_ torrents if I change from ALL to 720p.

So, to me, it seems like something about ALL when used with a mirror, isn't working properly.

**Comment by garfield69** [comment]
There is nothing magical about the ALL option.    
Behind the scenes, when the search string is prepared to build the url, if one of the quality buttons is active then that quality is appended to the search string with a blank in between, and if the ALL button is active then nothing is appended.      

url for *suits s07e05* with *ALL* quality `https://thepiratebay.org/search/Suits%20S07E05%20/0/99/0`
url fur *suits s07e05* with *720p* quality `https://thepiratebay.org/search/Suits%20S07E05%20720p/0/99/0`

then once the web site returns the search-results page, DuckieTV parses and filters with the *required* and *ignore* keywords (if they are active) and the results are presented.

What is the mirror that you are using? I can do a search with it on my sandbox and see if I can replicate your results....

**Comment by jandreaucodes** [comment]
Thanks for trying to replicate!

I've been using tpbonion.com but am happy to try with a different mirror if needed.

**Comment by garfield69** [comment]
tpbonion.com searching for *suits s07e05* will quality set to ALL
![image](https://user-images.githubusercontent.com/6933240/29197660-484eaa02-7e91-11e7-81bb-e47aa865320a.png)
looks good to me.       

However I have had failures, with tpbonion.com returning cloudflare http error 502 Bad Gateway, and this got me looking at the DuckieTV code, and I may have an explanation for you ...     

I have found that DuckieTV has special code in place for TPB search engine, which gets engaged when a TPB search returns a http error greater than 300.      
When this happens, DuckieTV invokes a TPB mirror resolver, which attempts 3 times to find a proxy via `http://www.piratebayproxylist.co`. If it finds a proxy that responds, then that proxy gets used for the search instead. If the 3 attempts fail then a `no result` is returned.       
I think that replacement proxy stays in place until the next DuckieTV restart, but I am not sure about that, I haven't looked that deep.

So it is likely that this is happening to you. When tpbonion.com returns an error >300 on a search, and an alternate proxy is auto-found, and it could return differing results depending on how up to date that mirror is with the official TPB site.     
This would fit with one of your earlier comments where you said that the problem was resolved at one point. By switching to the multi-SE and back again, you effectively restarted DuckieTV and reset back to using tpbonion.com again for that session.      

So you could try a different mirror to see if it is more stable, (one that does not use cloudflare DDOS protection) and see if you get more consistent results.      

or     
you could use the latest nightly https://chrome.google.com/webstore/detail/duckietv-browser-action-m/ikhklcamhmfmjbhckdjoabiepglbhaid (action mode) or https://chrome.google.com/webstore/detail/duckietv-new-tab-mode-nig/jndkngpbgmnkbhbjafmjhabcjmgeogfc (new tab mode)     
and use Jackett to define your custom TPB entry with tpbonion.com as its address. Then DuckieTV will not invoke the mirror-resolver. Jackett has code to handle most cloudflare protections, so it is a little more resistant to errors.

**Comment by jandreaucodes** [comment]
Thanks for all the digging @garfield69 !

I'll try the nightly build and see what happens.
