### ISSUE TITLE
[Question / Request] Artwork Refresh 

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#937]
How do I refresh the artwork both back ground and poster, because lots of it is out of date and there is newer artwork available on fan art.

If this is not possible can you add the ability in.

Thanks

**Comment by garfield69** [comment]
By default, at least once every 12 hours, DuckieTV gets a list from Trakt.tv of the series that have had updates since the last check.      
For those series, the fanart is refreshed at the same time as the series and its season and episode details are updated.      
This is done by issuing a fetch by tvdb_id from the fanart site. The one request contains all the image links for the series and its season and episodes.      
Only thing preventing an update to fanart would be if there has been an http error (servers busy, down, whatever), or a *not found*, which happens. Then the refresh for that series' fanart does not happen and the old fanart if it exists, remains.     
     
You can force a refresh for a particular series by visiting that series' *details* page and clicking on the *refresh* button.     

Or if you really need to, you could go to the *settings, backup* side panel, scroll down to the *refresh all series* section and click on the *refresh all series now* button.

**Comment by garfield69** [comment]
Addendum: discovered that the seriesDetails sidepanel *refresh* button did not in fact invoke a fanart refresh. this has been corrected. Fix will be included in the next Nightly after 201708130130.

**Comment by zero77** [comment]
Thanks, whenever the next nightly is out I will update.
