### ISSUE TITLE
Progress gauge displaying incorrect percentage value for transmission

### ISSUE THREAD

**Issue by jmarshallpresnell** [SchizoDuckie/DuckieTV#945]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Chrome Extension, Browser Action

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
v1.1.4

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows

**Describe the problem you are having and steps to reproduce if available**
Using transmission integration, the percentage complete shown on the torrent details "Progress" gauge is 1/100 what it should be. (This is probably due to the transmission RPC's JSON response "percentDone": 0.5378 being a number from 0 to 1 as opposed to 0 to 100. The 0.5378 example value above should display as 53.78%)

To reproduce: use transmission integration (obviously), click the "Torrent Client" button on the left rail, then click any actively downloading torrent in the right panel. Observe the right gauge's (Progress) value displayed vs the transmission web interface's value. 

**Attach any DuckieTV statistics or Developer Console logs if available**
none

**Comment by garfield69** [comment]
I have tested the transmissionQt 2.92 on my win7 x32 sandbox sourced from https://github.com/transmission/transmission-releases/raw/master/transmission-2.92-x86.msi,  in a local connection to DuckieTV 1.1.4 and the progress bar works as expected.     
![image](https://user-images.githubusercontent.com/6933240/29758321-a74ba30c-8c06-11e7-9e08-de0c6dbf4ad8.png)

Which version of Transmission are you connected to, and where did you source it from?     

Currently the DuckieTV Transmission client code checks if the *Base Path* is `/transmission/rpc` to determine if it needs to multiply the progress by 100 or not.      
This is because we found that WebServer (seedbox) versions of Transmission already adjust the progress value.     
So can you report what the *Base Path* is set to for your DuckietV Transmission client Please?
![image](https://user-images.githubusercontent.com/6933240/29758310-94fcf818-8c06-11e7-8f59-e0e1badec750.png)

We may need to revisit how we go about determining the scalar value...

**Comment by jmarshallpresnell** [comment]
My transmission host is on a fully updated Debian lxc container on a ProxMox host. Transmission 2.84 (14307). Installed via apt repository.

However, I do have the BasePath endpoint changed from the default to "/tx/rpc", which may explain the discrepancy since that is your determinant. Let me switch it back to default when I get home and see if the problem resolves.

**Comment by garfield69** [comment]
I see. In that case you will not be able to switch the *base path* to anything else, as this is a requirement for your *ProxMox Transmission* host that your DuckieTV is connected to. Changing it will break that connection.     

Would you be willing to perform a little fact finding mission for me please?      
I'm looking for some session details that your seedbox is using. For this I would need you to use your *Chrome Web Browser* to connect to your transmission server, then press the **F12** button to access the *Development Tools* page, click on the *Network* tab, and examine one of the *rpc* events that crop up regularly as the web browser polls the server.      
Check that the method is for a *session-get* by clicking on the *header* tab and scrolling to the bottom
![image](https://user-images.githubusercontent.com/6933240/29761356-0789ffc8-8c1d-11e7-99c5-26036f5abc6f.png)
If it is not, find another *rpc* event.      
IF found, then click on the *response* tab, select the output and *copy* it to your clipboard. Then *paste* it below.
![image](https://user-images.githubusercontent.com/6933240/29761514-81936ae8-8c1d-11e7-834d-b0ec2a4d5c5b.png)

Thanks.

**Comment by jmarshallpresnell** [comment]
Actually, I did switch it to the /transmission/rpc path before I saw your last comment, and it is working properly. 

I will switch back to the old paths to get the diagnostics that might help you out. (Easy switch, just the daemon config and Duckie, so no biggie - it's not like I never reconfigure the 22 servers in my house ... almost every day! LOL!)

**Comment by jmarshallpresnell** [comment]
Here's the JSON response that you asked for. It is the very first session-get request that succeeded on Duckie reload (the first session-get was probably to get the Auth header for subsequent requests) Note that this request was made with the BasePath reset to /tx/rpc as in the original report. Hope this helps a bit :)

{"arguments":{"alt-speed-down":50,"alt-speed-enabled":false,"alt-speed-time-begin":540,"alt-speed-time-day":127,"alt-speed-time-enabled":false,"alt-speed-time-end":1020,"alt-speed-up":50,"blocklist-enabled":true,"blocklist-size":410466,"blocklist-url":"http://john.bitsurge.net/public/biglist.p2p.gz","cache-size-mb":4,"config-dir":"/var/lib/transmission-daemon/info","dht-enabled":true,"download-dir":"/mnt/amanda/staging/In","download-dir-free-space":2107708727296,"download-queue-enabled":true,"download-queue-size":5,"encryption":"preferred","idle-seeding-limit":30,"idle-seeding-limit-enabled":false,"incomplete-dir":"/mnt/amanda/staging/Downloading","incomplete-dir-enabled":true,"lpd-enabled":false,"peer-limit-global":200,"peer-limit-per-torrent":50,"peer-port":41606,"peer-port-random-on-start":false,"pex-enabled":true,"port-forwarding-enabled":false,"queue-stalled-enabled":true,"queue-stalled-minutes":30,"rename-partial-files":true,"rpc-version":15,"rpc-version-minimum":1,"script-torrent-done-enabled":false,"script-torrent-done-filename":"","seed-queue-enabled":false,"seed-queue-size":10,"seedRatioLimit":2,"seedRatioLimited":false,"speed-limit-down":100,"speed-limit-down-enabled":false,"speed-limit-up":100,"speed-limit-up-enabled":false,"start-added-torrents":true,"trash-original-torrent-files":false,"units":{"memory-bytes":1024,"memory-units":["KiB","MiB","GiB","TiB"],"size-bytes":1000,"size-units":["kB","MB","GB","TB"],"speed-bytes":1000,"speed-units":["kB/s","MB/s","GB/s","TB/s"]},"utp-enabled":true,"version":"2.84 (14307)"},"result":"success"}

**Comment by garfield69** [comment]
Great thanks for that. I'm waiting on results from another user that is using the justseed.it service, so I can compare it with yours and my local Transmission session details. If there turns out to be a data point I can use to automate the scalar without relying in the BasePath, then I will implement it. But at this stage, your session details are no different than mine from my local machine.     
    
So you are able to resolve this issue by changing your Transmission configuration back to the default *BasePath*. Good to know.      

So the only question remaining for you is:     
Are you happy to continue using the default *BasePath*, or do you want the option to customise it?      
If the answer is *customise*, then I could add an option in the DuckieTV *Transmission Integration* Settings, say for example a `%x100` checkbox, which you could turn on/off in order to apply/not apply the times-100 scalar to the incoming *percentDone* value.       
But if the answer is *default* then, given you're the only one so far that has tripped over this, I could just close the ticket and leave it be.     
So, customise or default? :-)

**Comment by jmarshallpresnell** [comment]
As you properly labeled it, it's an edge case. I prefer really short API URLs in general, so it's always something I love to modify - but it's definitely just a preference, and one I can live without if needed.

As a developer myself, I always like to have the maximum configurable options available to future-proof my apps. So decoupling the x100 from the BasePath seems like a "good idea"<tm> in general terms. Additionally, does that value, the 100, get used anywhere else; for example torrent stop processing? If so, it becomes even more important to future proof that particular use case.

One interesting possibility is to look at the precision of the number itself, if the number has more than 2 digits after the decimal, it probably needs to be multiplied by 100. On transmission at least, it seems that the precision limit is 4 digits to the right. Of course, this may not be the case with all torrent clients. :(

At any rate, it's your call of course. I have a solution that will work for me, so I'm happy. Only have to modify one external script to use the default endpoint, and that's a one line change. :) 

Thanks for your efforts in this. :) If you need additional info in the future, please give a yell.

**Comment by garfield69** [comment]
FYI    
If (when) you upgrade to *DuckieTV 1.1.5* or the latest *Nightly*, you'll be able to restore your shortened basePath again.     
[edit] typical BuildBot has a mind of its own... I should have typed The Nightly after Tue Aug 29 2017.
