### ISSUE TITLE
Enormous problems since new version

### ISSUE THREAD

**Issue by Acki01** [SchizoDuckie/DuckieTV#964]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...
Chrome Extension new tab
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...
Latest update - can't check
**What is your Operating System (Windows, Mac, Linux, Android)**
...
Windows 10
**Describe the problem you are having and steps to reproduce if available**
...
All my contents have disappeared in the new update and when I try to use a backup, which I thankfully made 25 September, the web browser stops working. Trying to import fro Trak.tv also proves useless, since it also stalls the page and nothing happens.
**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Sorry about that, some users have reported a similar problem.      

So the best way to recover functionality (as long as you have the backup), is to:      

- visit the chrome://extensions/ on your browser,
- and use the trash-bin to remove your DuckieTV extension.
- Then shutdown your Browser completely and start it up again (this gives Chrome the chance to clean up the dataspace)
- then install the DuckieTV extension:
(Action mode) from https://chrome.google.com/webstore/detail/cdfkaloficjmdjbgmckaddgfcghgidei
(New Tab mode) from https://chrome.google.com/webstore/detail/hkbamkappmgfjjahmnlngibomenmbbdf
- and start the extension
- wait a minute or two for everything to settle down
- then at the *You have no series yet! page*, import your backup to restore your DuckieTV series and Settings.

Let me know how you go.

**Comment by Acki01** [comment]
no luck... stalls during import
![skarmklipp](https://user-images.githubusercontent.com/32490906/31243086-6c32a632-aa09-11e7-9b8e-53878eeaea79.PNG)

**Comment by garfield69** [comment]
Very Odd.       
After closing that extension and removing it, try using this one: 
https://chrome.google.com/webstore/detail/duckietv-new-tab-mode-nig/jndkngpbgmnkbhbjafmjhabcjmgeogfc

**Comment by hgshoush** [comment]
I am having the same issue since the latest upgrade, with one difference. I am not using the Chrome extension. I have the Duckie TV standalone installed on my Windows 10 machine. I no longer have any of my shows and when I try to load a backup from a few weeks ago it just sits there an spins. I have left it for 3 hours and nothing has happened.

**Comment by garfield69** [comment]
@hgshoush wrote:

>I am having the same issue since the latest upgrade [...] I have the Duckie TV standalone installed on my Windows 10 machine. [...]

For the Standalone version, since you have a backup, the simplest way to recover is:
1. Locate and delete the following folder: `C:\Users\<username>\AppData\Local\DuckieTV-Standalone`      
2. Then start DuckieTV and wait a few minutes for activity to settle down. 
3. Now perform your Backup import from the *you have no series yet!* page.
Let me know how you go. 
Thanks.

**Comment by garfield69** [comment]
@Acki01  Have you been able to resolve this?

**Comment by hgshoush** [comment]
Thank you, that fixed my problem!
