### ISSUE TITLE
Show disappears multiple times

### ISSUE THREAD

**Issue by cajeiri** [SchizoDuckie/DuckieTV#966]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Chrome New Tab

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Latest nightly

**What is your Operating System (Windows, Mac, Linux, Android)**
Win7 64bit

**Describe the problem you are having and steps to reproduce if available**
Added "Alias Grace", show pops up, I mark episode 1 as viewed, episode 2 as downloaded. Once I close the tab and reopen it, the show is no longer on the list. Removed and added it back, followed the same steps, same thing happened.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
cannot replicate this on my sandbox.     
Did you just install the nightly for the first time or is this happening following the chrome nightly push?      
Do you have a backup or using a synced trakt account?

**Comment by cajeiri** [comment]
It's a month-old install of the nightly.
I'm guessing it followed the nightly push. I have a backup from the 30th and I can make a backup now. Other option is to enable opt-in error tracking for you.

**Comment by garfield69** [comment]
what i really would love to have is a complete capture of your database and settings so I can try and see what might be going on for myself on my sandbox.      
For this I would need you to zip archive the the database at:
`C:\Users\<username>\AppData\Local\Google\Chrome\User Data\<profile>\databases\chrome-extension_jndkngpbgmnkbhbjafmjhabcjmgeogfc_0` where profile is usually `Default` but could be your chrome username
also include in the archive your **latest** backup file.     
then just drag and drop the zip file here.
thanks.

**Comment by cajeiri** [comment]
[Downloads.zip](https://github.com/SchizoDuckie/DuckieTV/files/1361682/Downloads.zip)
I have included a backup I just made plus the oldest one I had, just to be on the safe side. Database "1" is also included.

**Comment by garfield69** [comment]
OK.
Somewhere along the line you have ended up with an orphaned *episode* of **Znation**.     
This single *episode* record exists in the database, but without the supporting *series* record.
This causes the calendar sort routine to crash, preventing other episodes from being displayed on the calendar from that point.
It so happens that the broadcast date of the offending episode is 2017-10-07T01:00:00.000Z which is why the problem showed up on your weekly calendar now.

So nothing to do with the nightly update.

The good news is that there is nothing wrong with your data other than this one record.
I'm going to add some logic to the next nightly so that it can handle this anomaly.

But you may wish to clean up your database anyway.
One way to do this is to:
- make an up to date **backup** from the *settings,backup* panel
- and do an **import with wipe** from the same panel.

this will clear the database and settings, and then import from your backup.
the backup only contains episodes that have series attached, so **any** stray episode records should vanish.

or a far simpler method is to:
- press the **F12** key to open the *development tools* page, 
- click on the **console** tab to view the log
- at the `>` prompt paste the following and press enter
```javascript
CRUD.executeQuery('delete from Episodes where ID_Episode is 8923').then(function(res) {
  console.log('done!', res.rowsAffected, 'items deleted!')
});
```
this will delete just the one record, which may be all that is needed.

**Comment by cajeiri** [comment]
Ah, using the simpler method I fixed the problem per your instructions.

I removed Z Nation a week ago or so, something must have gone wrong at that point.
Thank you for your help! ^^
