### ISSUE TITLE
The Good Place episode listing is off by an episode

### ISSUE THREAD

**Issue by bjhiltbrand** [SchizoDuckie/DuckieTV#968]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))** -
STANDALONE
...

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5
...

**What is your Operating System (Windows, Mac, Linux, Android)**
WINDOWS
...

**Describe the problem you are having and steps to reproduce if available**
The Good Place started it's season with a 2 part premier. This has made it so that some sites list the episodes as Episode 1 (premier), episode 2, episode 3, etc. This is what DuckieTV is picking up on and using for the auto downloader.

However, the torrents are all listing the episodes as episode 1 (premier part 1), episode 2 (premier part 2), episode 3, episode 4, etc.

This makes it so that the episode downloaded using the auto downloader is not correct and is a week behind where the series actually is. I'm not sure where or how to fix this issue, but it seems to only be with this series out of the ones I watch. There may be others.

**Comment by garfield69** [comment]
As you may know, DuckieTV fetches show information from [Trakt.TV](https://trakt.tv/), which in turn uses data from [TMDB](https://www.themoviedb.org/) and [TVDB](http://thetvdb.com/).    
TMDB is used for the top level show info like title, year, genres, and country.    
TVDB is used for all season and episode info and as a fall back for info missing on TMDB.

DuckieTV uses a cross entity mapping service [theXem](http:thexem.de) for when the torrent scene does not line up with the Trakt.tv data.       

So any discrepancy you find is out of the control of DuckieTV.     

I see that thexem have *the Good Place* in their DB http://thexem.de/xem/show/3927, but that the table is empty.      
So if you want to have this fixed, consider joining #xem on irc.freenode.net and talk to them about this.

**Comment by bjhiltbrand** [comment]
Perfect. Thank you for the direction.

**Comment by lonelyfairie** [comment]
@bjhiltbrand did you get any response from the xem team regarding this show?

Nevermind. 

Went ahead and asked in the xem IRC and got this response:
[13:24] <lonelyfairie>  Hi, just wanted to know if the page for the show the good place can be fixed, as it is empty, http://thexem.de/xem/show/3927
[13:24] <lonelyfairie> the show is off by one episode regarding what is being released and what is shown in thetvdb and trakt.tv since they are considering the two part first episode of the season as 1 instead of two as it was released.
[13:27] <@ll> which episode is off? It looks like what is released matches tvdb
[13:29] <ignoremenow> the good place is good if you use web-dl's
[13:29] <ignoremenow> if you try to use the scene it will be one ep ahead
[13:30] <ignoremenow> the scene released a notice saying that they might fix this going forward, so we will see what happens next episode

**Comment by bjhiltbrand** [comment]
I asked on the IRC channel. I got a response from someone that said that they hadn't heard of the issue. That's as far as I got, as my computer blue-screened shortly thereafter. I didn't go ask again when I got back up and running. I'm glad you were able to get a more helpful answer. Sorry for not responding sooner here. On a side note, the episode downloaded from last week was correct.

**Comment by MFKDGAF** [comment]
I know I am late on this and sorry to revive this, but this is the reason why request #989 was created. 

I found that all episodes for The Good Place by the person SVA was off by the one episode. I wanted to just block The Good Place by uploader SVA but since the block was global it would block SVA on all other uploaded shows.
