### ISSUE TITLE
One Trakt.TV show doesn't load into Duckie!

### ISSUE THREAD

**Issue by syphondog3** [SchizoDuckie/DuckieTV#970]
First, DuckieTV has helped me so tremendously over the past few years in keeping organized of when shows come out -- especially when they take their annoying long breaks!

Recently, I tried to add the HBO show "Insecure" to Duckie via traktTV. When I manually click "import from DuckieTV", I see Insecure there, but the "refresh" icon keeps spinning on that show, and it never gets added (see attached screencap)

I tried to remove Insecure from Trakt and then re-adding it, but it doesn't work.

Is this a bug with that show?

I **have not** tried to remove the duckieTV extension and reinstall it.

![screenshot 2017-10-09 11 48 50](https://user-images.githubusercontent.com/32645908/31346693-ed5dc18e-ace7-11e7-99e1-9b1660610e6d.png)

Thanks!

**Comment by garfield69** [comment]
A little research has yielded the reason you are not able to import *Insecure*.     
The problem comes in two parts:
First, If I navigate to the DuckieTV *add a show* page I see that there are *two* Trakt.TV shows called *Insecure* on the Trakt.TV database.      
The first one is the proper record for the show and can be fetched by DuckieTV
![image](https://user-images.githubusercontent.com/6933240/31352715-42f5d43e-ad8c-11e7-9325-f979aaa8aa32.png)
But the second record is incomplete and cannot be fetched
![image](https://user-images.githubusercontent.com/6933240/31352722-57cdd550-ad8c-11e7-9a63-6246e618bb70.png)
Secondly, I see by looking at your screen capture that you are not using the latest version of DuckieTV, it looks to be 1.1.4 or earlier.
So the reason you cannot import *Insecure* from your Trakt.tv account is that 1.1.4 was not able to distinguish between the two versions of *Insecure* on Trakt.TV. It used a title search for imports.      
This was fixed in version 1.1.5, which now uses the Trakt_ID of the shows to import.

So If you upgrade to the latest version you should be able to import all the shows in your Trakt.TV account.     

Before upgrading I recommend making a backup of your shows and settings from the DuckieTV  *Settings, Backup* side panel, just in case there are problems during the upgrade.

**Comment by syphondog3** [comment]
Hello @garfield69!

Thanks for your immense help and thorough technical support!

1.) I did not know you could add shows directly through DuckieTV! I had been logging into Trakt.TV separately and adding it there! Cool!

2.) Why didn't DuckieTV auto-update like it normally does? It usually says DuckieTV has been updated to _____.  I never had to do anything manually before to update it?

3.) What is the proper way to update it? I looked through each of the DuckieTV menu options and didn't see an area to update. I had to somewhat painstakingly uninstall DuckieTV from my Chrome New Tab extensions and then reinstall it.

Somehow during this process of uninstalling, Chrome decided not to allow me to download extensions anymore! I had to go into the Windows hosts file and delete the line related to google in order to fix it. That was what Google troubleshooting that problem yielded.

Anyhow, after I reinstalled the now 1.1.5 update, everything works, including _Insecure_

Thanks for helping me with this!

Please let me know about my comments here, especially related to why it didn't auto-update like normal.

Thanks!!

**Comment by garfield69** [comment]
>2.) Why didn't DuckieTV auto-update like it normally does? It usually says DuckieTV has been updated to _____. I never had to do anything manually before to update it?    

I don't have an answer for you on this one. When we publish a release on the Google Chrome Extensions Web Store, the actual updating of the extensions on the user's browser is handled by the Chrome Browser itself. If for some reason this did not happen then it is out of our control.

>3.) What is the proper way to update it? I looked through each of the DuckieTV menu options and didn't see an area to update. I had to somewhat painstakingly uninstall DuckieTV from my Chrome New Tab extensions and then reinstall it.     

The extension update is handled by the Chrome Browser. DuckieTV (the extension) is not active during this process, its just a payload.       
If the Google web store does not push an update to replace an extension, then the accepted manual method is to visit the chrome extensions page at `chrome://extensions/`, tick the *Developer Mode* checkbox, and then use the *update extensions now* button.
![image](https://user-images.githubusercontent.com/6933240/31371149-f33e889a-adeb-11e7-9816-e780c567bf16.png)

>Somehow during this process of uninstalling, Chrome decided not to allow me to download extensions anymore! I had to go into the Windows hosts file and delete the line related to google in order to fix it. That was what Google troubleshooting that problem yielded.     

wow. maybe that is why the update did not happen. I've no idea. Glad you sorted it all out.
