### ISSUE TITLE
Category 'superhero' not in translation file

### ISSUE THREAD

**Issue by dzogas** [SchizoDuckie/DuckieTV#972]
What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))
...Chrome Extension (New Tab)

What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)
...1.1.6

What is your Operating System (Windows, Mac, Linux, Android)
... Windows

Describe the problem you are having and steps to reproduce if available
there is a category called 'superhero' (all lower case letters) which doens not exist in the el_GR.json file. I checked Italian as well and it seems it is missing from there too.

**Comment by garfield69** [comment]
Good to know. I will add this category along with the required code support.
And while I am at it, I will also add a few missing translation keys that I spotted while playing with other language settings.
Found so far are: the *ALL* button on the torrent dialogues, the *wiki FAQ's* on the Jackett panel.
I may need to do a second pass in Chinese to spot some more, that language makes it easy to spot the bits that should have translations :-)

**Comment by dzogas** [comment]
what do I do afterwards? I have to fork DuckieTv again, or the changes you make appear automatically?

**Comment by garfield69** [comment]
yes, you will need to fork again in order to pick up a fresh copy of the DuckieTV master source.

**Comment by garfield69** [comment]
But not while you still have a pull request to generate, or you will blow away your changes on your fork ! ;-)

**Comment by dzogas** [comment]
oh damn...  I will try to figure out now how to pull the request

**Comment by dzogas** [comment]
I think I did it right... but I do not know how to check this... sorry.... I hate being the new guy... ;)

**Comment by garfield69** [comment]
All Good. 
So take a break and relax.
You will know when the new keys are available when I've closed this ticket.
I usually add new keys with a Google Translator, so they almost always need a human afterwards to make sure the translations are relevant and contextually correct for the intended use. :-)

**Comment by dzogas** [comment]
I just noticed that the 'Pull down most visited sites" is not being translated in greek, I tried Italian and it works.... but I can't seem to find what I messed up (if I did) in CHROMETOPSITES-hover/hdr

**Comment by dzogas** [comment]
Also if I Refresh the page in Add a Show the title "Trending Shows... "and the categories, all revert to english... only in greek though...  it works as it should in Italian and French....

**Comment by garfield69** [comment]
@dzogas  I've completed adding the new translations keys, and implemented a setting in the *Display* sidepanel to enable Mixed Case fonts.      
Basically the default is to use Bebas Nueue, but if you enable the mixedCase option, then the Bebas font is dropped from the font-family on *h1,h2,h3* headers, the *Strong* class, and most of the *buttons*.      

So once you have forked a fresh copy of the master source, you can continue finishing off any outstanding translations.    

Let me know if you spot any text still displayed in Bebas... it's likely I've still got some css adjustments to make.

>I just noticed that the 'Pull down most visited sites" is not being translated in greek, I tried Italian and it works

~~Once you are on the new source, check again, it seems to work for me.~~     
[edit] Huh. you're right, shows in English when set to Greek, but works for every other language. Will Investigate.
[edit2] fixed with 7fa5e9f0a36d53d7d77df12cf74c777b8c26b854

>Also if I Refresh the page in Add a Show the title "Trending Shows... "and the categories, all revert to english... only in greek though... it works as it should in Italian and French....    

Yes, refreshing a page on some panels does not always work, an artefact of the way some panels are rendered. Restart the app when that happens, or navigate away from that page, to the main calendar, and then back again.

**Comment by garfield69** [comment]
@dzogas you may wish to make a fresh fork before starting on your translations. There have been 4 fixes since your last fork that will help in your testing :-)
