### ISSUE TITLE
Windows gets in focus at 00:00 each day

### ISSUE THREAD

**Issue by mindtricksdev** [SchizoDuckie/DuckieTV#997]
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows

**Describe the problem you are having and steps to reproduce if available**
Windows gets in focus at 00:00 each day. 
Start a movie fullscreen before 00:00. At 00:00 the DuckieTV window gains focus over the movie and I need to manually refocus the movie player.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment]
Yes, this is a result of the Internal Daily Reset that DuckieTV performs a couple seconds after midnight so that all the schedules and calendar events are set for the new day.       

If you want to avoid DuckieTV grabbing focus during this event, then try the following: 
Navigate to the *Settings > Window* side panel, and set the *Window on Start-up* to **Minimised** by clicking that button.     
You may also want to tick the *System Tray* check-boxes for *Always show Tray Icon* and Minimise Button Minimises DuckieTV to Tray*.      
![image](https://user-images.githubusercontent.com/6933240/33219294-5824e230-d1a6-11e7-8de9-1fc775f1decf.png)

I think that should prevent NWJS from stealing focus during the reset event.
